import type { Species } from "./types";

export const CENOZOIC_MODERN_SPECIES: Species[] = [
  {
    id: "megalodon",
    name: "巨齿鲨",
    nameEn: "Megalodon",
    era: "新生代",
    period: "2300万年前",
    keyTraits: ["已知最大鲨鱼", "长达18米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "软骨鱼纲" },
    extinct: true,
  },
  {
    id: "livyatan",
    name: "利维坦鲸",
    nameEn: "Livyatan",
    era: "新生代",
    period: "1300万年前",
    keyTraits: ["已知最大齿鲸", "顶级海洋掠食者"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "terror-bird",
    name: "恐鹤",
    nameEn: "Terror Bird",
    era: "新生代",
    period: "2000万年前",
    keyTraits: ["不能飞的巨型掠食鸟", "高达3米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "proconsul",
    name: "原康修尔猿",
    nameEn: "Proconsul",
    era: "新生代",
    period: "2300万年前",
    keyTraits: ["早期类人猿", "无尾"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "basilosaurus",
    name: "龙王鲸",
    nameEn: "Basilosaurus",
    era: "新生代",
    period: "4000万年前",
    keyTraits: ["早期鲸类", "长达18米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "ambulocetus",
    name: "游走鲸",
    nameEn: "Ambulocetus",
    era: "新生代",
    period: "4900万年前",
    keyTraits: ["鲸鱼陆地祖先", "半水生"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "blue-whale",
    name: "蓝鲸",
    nameEn: "Blue Whale",
    era: "新生代",
    period: "500万年前",
    keyTraits: ["地球有史以来最大动物", "长达30米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "platypus",
    name: "鸭嘴兽",
    nameEn: "Platypus",
    era: "新生代",
    period: "1亿年前",
    keyTraits: ["产卵哺乳动物", "电感受器"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "pangolin",
    name: "穿山甲",
    nameEn: "Pangolin",
    era: "新生代",
    period: "8000万年前",
    keyTraits: ["全身鳞甲", "最被偷猎的哺乳动物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "tardigrade",
    name: "水熊虫",
    nameEn: "Tardigrade",
    era: "新生代",
    period: "5亿年前",
    keyTraits: ["极端环境生存", "太空真空耐受"],
    taxonomy: { kingdom: "动物界", phylum: "缓步动物门" },
    extinct: false,
  },
  {
    id: "sivatherium",
    name: "西瓦兽",
    nameEn: "Sivatherium",
    era: "新生代",
    period: "100万年前",
    keyTraits: ["已知最大长颈鹿科", "巨型哺乳动物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "megatherium",
    name: "大地懒",
    nameEn: "Megatherium",
    era: "新生代",
    period: "1万年前",
    keyTraits: ["大象般大小的树懒", "可达6米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "glyptodon",
    name: "雕齿兽",
    nameEn: "Glyptodon",
    era: "新生代",
    period: "1万年前",
    keyTraits: ["巨型装甲哺乳动物", "龟壳般的背甲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "smilodon",
    name: "剑齿虎",
    nameEn: "Smilodon",
    era: "新生代",
    period: "250万年前",
    keyTraits: ["20厘米长的剑齿", "伏击型掠食者", "冰河时期猛兽"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "食肉目" },
    extinct: true,
  },
  {
    id: "mammoth",
    name: "猛犸象",
    nameEn: "Woolly Mammoth",
    era: "新生代",
    period: "40万年前",
    keyTraits: ["厚毛御寒", "长弯曲象牙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "长鼻目" },
    extinct: true,
  },
  {
    id: "columbian-mammoth",
    name: "哥伦比亚猛犸象",
    nameEn: "Columbian Mammoth",
    era: "第四纪",
    period: "100万年前",
    keyTraits: ["比猛犸象更大的近亲", "北美"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "australopithecus",
    name: "南方古猿",
    nameEn: "Australopithecus",
    era: "第四纪",
    period: "390万年前",
    keyTraits: ["直立行走的早期人科", "露西化石", "脑容量较小"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "ardipithecus",
    name: "地猿",
    nameEn: "Ardipithecus",
    era: "第四纪",
    period: "440万年前",
    keyTraits: ["早期人科", "可能直立行走"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "woolly-rhinoceros",
    name: "披毛犀",
    nameEn: "Woolly Rhinoceros",
    era: "第四纪",
    period: "350万年前",
    keyTraits: ["厚毛御寒", "冰河时期"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-habilis",
    name: "能人",
    nameEn: "Homo Habilis",
    era: "第四纪",
    period: "200万年前",
    keyTraits: ["最早使用石器的人属", "脑容量增大"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "homo-erectus",
    name: "直立人",
    nameEn: "Homo Erectus",
    era: "第四纪",
    period: "180万年前",
    keyTraits: ["最早使用火的人属", "走出非洲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "saber-tooth-cat",
    name: "刃齿虎",
    nameEn: "Smilodon fatalis",
    era: "第四纪",
    period: "160万年前",
    keyTraits: ["致命剑齿", "拉布雷亚沥青坑化石"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "gigantopithecus",
    name: "巨猿",
    nameEn: "Gigantopithecus",
    era: "第四纪",
    period: "100万年前",
    keyTraits: ["已知最大的灵长类", "身高可达3米", "与大熊猫共存"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "neanderthalensis",
    name: "尼安德特人",
    nameEn: "Homo Neanderthalensis",
    era: "第四纪",
    period: "40万年前",
    keyTraits: ["与智人杂交", "脑容量大于智人"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "cave-bear",
    name: "洞熊",
    nameEn: "Cave Bear",
    era: "第四纪",
    period: "30万年前",
    keyTraits: ["比棕熊更大", "欧洲洞穴化石"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "denisovan",
    name: "丹尼索瓦人",
    nameEn: "Denisovan",
    era: "第四纪",
    period: "30万年前",
    keyTraits: ["与智人杂交", "高海拔适应基因"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "homo-floresiensis",
    name: "弗洛勒斯人",
    nameEn: "Homo Floresiensis",
    era: "第四纪",
    period: "10万年前",
    keyTraits: ["矮小人种", "霍比特人"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "irish-elk",
    name: "大角鹿",
    nameEn: "Irish Elk",
    era: "第四纪",
    period: "7700年前灭绝",
    keyTraits: ["已知最大鹿角", "翼展可达3.6米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-sapiens",
    name: "智人",
    nameEn: "Homo Sapiens",
    era: "全新世",
    period: "30万年前",
    keyTraits: ["抽象思维", "语言", "工具制造", "文明建设"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: false,
  },
  {
    id: "moa",
    name: "恐鸟",
    nameEn: "Moa",
    era: "全新世",
    period: "600年前灭绝",
    keyTraits: ["新西兰巨型不会飞的鸟", "高达3.6米", "人类活动导致灭绝"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "dodo",
    name: "渡渡鸟",
    nameEn: "Dodo",
    era: "全新世",
    period: "1662年灭绝",
    keyTraits: ["不会飞的鸟", "人类导致灭绝"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "stellers-sea-cow",
    name: "斯特拉大海牛",
    nameEn: "Steller's Sea Cow",
    era: "全新世",
    period: "1768年灭绝",
    keyTraits: ["长达8米的海牛", "北太平洋"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "great-auk",
    name: "大海雀",
    nameEn: "Great Auk",
    era: "全新世",
    period: "1844年灭绝",
    keyTraits: ["不会飞的海鸟", "北极物种"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "quagga",
    name: "斑驴",
    nameEn: "Quagga",
    era: "全新世",
    period: "1883年灭绝",
    keyTraits: ["半身斑马半身马", "南非特有"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "thylacine",
    name: "袋狼",
    nameEn: "Thylacine",
    era: "全新世",
    period: "1936年灭绝",
    keyTraits: ["有袋类掠食者", "塔斯马尼亚虎"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-naledi",
    name: "纳莱迪人",
    nameEn: "Homo Naledi",
    era: "第四纪",
    period: "33万年前",
    keyTraits: ["脑容量较小", "可能有埋葬行为", "南非发现"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "elasmotherium",
    name: "板齿犀",
    nameEn: "Elasmotherium",
    era: "第四纪",
    period: "2.9万年前灭绝",
    keyTraits: ["巨型独角兽", "可能单角", "体重可达4吨"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "haasts-eagle",
    name: "哈斯特鹰",
    nameEn: "Haast's Eagle",
    era: "全新世",
    period: "1400年灭绝",
    keyTraits: ["已知最大飞鸟之一", "翼展3米", "新西兰顶级掠食者"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "okapi",
    name: "霍加狓",
    nameEn: "Okapi",
    era: "新生代",
    period: "2000万年前",
    keyTraits: ["长颈鹿唯一近亲", "刚果雨林特有", "斑马纹腿"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "coelacanth-living",
    name: "腔棘鱼",
    nameEn: "Coelacanth",
    era: "新生代",
    period: "4亿年前",
    keyTraits: ["活化石", "曾被认为已灭绝6500万年", "叶状鳍"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "腔棘鱼纲" },
    extinct: false,
  },
];
