import type { CrossReference } from "./types";

export const COSMOLOGY_REFS: CrossReference[] = [
  {
    fromDomain: "cosmology",
    fromId: "big-bang",
    fromTitle: "大爆炸理论",
    toDomain: "philosophy",
    toId: "leibniz",
    toTitle: "莱布尼茨",
    relation: "莱布尼茨提出的「为什么存在而非虚无」在大爆炸理论中获得了新的物理语境",
  },
  {
    fromDomain: "cosmology",
    fromId: "black-holes",
    fromTitle: "黑洞",
    toDomain: "universe-physics",
    toId: "relativity",
    toTitle: "相对论",
    relation: "黑洞是广义相对论预言的最极端天体",
  },
  {
    fromDomain: "cosmology",
    fromId: "dark-energy",
    fromTitle: "暗能量",
    toDomain: "universe-physics",
    toId: "quantum-mechanics",
    toTitle: "量子力学",
    relation: "暗能量可能与量子真空能有关，是物理学最大的未解之谜之一",
  },
  {
    fromDomain: "cosmology",
    fromId: "multiverse",
    fromTitle: "多重宇宙",
    toDomain: "philosophy",
    toId: "epistemology",
    toTitle: "认识论",
    relation: "多重宇宙假说挑战了可证伪性的科学划界标准",
  },
  {
    fromDomain: "cosmology",
    fromId: "cosmic-expansion",
    fromTitle: "宇宙膨胀",
    toDomain: "universe-physics",
    toId: "relativity",
    toTitle: "相对论",
    relation: "弗里德曼方程从广义相对论推导出宇宙膨胀解",
  },
  {
    fromDomain: "cosmology",
    fromId: "stellar-nucleosynthesis",
    fromTitle: "恒星核合成",
    toDomain: "life-science",
    toId: "origin-of-life",
    toTitle: "生命起源",
    relation: "恒星核合成产生了碳、氧等生命必需元素——我们都是星尘",
  },
  {
    fromDomain: "cosmology",
    fromId: "habitable-zone",
    fromTitle: "宜居带",
    toDomain: "life-science",
    toId: "ecology",
    toTitle: "生态学",
    relation: "宜居带的天体物理条件决定了行星上生态系统的可能性",
  },
  {
    fromDomain: "cosmology",
    fromId: "curved-spacetime",
    fromTitle: "弯曲时空",
    toDomain: "mathematics",
    toId: "geometry",
    toTitle: "几何学",
    relation: "黎曼微分几何是描述弯曲时空的核心数学语言",
  },
  {
    fromDomain: "cosmology",
    fromId: "cosmic-expansion",
    fromTitle: "宇宙膨胀",
    toDomain: "mathematics",
    toId: "differential-equations",
    toTitle: "微分方程",
    relation: "弗里德曼方程是一组描述宇宙膨胀的微分方程",
  },
  {
    fromDomain: "cosmology",
    fromId: "copernican-revolution",
    fromTitle: "哥白尼革命",
    toDomain: "human-history",
    toId: "scientific-revolution",
    toTitle: "科学革命",
    relation: "哥白尼日心说引发了天文学和世界观的根本变革",
  },
  {
    fromDomain: "cosmology",
    fromId: "space-race",
    fromTitle: "太空竞赛",
    toDomain: "human-history",
    toId: "cold-war",
    toTitle: "冷战",
    relation: "美苏太空竞赛是冷战最重要的科技对抗前线",
  },
];
