import type { CrossReference } from "./types";

// human-history has no per-era article pages, so every fromPath resolves to the
// timeline (the era is visible there). These render as *incoming* links on the
// philosophy/life-science/physics target pages. Refs whose target page does not
// exist (plant-domestication, math "algebra") were dropped.
export const HISTORY_REFS: CrossReference[] = [
  {
    fromDomain: "human-history",
    fromId: "scientific-revolution",
    fromTitle: "科学革命",
    fromPath: "/human-history/timeline",
    toDomain: "universe-physics",
    toId: "T4-milky-way",
    toTitle: "银河系",
    toPath: "/universe-physics/universe/milky-way",
    relation: "伽利略的望远镜观测揭示了银河系由无数恒星组成",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    fromPath: "/human-history/timeline",
    toDomain: "philosophy",
    toId: "confucius",
    toTitle: "孔子",
    toPath: "/philosophy/thinkers/confucius",
    relation: "轴心时代的思想家奠定了东西方哲学的基础",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    fromPath: "/human-history/timeline",
    toDomain: "philosophy",
    toId: "socrates",
    toTitle: "苏格拉底",
    toPath: "/philosophy/thinkers/socrates",
    relation: "苏格拉底是轴心时代希腊哲学的奠基者",
  },
  {
    fromDomain: "human-history",
    fromId: "enlightenment",
    fromTitle: "启蒙运动",
    fromPath: "/human-history/timeline",
    toDomain: "philosophy",
    toId: "kant",
    toTitle: "康德",
    toPath: "/philosophy/thinkers/kant",
    relation: "康德的「敢于求知」是启蒙运动的精神纲领",
  },
  {
    fromDomain: "human-history",
    fromId: "enlightenment",
    fromTitle: "启蒙运动",
    fromPath: "/human-history/timeline",
    toDomain: "philosophy",
    toId: "rousseau",
    toTitle: "卢梭",
    toPath: "/philosophy/thinkers/rousseau",
    relation: "卢梭的《社会契约论》是启蒙运动中最具革命性的政治哲学著作",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    fromPath: "/human-history/timeline",
    toDomain: "philosophy",
    toId: "laozi",
    toTitle: "老子",
    toPath: "/philosophy/thinkers/laozi",
    relation: "老子在轴心时代创立了道家学派，影响了东亚文明数千年",
  },
  {
    fromDomain: "human-history",
    fromId: "scientific-revolution",
    fromTitle: "科学革命",
    fromPath: "/human-history/timeline",
    toDomain: "life-science",
    toId: "darwin",
    toTitle: "达尔文",
    toPath: "/life-science/scientists/darwin",
    relation: "科学革命的方法论传统为达尔文的观察与归纳提供了范式",
  },
];
