import type { CrossReference } from "./types";

/**
 * Mathematics ↔ other domains. Math articles already render <RelatedContent>
 * but had no cross-domain data; these light up the bridges. Every entry carries
 * explicit fromPath/toPath because both sides are nested (section/slug) routes.
 */
export const MATHEMATICS_REFS: CrossReference[] = [
  {
    fromDomain: "mathematics",
    fromId: "godel-incompleteness",
    fromTitle: "哥德尔不完备定理",
    fromPath: "/mathematics/theorems/godel-incompleteness",
    toDomain: "computer-science",
    toId: "alan-turing",
    toTitle: "艾伦·图灵",
    toPath: "/computer-science/pioneers/alan-turing",
    relation: "哥德尔不完备定理与图灵的停机问题，从不同角度揭示了形式系统与计算的根本极限",
  },
  {
    fromDomain: "mathematics",
    fromId: "turing",
    fromTitle: "图灵",
    fromPath: "/mathematics/mathematicians/turing",
    toDomain: "computer-science",
    toId: "alan-turing",
    toTitle: "艾伦·图灵",
    toPath: "/computer-science/pioneers/alan-turing",
    relation: "图灵既是数学家，也是计算机科学的奠基者——可计算性理论横跨两门学科",
  },
  {
    fromDomain: "mathematics",
    fromId: "godel-incompleteness",
    fromTitle: "哥德尔不完备定理",
    fromPath: "/mathematics/theorems/godel-incompleteness",
    toDomain: "philosophy",
    toId: "russell",
    toTitle: "罗素",
    toPath: "/philosophy/thinkers/russell",
    relation: "不完备定理终结了罗素与希尔伯特为全部数学奠定完备、一致基础的宏大纲领",
  },
  {
    fromDomain: "mathematics",
    fromId: "godel-incompleteness",
    fromTitle: "哥德尔不完备定理",
    fromPath: "/mathematics/theorems/godel-incompleteness",
    toDomain: "philosophy",
    toId: "what-can-we-know",
    toTitle: "我们能知道什么？",
    toPath: "/philosophy/questions/what-can-we-know",
    relation: "数学中存在为真却无法证明的命题——这为「我们能知道什么」划出了一条硬边界",
  },
  {
    fromDomain: "mathematics",
    fromId: "noethers-theorem",
    fromTitle: "诺特定理",
    fromPath: "/mathematics/theorems/noethers-theorem",
    toDomain: "universe-physics",
    toId: "物理学--对称性与诺特定理",
    toTitle: "对称性与诺特定理",
    toPath: "/universe-physics/knowledge-base/物理学--对称性与诺特定理",
    relation: "诺特定理证明每一种连续对称性都对应一条守恒律，是现代物理学的支柱",
  },
  {
    fromDomain: "mathematics",
    fromId: "noether",
    fromTitle: "诺特",
    fromPath: "/mathematics/mathematicians/noether",
    toDomain: "universe-physics",
    toId: "物理学--对称性与诺特定理",
    toTitle: "对称性与诺特定理",
    toPath: "/universe-physics/knowledge-base/物理学--对称性与诺特定理",
    relation: "诺特的数学定理深刻地重塑了理论物理学对守恒律的理解",
  },
  {
    fromDomain: "mathematics",
    fromId: "pythagorean-theorem",
    fromTitle: "勾股定理",
    fromPath: "/mathematics/theorems/pythagorean-theorem",
    toDomain: "philosophy",
    toId: "pythagoras",
    toTitle: "毕达哥拉斯",
    toPath: "/philosophy/thinkers/pythagoras",
    relation: "毕达哥拉斯学派以此定理为信条，主张「万物皆数」",
  },
  {
    fromDomain: "mathematics",
    fromId: "cantors-theorem",
    fromTitle: "康托尔定理",
    fromPath: "/mathematics/theorems/cantors-theorem",
    toDomain: "philosophy",
    toId: "what-is-real",
    toTitle: "什么是真实？",
    toPath: "/philosophy/questions/what-is-real",
    relation: "康托尔证明存在不同「大小」的无穷，挑战了我们对实在与无限的直觉",
  },
  {
    fromDomain: "mathematics",
    fromId: "fundamental-theorem-of-calculus",
    fromTitle: "微积分基本定理",
    fromPath: "/mathematics/theorems/fundamental-theorem-of-calculus",
    toDomain: "universe-physics",
    toId: "经典物理--牛顿三大定律",
    toTitle: "牛顿三大定律",
    toPath: "/universe-physics/knowledge-base/经典物理--牛顿三大定律",
    relation: "微积分是牛顿表述运动定律的语言；二者几乎同时诞生",
  },
  {
    fromDomain: "mathematics",
    fromId: "euler-identity",
    fromTitle: "欧拉恒等式",
    fromPath: "/mathematics/theorems/euler-identity",
    toDomain: "philosophy",
    toId: "what-is-beauty",
    toTitle: "什么是美？",
    toPath: "/philosophy/questions/what-is-beauty",
    relation: "欧拉恒等式把五个最重要的常数凝于一式，常被视为「数学之美」的化身",
  },
  {
    fromDomain: "mathematics",
    fromId: "bayes-theorem",
    fromTitle: "贝叶斯定理",
    fromPath: "/mathematics/theorems/bayes-theorem",
    toDomain: "psychology",
    toId: "kahneman-tversky-1979",
    toTitle: "前景理论（卡尼曼与特沃斯基）",
    toPath: "/psychology/experiments/kahneman-tversky-1979",
    relation: "贝叶斯定理是衡量人类概率判断偏差的理性基准——卡尼曼揭示了我们如何系统地偏离它",
  },
  {
    fromDomain: "mathematics",
    fromId: "hilbert",
    fromTitle: "希尔伯特",
    fromPath: "/mathematics/mathematicians/hilbert",
    toDomain: "philosophy",
    toId: "what-can-we-know",
    toTitle: "我们能知道什么？",
    toPath: "/philosophy/questions/what-can-we-know",
    relation: "希尔伯特坚信「我们必须知道，我们必将知道」——哥德尔却证明了这一信念的限度",
  },
];
