import type { CrossReference } from "./types";

export const PHILOSOPHY_REFS: CrossReference[] = [
  {
    fromDomain: "philosophy",
    fromId: "aristotle",
    fromTitle: "亚里士多德",
    fromPath: "/philosophy/thinkers/aristotle",
    toDomain: "universe-physics",
    toId: "T7-earth",
    toTitle: "地球",
    toPath: "/universe-physics/universe/earth",
    relation: "亚里士多德通过月食阴影推断地球是球形",
  },
  {
    fromDomain: "philosophy",
    fromId: "kant",
    fromTitle: "康德",
    toDomain: "cosmology",
    toId: "cosmic-structure",
    toTitle: "宇宙结构",
    relation: "康德首次提出星云假说，认为银河是旋转扁平的恒星盘",
  },
  {
    fromDomain: "philosophy",
    fromId: "buddha",
    fromTitle: "佛陀",
    toDomain: "human-history",
    toId: "axial-age",
    toTitle: "轴心时代",
    relation: "佛陀与孔子、苏格拉底同处轴心时代，各自开创了深远的思想传统",
  },
  {
    fromDomain: "philosophy",
    fromId: "determinism",
    fromTitle: "决定论",
    toDomain: "universe-physics",
    toId: "quantum-mechanics",
    toTitle: "量子力学",
    relation: "决定论哲学在量子力学的不确定性原理面前需要重新审视",
  },
  {
    fromDomain: "philosophy",
    fromId: "aristotle",
    fromTitle: "亚里士多德",
    toDomain: "universe-physics",
    toId: "classical-mechanics",
    toTitle: "经典力学",
    relation: "亚里士多德的自然哲学是物理学的前身，其力学理论统治了近两千年",
  },
  {
    fromDomain: "philosophy",
    fromId: "descartes",
    fromTitle: "笛卡尔",
    toDomain: "universe-physics",
    toId: "classical-mechanics",
    toTitle: "经典力学",
    relation: "笛卡尔的机械论宇宙观为经典力学提供了哲学框架",
  },
  {
    fromDomain: "philosophy",
    fromId: "socrates",
    fromTitle: "苏格拉底",
    toDomain: "human-history",
    toId: "axial-age",
    toTitle: "轴心时代",
    relation: "苏格拉底的问答法开启了西方理性传统",
  },
  {
    fromDomain: "philosophy",
    fromId: "kant",
    fromTitle: "康德",
    toDomain: "human-history",
    toId: "enlightenment",
    toTitle: "启蒙运动",
    relation: "康德是启蒙运动的哲学总结者，其三大批判奠定了现代哲学",
  },
  {
    fromDomain: "philosophy",
    fromId: "marx",
    fromTitle: "马克思",
    toDomain: "human-history",
    toId: "industrial-revolution",
    toTitle: "工业革命",
    relation: "马克思对工业资本主义的批判改变了人类历史进程",
  },
  {
    fromDomain: "philosophy",
    fromId: "plato",
    fromTitle: "柏拉图",
    toDomain: "human-history",
    toId: "axial-age",
    toTitle: "轴心时代",
    relation: "柏拉图的学园是西方高等教育的原型",
  },
  {
    fromDomain: "philosophy",
    fromId: "philosophy-of-mathematics",
    fromTitle: "数学哲学",
    toDomain: "mathematics",
    toId: "godel",
    toTitle: "哥德尔",
    relation: "数学哲学围绕哥德尔定理展开了关于数学真理本质的核心争论",
  },
  {
    fromDomain: "philosophy",
    fromId: "plato",
    fromTitle: "柏拉图",
    toDomain: "mathematics",
    toId: "geometry",
    toTitle: "几何学",
    relation: "柏拉图认为几何形式是永恒不变的理念，学园门口写着「不懂几何者勿入」",
  },
  {
    fromDomain: "philosophy",
    fromId: "epistemology",
    fromTitle: "认识论",
    toDomain: "mathematics",
    toId: "probability",
    toTitle: "概率论",
    relation: "贝叶斯认识论将概率论与知识的确定性联系起来",
  },
  {
    fromDomain: "philosophy",
    fromId: "nietzsche",
    fromTitle: "尼采",
    toDomain: "life-science",
    toId: "darwin",
    toTitle: "达尔文",
    relation: "尼采的道德谱系学对进化论的伦理含义进行了哲学反思",
  },
  {
    fromDomain: "philosophy",
    fromId: "bioethics",
    fromTitle: "生命伦理学",
    toDomain: "life-science",
    toId: "genetic-engineering",
    toTitle: "基因工程",
    relation: "生命伦理学为基因工程的应用划定了道德边界",
  },
  {
    fromDomain: "philosophy",
    fromId: "philosophy-of-mind",
    fromTitle: "心灵哲学",
    toDomain: "life-science",
    toId: "consciousness-studies",
    toTitle: "意识研究",
    relation: "心灵哲学的概念框架为意识的科学研究提供了方向",
  },
  {
    fromDomain: "philosophy",
    fromId: "aristotle",
    fromTitle: "亚里士多德",
    toDomain: "life-science",
    toId: "biology-classification",
    toTitle: "生物分类学",
    relation: "亚里士多德是生物分类学的奠基人，观察记录了 500 多个物种",
  },
  {
    fromDomain: "philosophy",
    fromId: "epistemology",
    fromTitle: "认识论",
    toDomain: "cosmology",
    toId: "multiverse",
    toTitle: "多重宇宙",
    relation: "认识论追问：我们能否认识那些原则上不可观测的宇宙？",
  },
];
