import type { CrossReference } from "./types";

// Every ref carries explicit fromPath/toPath that resolves to a real page.
// Refs whose endpoints were never built as pages (axial-age, bioethics,
// biology-classification, consciousness-studies, philosophy-of-mathematics …)
// were removed rather than left to 404. Guarded by scripts/check-cross-refs.ts.
export const PHILOSOPHY_REFS: CrossReference[] = [
  {
    fromDomain: "philosophy",
    fromId: "aristotle",
    fromTitle: "亚里士多德",
    fromPath: "/philosophy/thinkers/aristotle",
    toDomain: "universe-physics",
    toId: "T7-earth",
    toTitle: "地球",
    toPath: "/universe-physics/universe/earth",
    relation: "亚里士多德通过月食阴影推断地球是球形",
  },
  {
    fromDomain: "philosophy",
    fromId: "kant",
    fromTitle: "康德",
    fromPath: "/philosophy/thinkers/kant",
    toDomain: "cosmology",
    toId: "宇宙大尺度结构",
    toTitle: "宇宙大尺度结构",
    toPath: "/cosmology/knowledge-base/宇宙大尺度结构",
    relation: "康德首次提出星云假说，认为银河是旋转扁平的恒星盘",
  },
  {
    fromDomain: "philosophy",
    fromId: "determinism",
    fromTitle: "决定论",
    fromPath: "/philosophy/concepts/determinism",
    toDomain: "universe-physics",
    toId: "quantum-mechanics",
    toTitle: "量子力学",
    toPath: "/universe-physics/physics/quantum-mechanics",
    relation: "决定论哲学在量子力学的不确定性原理面前需要重新审视",
  },
  {
    fromDomain: "philosophy",
    fromId: "aristotle",
    fromTitle: "亚里士多德",
    fromPath: "/philosophy/thinkers/aristotle",
    toDomain: "universe-physics",
    toId: "classical-mechanics",
    toTitle: "经典力学",
    toPath: "/universe-physics/physics/classical-mechanics",
    relation: "亚里士多德的自然哲学是物理学的前身，其力学理论统治了近两千年",
  },
  {
    fromDomain: "philosophy",
    fromId: "descartes",
    fromTitle: "笛卡尔",
    fromPath: "/philosophy/thinkers/descartes",
    toDomain: "universe-physics",
    toId: "classical-mechanics",
    toTitle: "经典力学",
    toPath: "/universe-physics/physics/classical-mechanics",
    relation: "笛卡尔的机械论宇宙观为经典力学提供了哲学框架",
  },
  {
    fromDomain: "philosophy",
    fromId: "plato",
    fromTitle: "柏拉图",
    fromPath: "/philosophy/thinkers/plato",
    toDomain: "mathematics",
    toId: "euclidean-geometry",
    toTitle: "几何学",
    toPath: "/mathematics/concepts/euclidean-geometry",
    relation: "柏拉图认为几何形式是永恒不变的理念，学园门口写着「不懂几何者勿入」",
  },
  {
    fromDomain: "philosophy",
    fromId: "what-is-knowledge",
    fromTitle: "认识论",
    fromPath: "/philosophy/questions/what-is-knowledge",
    toDomain: "mathematics",
    toId: "probability",
    toTitle: "概率论",
    toPath: "/mathematics/concepts/probability",
    relation: "贝叶斯认识论将概率论与知识的确定性联系起来",
  },
  {
    fromDomain: "philosophy",
    fromId: "nietzsche",
    fromTitle: "尼采",
    fromPath: "/philosophy/thinkers/nietzsche",
    toDomain: "life-science",
    toId: "darwin",
    toTitle: "达尔文",
    toPath: "/life-science/scientists/darwin",
    relation: "尼采的道德谱系学对进化论的伦理含义进行了哲学反思",
  },
  {
    fromDomain: "philosophy",
    fromId: "what-is-knowledge",
    fromTitle: "认识论",
    fromPath: "/philosophy/questions/what-is-knowledge",
    toDomain: "cosmology",
    toId: "多重宇宙假说",
    toTitle: "多重宇宙",
    toPath: "/cosmology/knowledge-base/多重宇宙假说",
    relation: "认识论追问：我们能否认识那些原则上不可观测的宇宙？",
  },
];
