import type { CrossReference } from "./types";

export const PHYSICS_REFS: CrossReference[] = [
  {
    fromDomain: "universe-physics",
    fromId: "T7-earth",
    fromTitle: "地球",
    toDomain: "human-history",
    toId: "prehistoric",
    toTitle: "史前时代",
    relation: "地球 45 亿年的历史中，人类文明仅占最后 0.0007%",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T0-observable",
    fromTitle: "可观测宇宙",
    toDomain: "philosophy",
    toId: "kant",
    toTitle: "康德",
    relation: "康德的《纯粹理性批判》探讨了宇宙是否有起点的「二律背反」",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T0-observable",
    fromTitle: "可观测宇宙",
    toDomain: "philosophy",
    toId: "copernicus",
    toTitle: "哥白尼",
    relation: "日心说开启了科学革命，改变了人类对自身在宇宙中位置的认知",
  },
  {
    fromDomain: "universe-physics",
    fromId: "classical-mechanics",
    fromTitle: "经典力学",
    toDomain: "mathematics",
    toId: "calculus",
    toTitle: "微积分",
    relation: "牛顿发明微积分正是为了描述力学运动方程",
  },
  {
    fromDomain: "universe-physics",
    fromId: "quantum-mechanics",
    fromTitle: "量子力学",
    toDomain: "mathematics",
    toId: "linear-algebra",
    toTitle: "线性代数",
    relation: "量子态的叠加与测量依赖希尔伯特空间中的线性代数",
  },
  {
    fromDomain: "universe-physics",
    fromId: "relativity",
    fromTitle: "相对论",
    toDomain: "mathematics",
    toId: "differential-equations",
    toTitle: "微分方程",
    relation: "爱因斯坦场方程是一组非线性偏微分方程",
  },
  {
    fromDomain: "universe-physics",
    fromId: "thermodynamics",
    fromTitle: "热力学",
    toDomain: "mathematics",
    toId: "statistics",
    toTitle: "统计学",
    relation: "统计力学用概率论和统计方法推导热力学定律",
  },
  {
    fromDomain: "universe-physics",
    fromId: "electromagnetism",
    fromTitle: "电磁学",
    toDomain: "mathematics",
    toId: "vector-calculus",
    toTitle: "向量微积分",
    relation: "麦克斯韦方程组用向量微积分统一了电与磁",
  },
  {
    fromDomain: "universe-physics",
    fromId: "quantum-mechanics",
    fromTitle: "量子力学",
    toDomain: "philosophy",
    toId: "determinism",
    toTitle: "决定论",
    relation: "量子力学的概率诠释对经典决定论构成根本挑战",
  },
  {
    fromDomain: "universe-physics",
    fromId: "relativity",
    fromTitle: "相对论",
    toDomain: "philosophy",
    toId: "phenomenology",
    toTitle: "现象学",
    relation: "相对论的时空观革新了现象学对时间意识的分析",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T0-observable",
    fromTitle: "可观测宇宙",
    toDomain: "philosophy",
    toId: "existentialism",
    toTitle: "存在主义",
    relation: "宇宙的浩瀚引发了人类对自身存在意义的终极追问",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T1-cosmic-web",
    fromTitle: "宇宙纤维结构",
    toDomain: "cosmology",
    toId: "dark-matter",
    toTitle: "暗物质",
    relation: "暗物质的引力塑造了宇宙的大尺度纤维结构",
  },
];
