import type { CrossReference } from "./types";

// fromPath is required: these refs render on the *target* domain's page (e.g.
// the Kant article) linking back to physics. Without fromPath they resolve to
// /universe-physics/<id>, which 404s — the tier routes are nested under
// /universe/<slug> (cosmic tiers) or /physics/<slug> (physics tiers).
export const PHYSICS_REFS: CrossReference[] = [
  {
    fromDomain: "universe-physics",
    fromId: "T7-earth",
    fromTitle: "地球",
    fromPath: "/universe-physics/universe/earth",
    toDomain: "human-history",
    toId: "prehistoric",
    toTitle: "史前时代",
    toPath: "/human-history/timeline",
    relation: "地球 45 亿年的历史中，人类文明仅占最后 0.0007%",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T0-observable",
    fromTitle: "可观测宇宙",
    fromPath: "/universe-physics/universe/observable",
    toDomain: "philosophy",
    toId: "kant",
    toTitle: "康德",
    toPath: "/philosophy/thinkers/kant",
    relation: "康德的《纯粹理性批判》探讨了宇宙是否有起点的「二律背反」",
  },
  {
    fromDomain: "universe-physics",
    fromId: "classical-mechanics",
    fromTitle: "经典力学",
    fromPath: "/universe-physics/physics/classical-mechanics",
    toDomain: "mathematics",
    toId: "derivative",
    toTitle: "微积分",
    toPath: "/mathematics/concepts/derivative",
    relation: "牛顿发明微积分正是为了描述力学运动方程",
  },
  {
    fromDomain: "universe-physics",
    fromId: "quantum-mechanics",
    fromTitle: "量子力学",
    fromPath: "/universe-physics/physics/quantum-mechanics",
    toDomain: "mathematics",
    toId: "linear-algebra",
    toTitle: "线性代数",
    toPath: "/mathematics/concepts/linear-algebra",
    relation: "量子态的叠加与测量依赖希尔伯特空间中的线性代数",
  },
  {
    fromDomain: "universe-physics",
    fromId: "relativity",
    fromTitle: "相对论",
    fromPath: "/universe-physics/physics/relativity",
    toDomain: "mathematics",
    toId: "differential-equation",
    toTitle: "微分方程",
    toPath: "/mathematics/concepts/differential-equation",
    relation: "爱因斯坦场方程是一组非线性偏微分方程",
  },
  {
    fromDomain: "universe-physics",
    fromId: "thermodynamics",
    fromTitle: "热力学",
    fromPath: "/universe-physics/physics/thermodynamics",
    toDomain: "mathematics",
    toId: "statistics",
    toTitle: "统计学",
    toPath: "/mathematics/concepts/statistics",
    relation: "统计力学用概率论和统计方法推导热力学定律",
  },
  {
    fromDomain: "universe-physics",
    fromId: "electromagnetism",
    fromTitle: "电磁学",
    fromPath: "/universe-physics/physics/electromagnetism",
    toDomain: "mathematics",
    toId: "multivariable-calculus",
    toTitle: "向量微积分",
    toPath: "/mathematics/concepts/multivariable-calculus",
    relation: "麦克斯韦方程组用向量微积分统一了电与磁",
  },
  {
    fromDomain: "universe-physics",
    fromId: "quantum-mechanics",
    fromTitle: "量子力学",
    fromPath: "/universe-physics/physics/quantum-mechanics",
    toDomain: "philosophy",
    toId: "determinism",
    toTitle: "决定论",
    toPath: "/philosophy/isms/determinism",
    relation: "量子力学的概率诠释对经典决定论构成根本挑战",
  },
  {
    fromDomain: "universe-physics",
    fromId: "relativity",
    fromTitle: "相对论",
    fromPath: "/universe-physics/physics/relativity",
    toDomain: "philosophy",
    toId: "phenomenology",
    toTitle: "现象学",
    toPath: "/philosophy/schools/phenomenology",
    relation: "相对论的时空观革新了现象学对时间意识的分析",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T0-observable",
    fromTitle: "可观测宇宙",
    fromPath: "/universe-physics/universe/observable",
    toDomain: "philosophy",
    toId: "existentialism",
    toTitle: "存在主义",
    toPath: "/philosophy/schools/existentialism",
    relation: "宇宙的浩瀚引发了人类对自身存在意义的终极追问",
  },
  {
    fromDomain: "universe-physics",
    fromId: "T1-cosmic-web",
    fromTitle: "宇宙纤维结构",
    fromPath: "/universe-physics/universe/cosmic-web",
    toDomain: "cosmology",
    toId: "宇宙大尺度结构",
    toTitle: "宇宙大尺度结构",
    toPath: "/cosmology/knowledge-base/宇宙大尺度结构",
    relation: "暗物质的引力塑造了宇宙的大尺度纤维结构",
  },
];
