export {
  getTheoristSlugs,
  getTheoristBySlug,
  getAllTheorists,
  getExperimentSlugs,
  getExperimentBySlug,
  getAllExperiments,
  getPhenomenonSlugs,
  getPhenomenonBySlug,
  getAllPhenomena,
  getSchoolSlugs,
  getSchoolBySlug,
  getAllSchools,
  getDisorderSlugs,
  getDisorderBySlug,
  getAllDisorders,
  getDebateSlugs,
  getDebateBySlug,
  getAllDebates,
  getDialogueSlugs,
  getDialogueBySlug,
  getAllDialogues,
} from "./mdx/index";
