export type {
  Era,
  PhilosopherFrontmatter,
  Philosopher,
  QuestionFrontmatter,
  Question,
  SchoolFrontmatter,
  School,
  ExperimentFrontmatter,
  Experiment,
  DialogueFrontmatter,
  Dialogue,
  ConceptFrontmatter,
  Concept,
} from "@/lib/types";
