// AUTO-GENERATED + merge-preserved by scripts/gen-kb-index.ts (pnpm gen-kb).
// Each slug MUST resolve to a real file under content/universe-physics/knowledge-base/.
export const UNIVERSE_PHYSICS_KB_DATA = [
  {
    slug: "经典物理--角动量与守恒律",
    title: "角动量与守恒律",
    category: "经典物理",
    excerpt: "角动量守恒、开普勒第二定律、转动惯量、自旋、量子角动量、陀螺进动与诺特定理。",
  },
  {
    slug: "物理学--对称性与诺特定理",
    title: "对称性与诺特定理",
    category: "物理学",
    excerpt: "诺特定理、对称性与守恒律、规范对称性、自发对称性破缺、希格斯机制与标准模型。",
  },
  {
    slug: "电磁学--麦克斯韦方程组",
    title: "麦克斯韦方程组",
    category: "电磁学",
    excerpt: "高斯定律、法拉第感应定律、安培-麦克斯韦定律、位移电流、电磁波与光速预言。",
  },
  {
    slug: "前沿物理--核聚变与恒星能源",
    title: "核聚变与恒星能源",
    category: "前沿物理",
    excerpt: "质子-质子链、CNO循环、量子隧穿与太阳能源、劳森判据、ITER托卡马克与恒星核合成。",
  },
  {
    slug: "前沿物理--凝聚态物理与量子材料",
    title: "凝聚态物理与量子材料",
    category: "前沿物理",
    excerpt: "能带论、拓扑绝缘体、量子霍尔效应、石墨烯、魔角超导与涌现现象。",
  },
  {
    slug: "物理学--粒子物理与加速器",
    title: "粒子物理与加速器",
    category: "物理学",
    excerpt: "标准模型、夸克与轻子、规范玻色子、LHC与希格斯玻色子发现、超对称困境。",
  },
  {
    slug: "物理学--宇宙微波背景辐射",
    title: "宇宙微波背景辐射",
    category: "物理学",
    excerpt: "CMB、复合时期、声学振荡、普朗克卫星宇宙学参数、哈勃张力与宇宙暴胀。",
  },
  {
    slug: "电磁学--超导体",
    title: "超导体",
    category: "电磁学",
    excerpt:
      "超导、零电阻、迈斯纳效应、BCS理论、库珀对、临界温度、高温超导、约瑟夫森结、磁通量子化。",
  },
  {
    slug: "电磁学--电磁波谱",
    title: "电磁波谱",
    category: "电磁学",
    excerpt: "无线电波、微波、红外线、可见光、紫外线、X射线、伽马射线、频率、波长与光子能量。",
  },
  {
    slug: "电磁学--法拉第与电磁感应",
    title: "法拉第与电磁感应",
    category: "电磁学",
    excerpt: "法拉第电磁感应定律、磁通量、楞次定律、发电机、变压器、麦克斯韦方程与电磁场。",
  },
  {
    slug: "电磁学--光的本质",
    title: "光的本质",
    category: "电磁学",
    excerpt: "光的波动说、粒子说、光子、波粒二象性、双缝实验、电磁波、量子电动力学与光速。",
  },
  {
    slug: "经典物理--波动与振动",
    title: "波动与振动",
    category: "经典物理",
    excerpt: "简谐振动、波动方程、声波、水波、地震波、横波、纵波、干涉、衍射与多普勒效应。",
  },
  {
    slug: "经典物理--能量守恒",
    title: "能量守恒",
    category: "经典物理",
    excerpt: "能量守恒定律、热力学第一定律、永动机、焦耳、功、内能、热功当量与诺特定理。",
  },
  {
    slug: "经典物理--牛顿三大定律",
    title: "牛顿三大定律",
    category: "经典物理",
    excerpt: "惯性定律、F=ma、作用力与反作用力、参考系、伽利略变换、动量守恒与经典力学。",
  },
  {
    slug: "经典物理--万有引力",
    title: "万有引力",
    category: "经典物理",
    excerpt: "万有引力定律、引力常数、开普勒定律、潮汐、引力场、等效原理、广义相对论与海王星。",
  },
  {
    slug: "量子物理--波粒二象性",
    title: "波粒二象性",
    category: "量子物理",
    excerpt: "双缝实验、光电效应、德布罗意波、互补原理、波函数、概率幅、光子与电子衍射。",
  },
  {
    slug: "量子物理--不确定性原理",
    title: "不确定性原理",
    category: "量子物理",
    excerpt: "海森堡不确定性原理、位置-动量关系、能量-时间关系、量子涨落、零点能与量子极限。",
  },
  {
    slug: "量子物理--量子纠缠",
    title: "量子纠缠",
    category: "量子物理",
    excerpt: "EPR悖论、贝尔不等式、非定域性、量子关联、隐变量、量子通信与量子密钥分发。",
  },
  {
    slug: "量子物理--量子隧穿",
    title: "量子隧穿",
    category: "量子物理",
    excerpt: "隧穿效应、势垒穿透、太阳核聚变、扫描隧穿显微镜、α衰变、约瑟夫森效应与闪存。",
  },
  {
    slug: "前沿物理--暗物质",
    title: "暗物质",
    category: "前沿物理",
    excerpt: "WIMP、轴子、星系旋转曲线、引力透镜、宇宙微波背景、直接探测、间接探测与ΛCDM模型。",
  },
  {
    slug: "前沿物理--量子计算",
    title: "量子计算",
    category: "前沿物理",
    excerpt: "量子比特、量子叠加、量子纠缠、量子算法、Shor算法、Grover算法、量子纠错与量子互联网。",
  },
  {
    slug: "前沿物理--希格斯玻色子",
    title: "希格斯玻色子",
    category: "前沿物理",
    excerpt: "希格斯场、质量起源、对称性自发破缺、标准模型、LHC、CERN、电弱统一与希格斯机制。",
  },
  {
    slug: "前沿物理--弦理论",
    title: "弦理论",
    category: "前沿物理",
    excerpt: "弦理论、额外维度、M理论、超对称、超弦、D膜、弦景观、对偶性与量子引力。",
  },
  {
    slug: "前沿物理--宇宙暴胀",
    title: "宇宙暴胀",
    category: "前沿物理",
    excerpt:
      "极早期宇宙、暴胀场、量子涨落、宇宙微波背景、原初引力波、多宇宙、视界问题与平坦性问题。",
  },
  {
    slug: "热力学--绝对零度",
    title: "绝对零度",
    category: "热力学",
    excerpt:
      "热力学第三定律、玻色-爱因斯坦凝聚、超流体、液氦、量子基态、零点能、激光冷却与磁冷却。",
  },
  {
    slug: "热力学--麦克斯韦妖",
    title: "麦克斯韦妖",
    category: "热力学",
    excerpt: "信息与热力学、兰道尔原理、信息擦除、布里渊、西拉德、贝内特、熵与可逆计算。",
  },
  {
    slug: "热力学--熵与时间之箭",
    title: "熵与时间之箭",
    category: "热力学",
    excerpt: "熵、热力学第二定律、时间之箭、玻尔兹曼、香农、信息熵、可逆性、涨落与麦克斯韦妖。",
  },
  {
    slug: "热力学--相变",
    title: "相变",
    category: "热力学",
    excerpt: "一级相变、二级相变、临界点、三相点、克劳修斯-克拉佩龙方程、朗道理论与对称性破缺。",
  },
  {
    slug: "物理学--暗物质与暗能量",
    title: "暗物质与暗能量",
    category: "物理学",
    excerpt: "暗物质、暗能量、宇宙学常数、WIMP、轴子、星系旋转曲线、超新星、大尺度结构与ΛCDM模型。",
  },
  {
    slug: "物理学--标准模型与超越",
    title: "标准模型与超越",
    category: "物理学",
    excerpt:
      "标准模型、希格斯玻色子、希格斯机制、超对称、大统一理论、夸克、轻子、规范对称性与电弱统一。",
  },
  {
    slug: "物理学--量子力学诠释",
    title: "量子力学诠释",
    category: "物理学",
    excerpt: "哥本哈根诠释、多世界诠释、退相干历史、波函数坍缩、测量问题、薛定谔猫与贝尔不等式。",
  },
  {
    slug: "物理学--引力波天文学",
    title: "引力波天文学",
    category: "物理学",
    excerpt:
      "引力波、LIGO、广义相对论、中子星合并、黑洞、多信使天文学、激光干涉仪与脉冲星计时阵列。",
  },
  {
    slug: "物理学--宇宙的最终命运",
    title: "宇宙的最终命运",
    category: "物理学",
    excerpt: "热寂、大撕裂、大反弹、大挤压、宇宙学常数、熵增、暗能量、质子衰变与霍金辐射。",
  },
  {
    slug: "相对论--广义相对论",
    title: "广义相对论",
    category: "相对论",
    excerpt:
      "弯曲时空、等效原理、爱因斯坦场方程、引力透镜、引力红移、水星近日点进动、黑洞与宇宙学。",
  },
  {
    slug: "相对论--黑洞",
    title: "黑洞",
    category: "相对论",
    excerpt: "事件视界、奇点、史瓦西半径、霍金辐射、超大质量黑洞、恒星坍缩、吸积盘与信息悖论。",
  },
  {
    slug: "相对论--狭义相对论",
    title: "狭义相对论",
    category: "相对论",
    excerpt: "时间膨胀、长度收缩、E=mc²、光速不变原理、洛伦兹变换、同时性的相对性与四维时空。",
  },
  {
    slug: "相对论--引力波",
    title: "引力波",
    category: "相对论",
    excerpt:
      "LIGO、广义相对论、时空涟漪、黑洞合并、中子星、激光干涉仪、脉冲星计时阵列与多信使天文学。",
  },
  {
    slug: "光学--geometric-optics-and-lenses",
    title: "几何光学与透镜成像",
    category: "光学",
    excerpt: "几何光学、折射定律、透镜、焦距、球差、色差、费马原理、成像方程、光学仪器、像差",
  },
  {
    slug: "光学--interference-and-diffraction",
    title: "光的干涉与衍射",
    category: "光学",
    excerpt: "干涉、衍射、杨氏双缝、惠更斯原理、分辨率、全息、衍射极限、相干光、激光",
  },
  {
    slug: "光学--optical-fiber-and-total-internal-reflection",
    title: "光纤与全内反射",
    category: "光学",
    excerpt: "全内反射、光纤、临界角、通信、倏逝波、光纤传感、内窥镜、互联网基础设施",
  },
  {
    slug: "光学--polarization",
    title: "偏振",
    category: "光学",
    excerpt: "偏振、马吕斯定律、双折射、圆偏振、椭圆偏振、布儒斯特角、LCD、光学活性、手性",
  },
  {
    slug: "原子物理--atomic-spectra",
    title: "原子光谱",
    category: "原子物理",
    excerpt: "原子物理、光谱学、发射光谱、吸收光谱、里德堡公式、精细结构、塞曼效应",
  },
  {
    slug: "原子物理--bohr-atom-model",
    title: "玻尔原子模型",
    category: "原子物理",
    excerpt: "原子物理、玻尔模型、量子化、原子光谱、氢原子、角动量量子化、旧量子论",
  },
  {
    slug: "原子物理--electron-orbitals-quantum-numbers",
    title: "电子轨道与量子数",
    category: "原子物理",
    excerpt: "原子物理、原子轨道、量子数、电子构型、洪特规则、构建原理、元素周期律",
  },
  {
    slug: "原子物理--hydrogen-atom-quantum-theory",
    title: "氢原子的量子理论",
    category: "原子物理",
    excerpt: "原子物理、氢原子、薛定谔方程、量子数、原子轨道、球谐函数、精细结构、QED",
  },
  {
    slug: "核物理--binding-energy-mass-defect",
    title: "结合能与质量亏损",
    category: "核物理",
    excerpt: "核物理、结合能、质量亏损、E=mc²、核稳定性、铁峰、核合成、恒星能量",
  },
  {
    slug: "核物理--nuclear-fission",
    title: "核裂变",
    category: "核物理",
    excerpt: "核物理、核裂变、链式反应、临界质量、铀-235、钚-239、核反应堆、原子弹",
  },
  {
    slug: "核物理--radioactive-decay",
    title: "放射性衰变",
    category: "核物理",
    excerpt: "核物理、放射性、α衰变、β衰变、γ辐射、半衰期、居里、卢瑟福、放射性碳定年",
  },
  {
    slug: "热力学--carnot-cycle-and-heat-engines",
    title: "卡诺循环与热机",
    category: "热力学",
    excerpt: "卡诺循环、热机、卡诺效率、可逆过程、等温膨胀、绝热过程、热力学第二定律、制冷机",
  },
  {
    slug: "热力学--kinetic-theory-of-gases",
    title: "气体动理论",
    category: "热力学",
    excerpt:
      "气体动理论、麦克斯韦速率分布、分子碰撞、平均自由程、玻尔兹曼、布朗运动、理想气体、扩散",
  },
  {
    slug: "热力学--laws-of-thermodynamics",
    title: "热力学三大定律",
    category: "热力学",
    excerpt: "热力学、焦耳、克劳修斯、开尔文、热力学第零定律、能量守恒、熵增、绝对零度、热平衡",
  },
  {
    slug: "热力学--phase-transitions-and-critical-phenomena",
    title: "相变与临界现象",
    category: "热力学",
    excerpt: "相变、临界现象、序参量、普适类、伊辛模型、重整化群、超导、超流、临界乳光",
  },
  {
    slug: "热力学--statistical-mechanics-boltzmann",
    title: "统计力学与玻尔兹曼分布",
    category: "热力学",
    excerpt:
      "统计力学、玻尔兹曼分布、配分函数、系综、自由能、涨落、量子统计、费米-狄拉克、玻色-爱因斯坦",
  },
  {
    slug: "电磁学--capacitance-and-inductance",
    title: "电容与电感",
    category: "电磁学",
    excerpt: "电容、电感、LC振荡、电磁感应、自感、互感、变压器、电路、储能、谐振",
  },
  {
    slug: "电磁学--coulomb-law-electrostatics",
    title: "库仑定律与静电场",
    category: "电磁学",
    excerpt: "库仑定律、静电场、电场线、高斯定理、电势、点电荷、叠加原理、麦克斯韦方程",
  },
  {
    slug: "电磁学--dielectrics-and-polarization",
    title: "电介质与电极化",
    category: "电磁学",
    excerpt: "电介质、电极化、介电常数、铁电体、压电效应、偶极子、极化率、分子偶极",
  },
  {
    slug: "电磁学--plasma-physics",
    title: "等离子体物理",
    category: "电磁学",
    excerpt: "等离子体、电离气体、德拜屏蔽、朗缪尔、磁约束、惯性约束、核聚变、太阳风、磁流体力学",
  },
  {
    slug: "粒子物理--antimatter",
    title: "反物质",
    category: "粒子物理",
    excerpt: "粒子物理、反物质、正电子、反质子、湮灭、CP破坏、物质-反物质不对称、狄拉克方程",
  },
  {
    slug: "粒子物理--feynman-diagrams-perturbation",
    title: "费曼图与微扰论",
    category: "粒子物理",
    excerpt: "粒子物理、费曼图、微扰论、量子电动力学、传播子、顶点、精细结构常数、重正化",
  },
  {
    slug: "粒子物理--neutrino-physics",
    title: "中微子物理",
    category: "粒子物理",
    excerpt: "粒子物理、中微子、中微子振荡、中微子质量、β衰变、泡利、太阳中微子问题、大气中微子",
  },
  {
    slug: "粒子物理--quarks-and-leptons",
    title: "夸克与轻子",
    category: "粒子物理",
    excerpt: "粒子物理、夸克、轻子、标准模型、色荷、禁闭、强相互作用、QCD、盖尔曼",
  },
  {
    slug: "经典物理--chaos-three-body-problem",
    title: "混沌与三体问题",
    category: "经典物理",
    excerpt: "混沌、三体问题、蝴蝶效应、庞加莱、李雅普诺夫指数、奇怪吸引子、分形、确定性混沌",
  },
  {
    slug: "经典物理--fluid-mechanics-bernoulli",
    title: "流体力学与伯努利原理",
    category: "经典物理",
    excerpt: "流体力学、伯努利原理、黏性、湍流、纳维-斯托克斯方程、连续性方程、升力、雷诺数",
  },
  {
    slug: "经典物理--lagrangian-hamiltonian-mechanics",
    title: "拉格朗日与哈密顿力学",
    category: "经典物理",
    excerpt: "分析力学、拉格朗日量、哈密顿量、最小作用量原理、广义坐标、诺特定理、辛几何、正则方程",
  },
  {
    slug: "经典物理--momentum-conservation-collisions",
    title: "动量守恒与碰撞",
    category: "经典物理",
    excerpt: "动量守恒、碰撞、弹性碰撞、非弹性碰撞、冲量、质心系、对称性、粒子物理",
  },
  {
    slug: "经典物理--rigid-body-rotation",
    title: "刚体转动与转动惯量",
    category: "经典物理",
    excerpt: "刚体、转动惯量、角动量、力矩、欧拉方程、进动、陀螺、平行轴定理、主轴",
  },
  {
    slug: "经典物理--simple-harmonic-motion",
    title: "简谐振动与共振",
    category: "经典物理",
    excerpt: "简谐振动、共振、胡克定律、角频率、阻尼、受迫振动、弹簧摆、傅里叶分析",
  },
  {
    slug: "经典物理--waves-and-acoustics",
    title: "波动与声学",
    category: "经典物理",
    excerpt: "波动、声学、横波、纵波、多普勒效应、驻波、声速、声强、傅里叶分析、超声波",
  },
  {
    slug: "量子物理--identical-particles-statistics",
    title: "全同粒子与量子统计",
    category: "量子物理",
    excerpt: "量子力学、全同粒子、玻色-爱因斯坦统计、费米-狄拉克统计、BEC、超流、超导",
  },
  {
    slug: "量子物理--pauli-exclusion-principle",
    title: "泡利不相容原理",
    category: "量子物理",
    excerpt: "量子力学、泡利不相容原理、费米子、量子数、电子壳层、元素周期律、白矮星",
  },
  {
    slug: "量子物理--quantum-decoherence",
    title: "量子退相干",
    category: "量子物理",
    excerpt: "量子力学、退相干、量子-经典边界、环境相互作用、密度矩阵、指针态、量子计算",
  },
  {
    slug: "量子物理--quantum-harmonic-oscillator",
    title: "量子谐振子",
    category: "量子物理",
    excerpt: "量子力学、谐振子、零点能、升降算符、量子场论、声子、福克态",
  },
  {
    slug: "量子物理--quantum-measurement",
    title: "量子测量问题",
    category: "量子物理",
    excerpt: "量子力学、测量问题、波函数坍缩、哥本哈根诠释、多世界诠释、退相干、观测者效应",
  },
  {
    slug: "量子物理--quantum-spin",
    title: "量子自旋",
    category: "量子物理",
    excerpt: "量子力学、自旋、角动量、泡利矩阵、斯特恩-盖拉赫实验、自旋磁矩、量子数",
  },
  {
    slug: "量子物理--schrodinger-equation",
    title: "薛定谔方程",
    category: "量子物理",
    excerpt: "量子力学、薛定谔方程、波动方程、哈密顿量、定态、能量本征态、量子动力学",
  },
  {
    slug: "量子物理--wave-function-probability",
    title: "波函数与概率诠释",
    category: "量子物理",
    excerpt: "量子力学、波函数、概率诠释、玻恩规则、测量问题、哥本哈根诠释、叠加态",
  },
  {
    slug: "光学--光的色散与彩虹",
    title: "光的色散与彩虹",
    category: "光学",
    excerpt: "色散、彩虹、折射率、棱镜、牛顿、阿贝折射率、色差",
  },
  {
    slug: "光学--全息术",
    title: "全息术",
    category: "光学",
    excerpt: "全息术、全息图、波前重建、干涉、衍射、三维成像、加博",
  },
  {
    slug: "光学--激光原理与应用",
    title: "激光原理与应用",
    category: "光学",
    excerpt: "激光、受激辐射、粒子数反转、光学谐振腔、相干光、激光应用",
  },
  {
    slug: "光学--非线性光学",
    title: "非线性光学",
    category: "光学",
    excerpt: "非线性光学、倍频、参量过程、克尔效应、孤子、光学参量放大",
  },
  {
    slug: "凝聚态物理--bose-einstein-condensate",
    title: "玻色-爱因斯坦凝聚",
    category: "凝聚态物理",
    excerpt: "凝聚态物理、玻色-爱因斯坦凝聚、BEC、激光冷却、冷原子、量子气体、宏观波函数、诺贝尔奖",
  },
  {
    slug: "凝聚态物理--crystal-structure-bragg-diffraction",
    title: "晶体结构与布拉格衍射",
    category: "凝聚态物理",
    excerpt: "凝聚态物理、晶体学、布拉格衍射、X射线、晶格、单元胞、倒格空间、结构解析",
  },
  {
    slug: "凝聚态物理--phonons-lattice-vibrations",
    title: "声子与晶格振动",
    category: "凝聚态物理",
    excerpt: "凝聚态物理、声子、晶格振动、爱因斯坦模型、德拜模型、热容量、热导率、超导、电声子耦合",
  },
  {
    slug: "凝聚态物理--quantum-hall-effect",
    title: "量子霍尔效应",
    category: "凝聚态物理",
    excerpt:
      "凝聚态物理、量子霍尔效应、拓扑、整数量子霍尔、分数量子霍尔、克利青、劳林、朗道能级、二维电子气",
  },
  {
    slug: "凝聚态物理--semiconductor-physics",
    title: "半导体物理",
    category: "凝聚态物理",
    excerpt: "凝聚态物理、半导体、能带理论、晶体管、掺杂、pn结、硅、集成电路",
  },
  {
    slug: "凝聚态物理--superfluidity",
    title: "超流体",
    category: "凝聚态物理",
    excerpt: "凝聚态物理、超流体、氦-4、氦-3、玻色-爱因斯坦凝聚、朗道、卡皮查、量子涡旋、无粘流动",
  },
  {
    slug: "凝聚态物理--topological-insulators",
    title: "拓扑绝缘体",
    category: "凝聚态物理",
    excerpt:
      "凝聚态物理、拓扑绝缘体、拓扑物质、时间反演对称性、自旋-轨道耦合、表面态、狄拉克锥、量子霍尔效应",
  },
  {
    slug: "应用物理--晶体管与半导体器件",
    title: "晶体管与半导体器件",
    category: "应用物理",
    excerpt: "晶体管、半导体、集成电路、摩尔定律、p-n结、MOSFET、量子效应",
  },
  {
    slug: "应用物理--核磁共振成像MRI原理",
    title: "核磁共振成像MRI原理",
    category: "应用物理",
    excerpt: "MRI、核磁共振、自旋、拉莫尔进动、梯度磁场、傅里叶变换、医学成像",
  },
  {
    slug: "核物理--neutron-capture-nucleosynthesis",
    title: "中子俘获与元素合成",
    category: "核物理",
    excerpt:
      "核物理、元素合成、中子俘获、s过程、r过程、千新星、中子星合并、核天体物理、B2FH、铁峰、重元素起源",
  },
  {
    slug: "核物理--nuclear-magnetic-resonance",
    title: "核磁共振",
    category: "核物理",
    excerpt: "核物理、核磁共振、NMR、MRI、核磁矩、拉莫尔进动、化学位移、自旋弛豫、医学成像、拉比",
  },
  {
    slug: "核物理--nuclear-shell-liquid-drop-models",
    title: "核壳层模型与液滴模型",
    category: "核物理",
    excerpt:
      "核物理、核壳层模型、液滴模型、幻数、结合能、核形状、玛丽亚·迈耶、延森、核裂变、核稳定性",
  },
  {
    slug: "核物理--radioactive-decay-chains",
    title: "核衰变链",
    category: "核物理",
    excerpt:
      "核物理、放射性衰变、衰变链、α衰变、β衰变、γ衰变、半衰期、铀衰变链、核地质学、放射性定年",
  },
  {
    slug: "热力学--制冷与热泵",
    title: "制冷与热泵",
    category: "热力学",
    excerpt: "制冷、热泵、卡诺循环、制冷剂、COP、压缩制冷、热力学第二定律",
  },
  {
    slug: "热力学--热传导对流与辐射",
    title: "热传导对流与辐射",
    category: "热力学",
    excerpt: "热传导、对流、热辐射、傅里叶定律、斯特藩-玻尔兹曼、黑体辐射、传热学",
  },
  {
    slug: "物理学--参考系与惯性",
    title: "参考系与惯性",
    category: "物理学",
    excerpt: "经典力学、参考系、惯性参考系、非惯性参考系、惯性力、科里奥利力、马赫原理、相对论",
  },
  {
    slug: "物理学--多普勒效应与相对论多普勒",
    title: "多普勒效应与相对论多普勒",
    category: "物理学",
    excerpt: "多普勒效应、相对论多普勒、红移、蓝移、横向多普勒、时间膨胀、宇宙学红移、雷达测速",
  },
  {
    slug: "物理学--宇宙学红移与膨胀",
    title: "宇宙学红移与膨胀",
    category: "物理学",
    excerpt: "宇宙学、宇宙膨胀、哈勃定律、宇宙学红移、暗能量、FLRW度规、标度因子、大爆炸",
  },
  {
    slug: "物理学--时间膨胀与长度收缩",
    title: "时间膨胀与长度收缩",
    category: "物理学",
    excerpt: "狭义相对论、时间膨胀、长度收缩、洛伦兹收缩、固有时、固有长度、洛伦兹因子、实验验证",
  },
  {
    slug: "物理学--洛伦兹变换",
    title: "洛伦兹变换",
    category: "物理学",
    excerpt: "狭义相对论、洛伦兹变换、伽利略变换、同时性、时间膨胀、长度收缩、洛伦兹群、惯性参考系",
  },
  {
    slug: "物理学--相对论性动量与能量",
    title: "相对论性动量与能量",
    category: "物理学",
    excerpt:
      "狭义相对论、相对论性动量、相对论性能量、四维动量、能量-动量关系、质量-能量等价、粒子物理",
  },
  {
    slug: "物理学--质能等价",
    title: "质能等价 E=mc²",
    category: "物理学",
    excerpt: "狭义相对论、质能等价、爱因斯坦、核能、静止质量、结合能、核裂变、核聚变",
  },
  {
    slug: "电磁学--天线与电磁辐射",
    title: "天线与电磁辐射",
    category: "电磁学",
    excerpt: "天线、电磁辐射、赫兹、无线通信、雷达、方向性、波段",
  },
  {
    slug: "电磁学--安培定律与磁场",
    title: "安培定律与磁场",
    category: "电磁学",
    excerpt: "安培定律、磁场、比奥-萨伐尔定律、洛伦兹力、电动机、磁性材料",
  },
  {
    slug: "电磁学--电磁波的产生与传播",
    title: "电磁波的产生与传播",
    category: "电磁学",
    excerpt: "电磁波、麦克斯韦、传播、折射率、色散、波速、极化",
  },
  {
    slug: "电磁学--电路分析与基尔霍夫定律",
    title: "电路分析与基尔霍夫定律",
    category: "电磁学",
    excerpt: "电路分析、基尔霍夫定律、电阻、欧姆定律、节点电压、网格电流",
  },
  {
    slug: "相对论--克尔转动黑洞",
    title: "克尔转动黑洞",
    category: "相对论",
    excerpt: "黑洞、克尔度规、转动黑洞、彭德尔顿效应、能层、角动量、吸积盘、相对论喷流",
  },
  {
    slug: "相对论--双生子佯谬",
    title: "双生子佯谬",
    category: "相对论",
    excerpt: "狭义相对论、时间膨胀、双生子佯谬、加速度、固有时、参考系、时空几何",
  },
  {
    slug: "相对论--史瓦西黑洞",
    title: "史瓦西黑洞",
    category: "相对论",
    excerpt: "黑洞、史瓦西度规、事件视界、奇点、广义相对论、时空弯曲、引力坍缩",
  },
  {
    slug: "相对论--广义相对论的实验检验",
    title: "广义相对论的实验检验",
    category: "相对论",
    excerpt: "广义相对论、实验检验、PPN参数、引力波、水星进动、光线偏折、Shapiro延迟、EHT",
  },
  {
    slug: "相对论--引力红移与引力时间膨胀",
    title: "引力红移与引力时间膨胀",
    category: "相对论",
    excerpt: "广义相对论、引力红移、引力时间膨胀、等效原理、GPS、庞德-雷布卡实验、时空弯曲",
  },
  {
    slug: "相对论--引力透镜的物理",
    title: "引力透镜的物理",
    category: "相对论",
    excerpt: "广义相对论、引力透镜、爱因斯坦环、微引力透镜、暗物质、引力弯光、宇宙学",
  },
  {
    slug: "相对论--时空弯曲与测地线",
    title: "时空弯曲与测地线",
    category: "相对论",
    excerpt: "广义相对论、时空弯曲、测地线、黎曼几何、爱因斯坦场方程、曲率张量、自由落体",
  },
  {
    slug: "相对论--等效原理",
    title: "等效原理",
    category: "相对论",
    excerpt: "广义相对论、等效原理、引力质量、惯性质量、爱因斯坦、自由落体、时空弯曲",
  },
  {
    slug: "相对论--闵可夫斯基时空与四维矢量",
    title: "闵可夫斯基时空与四维矢量",
    category: "相对论",
    excerpt: "狭义相对论、闵可夫斯基时空、四维矢量、世界线、固有时、洛伦兹不变量、光锥、时空间隔",
  },
  {
    slug: "粒子物理--cp-violation-matter-antimatter",
    title: "CP破坏与物质反物质不对称",
    category: "粒子物理",
    excerpt:
      "粒子物理、CP破坏、物质反物质不对称、重子不对称、萨哈罗夫条件、中性K介子、B介子、CKM矩阵、弱相互作用",
  },
  {
    slug: "粒子物理--higgs-mechanism",
    title: "希格斯机制与希格斯玻色子",
    category: "粒子物理",
    excerpt: "粒子物理、希格斯玻色子、希格斯机制、标准模型、自发对称破缺、质量起源、LHC、CERN",
  },
  {
    slug: "粒子物理--particle-accelerators",
    title: "粒子加速器与对撞机",
    category: "粒子物理",
    excerpt: "粒子物理、加速器、对撞机、LHC、同步辐射、电子加速器、质子加速器、CERN、费米实验室",
  },
  {
    slug: "粒子物理--quantum-chromodynamics",
    title: "强相互作用与量子色动力学",
    category: "粒子物理",
    excerpt:
      "粒子物理、量子色动力学、QCD、强相互作用、色禁闭、渐近自由、胶子、夸克禁闭、格点QCD、核力",
  },
  {
    slug: "粒子物理--standard-model-overview",
    title: "标准模型概览",
    category: "粒子物理",
    excerpt:
      "粒子物理、标准模型、规范理论、基本粒子、费米子、玻色子、对称性、强相互作用、弱相互作用、电磁相互作用",
  },
  {
    slug: "经典物理--万有引力与开普勒定律",
    title: "万有引力与开普勒定律",
    category: "经典物理",
    excerpt: "万有引力、开普勒定律、牛顿、行星运动、引力常数、轨道力学",
  },
  {
    slug: "经典物理--弹性与材料力学",
    title: "弹性与材料力学",
    category: "经典物理",
    excerpt: "弹性、胡克定律、应力、应变、杨氏模量、材料力学、断裂、疲劳",
  },
  {
    slug: "经典物理--摩擦与耗散",
    title: "摩擦与耗散",
    category: "经典物理",
    excerpt: "摩擦、耗散、库仑摩擦、黏性、阻力、润滑、摩擦学、能量耗散",
  },
  {
    slug: "经典物理--表面张力与毛细现象",
    title: "表面张力与毛细现象",
    category: "经典物理",
    excerpt: "表面张力、毛细现象、浸润、接触角、拉普拉斯压强、生物物理、纳米流体",
  },
  {
    slug: "光学--激光冷却与原子阱",
    title: "激光冷却与原子阱",
    category: "光学",
    excerpt:
      "激光冷却、原子阱、磁光阱、多普勒冷却、蒸发冷却、光晶格、原子钟、量子模拟、冷原子、玻色-爱因斯坦凝聚",
  },
  {
    slug: "凝聚态物理--磁性与铁磁体",
    title: "磁性与铁磁体",
    category: "凝聚态物理",
    excerpt:
      "铁磁性、磁畴、居里温度、反铁磁性、磁滞、量子磁性、海森堡模型、自旋波、磁存储、自旋电子学",
  },
  {
    slug: "前沿物理--量子场论导论",
    title: "量子场论导论",
    category: "前沿物理",
    excerpt: "量子场论、费曼图、重正化、路径积分、虚粒子、量子电动力学、标准模型、真空涨落",
  },
  {
    slug: "原子物理--光电效应与量子化光",
    title: "光电效应与量子化光",
    category: "原子物理",
    excerpt: "光电效应、光量子、光子、爱因斯坦、普朗克常数、功函数、太阳能电池、光电倍增管、量子化",
  },
  {
    slug: "应用物理--地球物理与地震波",
    title: "地球物理与地震波",
    category: "应用物理",
    excerpt: "地球物理、地震波、P波、S波、地球内部结构、板块构造、地震学、莫霍面、地核",
  },
  {
    slug: "应用物理--生物物理导论",
    title: "生物物理导论",
    category: "应用物理",
    excerpt: "生物物理、DNA双螺旋、细胞膜、离子通道、分子马达、蛋白质折叠、布朗运动、物理生物学",
  },
  {
    slug: "应用物理--电子学与放大器电路",
    title: "电子学与放大器电路",
    category: "应用物理",
    excerpt: "电子学、放大器、三极管、运算放大器、负反馈、晶体管、增益、带宽、信号处理、模拟电路",
  },
  {
    slug: "热力学--自由能与化学势",
    title: "自由能与化学势",
    category: "热力学",
    excerpt:
      "自由能、亥姆霍兹自由能、吉布斯自由能、化学势、相平衡、化学平衡、热力学势、麦克斯韦关系",
  },
  {
    slug: "热力学--非平衡态热力学",
    title: "非平衡态热力学",
    category: "热力学",
    excerpt:
      "非平衡态热力学、昂萨格关系、最小熵产生、普里戈金、耗散结构、自组织、贝纳德对流、化学振荡",
  },
  {
    slug: "物理学--对称性与群论基础",
    title: "对称性与群论基础",
    category: "物理学",
    excerpt: "对称性、群论、诺特定理、规范对称性、李群、守恒律、标准模型、自发对称性破缺",
  },
  {
    slug: "物理学--普朗克常数与量子化",
    title: "普朗克常数与量子化",
    category: "物理学",
    excerpt: "普朗克常数、黑体辐射、量子化、普朗克、维恩定律、瑞利-金斯公式、紫外灾难、自然单位制",
  },
  {
    slug: "相对论--相对论性动力学与四维力",
    title: "相对论性动力学与四维力",
    category: "相对论",
    excerpt:
      "相对论性动力学、四维力、相对论性动量、质能方程、相对论性粒子、加速器物理、闵可夫斯基时空、四维速度",
  },
  {
    slug: "经典物理--声学与多普勒效应",
    title: "声学与多普勒效应",
    category: "经典物理",
    excerpt: "声学、多普勒效应、声速、音调、超声波、冲击波、马赫数、次声波、建筑声学、声纳",
  },
  {
    slug: "经典物理--振动与简正模式",
    title: "振动与简正模式",
    category: "经典物理",
    excerpt: "简正模式、振动、耦合振子、共振、傅里叶分析、声学、正则坐标、简谐振动、本征值",
  },
  {
    slug: "经典物理--流体湍流与雷诺数",
    title: "流体湍流与雷诺数",
    category: "经典物理",
    excerpt: "湍流、雷诺数、流体力学、纳维-斯托克斯方程、层流、混沌、边界层、湍流模型",
  },
  {
    slug: "前沿物理--量子场论与重整化",
    title: "量子场论与重整化",
    category: "前沿物理",
    excerpt: "量子场论、重整化、重整化群、跑动耦合、有效场论、费曼图、紫外发散、标准模型",
  },
  {
    slug: "天体物理--恒星结构与演化",
    title: "恒星结构与演化",
    category: "天体物理",
    excerpt:
      "恒星结构、流体静力平衡、核聚变、主序星、红巨星、白矮星、中子星、简并压、钱德拉塞卡极限",
  },
];
