export const CONCEPTS = [
  { slug: "categorical-imperative", title: "绝对命令", title_en: "Categorical Imperative", field: "伦理学", key_figures: ["康德"] },
  { slug: "social-contract", title: "社会契约", title_en: "Social Contract", field: "政治哲学", key_figures: ["霍布斯", "洛克", "卢梭"] },
  { slug: "tabula-rasa", title: "白板说", title_en: "Tabula Rasa", field: "认识论", key_figures: ["洛克"] },
  { slug: "cogito", title: "我思故我在", title_en: "Cogito Ergo Sum", field: "认识论", key_figures: ["笛卡尔"] },
  { slug: "allegory-of-cave", title: "洞穴比喻", title_en: "Allegory of the Cave", field: "形而上学", key_figures: ["柏拉图"] },
  { slug: "golden-mean", title: "中庸之道", title_en: "Golden Mean", field: "伦理学", key_figures: ["亚里士多德", "孔子"] },
  { slug: "will-to-power", title: "权力意志", title_en: "Will to Power", field: "形而上学", key_figures: ["尼采"] },
  { slug: "veil-of-ignorance", title: "无知之幕", title_en: "Veil of Ignorance", field: "政治哲学", key_figures: ["罗尔斯"] },
  { slug: "utilitarianism-concept", title: "功利主义", title_en: "Utilitarianism", field: "伦理学", key_figures: ["边沁", "密尔"] },
  { slug: "existentialism-concept", title: "存在主义", title_en: "Existentialism", field: "形而上学", key_figures: ["萨特", "海德格尔", "加缪"] },
  { slug: "dualism", title: "二元论", title_en: "Dualism", field: "形而上学", key_figures: ["笛卡尔"] },
  { slug: "phenomenology", title: "现象学", title_en: "Phenomenology", field: "认识论", key_figures: ["胡塞尔", "海德格尔"] },
  { slug: "deconstruction", title: "解构主义", title_en: "Deconstruction", field: "逻辑学", key_figures: ["德里达"] },
  { slug: "empiricism", title: "经验主义", title_en: "Empiricism", field: "认识论", key_figures: ["休谟", "洛克", "贝克莱"] },
  { slug: "rationalism", title: "理性主义", title_en: "Rationalism", field: "认识论", key_figures: ["笛卡尔", "斯宾诺莎", "莱布尼茨"] },
  { slug: "materialism", title: "唯物主义", title_en: "Materialism", field: "形而上学", key_figures: ["马克思", "德谟克利特"] },
  { slug: "idealism", title: "唯心主义", title_en: "Idealism", field: "形而上学", key_figures: ["柏拉图", "黑格尔", "贝克莱"] },
  { slug: "nihilism", title: "虚无主义", title_en: "Nihilism", field: "形而上学", key_figures: ["尼采"] },
  { slug: "absurdism", title: "荒诞主义", title_en: "Absurdism", field: "伦理学", key_figures: ["加缪"] },
  { slug: "stoicism-concept", title: "斯多葛主义", title_en: "Stoicism", field: "伦理学", key_figures: ["爱比克泰德", "马可·奥勒留", "塞涅卡"] },
  { slug: "epicureanism", title: "伊壁鸠鲁主义", title_en: "Epicureanism", field: "伦理学", key_figures: ["伊壁鸠鲁"] },
  { slug: "free-will", title: "自由意志", title_en: "Free Will", field: "形而上学", key_figures: ["康德", "萨特", "休谟"] },
  { slug: "determinism", title: "决定论", title_en: "Determinism", field: "形而上学", key_figures: ["拉普拉斯", "斯宾诺莎"] },
  { slug: "hermeneutics", title: "诠释学", title_en: "Hermeneutics", field: "认识论", key_figures: ["伽达默尔", "施莱尔马赫"] },
  { slug: "pragmatism", title: "实用主义", title_en: "Pragmatism", field: "认识论", key_figures: ["詹姆斯", "皮尔士", "杜威"] },
  { slug: "monism", title: "一元论", title_en: "Monism", field: "形而上学", key_figures: ["斯宾诺莎", "黑格尔"] },
  { slug: "dialectics", title: "辩证法", title_en: "Dialectics", field: "逻辑学", key_figures: ["黑格尔", "马克思"] },
  { slug: "aesthetics", title: "美学", title_en: "Aesthetics", field: "美学", key_figures: ["康德", "黑格尔", "鲍姆加登"] },
  { slug: "sublime", title: "崇高", title_en: "The Sublime", field: "美学", key_figures: ["伯克", "康德"] },
  { slug: "will", title: "意志", title_en: "The Will", field: "形而上学", key_figures: ["叔本华", "尼采", "康德"] },
  { slug: "overman", title: "超人", title_en: "Übermensch", field: "伦理学", key_figures: ["尼采"] },
  { slug: "eternal-recurrence", title: "永恒回归", title_en: "Eternal Recurrence", field: "形而上学", key_figures: ["尼采"] },
  { slug: "intersubjectivity", title: "主体间性", title_en: "Intersubjectivity", field: "认识论", key_figures: ["胡塞尔", "哈贝马斯"] },
  { slug: "deconstruction-concept", title: "差异", title_en: "Différance", field: "逻辑学", key_figures: ["德里达"] },
  { slug: "biopower", title: "生命权力", title_en: "Biopower", field: "政治哲学", key_figures: ["福柯"] },
  { slug: "discourse", title: "话语", title_en: "Discourse", field: "逻辑学", key_figures: ["福柯", "哈贝马斯"] },
  { slug: "simulacrum", title: "拟像", title_en: "Simulacrum", field: "形而上学", key_figures: ["鲍德里亚"] },
  { slug: "other", title: "他者", title_en: "The Other", field: "伦理学", key_figures: ["列维纳斯", "萨特", "波伏瓦"] },
  { slug: "jouissance", title: "享乐", title_en: "Jouissance", field: "伦理学", key_figures: ["拉康", "巴特"] },
  { slug: "noosphere", title: "心智圈", title_en: "Noosphere", field: "形而上学", key_figures: ["德日进", "维尔纳茨基"] },
] as const;
