export const ISMS = [
  { slug: "materialism", title: "唯物主义", title_en: "Materialism", category: "本体论", era: "古代", key_figures: ["德谟克利特", "马克思", "霍布斯"] },
  { slug: "idealism", title: "唯心主义", title_en: "Idealism", category: "本体论", era: "古代", key_figures: ["柏拉图", "黑格尔", "贝克莱"] },
  { slug: "dualism", title: "二元论", title_en: "Dualism", category: "本体论", era: "近代", key_figures: ["笛卡尔"] },
  { slug: "monism", title: "一元论", title_en: "Monism", category: "本体论", era: "近代", key_figures: ["斯宾诺莎"] },
  { slug: "pantheism", title: "泛神论", title_en: "Pantheism", category: "本体论", era: "近代", key_figures: ["斯宾诺莎"] },
  { slug: "empiricism", title: "经验主义", title_en: "Empiricism", category: "认识论", era: "近代", key_figures: ["休谟", "洛克", "贝克莱"] },
  { slug: "rationalism", title: "理性主义", title_en: "Rationalism", category: "认识论", era: "近代", key_figures: ["笛卡尔", "斯宾诺莎", "莱布尼茨"] },
  { slug: "skepticism", title: "怀疑主义", title_en: "Skepticism", category: "认识论", era: "古代", key_figures: ["皮浪", "休谟"] },
  { slug: "positivism", title: "实证主义", title_en: "Positivism", category: "认识论", era: "近代", key_figures: ["孔德", "密尔"] },
  { slug: "pragmatism", title: "实用主义", title_en: "Pragmatism", category: "认识论", era: "现代", key_figures: ["詹姆斯", "皮尔士", "杜威"] },
  { slug: "utilitarianism", title: "功利主义", title_en: "Utilitarianism", category: "伦理学", era: "近代", key_figures: ["边沁", "密尔"] },
  { slug: "deontology", title: "义务论", title_en: "Deontology", category: "伦理学", era: "近代", key_figures: ["康德"] },
  { slug: "virtue-ethics", title: "德性伦理学", title_en: "Virtue Ethics", category: "伦理学", era: "古代", key_figures: ["亚里士多德"] },
  { slug: "stoicism", title: "斯多葛主义", title_en: "Stoicism", category: "伦理学", era: "古代", key_figures: ["爱比克泰德", "马可·奥勒留", "塞涅卡"] },
  { slug: "epicureanism", title: "伊壁鸠鲁主义", title_en: "Epicureanism", category: "伦理学", era: "古代", key_figures: ["伊壁鸠鲁"] },
  { slug: "nihilism", title: "虚无主义", title_en: "Nihilism", category: "伦理学", era: "近代", key_figures: ["尼采"] },
  { slug: "existentialism", title: "存在主义", title_en: "Existentialism", category: "伦理学", era: "现代", key_figures: ["萨特", "海德格尔", "加缪"] },
  { slug: "absurdism", title: "荒诞主义", title_en: "Absurdism", category: "伦理学", era: "现代", key_figures: ["加缪"] },
  { slug: "structuralism", title: "结构主义", title_en: "Structuralism", category: "逻辑学", era: "现代", key_figures: ["索绪尔", "列维-斯特劳斯"] },
  { slug: "post-structuralism", title: "后结构主义", title_en: "Post-Structuralism", category: "逻辑学", era: "当代", key_figures: ["德里达", "福柯"] },
  { slug: "deconstruction", title: "解构主义", title_en: "Deconstruction", category: "逻辑学", era: "当代", key_figures: ["德里达"] },
  { slug: "phenomenology", title: "现象学", title_en: "Phenomenology", category: "认识论", era: "现代", key_figures: ["胡塞尔", "海德格尔"] },
  { slug: "hermeneutics", title: "诠释学", title_en: "Hermeneutics", category: "认识论", era: "现代", key_figures: ["伽达默尔", "施莱尔马赫"] },
  { slug: "marxism", title: "马克思主义", title_en: "Marxism", category: "政治哲学", era: "近代", key_figures: ["马克思", "恩格斯"] },
  { slug: "feminism", title: "女性主义", title_en: "Feminism", category: "政治哲学", era: "现代", key_figures: ["波伏瓦", "巴特勒"] },
  { slug: "liberalism", title: "自由主义", title_en: "Liberalism", category: "政治哲学", era: "近代", key_figures: ["洛克", "密尔", "罗尔斯"] },
  { slug: "social-contract-theory", title: "社会契约论", title_en: "Social Contract Theory", category: "政治哲学", era: "近代", key_figures: ["霍布斯", "洛克", "卢梭"] },
] as const;
