export const QUESTIONS = [
  { slug: "what-is-real", title: "什么是真实？", field: "形而上学", key_figures: ["柏拉图", "笛卡尔", "贝克莱"], tags: ["存在", "现实"] },
  { slug: "free-will-exists", title: "自由意志存在吗？", field: "形而上学", key_figures: ["康德", "休谟", "萨特"], tags: ["决定论", "自由"] },
  { slug: "what-is-knowledge", title: "什么是知识？", field: "认识论", key_figures: ["柏拉图", "笛卡尔", "盖梯尔"], tags: ["知识", "信念"] },
  { slug: "mind-body-problem", title: "心灵与身体的关系是什么？", field: "形而上学", key_figures: ["笛卡尔", "莱布尼茨", "查尔默斯"], tags: ["意识", "二元论"] },
  { slug: "what-is-justice", title: "什么是正义？", field: "政治哲学", key_figures: ["柏拉图", "罗尔斯", "诺齐克"], tags: ["公正", "分配"] },
  { slug: "meaning-of-life", title: "生命的意义是什么？", field: "伦理学", key_figures: ["亚里士多德", "加缪", "弗兰克尔"], tags: ["存在", "目的"] },
  { slug: "does-god-exist", title: "神存在吗？", field: "宗教哲学", key_figures: ["阿奎那", "安瑟伦", "帕斯卡"], tags: ["信仰", "理性"] },
  { slug: "what-is-beauty", title: "什么是美？", field: "美学", key_figures: ["柏拉图", "康德", "黑格尔"], tags: ["审美", "艺术"] },
  { slug: "problem-of-evil", title: "恶的问题如何解答？", field: "宗教哲学", key_figures: ["奥古斯丁", "莱布尼茨", "休谟"], tags: ["神义论", "苦难"] },
  { slug: "what-is-consciousness", title: "什么是意识？", field: "心灵哲学", key_figures: ["笛卡尔", "内格尔", "查尔默斯"], tags: ["感质", "心灵"] },
  { slug: "personal-identity", title: "什么使你成为你？", field: "形而上学", key_figures: ["洛克", "休谟", "帕菲特"], tags: ["同一性", "自我"] },
  { slug: "trolley-problem-q", title: "我们应该如何做道德决策？", field: "伦理学", key_figures: ["康德", "密尔", "福特"], tags: ["功利主义", "义务论"] },
  { slug: "what-is-time", title: "什么是时间？", field: "形而上学", key_figures: ["奥古斯丁", "麦克塔格特", "爱因斯坦"], tags: ["时间", "永恒"] },
  { slug: "language-thought", title: "语言如何塑造思维？", field: "语言哲学", key_figures: ["维特根斯坦", "乔姆斯基", "沃尔夫"], tags: ["语言", "认知"] },
  { slug: "can-machines-think", title: "机器能思考吗？", field: "心灵哲学", key_figures: ["图灵", "塞尔", "丹尼特"], tags: ["人工智能", "意识"] },
  { slug: "what-is-art", title: "什么是艺术？", field: "美学", key_figures: ["柏拉图", "托尔斯泰", "丹托"], tags: ["美学", "创造"] },
  { slug: "nature-of-morality", title: "道德是客观的还是主观的？", field: "伦理学", key_figures: ["柏拉图", "休谟", "麦基"], tags: ["道德实在论", "相对主义"] },
  { slug: "political-obligation", title: "我们为什么有服从国家的义务？", field: "政治哲学", key_figures: ["霍布斯", "洛克", "沃尔夫"], tags: ["权威", "自由"] },
  { slug: "problem-of-induction", title: "归纳推理可靠吗？", field: "认识论", key_figures: ["休谟", "波普尔", "古德曼"], tags: ["科学方法", "因果"] },
  { slug: "what-is-truth", title: "什么是真理？", field: "认识论", key_figures: ["亚里士多德", "塔斯基", "詹姆斯"], tags: ["真理", "符合论"] },
] as const;
