export const SCHOOLS_DATA = [
  { slug: "african-philosophy", title: "非洲哲学", subtitle: "African Philosophy", era: "古代" },
  { slug: "analytic-philosophy", title: "分析哲学", subtitle: "Analytic Philosophy", era: "当代" },
  { slug: "aristotelianism", title: "亚里士多德主义", subtitle: "Aristotelianism", era: "古代" },
  { slug: "buddhism-philosophy", title: "佛教哲学", subtitle: "Buddhist Philosophy", era: "古代" },
  { slug: "chinese-buddhism", title: "中国佛教哲学", subtitle: "Chinese Buddhism", era: "古代" },
  { slug: "confucianism-extended", title: "儒学扩展", subtitle: "Confucianism Extended", era: "跨时代" },
  { slug: "confucianism", title: "儒家哲学体系", subtitle: "Confucianism", era: "古代" },
  { slug: "continental-philosophy", title: "大陆哲学", subtitle: "Continental Philosophy", era: "当代" },
  { slug: "critical-theory", title: "批判理论", subtitle: "Critical Theory", era: "当代" },
  { slug: "cynicism", title: "犬儒主义", subtitle: "Cynicism", era: "古代" },
  { slug: "empiricism", title: "经验主义", subtitle: "Empiricism", era: "近代" },
  { slug: "epicureanism", title: "伊壁鸠鲁主义", subtitle: "Epicureanism", era: "古代" },
  { slug: "existentialism-early", title: "早期存在主义", subtitle: "Early Existentialism", era: "近代" },
  { slug: "existentialism", title: "存在主义", subtitle: "Existentialism", era: "现代" },
  { slug: "feminist-philosophy", title: "女性主义哲学", subtitle: "Feminist Philosophy", era: "当代" },
  { slug: "german-idealism", title: "德国古典哲学", subtitle: "German Idealism", era: "近代" },
  { slug: "hindu-philosophy", title: "印度哲学六派", subtitle: "Hindu Philosophy", era: "古代" },
  { slug: "legalism", title: "法家", subtitle: "Legalism", era: "古代" },
  { slug: "logical-positivism", title: "逻辑实证主义", subtitle: "Logical Positivism", era: "现代" },
  { slug: "marxism-philosophy", title: "马克思主义哲学", subtitle: "Marxist Philosophy", era: "近代" },
  { slug: "mohism", title: "墨家", subtitle: "Mohism", era: "古代" },
  { slug: "neo-confucianism", title: "宋明理学", subtitle: "Neo-Confucianism", era: "古代" },
  { slug: "neoplatonism", title: "新柏拉图主义", subtitle: "Neoplatonism", era: "古代" },
  { slug: "phenomenology", title: "现象学", subtitle: "Phenomenology", era: "现代" },
  { slug: "philosophy-of-mind", title: "心灵哲学", subtitle: "Philosophy of Mind", era: "当代" },
  { slug: "platonism", title: "柏拉图主义", subtitle: "Platonism", era: "古代" },
  { slug: "political-philosophy", title: "政治哲学", subtitle: "Political Philosophy", era: "当代" },
  { slug: "post-structuralism", title: "后结构主义", subtitle: "Post-Structuralism", era: "当代" },
  { slug: "postmodernism", title: "后现代主义", subtitle: "Postmodernism", era: "当代" },
  { slug: "pragmatism", title: "实用主义", subtitle: "Pragmatism", era: "现代" },
  { slug: "presocratics", title: "前苏格拉底哲学", subtitle: "Pre-Socratics", era: "古代" },
  { slug: "rationalism", title: "理性主义", subtitle: "Rationalism", era: "近代" },
  { slug: "sophists", title: "智者学派", subtitle: "Sophists", era: "古代" },
  { slug: "stoicism", title: "斯多葛主义", subtitle: "Stoicism", era: "古代" },
  { slug: "structuralism-poststructuralism", title: "结构主义与后结构主义", subtitle: "Structuralism & Post-Structuralism", era: "当代" },
  { slug: "structuralism", title: "结构主义", subtitle: "Structuralism", era: "当代" },
  { slug: "taoism", title: "道家哲学体系", subtitle: "Taoism", era: "古代" },
  { slug: "utilitarianism", title: "功利主义", subtitle: "Utilitarianism", era: "近代" },
] as const;
