export const THINKERS_DATA = [
  { slug: "al-ghazali", title: "安萨里", subtitle: "Al-Ghazali", era: "近代" },
  { slug: "aquinas", title: "托马斯·阿奎那", subtitle: "Thomas Aquinas", era: "古代" },
  { slug: "aristotle", title: "亚里士多德", subtitle: "Aristotle", era: "古代" },
  { slug: "augustine", title: "奥古斯丁", subtitle: "Augustine of Hippo", era: "古代" },
  { slug: "averroes", title: "阿威罗伊", subtitle: "Averroes", era: "近代" },
  { slug: "avicenna", title: "阿维森纳", subtitle: "Avicenna", era: "近代" },
  { slug: "baudrillard", title: "鲍德里亚", subtitle: "Jean Baudrillard", era: "当代" },
  { slug: "buddha", title: "释迦牟尼", subtitle: "Siddhartha Gautama", era: "古代" },
  { slug: "confucius", title: "孔子", subtitle: "Confucius", era: "古代" },
  { slug: "deleuze", title: "德勒兹", subtitle: "Gilles Deleuze", era: "当代" },
  { slug: "derrida", title: "德里达", subtitle: "Jacques Derrida", era: "当代" },
  { slug: "descartes", title: "笛卡尔", subtitle: "René Descartes", era: "近代" },
  { slug: "dong-zhongshu", title: "董仲舒", subtitle: "Dong Zhongshu", era: "近代" },
  { slug: "edward-said", title: "爱德华·萨义德", subtitle: "Edward Said", era: "当代" },
  { slug: "epictetus", title: "爱比克泰德", subtitle: "Epictetus", era: "古代" },
  { slug: "epicurus", title: "伊壁鸠鲁", subtitle: "Epicurus", era: "古代" },
  { slug: "foucault", title: "福柯", subtitle: "Michel Foucault", era: "当代" },
  { slug: "frege", title: "弗雷格", subtitle: "Gottlob Frege", era: "近代" },
  { slug: "gadamer", title: "伽达默尔", subtitle: "Hans-Georg Gadamer", era: "当代" },
  { slug: "gayatri-spivak", title: "佳亚特里·斯皮瓦克", subtitle: "Gayatri Chakravorty Spivak", era: "当代" },
  { slug: "habermas", title: "哈贝马斯", subtitle: "Jürgen Habermas", era: "当代" },
  { slug: "han-feizi", title: "韩非子", subtitle: "Han Feizi", era: "古代" },
  { slug: "hannah-arendt", title: "汉娜·阿伦特", subtitle: "Hannah Arendt", era: "当代" },
  { slug: "hans-jonas", title: "汉斯·约纳斯", subtitle: "Hans Jonas", era: "当代" },
  { slug: "hegel", title: "黑格尔", subtitle: "Hegel", era: "近代" },
  { slug: "heidegger", title: "海德格尔", subtitle: "Martin Heidegger", era: "现代" },
  { slug: "hume", title: "休谟", subtitle: "David Hume", era: "近代" },
  { slug: "husserl", title: "胡塞尔", subtitle: "Edmund Husserl", era: "现代" },
  { slug: "ibn-khaldun", title: "伊本·赫勒敦", subtitle: "Ibn Khaldun", era: "近代" },
  { slug: "kant", title: "康德", subtitle: "Immanuel Kant", era: "近代" },
  { slug: "kierkegaard", title: "克尔凯郭尔", subtitle: "Søren Kierkegaard", era: "近代" },
  { slug: "laozi", title: "老子", subtitle: "Laozi", era: "古代" },
  { slug: "leibniz", title: "莱布尼茨", subtitle: "Leibniz", era: "近代" },
  { slug: "levinas", title: "列维纳斯", subtitle: "Emmanuel Levinas", era: "当代" },
  { slug: "locke", title: "洛克", subtitle: "John Locke", era: "近代" },
  { slug: "marcus-aurelius", title: "马可·奥勒留", subtitle: "Marcus Aurelius", era: "古代" },
  { slug: "marx", title: "马克思", subtitle: "Karl Marx", era: "近代" },
  { slug: "mencius", title: "孟子", subtitle: "Mencius", era: "古代" },
  { slug: "merleau-ponty", title: "梅洛-庞蒂", subtitle: "Maurice Merleau-Ponty", era: "当代" },
  { slug: "montesquieu", title: "孟德斯鸠", subtitle: "Montesquieu", era: "近代" },
  { slug: "mozi", title: "墨子", subtitle: "Mozi", era: "古代" },
  { slug: "nagarjuna", title: "龙树", subtitle: "Nagarjuna", era: "古代" },
  { slug: "nietzsche", title: "尼采", subtitle: "Friedrich Nietzsche", era: "近代" },
  { slug: "nishida-kitaro", title: "西田几多郎", subtitle: "Nishida Kitaro", era: "当代" },
  { slug: "plato", title: "柏拉图", subtitle: "Plato", era: "古代" },
  { slug: "popper", title: "波普尔", subtitle: "Karl Popper", era: "当代" },
  { slug: "quine", title: "蒯因", subtitle: "W.V.O. Quine", era: "当代" },
  { slug: "ramanuja", title: "罗摩努阇", subtitle: "Ramanuja", era: "古代" },
  { slug: "rawls", title: "罗尔斯", subtitle: "John Rawls", era: "当代" },
  { slug: "russell", title: "罗素", subtitle: "Bertrand Russell", era: "当代" },
  { slug: "sartre", title: "萨特", subtitle: "Jean-Paul Sartre", era: "当代" },
  { slug: "schopenhauer", title: "叔本华", subtitle: "Arthur Schopenhauer", era: "近代" },
  { slug: "seneca", title: "塞涅卡", subtitle: "Seneca", era: "古代" },
  { slug: "shankara", title: "商羯罗", subtitle: "Shankara", era: "古代" },
  { slug: "simone-de-beauvoir", title: "波伏瓦", subtitle: "Simone de Beauvoir", era: "当代" },
  { slug: "simone-weil", title: "西蒙娜·薇依", subtitle: "Simone Weil", era: "当代" },
  { slug: "socrates", title: "苏格拉底", subtitle: "Socrates", era: "古代" },
  { slug: "spinoza", title: "斯宾诺莎", subtitle: "Spinoza", era: "近代" },
  { slug: "thomas-kuhn", title: "托马斯·库恩", subtitle: "Thomas Kuhn", era: "当代" },
  { slug: "toegye", title: "退溪李滉", subtitle: "Toegye (Yi Hwang)", era: "近代" },
  { slug: "wang-fuzhi", title: "王夫之", subtitle: "Wang Fuzhi", era: "近代" },
  { slug: "wang-yangming", title: "王阳明", subtitle: "Wang Yangming", era: "近代" },
  { slug: "wittgenstein", title: "维特根斯坦", subtitle: "Ludwig Wittgenstein", era: "当代" },
  { slug: "xunzi-extended", title: "荀子（深度扩展）", subtitle: "Xunzi (Extended)", era: "古代" },
  { slug: "xunzi", title: "荀子", subtitle: "Xunzi", era: "古代" },
  { slug: "zhou-dunyi", title: "周敦颐", subtitle: "Zhou Dunyi", era: "近代" },
  { slug: "zhu-xi", title: "朱熹", subtitle: "Zhu Xi", era: "近代" },
  { slug: "zhuangzi", title: "庄子", subtitle: "Zhuangzi", era: "古代" },
] as const;
