// @vitest-environment happy-dom
import { existsSync, readFileSync } from "node:fs";
import { afterEach, describe, expect, it, vi } from "vitest";
import {
  createSearchClient,
  isSafeSearchHit,
  loadArtifact,
  SEARCH_WORKER_TIMEOUT_MS,
} from "../client";
import { SEARCH_INDEX_URL, SEARCH_INDEX_VERSION } from "../types";

const artifactJson = readFileSync("public/search-index.json", "utf-8");

function mockFetch(body: string, ok = true) {
  const fetchMock = vi.fn().mockResolvedValue({
    ok,
    json: async () => JSON.parse(body) as unknown,
  });
  vi.stubGlobal("fetch", fetchMock);
  return fetchMock;
}

afterEach(() => {
  vi.useRealTimers();
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
});

describe("loadArtifact", () => {
  it("fetches the generated index", async () => {
    const fetchMock = mockFetch(artifactJson);
    const artifact = await loadArtifact();
    expect(fetchMock).toHaveBeenCalledWith(SEARCH_INDEX_URL, expect.anything());
    expect(artifact.v).toBe(SEARCH_INDEX_VERSION);
  });

  it("rejects an index built by an incompatible generator", async () => {
    mockFetch(JSON.stringify({ v: SEARCH_INDEX_VERSION + 1, docs: [], index: {} }));
    await expect(loadArtifact()).rejects.toThrow(/version/i);
  });

  it("rejects a failed response instead of parsing an error page", async () => {
    mockFetch("{}", false);
    await expect(loadArtifact()).rejects.toThrow();
  });
});

describe("search client module graph", () => {
  it("ships a classic worker file outside the Turbopack chunk wrapper", () => {
    expect(existsSync("public/search.worker.js")).toBe(true);
    expect(readFileSync("public/search.worker.js", "utf-8")).toContain(
      "generated by pnpm gen-search-worker"
    );
  });

  it("does not statically import MiniSearch or the engine", () => {
    const src = readFileSync("lib/search/client.ts", "utf-8");
    expect(src).not.toMatch(/from ["']minisearch["']/);
    expect(src).not.toMatch(/^import (?!type\s)[^;]+from ["']\.\/engine["']/m);
    expect(src).not.toMatch(/^export (?!type\s)[^;]+from ["']\.\/engine["']/m);
    expect(src).toContain('import("./engine")');
  });
});

describe("createSearchClient without a Worker", () => {
  it("still answers queries on the main thread", async () => {
    vi.stubGlobal("Worker", undefined);
    mockFetch(artifactJson);

    const client = createSearchClient();
    const hits = await client.search("热力学", 5);

    expect(hits.length).toBeGreaterThan(0);
    expect(hits[0]!.url.startsWith("/")).toBe(true);
  });

  it("loads the index once no matter how many queries arrive", async () => {
    vi.stubGlobal("Worker", undefined);
    const fetchMock = mockFetch(artifactJson);

    const client = createSearchClient();
    await Promise.all([client.search("熵", 5), client.search("引力", 5), client.search("演化", 5)]);

    expect(fetchMock).toHaveBeenCalledTimes(1);
  });

  it("reports no results rather than throwing when the index cannot load", async () => {
    vi.stubGlobal("Worker", undefined);
    vi.stubGlobal("fetch", vi.fn().mockRejectedValue(new Error("offline")));

    const client = createSearchClient();
    await expect(client.search("熵", 5)).resolves.toEqual([]);
  });

  it("schedules warmup on idle instead of parsing inside the open handler", async () => {
    vi.stubGlobal("Worker", undefined);
    const fetchMock = mockFetch(artifactJson);
    const idle = vi.fn((callback: IdleRequestCallback) => {
      callback({ didTimeout: false, timeRemaining: () => 10 } as IdleDeadline);
      return 1;
    });
    vi.stubGlobal("requestIdleCallback", idle);

    const client = createSearchClient();
    client.warmup();

    expect(idle).toHaveBeenCalledTimes(1);
    await client.search("熵", 3);
    expect(fetchMock).toHaveBeenCalledTimes(1);
  });
});

describe("createSearchClient with a Worker", () => {
  it("answers title queries through the worker protocol", async () => {
    class FakeWorker {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      constructor(public url: string) {}
      postMessage(data: { type: string; id?: number; query?: string; limit?: number }) {
        if (data.type === "search") {
          queueMicrotask(() => {
            this.onmessage?.({
              data: {
                type: "result",
                id: data.id,
                hits: [
                  {
                    title: "热力学",
                    subtitle: "",
                    url: "/universe-physics/physics/thermodynamics",
                    section: "universe-physics",
                    kind: "concept",
                    score: 1,
                  },
                ],
              },
            } as MessageEvent);
          });
        }
      }
      terminate() {}
    }
    vi.stubGlobal("Worker", FakeWorker);

    const client = createSearchClient();
    const hits = await client.search("热力学", 5);

    expect(hits[0]?.url).toBe("/universe-physics/physics/thermodynamics");
    client.dispose();
  });

  it("falls back to the main thread when the worker errors", async () => {
    class FakeWorker {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      constructor(public url: string) {
        queueMicrotask(() => this.onerror?.(new ErrorEvent("error")));
      }
      postMessage() {}
      terminate() {}
    }
    vi.stubGlobal("Worker", FakeWorker);
    mockFetch(artifactJson);

    const client = createSearchClient();
    const hits = await client.search("热力学", 5);
    expect(hits.length).toBeGreaterThan(0);
    client.dispose();
  });

  it("answers on the main thread after dispose instead of messaging a dead worker", async () => {
    let terminated = false;
    class FakeWorker {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      constructor(public url: string) {}
      postMessage() {
        if (terminated) throw new Error("Worker has been terminated");
      }
      terminate() {
        terminated = true;
      }
    }
    vi.stubGlobal("Worker", FakeWorker);
    mockFetch(artifactJson);

    const client = createSearchClient();
    client.dispose();
    const hits = await client.search("热力学", 5);
    expect(hits.length).toBeGreaterThan(0);
    expect(hits[0]!.url.startsWith("/")).toBe(true);
  });

  it("falls back to the main thread when the worker never answers", async () => {
    class FakeWorker {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      constructor(public url: string) {}
      postMessage() {}
      terminate() {}
    }
    vi.useFakeTimers();
    vi.stubGlobal("Worker", FakeWorker);
    mockFetch(artifactJson);

    const client = createSearchClient();
    const searchPromise = client.search("热力学", 5);
    await vi.advanceTimersByTimeAsync(SEARCH_WORKER_TIMEOUT_MS);
    const hits = await searchPromise;
    expect(hits.length).toBeGreaterThan(0);
    expect(hits[0]!.url.startsWith("/")).toBe(true);
    client.dispose();
  });

  it("drops worker hits whose urls are not same-origin paths", async () => {
    class FakeWorker {
      onmessage: ((event: MessageEvent) => void) | null = null;
      onerror: ((event: ErrorEvent) => void) | null = null;
      constructor(public url: string) {}
      postMessage(data: { type: string; id?: number }) {
        if (data.type !== "search") return;
        queueMicrotask(() => {
          this.onmessage?.({
            data: {
              type: "result",
              id: data.id,
              hits: [
                {
                  title: "xss",
                  subtitle: "",
                  url: "javascript:alert(1)",
                  section: "philosophy",
                  kind: "concept",
                  score: 9,
                },
                {
                  title: "cdn",
                  subtitle: "",
                  url: "//evil.example/search",
                  section: "philosophy",
                  kind: "concept",
                  score: 8,
                },
                {
                  title: "热力学",
                  subtitle: "",
                  url: "/universe-physics/physics/thermodynamics",
                  section: "universe-physics",
                  kind: "concept",
                  score: 1,
                },
              ],
            },
          } as MessageEvent);
        });
      }
      terminate() {}
    }
    vi.stubGlobal("Worker", FakeWorker);

    const client = createSearchClient();
    const hits = await client.search("热力学", 5);
    expect(hits).toHaveLength(1);
    expect(hits[0]?.url).toBe("/universe-physics/physics/thermodynamics");
    client.dispose();
  });
});

describe("isSafeSearchHit", () => {
  it("accepts in-site article paths and rejects schemes", () => {
    expect(
      isSafeSearchHit({
        title: "熵",
        subtitle: "",
        url: "/universe-physics/physics/thermodynamics",
        section: "universe-physics",
        kind: "concept",
        score: 1,
      })
    ).toBe(true);
    expect(isSafeSearchHit({ title: "x", url: "javascript:alert(1)" })).toBe(false);
    expect(isSafeSearchHit({ title: "x", url: "/\\evil.example/x" })).toBe(false);
    expect(isSafeSearchHit({ title: "x", url: "//evil.example/x" })).toBe(false);
    expect(isSafeSearchHit({ title: "x", url: "https://evil.example/x" })).toBe(false);
    expect(isSafeSearchHit({ title: "x", url: "" })).toBe(false);
    expect(isSafeSearchHit(null)).toBe(false);
  });
});
