import type { CrossLink } from "./types";

export const LINKS_PHILOSOPHY_HISTORY_EXPANDED: CrossLink[] = [
  // Philosophy ↔ Human History (Round 1 expansion)
  {
    sourceApp: "philosophy",
    sourceId: "locke",
    sourceTitle: "洛克",
    targetApp: "human-history",
    targetId: "glorious-revolution",
    targetTitle: "光荣革命",
    relationship: "洛克的社会契约论为光荣革命提供理论基础",
  },
  {
    sourceApp: "philosophy",
    sourceId: "rousseau",
    sourceTitle: "卢梭",
    targetApp: "human-history",
    targetId: "french-revolution",
    targetTitle: "法国大革命",
    relationship: "卢梭的社会契约论深刻影响了法国大革命",
  },
  {
    sourceApp: "philosophy",
    sourceId: "voltaire",
    sourceTitle: "伏尔泰",
    targetApp: "human-history",
    targetId: "enlightenment",
    targetTitle: "启蒙运动",
    relationship: "伏尔泰是启蒙运动的精神领袖",
  },
  {
    sourceApp: "philosophy",
    sourceId: "avicenna",
    sourceTitle: "伊本·西那",
    targetApp: "human-history",
    targetId: "islamic-golden-age",
    targetTitle: "伊斯兰黄金时代",
    relationship: "伊本·西那是伊斯兰黄金时代最伟大的博学家",
  },
  {
    sourceApp: "philosophy",
    sourceId: "averroes",
    sourceTitle: "伊本·鲁世德",
    targetApp: "human-history",
    targetId: "islamic-golden-age",
    targetTitle: "伊斯兰黄金时代",
    relationship: "伊本·鲁世德对亚里士多德的注释推动了伊斯兰哲学繁荣",
  },
  {
    sourceApp: "philosophy",
    sourceId: "mencius",
    sourceTitle: "孟子",
    targetApp: "human-history",
    targetId: "warring-states",
    targetTitle: "战国时期",
    relationship: "孟子在战国时期发展了儒家学说",
  },
  {
    sourceApp: "philosophy",
    sourceId: "laozi",
    sourceTitle: "老子",
    targetApp: "human-history",
    targetId: "spring-autumn",
    targetTitle: "春秋时期",
    relationship: "老子在春秋时期创立道家学派",
  },
  {
    sourceApp: "philosophy",
    sourceId: "han-feizi",
    sourceTitle: "韩非子",
    targetApp: "human-history",
    targetId: "qin-dynasty",
    targetTitle: "秦朝",
    relationship: "韩非子的法家思想是秦统一六国的意识形态基础",
  },
  {
    sourceApp: "human-history",
    sourceId: "glorious-revolution",
    sourceTitle: "光荣革命",
    targetApp: "philosophy",
    targetId: "locke",
    targetTitle: "洛克",
    relationship: "光荣革命的实践验证了洛克的政治哲学",
  },
  {
    sourceApp: "human-history",
    sourceId: "french-revolution",
    sourceTitle: "法国大革命",
    targetApp: "philosophy",
    targetId: "rousseau",
    targetTitle: "卢梭",
    relationship: "法国大革命将卢梭的理想付诸实践",
  },
  {
    sourceApp: "human-history",
    sourceId: "enlightenment",
    sourceTitle: "启蒙运动",
    targetApp: "philosophy",
    targetId: "voltaire",
    targetTitle: "伏尔泰",
    relationship: "启蒙运动是伏尔泰思想的集体成就",
  },
  {
    sourceApp: "human-history",
    sourceId: "islamic-golden-age",
    sourceTitle: "伊斯兰黄金时代",
    targetApp: "philosophy",
    targetId: "avicenna",
    targetTitle: "伊本·西那",
    relationship: "伊斯兰黄金时代孕育了伊本·西那的百科全书式学问",
  },
  {
    sourceApp: "human-history",
    sourceId: "islamic-golden-age",
    sourceTitle: "伊斯兰黄金时代",
    targetApp: "philosophy",
    targetId: "averroes",
    targetTitle: "伊本·鲁世德",
    relationship: "伊斯兰黄金时代见证了理性主义哲学的巅峰",
  },
  {
    sourceApp: "human-history",
    sourceId: "warring-states",
    sourceTitle: "战国时期",
    targetApp: "philosophy",
    targetId: "mencius",
    targetTitle: "孟子",
    relationship: "战国百家争鸣催生了孟子的心性之学",
  },
  {
    sourceApp: "human-history",
    sourceId: "spring-autumn",
    sourceTitle: "春秋时期",
    targetApp: "philosophy",
    targetId: "laozi",
    targetTitle: "老子",
    relationship: "春秋乱世促使老子反思天道与人道",
  },
  {
    sourceApp: "human-history",
    sourceId: "qin-dynasty",
    sourceTitle: "秦朝",
    targetApp: "philosophy",
    targetId: "han-feizi",
    targetTitle: "韩非子",
    relationship: "秦始皇实践了韩非子的法家治国理念",
  },

  // Universe Physics ↔ Human History (Round 1 expansion)
  {
    sourceApp: "universe-physics",
    sourceId: "heliocentrism",
    sourceTitle: "日心说",
    targetApp: "human-history",
    targetId: "scientific-revolution",
    targetTitle: "科学革命",
    relationship: "哥白尼日心说开启了科学革命",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "particle-physics",
    sourceTitle: "粒子物理",
    targetApp: "human-history",
    targetId: "space-race",
    targetTitle: "太空竞赛",
    relationship: "粒子物理和航天技术在冷战时期相互推动",
  },
  {
    sourceApp: "human-history",
    sourceId: "scientific-revolution",
    sourceTitle: "科学革命",
    targetApp: "universe-physics",
    targetId: "heliocentrism",
    targetTitle: "日心说",
    relationship: "科学革命以哥白尼日心说为起点",
  },
  {
    sourceApp: "human-history",
    sourceId: "space-race",
    sourceTitle: "太空竞赛",
    targetApp: "universe-physics",
    targetId: "particle-physics",
    targetTitle: "粒子物理",
    relationship: "太空竞赛推动了粒子物理和火箭技术的融合",
  },

  // Physics ↔ Life Science (Round 2 expansion)
  {
    sourceApp: "universe-physics",
    sourceId: "quantum-mechanics",
    sourceTitle: "量子力学",
    targetApp: "life-science",
    targetId: "radiation-mutations",
    targetTitle: "辐射与突变",
    relationship: "量子力学解释辐射如何导致DNA突变",
  },
  {
    sourceApp: "life-science",
    sourceId: "radiation-mutations",
    sourceTitle: "辐射与突变",
    targetApp: "universe-physics",
    targetId: "quantum-mechanics",
    targetTitle: "量子力学",
    relationship: "DNA突变的分子机制需要量子力学来解释",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "thermodynamics",
    sourceTitle: "热力学",
    targetApp: "life-science",
    targetId: "metabolism",
    targetTitle: "新陈代谢",
    relationship: "热力学定律支配生物体的能量代谢过程",
  },
  {
    sourceApp: "life-science",
    sourceId: "metabolism",
    sourceTitle: "新陈代谢",
    targetApp: "universe-physics",
    targetId: "thermodynamics",
    targetTitle: "热力学",
    relationship: "生物新陈代谢遵循热力学第二定律",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "astrophysics",
    sourceTitle: "天体物理",
    targetApp: "life-science",
    targetId: "earth-formation",
    targetTitle: "地球形成",
    relationship: "天体物理学解释地球形成与生命起源的物质基础",
  },
  {
    sourceApp: "life-science",
    sourceId: "earth-formation",
    sourceTitle: "地球形成",
    targetApp: "universe-physics",
    targetId: "astrophysics",
    targetTitle: "天体物理",
    relationship: "地球的形成过程是天体物理学研究的核心课题",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "nuclear-physics",
    sourceTitle: "核物理",
    targetApp: "life-science",
    targetId: "carbon-dating",
    targetTitle: "碳-14定年",
    relationship: "核物理技术实现了碳-14放射性定年法",
  },
  {
    sourceApp: "life-science",
    sourceId: "carbon-dating",
    sourceTitle: "碳-14定年",
    targetApp: "universe-physics",
    targetId: "nuclear-physics",
    targetTitle: "核物理",
    relationship: "碳-14定年法依赖核物理的放射性衰变原理",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "optics",
    sourceTitle: "光学",
    targetApp: "life-science",
    targetId: "cell-biology",
    targetTitle: "细胞生物学",
    relationship: "光学显微镜技术推动了细胞生物学的诞生",
  },
  {
    sourceApp: "life-science",
    sourceId: "cell-biology",
    sourceTitle: "细胞生物学",
    targetApp: "universe-physics",
    targetId: "optics",
    targetTitle: "光学",
    relationship: "细胞生物学的发展依赖光学技术的进步",
  },
];
