import type { CrossLink } from "./types";

export const LINKS_LIFE_SCIENCE: CrossLink[] = [
  // Life Science ↔ Universe Physics
  {
    sourceApp: "life-science",
    sourceId: "earth-formation",
    sourceTitle: "地球形成",
    targetApp: "universe-physics",
    targetId: "earth",
    targetTitle: "地球",
    relationship: "地球的形成为生命起源提供了条件",
  },
  {
    sourceApp: "life-science",
    sourceId: "atmosphere-evolution",
    sourceTitle: "大气演化",
    targetApp: "universe-physics",
    targetId: "earth",
    targetTitle: "地球",
    relationship: "地球大气层的演化影响了生命的进化方向",
  },
  {
    sourceApp: "life-science",
    sourceId: "mass-extinction-asteroid",
    sourceTitle: "小行星撞击大灭绝",
    targetApp: "universe-physics",
    targetId: "solar-system",
    targetTitle: "太阳系",
    relationship: "太阳系中小行星的运动导致了白垩纪大灭绝",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "earth",
    sourceTitle: "地球",
    targetApp: "life-science",
    targetId: "earth-formation",
    targetTitle: "地球形成",
    relationship: "地球的地质条件决定了生命演化的方向",
  },

  // Life Science ↔ Human History
  {
    sourceApp: "life-science",
    sourceId: "human-evolution",
    sourceTitle: "人类进化",
    targetApp: "human-history",
    targetId: "early-civilization",
    targetTitle: "早期文明",
    relationship: "从智人到文明的演化历程",
  },
  {
    sourceApp: "life-science",
    sourceId: "agriculture-origin",
    sourceTitle: "农业起源",
    targetApp: "human-history",
    targetId: "agricultural-revolution",
    targetTitle: "农业革命",
    relationship: "植物驯化推动了农业文明的诞生",
  },
  {
    sourceApp: "life-science",
    sourceId: "medicine-history",
    sourceTitle: "医学发展",
    targetApp: "human-history",
    targetId: "scientific-revolution",
    targetTitle: "科学革命",
    relationship: "生物学与医学的进步是科学革命的重要组成部分",
  },
  {
    sourceApp: "human-history",
    sourceId: "agricultural-revolution",
    sourceTitle: "农业革命",
    targetApp: "life-science",
    targetId: "agriculture-origin",
    targetTitle: "农业起源",
    relationship: "人类对植物和动物的驯化改变了进化方向",
  },

  // Life Science ↔ Philosophy
  {
    sourceApp: "life-science",
    sourceId: "darwin",
    sourceTitle: "达尔文",
    targetApp: "philosophy",
    targetId: "determinism",
    targetTitle: "决定论",
    relationship: "进化论对自然目的论的挑战",
  },
  {
    sourceApp: "life-science",
    sourceId: "genetic-engineering",
    sourceTitle: "基因工程",
    targetApp: "philosophy",
    targetId: "bioethics",
    targetTitle: "生命伦理学",
    relationship: "基因编辑技术引发的伦理讨论",
  },
  {
    sourceApp: "philosophy",
    sourceId: "aristotle",
    sourceTitle: "亚里士多德",
    targetApp: "life-science",
    targetId: "biology-origin",
    targetTitle: "生物学起源",
    relationship: "亚里士多德是生物学分类的先驱",
  },
  {
    sourceApp: "philosophy",
    sourceId: "determinism",
    sourceTitle: "决定论",
    targetApp: "life-science",
    targetId: "darwin",
    targetTitle: "达尔文",
    relationship: "自然选择与决定论的哲学关系",
  },

  // Life Science ↔ Human History (Round 1 expansion)
  {
    sourceApp: "life-science",
    sourceId: "human-evolution",
    sourceTitle: "人类进化",
    targetApp: "human-history",
    targetId: "human-prehistory",
    targetTitle: "人类史前史",
    relationship: "人类进化历程是史前史的核心线索",
  },
  {
    sourceApp: "life-science",
    sourceId: "mass-extinction",
    sourceTitle: "物种大灭绝",
    targetApp: "human-history",
    targetId: "historical-climate",
    targetTitle: "历史气候事件",
    relationship: "大灭绝事件揭示了气候对文明兴衰的影响",
  },
  {
    sourceApp: "life-science",
    sourceId: "agriculture-origin",
    sourceTitle: "农业起源",
    targetApp: "human-history",
    targetId: "neolithic-revolution",
    targetTitle: "新石器革命",
    relationship: "农业起源与新石器革命的同步发生",
  },
  {
    sourceApp: "human-history",
    sourceId: "human-prehistory",
    sourceTitle: "人类史前史",
    targetApp: "life-science",
    targetId: "human-evolution",
    targetTitle: "人类进化",
    relationship: "史前史记录了人类从生物进化到文化进化的转变",
  },
  {
    sourceApp: "human-history",
    sourceId: "historical-climate",
    sourceTitle: "历史气候事件",
    targetApp: "life-science",
    targetId: "mass-extinction",
    targetTitle: "物种大灭绝",
    relationship: "历史上的气候波动与生物灭绝模式相呼应",
  },
  {
    sourceApp: "human-history",
    sourceId: "neolithic-revolution",
    sourceTitle: "新石器革命",
    targetApp: "life-science",
    targetId: "agriculture-origin",
    targetTitle: "农业起源",
    relationship: "新石器革命是人类从狩猎采集转向农业的关键转折",
  },

  // Life Science ↔ Philosophy (Round 1 expansion)
  {
    sourceApp: "life-science",
    sourceId: "darwin",
    sourceTitle: "达尔文",
    targetApp: "philosophy",
    targetId: "nietzsche",
    targetTitle: "尼采",
    relationship: "进化论与道德谱系学的深层对话",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolutionary-ethics",
    sourceTitle: "进化伦理学",
    targetApp: "philosophy",
    targetId: "utilitarianism",
    targetTitle: "功利主义",
    relationship: "进化伦理学与功利主义对道德起源的不同解释",
  },
  {
    sourceApp: "life-science",
    sourceId: "consciousness-neuroscience",
    sourceTitle: "意识神经科学",
    targetApp: "philosophy",
    targetId: "philosophy-of-mind",
    targetTitle: "心灵哲学",
    relationship: "神经科学对意识的研究与心灵哲学的核心问题交汇",
  },
  {
    sourceApp: "philosophy",
    sourceId: "nietzsche",
    sourceTitle: "尼采",
    targetApp: "life-science",
    targetId: "darwin",
    targetTitle: "达尔文",
    relationship: "尼采的权力意志与达尔文进化论的思想碰撞",
  },
  {
    sourceApp: "philosophy",
    sourceId: "utilitarianism",
    sourceTitle: "功利主义",
    targetApp: "life-science",
    targetId: "evolutionary-ethics",
    targetTitle: "进化伦理学",
    relationship: "功利主义的计算与进化适应度的类比",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-mind",
    sourceTitle: "心灵哲学",
    targetApp: "life-science",
    targetId: "consciousness-neuroscience",
    targetTitle: "意识神经科学",
    relationship: "心灵哲学为意识神经科学提供概念框架",
  },

  // Life Science ↔ Universe Physics (Round 1 expansion)
  {
    sourceApp: "life-science",
    sourceId: "earth-formation",
    sourceTitle: "地球形成",
    targetApp: "universe-physics",
    targetId: "solar-system",
    targetTitle: "太阳系",
    relationship: "地球在太阳系中的形成过程",
  },
  {
    sourceApp: "life-science",
    sourceId: "atmosphere-evolution",
    sourceTitle: "大气演化",
    targetApp: "universe-physics",
    targetId: "thermodynamics",
    targetTitle: "热力学",
    relationship: "大气演化受热力学定律支配",
  },
  {
    sourceApp: "life-science",
    sourceId: "radiation-mutations",
    sourceTitle: "辐射与突变",
    targetApp: "universe-physics",
    targetId: "nuclear-physics",
    targetTitle: "核物理",
    relationship: "核辐射导致DNA突变是进化变异的重要来源",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "solar-system",
    sourceTitle: "太阳系",
    targetApp: "life-science",
    targetId: "earth-formation",
    targetTitle: "地球形成",
    relationship: "太阳系的形成条件决定了地球的宜居性",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "thermodynamics",
    sourceTitle: "热力学",
    targetApp: "life-science",
    targetId: "atmosphere-evolution",
    targetTitle: "大气演化",
    relationship: "热力学原理驱动大气化学反应和气候系统",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "nuclear-physics",
    sourceTitle: "核物理",
    targetApp: "life-science",
    targetId: "radiation-mutations",
    targetTitle: "辐射与突变",
    relationship: "核物理揭示的辐射机制解释了生物突变的物理基础",
  },
];
