import type { CrossLink } from "./types";

export const LINKS_MATHEMATICS: CrossLink[] = [
  // Mathematics ↔ Universe Physics
  {
    sourceApp: "mathematics",
    sourceId: "newton-calculus",
    sourceTitle: "牛顿微积分",
    targetApp: "universe-physics",
    targetId: "classical-mechanics",
    targetTitle: "经典力学",
    relationship: "牛顿发明微积分以描述力学运动规律",
  },
  {
    sourceApp: "mathematics",
    sourceId: "euler",
    sourceTitle: "欧拉",
    targetApp: "universe-physics",
    targetId: "fluid-dynamics",
    targetTitle: "流体力学",
    relationship: "欧拉方程是流体力学的基础方程",
  },
  {
    sourceApp: "mathematics",
    sourceId: "riemann",
    sourceTitle: "黎曼",
    targetApp: "universe-physics",
    targetId: "relativity",
    targetTitle: "相对论",
    relationship: "黎曼几何为广义相对论提供了弯曲时空的数学框架",
  },
  {
    sourceApp: "mathematics",
    sourceId: "fourier",
    sourceTitle: "傅里叶",
    targetApp: "universe-physics",
    targetId: "thermodynamics",
    targetTitle: "热力学",
    relationship: "傅里叶分析源于热传导方程的研究",
  },
  {
    sourceApp: "mathematics",
    sourceId: "hilbert",
    sourceTitle: "希尔伯特",
    targetApp: "universe-physics",
    targetId: "quantum-mechanics",
    targetTitle: "量子力学",
    relationship: "希尔伯特空间是量子力学的数学基础",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "classical-mechanics",
    sourceTitle: "经典力学",
    targetApp: "mathematics",
    targetId: "newton-calculus",
    targetTitle: "牛顿微积分",
    relationship: "经典力学的运动方程依赖微积分工具",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "fluid-dynamics",
    sourceTitle: "流体力学",
    targetApp: "mathematics",
    targetId: "euler",
    targetTitle: "欧拉",
    relationship: "流体力学的欧拉方程展示了数学与物理的统一",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "relativity",
    sourceTitle: "相对论",
    targetApp: "mathematics",
    targetId: "riemann",
    targetTitle: "黎曼",
    relationship: "广义相对论验证了黎曼几何的物理实在性",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "thermodynamics",
    sourceTitle: "热力学",
    targetApp: "mathematics",
    targetId: "fourier",
    targetTitle: "傅里叶",
    relationship: "热力学研究推动了傅里叶分析的发展",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "quantum-mechanics",
    sourceTitle: "量子力学",
    targetApp: "mathematics",
    targetId: "hilbert",
    targetTitle: "希尔伯特",
    relationship: "量子力学的数学表述依赖希尔伯特空间理论",
  },

  // Mathematics ↔ Philosophy
  {
    sourceApp: "mathematics",
    sourceId: "godel",
    sourceTitle: "哥德尔",
    targetApp: "philosophy",
    targetId: "philosophy-of-mind",
    targetTitle: "心灵哲学",
    relationship: "哥德尔不完备定理对心灵哲学的深远影响",
  },
  {
    sourceApp: "mathematics",
    sourceId: "logic",
    sourceTitle: "逻辑学",
    targetApp: "philosophy",
    targetId: "analytic-philosophy",
    targetTitle: "分析哲学",
    relationship: "数理逻辑是分析哲学的方法论基础",
  },
  {
    sourceApp: "mathematics",
    sourceId: "set-theory",
    sourceTitle: "集合论",
    targetApp: "philosophy",
    targetId: "philosophy-of-mathematics",
    targetTitle: "数学哲学",
    relationship: "集合论悖论引发了数学基础的哲学危机",
  },
  {
    sourceApp: "mathematics",
    sourceId: "probability",
    sourceTitle: "概率论",
    targetApp: "philosophy",
    targetId: "epistemology",
    targetTitle: "认识论",
    relationship: "概率论为知识的确定性提供了数学度量",
  },
  {
    sourceApp: "mathematics",
    sourceId: "category-theory",
    sourceTitle: "范畴论",
    targetApp: "philosophy",
    targetId: "structuralism",
    targetTitle: "结构主义",
    relationship: "范畴论体现了数学结构主义的核心思想",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-mind",
    sourceTitle: "心灵哲学",
    targetApp: "mathematics",
    targetId: "godel",
    targetTitle: "哥德尔",
    relationship: "心灵哲学借助哥德尔定理探讨意识与计算的边界",
  },
  {
    sourceApp: "philosophy",
    sourceId: "analytic-philosophy",
    sourceTitle: "分析哲学",
    targetApp: "mathematics",
    targetId: "logic",
    targetTitle: "逻辑学",
    relationship: "分析哲学的逻辑分析方法源于数理逻辑",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-mathematics",
    sourceTitle: "数学哲学",
    targetApp: "mathematics",
    targetId: "set-theory",
    targetTitle: "集合论",
    relationship: "数学哲学围绕集合论基础问题展开核心争论",
  },
  {
    sourceApp: "philosophy",
    sourceId: "epistemology",
    sourceTitle: "认识论",
    targetApp: "mathematics",
    targetId: "probability",
    targetTitle: "概率论",
    relationship: "认识论中的贝叶斯推理依赖概率论",
  },
  {
    sourceApp: "philosophy",
    sourceId: "structuralism",
    sourceTitle: "结构主义",
    targetApp: "mathematics",
    targetId: "category-theory",
    targetTitle: "范畴论",
    relationship: "结构主义哲学从范畴论中汲取了形式化工具",
  },

  // Mathematics ↔ Human History
  {
    sourceApp: "mathematics",
    sourceId: "al-khwarizmi",
    sourceTitle: "花拉子米",
    targetApp: "human-history",
    targetId: "islamic-golden-age",
    targetTitle: "伊斯兰黄金时代",
    relationship: "花拉子米的代数学著作是伊斯兰黄金时代的科学巅峰",
  },
  {
    sourceApp: "mathematics",
    sourceId: "fibonacci",
    sourceTitle: "斐波那契",
    targetApp: "human-history",
    targetId: "italian-renaissance",
    targetTitle: "意大利文艺复兴",
    relationship: "斐波那契将阿拉伯数学引入欧洲推动了文艺复兴",
  },
  {
    sourceApp: "mathematics",
    sourceId: "turing",
    sourceTitle: "图灵",
    targetApp: "human-history",
    targetId: "wwii-codebreaking",
    targetTitle: "二战密码破译",
    relationship: "图灵在布莱切利园破解了恩尼格玛密码机",
  },
  {
    sourceApp: "human-history",
    sourceId: "islamic-golden-age",
    sourceTitle: "伊斯兰黄金时代",
    targetApp: "mathematics",
    targetId: "al-khwarizmi",
    targetTitle: "花拉子米",
    relationship: "伊斯兰黄金时代孕育了代数学之父花拉子米",
  },
  {
    sourceApp: "human-history",
    sourceId: "italian-renaissance",
    sourceTitle: "意大利文艺复兴",
    targetApp: "mathematics",
    targetId: "fibonacci",
    targetTitle: "斐波那契",
    relationship: "意大利文艺复兴时期数学与商业的交融",
  },
  {
    sourceApp: "human-history",
    sourceId: "wwii-codebreaking",
    sourceTitle: "二战密码破译",
    targetApp: "mathematics",
    targetId: "turing",
    targetTitle: "图灵",
    relationship: "二战密码破译催生了现代计算机科学的雏形",
  },

  // Mathematics ↔ Life Science
  {
    sourceApp: "mathematics",
    sourceId: "statistics",
    sourceTitle: "统计学",
    targetApp: "life-science",
    targetId: "clinical-trials",
    targetTitle: "临床试验",
    relationship: "统计学方法是临床试验设计与分析的基石",
  },
  {
    sourceApp: "mathematics",
    sourceId: "population-genetics",
    sourceTitle: "群体遗传学",
    targetApp: "life-science",
    targetId: "evolution-theory",
    targetTitle: "进化论",
    relationship: "群体遗传学用数学模型描述进化的遗传机制",
  },
  {
    sourceApp: "life-science",
    sourceId: "clinical-trials",
    sourceTitle: "临床试验",
    targetApp: "mathematics",
    targetId: "statistics",
    targetTitle: "统计学",
    relationship: "临床试验的随机对照设计依赖统计学理论",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution-theory",
    sourceTitle: "进化论",
    targetApp: "mathematics",
    targetId: "population-genetics",
    targetTitle: "群体遗传学",
    relationship: "进化论的现代综合依赖群体遗传学的数学框架",
  },
];
