import type { CrossLink } from "./types";

export const LINKS_ECONOMICS: CrossLink[] = [
  // Economics ↔ Philosophy
  {
    sourceApp: "economics",
    sourceId: "adam-smith",
    sourceTitle: "亚当·斯密",
    targetApp: "philosophy",
    targetId: "utilitarianism",
    targetTitle: "功利主义",
    relationship: "亚当·斯密的古典经济学与功利主义的关联",
  },
  {
    sourceApp: "economics",
    sourceId: "karl-marx",
    sourceTitle: "卡尔·马克思",
    targetApp: "philosophy",
    targetId: "marx",
    targetTitle: "马克思",
    relationship: "马克思的政治经济学源于其哲学体系",
  },
  {
    sourceApp: "economics",
    sourceId: "behavioral-economics",
    sourceTitle: "行为经济学",
    targetApp: "philosophy",
    targetId: "epistemology",
    targetTitle: "认识论",
    relationship: "行为经济学挑战了理性选择的认识论假设",
  },
  {
    sourceApp: "economics",
    sourceId: "game-theory",
    sourceTitle: "博弈论",
    targetApp: "philosophy",
    targetId: "analytic-philosophy",
    targetTitle: "分析哲学",
    relationship: "博弈论的逻辑结构与分析哲学方法的交汇",
  },
  {
    sourceApp: "philosophy",
    sourceId: "utilitarianism",
    sourceTitle: "功利主义",
    targetApp: "economics",
    targetId: "welfare-economics",
    targetTitle: "福利经济学",
    relationship: "福利经济学的效用理论源于功利主义哲学",
  },
  {
    sourceApp: "philosophy",
    sourceId: "marx",
    sourceTitle: "马克思",
    targetApp: "economics",
    targetId: "karl-marx",
    targetTitle: "卡尔·马克思",
    relationship: "马克思哲学体系中的政治经济学批判",
  },
  {
    sourceApp: "philosophy",
    sourceId: "epistemology",
    sourceTitle: "认识论",
    targetApp: "economics",
    targetId: "behavioral-economics",
    targetTitle: "行为经济学",
    relationship: "认识论对经济理性假设的哲学反思",
  },
  {
    sourceApp: "philosophy",
    sourceId: "analytic-philosophy",
    sourceTitle: "分析哲学",
    targetApp: "economics",
    targetId: "game-theory",
    targetTitle: "博弈论",
    relationship: "分析哲学的逻辑工具影响了博弈论的形式化",
  },

  // Economics ↔ Human History
  {
    sourceApp: "economics",
    sourceId: "great-depression",
    sourceTitle: "大萧条",
    targetApp: "human-history",
    targetId: "great-depression",
    targetTitle: "大萧条",
    relationship: "大萧条是20世纪最重要的经济与历史事件",
  },
  {
    sourceApp: "economics",
    sourceId: "industrial-revolution",
    sourceTitle: "工业革命经济学",
    targetApp: "human-history",
    targetId: "industrial-revolution",
    targetTitle: "工业革命",
    relationship: "工业革命的经济学分析",
  },
  {
    sourceApp: "economics",
    sourceId: "bretton-woods",
    sourceTitle: "布雷顿森林体系",
    targetApp: "human-history",
    targetId: "bretton-woods",
    targetTitle: "布雷顿森林会议",
    relationship: "布雷顿森林体系塑造了战后国际经济秩序",
  },
  {
    sourceApp: "economics",
    sourceId: "adam-smith",
    sourceTitle: "亚当·斯密",
    targetApp: "human-history",
    targetId: "enlightenment",
    targetTitle: "启蒙运动",
    relationship: "亚当·斯密是启蒙运动时期最重要的经济学家",
  },
  {
    sourceApp: "human-history",
    sourceId: "enlightenment",
    sourceTitle: "启蒙运动",
    targetApp: "economics",
    targetId: "adam-smith",
    targetTitle: "亚当·斯密",
    relationship: "启蒙运动催生了古典经济学的诞生",
  },

  // Economics ↔ Psychology
  {
    sourceApp: "economics",
    sourceId: "daniel-kahneman",
    sourceTitle: "丹尼尔·卡尼曼",
    targetApp: "psychology",
    targetId: "daniel-kahneman",
    targetTitle: "丹尼尔·卡尼曼",
    relationship: "卡尼曼将心理学洞见融入经济决策研究",
  },
  {
    sourceApp: "economics",
    sourceId: "richard-thaler",
    sourceTitle: "理查德·塞勒",
    targetApp: "psychology",
    targetId: "richard-thaler",
    targetTitle: "理查德·塞勒",
    relationship: "塞勒的助推理论融合了经济学与心理学",
  },
  {
    sourceApp: "economics",
    sourceId: "amos-tversky",
    sourceTitle: "阿莫斯·特沃斯基",
    targetApp: "psychology",
    targetId: "amos-tversky",
    targetTitle: "阿莫斯·特沃斯基",
    relationship: "特沃斯基的启发式与偏误研究奠定了行为经济学基础",
  },
  {
    sourceApp: "economics",
    sourceId: "prospect-theory",
    sourceTitle: "前景理论",
    targetApp: "psychology",
    targetId: "anchoring-bias",
    targetTitle: "锚定效应",
    relationship: "前景理论揭示了锚定效应对经济决策的影响",
  },
  {
    sourceApp: "economics",
    sourceId: "prospect-theory",
    sourceTitle: "前景理论",
    targetApp: "psychology",
    targetId: "framing-effect",
    targetTitle: "框架效应",
    relationship: "前景理论的核心机制之一是框架效应",
  },
  {
    sourceApp: "economics",
    sourceId: "behavioral-economics",
    sourceTitle: "行为经济学",
    targetApp: "psychology",
    targetId: "cognitive-bias",
    targetTitle: "认知偏误",
    relationship: "行为经济学以认知偏误为理论基石",
  },
  {
    sourceApp: "psychology",
    sourceId: "daniel-kahneman",
    sourceTitle: "丹尼尔·卡尼曼",
    targetApp: "economics",
    targetId: "daniel-kahneman",
    targetTitle: "丹尼尔·卡尼曼",
    relationship: "卡尼曼因行为经济学研究获得诺贝尔经济学奖",
  },
  {
    sourceApp: "psychology",
    sourceId: "richard-thaler",
    sourceTitle: "理查德·塞勒",
    targetApp: "economics",
    targetId: "richard-thaler",
    targetTitle: "理查德·塞勒",
    relationship: "塞勒将心理学实验发现应用于经济政策设计",
  },
  {
    sourceApp: "psychology",
    sourceId: "amos-tversky",
    sourceTitle: "阿莫斯·特沃斯基",
    targetApp: "economics",
    targetId: "amos-tversky",
    targetTitle: "阿莫斯·特沃斯基",
    relationship: "特沃斯基与卡尼曼的合作开创了行为经济学",
  },
  {
    sourceApp: "psychology",
    sourceId: "anchoring-bias",
    sourceTitle: "锚定效应",
    targetApp: "economics",
    targetId: "prospect-theory",
    targetTitle: "前景理论",
    relationship: "锚定效应是前景理论描述的决策偏误之一",
  },
  {
    sourceApp: "psychology",
    sourceId: "framing-effect",
    sourceTitle: "框架效应",
    targetApp: "economics",
    targetId: "prospect-theory",
    targetTitle: "前景理论",
    relationship: "框架效应证明了经济决策并非完全理性",
  },
  {
    sourceApp: "psychology",
    sourceId: "cognitive-bias",
    sourceTitle: "认知偏误",
    targetApp: "economics",
    targetId: "behavioral-economics",
    targetTitle: "行为经济学",
    relationship: "认知偏误研究为行为经济学提供了心理学基础",
  },

  // Economics ↔ Life Science
  {
    sourceApp: "economics",
    sourceId: "health-economics",
    sourceTitle: "健康经济学",
    targetApp: "life-science",
    targetId: "clinical-trials",
    targetTitle: "临床试验",
    relationship: "健康经济学评估临床试验的成本效益",
  },
  {
    sourceApp: "economics",
    sourceId: "environmental-economics",
    sourceTitle: "环境经济学",
    targetApp: "life-science",
    targetId: "ecology",
    targetTitle: "生态学",
    relationship: "环境经济学为生态系统服务赋予经济价值",
  },
  {
    sourceApp: "life-science",
    sourceId: "ecology",
    sourceTitle: "生态学",
    targetApp: "economics",
    targetId: "environmental-economics",
    targetTitle: "环境经济学",
    relationship: "生态学为环境经济学提供科学依据",
  },
  {
    sourceApp: "life-science",
    sourceId: "clinical-trials",
    sourceTitle: "临床试验",
    targetApp: "economics",
    targetId: "health-economics",
    targetTitle: "健康经济学",
    relationship: "临床试验的经济学分析影响医疗资源配置",
  },

  // Economics ↔ Mathematics
  {
    sourceApp: "economics",
    sourceId: "econometrics",
    sourceTitle: "计量经济学",
    targetApp: "mathematics",
    targetId: "statistics",
    targetTitle: "统计学",
    relationship: "计量经济学的理论基础是统计学",
  },
  {
    sourceApp: "economics",
    sourceId: "game-theory",
    sourceTitle: "博弈论",
    targetApp: "mathematics",
    targetId: "probability",
    targetTitle: "概率论",
    relationship: "博弈论中的混合策略依赖概率论",
  },
  {
    sourceApp: "mathematics",
    sourceId: "statistics",
    sourceTitle: "统计学",
    targetApp: "economics",
    targetId: "econometrics",
    targetTitle: "计量经济学",
    relationship: "统计学方法是计量经济学的核心工具",
  },
  {
    sourceApp: "mathematics",
    sourceId: "probability",
    sourceTitle: "概率论",
    targetApp: "economics",
    targetId: "game-theory",
    targetTitle: "博弈论",
    relationship: "概率论为博弈论的不确定性建模提供数学基础",
  },

  // New knowledge-base cross-links
  {
    sourceApp: "economics",
    sourceId: "tulip-mania",
    sourceTitle: "郁金香狂热",
    targetApp: "human-history",
    targetId: "dutch-golden-age",
    targetTitle: "荷兰黄金时代",
    relationship: "郁金香狂热是荷兰黄金时代最著名的投机泡沫",
  },
  {
    sourceApp: "human-history",
    sourceId: "dutch-golden-age",
    sourceTitle: "荷兰黄金时代",
    targetApp: "economics",
    targetId: "tulip-mania",
    targetTitle: "郁金香狂热",
    relationship: "荷兰黄金时代的商业繁荣催生了郁金香投机泡沫",
  },
  {
    sourceApp: "economics",
    sourceId: "china-economic-rise",
    sourceTitle: "中国经济崛起",
    targetApp: "human-history",
    targetId: "modern-china",
    targetTitle: "现代中国",
    relationship: "中国经济崛起是现代中国历史进程的核心驱动力",
  },
  {
    sourceApp: "human-history",
    sourceId: "modern-china",
    sourceTitle: "现代中国",
    targetApp: "economics",
    targetId: "china-economic-rise",
    targetTitle: "中国经济崛起",
    relationship: "现代中国的改革开放政策推动了经济的高速增长",
  },
  {
    sourceApp: "economics",
    sourceId: "market-efficiency",
    sourceTitle: "市场效率",
    targetApp: "psychology",
    targetId: "behavioral-biases",
    targetTitle: "行为偏误",
    relationship: "行为偏误研究挑战了市场效率假说的理性人假设",
  },
  {
    sourceApp: "psychology",
    sourceId: "behavioral-biases",
    sourceTitle: "行为偏误",
    targetApp: "economics",
    targetId: "market-efficiency",
    targetTitle: "市场效率",
    relationship: "行为偏误是导致市场效率偏离的重要心理因素",
  },
  {
    sourceApp: "economics",
    sourceId: "development-economics",
    sourceTitle: "发展经济学",
    targetApp: "life-science",
    targetId: "health-nutrition",
    targetTitle: "健康与营养",
    relationship: "发展经济学关注健康与营养对人力资本和经济增长的影响",
  },
  {
    sourceApp: "life-science",
    sourceId: "health-nutrition",
    sourceTitle: "健康与营养",
    targetApp: "economics",
    targetId: "development-economics",
    targetTitle: "发展经济学",
    relationship: "健康与营养水平是衡量发展中国家经济发展的重要指标",
  },
  {
    sourceApp: "economics",
    sourceId: "platform-economics",
    sourceTitle: "平台经济学",
    targetApp: "philosophy",
    targetId: "ai-ethics",
    targetTitle: "AI伦理",
    relationship: "平台经济学的算法推荐与定价引发了AI伦理讨论",
  },
  {
    sourceApp: "philosophy",
    sourceId: "ai-ethics",
    sourceTitle: "AI伦理",
    targetApp: "economics",
    targetId: "platform-economics",
    targetTitle: "平台经济学",
    relationship: "AI伦理框架对平台经济的算法治理提出了规范性要求",
  },

  // Knowledge-base cross-links: order-book ↔ psychology
  {
    sourceApp: "economics",
    sourceId: "order-book",
    sourceTitle: "订单簿",
    targetApp: "psychology",
    targetId: "behavioral-trading",
    targetTitle: "行为交易",
    relationship: "订单簿分析揭示了交易者行为中的心理偏差模式",
  },
  {
    sourceApp: "psychology",
    sourceId: "behavioral-trading",
    sourceTitle: "行为交易",
    targetApp: "economics",
    targetId: "order-book",
    targetTitle: "订单簿",
    relationship: "行为交易研究解释了订单簿中非理性交易行为的心理机制",
  },

  // Knowledge-base cross-links: price-formation ↔ philosophy
  {
    sourceApp: "economics",
    sourceId: "price-formation",
    sourceTitle: "价格形成",
    targetApp: "philosophy",
    targetId: "epistemology",
    targetTitle: "认识论",
    relationship: "市场价格的信息聚合功能与认识论中的集体智慧问题相关",
  },
  {
    sourceApp: "philosophy",
    sourceId: "epistemology",
    sourceTitle: "认识论",
    targetApp: "economics",
    targetId: "price-formation",
    targetTitle: "价格形成",
    relationship: "认识论为理解市场价格如何反映分散知识提供了哲学基础",
  },

  // Knowledge-base cross-links: inflation-mechanism ↔ history
  {
    sourceApp: "economics",
    sourceId: "inflation-mechanism",
    sourceTitle: "通胀机制",
    targetApp: "human-history",
    targetId: "hyperinflation",
    targetTitle: "恶性通胀",
    relationship: "历史上的恶性通胀事件为通胀机制研究提供了极端案例",
  },
  {
    sourceApp: "human-history",
    sourceId: "hyperinflation",
    sourceTitle: "恶性通胀",
    targetApp: "economics",
    targetId: "inflation-mechanism",
    targetTitle: "通胀机制",
    relationship: "恶性通胀的历史教训验证了货币超发与物价飞涨的因果关系",
  },

  // Knowledge-base cross-links: real-estate-economics ↔ history
  {
    sourceApp: "economics",
    sourceId: "real-estate-economics",
    sourceTitle: "房地产经济学",
    targetApp: "human-history",
    targetId: "2008-financial-crisis",
    targetTitle: "2008年金融危机",
    relationship: "2008年金融危机的根源在于房地产泡沫与次贷证券化",
  },
  {
    sourceApp: "human-history",
    sourceId: "2008-financial-crisis",
    sourceTitle: "2008年金融危机",
    targetApp: "economics",
    targetId: "real-estate-economics",
    targetTitle: "房地产经济学",
    relationship: "2008年金融危机是房地产市场崩塌引发系统性风险的典型案例",
  },

  // Knowledge-base cross-links: sovereign-debt ↔ history
  {
    sourceApp: "economics",
    sourceId: "sovereign-debt",
    sourceTitle: "主权债务",
    targetApp: "human-history",
    targetId: "debt-crises",
    targetTitle: "债务危机",
    relationship: "主权债务违约在历史上反复出现，从古罗马到现代阿根廷",
  },
  {
    sourceApp: "human-history",
    sourceId: "debt-crises",
    sourceTitle: "债务危机",
    targetApp: "economics",
    targetId: "sovereign-debt",
    targetTitle: "主权债务",
    relationship: "历史上的债务危机揭示了主权债务累积的系统性风险",
  },

  // Knowledge-base cross-links: stock-valuation ↔ mathematics
  {
    sourceApp: "economics",
    sourceId: "stock-valuation",
    sourceTitle: "股票估值",
    targetApp: "mathematics",
    targetId: "statistics",
    targetTitle: "统计学",
    relationship: "股票估值模型依赖统计学方法进行现金流预测和风险评估",
  },
  {
    sourceApp: "mathematics",
    sourceId: "statistics",
    sourceTitle: "统计学",
    targetApp: "economics",
    targetId: "stock-valuation",
    targetTitle: "股票估值",
    relationship: "统计学为DCF模型和股票估值提供了概率分布和回归分析工具",
  },

  // New bidirectional links from cross-domain content improvement
  // Economics economists ↔ Mathematics
  {
    sourceApp: "economics",
    sourceId: "thomas-schelling",
    sourceTitle: "托马斯·谢林",
    targetApp: "mathematics",
    targetId: "game-theory",
    targetTitle: "博弈论",
    relationship: "谢林的冲突协调理论建立在博弈论的数学框架之上",
  },
  {
    sourceApp: "mathematics",
    sourceId: "game-theory",
    sourceTitle: "博弈论",
    targetApp: "economics",
    targetId: "thomas-schelling",
    targetTitle: "托马斯·谢林",
    relationship: "博弈论为谢林的冲突与协调模型提供了形式化工具",
  },

  // Economics economists ↔ Life Science
  {
    sourceApp: "economics",
    sourceId: "elinor-ostrom",
    sourceTitle: "埃莉诺·奥斯特罗姆",
    targetApp: "life-science",
    targetId: "ecology",
    targetTitle: "生态学",
    relationship: "奥斯特罗姆的公共资源治理理论直接回应了生态学中的公地悲剧问题",
  },
  {
    sourceApp: "life-science",
    sourceId: "ecology",
    sourceTitle: "生态学",
    targetApp: "economics",
    targetId: "elinor-ostrom",
    targetTitle: "埃莉诺·奥斯特罗姆",
    relationship: "生态学中的公地悲剧问题需要奥斯特罗姆式的制度解决方案",
  },
  {
    sourceApp: "economics",
    sourceId: "esther-duflo",
    sourceTitle: "埃斯特·杜弗洛",
    targetApp: "life-science",
    targetId: "clinical-trials",
    targetTitle: "临床试验",
    relationship: "杜弗洛的RCT方法论直接借鉴了临床医学的随机对照试验设计",
  },
  {
    sourceApp: "life-science",
    sourceId: "clinical-trials",
    sourceTitle: "临床试验",
    targetApp: "economics",
    targetId: "esther-duflo",
    targetTitle: "埃斯特·杜弗洛",
    relationship: "临床试验的方法论被杜弗洛引入发展经济学，开创了实证发展经济学",
  },

  // Economics concepts ↔ Mathematics
  {
    sourceApp: "economics",
    sourceId: "nash-equilibrium",
    sourceTitle: "纳什均衡",
    targetApp: "mathematics",
    targetId: "game-theory",
    targetTitle: "博弈论",
    relationship: "纳什均衡是博弈论的核心数学概念——角谷不动点定理证明其存在性",
  },
  {
    sourceApp: "mathematics",
    sourceId: "game-theory",
    sourceTitle: "博弈论",
    targetApp: "economics",
    targetId: "nash-equilibrium",
    targetTitle: "纳什均衡",
    relationship: "博弈论为纳什均衡的数学定义和存在性证明提供了严格的数学框架",
  },
  {
    sourceApp: "economics",
    sourceId: "gini-coefficient",
    sourceTitle: "基尼系数",
    targetApp: "mathematics",
    targetId: "statistics",
    targetTitle: "统计学",
    relationship: "基尼系数的计算依赖于洛伦兹曲线和积分学——统计学的核心工具",
  },
  {
    sourceApp: "mathematics",
    sourceId: "statistics",
    sourceTitle: "统计学",
    targetApp: "economics",
    targetId: "gini-coefficient",
    targetTitle: "基尼系数",
    relationship: "统计学为基尼系数的计算和不平等度量提供了数学方法",
  },

  // Economics concepts ↔ Psychology
  {
    sourceApp: "economics",
    sourceId: "moral-hazard",
    sourceTitle: "道德风险",
    targetApp: "psychology",
    targetId: "cognitive-bias",
    targetTitle: "认知偏差",
    relationship: "道德风险中的风险补偿行为与认知偏差中的过度自信密切相关",
  },
  {
    sourceApp: "psychology",
    sourceId: "cognitive-bias",
    sourceTitle: "认知偏差",
    targetApp: "economics",
    targetId: "moral-hazard",
    targetTitle: "道德风险",
    relationship: "认知偏差（如过度自信、乐观偏差）是道德风险行为的心理基础",
  },
  {
    sourceApp: "economics",
    sourceId: "opportunity-cost",
    sourceTitle: "机会成本",
    targetApp: "psychology",
    targetId: "cognitive-bias",
    targetTitle: "认知偏差",
    relationship: "人们常常忽视机会成本——沉没成本谬误反映了对已投入资源的过度关注",
  },
  {
    sourceApp: "psychology",
    sourceId: "cognitive-bias",
    sourceTitle: "认知偏差",
    targetApp: "economics",
    targetId: "opportunity-cost",
    targetTitle: "机会成本",
    relationship: "认知偏差导致人们系统性地忽视机会成本——行为经济学的核心发现",
  },

  // Economics concepts ↔ Philosophy
  {
    sourceApp: "economics",
    sourceId: "creative-destruction",
    sourceTitle: "创造性破坏",
    targetApp: "philosophy",
    targetId: "hegel",
    targetTitle: "黑格尔",
    relationship: "熊彼特的创造性破坏与黑格尔的辩证法——正题-反题-合题的否定之否定",
  },
  {
    sourceApp: "economics",
    sourceId: "tragedy-of-commons",
    sourceTitle: "公地悲剧",
    targetApp: "philosophy",
    targetId: "locke",
    targetTitle: "洛克",
    relationship: "公地悲剧问题与社会契约论——人类如何从个体理性走向集体理性",
  },
];
