import type { CrossReference } from "./types";

export const HISTORY_REFS: CrossReference[] = [
  {
    fromDomain: "human-history",
    fromId: "scientific-revolution",
    fromTitle: "科学革命",
    toDomain: "universe-physics",
    toId: "T4-milky-way",
    toTitle: "银河系",
    relation: "伽利略的望远镜观测揭示了银河系由无数恒星组成",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    toDomain: "philosophy",
    toId: "confucius",
    toTitle: "孔子",
    relation: "轴心时代的思想家奠定了东西方哲学的基础",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    toDomain: "philosophy",
    toId: "socrates",
    toTitle: "苏格拉底",
    relation: "苏格拉底是轴心时代希腊哲学的奠基者",
  },
  {
    fromDomain: "human-history",
    fromId: "enlightenment",
    fromTitle: "启蒙运动",
    toDomain: "philosophy",
    toId: "kant",
    toTitle: "康德",
    relation: "康德的「敢于求知」是启蒙运动的精神纲领",
  },
  {
    fromDomain: "human-history",
    fromId: "enlightenment",
    fromTitle: "启蒙运动",
    toDomain: "philosophy",
    toId: "rousseau",
    toTitle: "卢梭",
    relation: "卢梭的《社会契约论》是启蒙运动中最具革命性的政治哲学著作",
  },
  {
    fromDomain: "human-history",
    fromId: "axial-age",
    fromTitle: "轴心时代",
    toDomain: "philosophy",
    toId: "laozi",
    toTitle: "老子",
    relation: "老子在轴心时代创立了道家学派，影响了东亚文明数千年",
  },
  {
    fromDomain: "human-history",
    fromId: "scientific-revolution",
    fromTitle: "科学革命",
    toDomain: "life-science",
    toId: "darwin",
    toTitle: "达尔文",
    relation: "科学革命的方法论传统为达尔文的观察与归纳提供了范式",
  },
  {
    fromDomain: "human-history",
    fromId: "agricultural-revolution",
    fromTitle: "农业革命",
    toDomain: "life-science",
    toId: "plant-domestication",
    toTitle: "植物驯化",
    relation: "约 1 万年前人类开始驯化野生植物，彻底改变了进化方向",
  },
  {
    fromDomain: "human-history",
    fromId: "islamic-golden-age",
    fromTitle: "伊斯兰黄金时代",
    toDomain: "mathematics",
    toId: "algebra",
    toTitle: "代数学",
    relation: "伊斯兰黄金时代传承并发展了希腊和印度的数学遗产，创立了代数学",
  },
];
