import type { EraContent } from "./types";

const era: EraContent = {
  id: "age-of-dinosaurs",
  name: { primary: "恐龙时代", latin: "Age of Dinosaurs" },
  tagline: "中生代：爬行动物统治地球1.7亿年",
  timeRange: "2.3亿年前 - 6600万年前",
  dataCards: [
    {
      label: "恐龙统治时长",
      latinLabel: "Dinosaur reign",
      value: "~1.7亿年",
      hint: "三叠纪晚期 → 白垩纪末",
    },
    {
      label: "已知恐龙物种数",
      latinLabel: "Known dinosaur species",
      value: "~1000+",
      hint: "截至2024年 · 每年新增约50种",
    },
    {
      label: "最大恐龙",
      latinLabel: "Largest dinosaur",
      value: "阿根廷龙",
      hint: "约 35-40 米 · 70-80 吨 · 蜥脚类",
    },
    {
      label: "最小型恐龙",
      latinLabel: "Smallest dinosaur",
      value: "小盗龙",
      hint: "约 77 cm · 四翼 · 会飞/滑翔",
    },
    {
      label: "恐龙代谢率",
      latinLabel: "Dinosaur metabolism",
      value: "中温（内温）",
      hint: "2022年同位素证据 · 不完全是冷血",
    },
    {
      label: "始祖鸟",
      latinLabel: "Archaeopteryx",
      value: "1.5亿年前",
      hint: "最早确认的鸟类 · 德国索伦霍芬",
    },
    {
      label: "白垩纪末撞击体",
      latinLabel: "K-Pg impactor",
      value: "直径 ~10 km",
      hint: "希克苏鲁伯陨石坑 · 尤卡坦半岛",
    },
    {
      label: "翼龙最大翼展",
      latinLabel: "Largest pterosaur wingspan",
      value: "~10-11米",
      hint: "风神翼龙 Quetzalcoatlus · 长颈鹿大小",
    },
    {
      label: "中国带羽毛恐龙物种数",
      latinLabel: "Feathered dinosaur species from China",
      value: "~80种",
      hint: "辽宁热河生物群为主 · 占全球带羽毛恐龙发现的90%以上",
    },
    {
      label: "德干暗色岩面积",
      latinLabel: "Deccan Traps area",
      value: "~50万km²",
      hint: "印度中西部 · 喷发量约100万km³熔岩 · 跨K-Pg边界",
    },
  ],
  narrative: [
    {
      heading: "恐龙崛起：从边缘到霸主",
      body: [
        "恐龙的故事开始于三叠纪晚期（约 2.3 亿年前），当时盘古大陆（Pangaea）刚刚形成。最早的恐龙是小型、双足、杂食或肉食性的动物，生活在南美洲（阿根廷的伊斯基瓜拉斯托组）。在三叠纪-侏罗纪之交的大灭绝（约 2.01 亿年前）之后，恐龙迅速填补了空出的生态位，成为陆地上的主导脊椎动物。",
        "关于恐龙为什么会统治中生代的陆地，有几个关键因素：（1）直立姿态——恐龙的腿位于身体正下方（像哺乳动物），而非像蜥蜴那样向两侧伸展，这让它们在长距离运动时更高效；（2）气囊呼吸系统——恐龙继承了鳄鱼祖先的气囊系统（类似鸟类），能够在吸气和呼气时都进行气体交换，呼吸效率远高于哺乳动物；（3）中温代谢——2022年，Wiemann 等人通过分析恐龙骨骼化石中的分子标志物，证明恐龙是中温动物（内温，但体温可能低于哺乳动物），这让它们在各种气候条件下都保持活跃。",
        "中生代分为三个纪：三叠纪（2.52-2.01亿年前）、侏罗纪（2.01-1.45亿年前）和白垩纪（1.45-0.66亿年前）。每个纪都有标志性的恐龙群体：三叠纪是早期蜥脚类和兽脚类；侏罗纪是蜥脚类的巨型化巅峰（梁龙、腕龙、雷龙）和最早的鸟类；白垩纪是角龙类（三角龙）、鸭嘴龙（副栉龙）和暴龙类（霸王龙）的黄金时代。",
      ],
    },
    {
      heading: "恐龙不是蜥蜴：颠覆性的认知革命",
      body: [
        "大众文化中「恐龙」常被描绘为笨拙、迟钝、拖着尾巴的巨型蜥蜴——但这一形象早已过时。1969年，John Ostrom 发表了对恐爪龙（Deinonychus）的描述，彻底改变了古生物学对恐龙的认知。恐爪龙是一种约 3 米长的敏捷捕食者，拥有巨大的镰刀状趾爪，可能以群体协作方式猎捕——这与当时流行的「笨拙冷血巨兽」形象截然不同。",
        "Ostrom 还发现了始祖鸟（Archaeopteryx）与恐爪龙之间的惊人解剖学相似性，重新提出了鸟类是恐龙后代的假说。今天，这一假说已经被压倒性的证据所支持：鸟类就是兽脚类恐龙的一个分支——它们不是恐龙的「后代」，它们就是恐龙。当你吃鸡肉时，你吃的是恐龙肉。",
        "恐龙的羽毛化是 20 世纪 90 年代以来最重要的古生物学发现之一。1996年，中国辽宁发现了中华龙鸟（Sinosauropteryx）——第一种被确认有丝状「原羽」的非鸟类恐龙。此后，在中国辽西地区发现了大量带羽毛恐龙化石——包括四翼的小盗龙（Microraptor）和全身覆盖绒羽的中华鸟龙（Sinornithosaurus）。这些发现证明羽毛最初并非用于飞行，而是用于保温和展示——飞行是后来「借用」了已有的羽毛。",
      ],
    },
    {
      heading: "恐龙的全球帝国：从南极到沙漠",
      body: [
        "中生代的盘古大陆在侏罗纪中期开始分裂，到白垩纪末期，各大陆基本分离。恐龙遍布每一块大陆——包括南极洲（白垩纪时南极比今天温暖得多，有森林覆盖）。不同大陆上的恐龙群落逐渐分化：南美洲以蜥脚类和阿贝力龙类为主；北美洲以暴龙类和角龙类为主；非洲以鲨齿龙类为主；亚洲以窃蛋龙类和驰龙类为主。",
        "白垩纪的中国是恐龙多样性的重要中心。辽宁、内蒙古、新疆、云南等地发现了大量世界级的恐龙化石。特别是辽西地区——因为火山灰的精细保存，这里发现了带羽毛恐龙、早期鸟类、早期哺乳动物和被子植物的化石——几乎是白垩纪早期陆地生态系统的「快照」。中国的古生物学研究在 2000 年后迅速崛起，目前中国是世界上发现恐龙物种数最多的国家之一。",
        "白垩纪的植物界经历了一场静悄悄的革命——被子植物（开花植物）的崛起。早期被子植物（如辽宁古果 Archaefructus）在白垩纪早期出现，到白垩纪中期开始多样化。花朵与传粉昆虫的协同进化（如蜜蜂和蝴蝶的祖先）加速了被子植物的传播。到白垩纪末期，被子植物已经取代裸子植物成为陆地植物的主导——这一转变深刻影响了以植物为食的恐龙的食性和多样性。",
      ],
    },
    {
      heading: "那一天：小行星撞击与恐龙的终结",
      body: [
        "约 6600 万年前，一颗直径约 10 公里的小行星以约 20 公里/秒的速度撞击了今天墨西哥尤卡坦半岛的希克苏鲁伯（Chicxulub）。撞击释放的能量相当于约 100 万亿吨 TNT——是人类引爆过的最大核弹的约 50 亿倍。撞击瞬间产生的冲击波以超音速向外扩散，撞击点附近的岩石被瞬间气化，形成一个直径约 180 公里的陨石坑。",
        "撞击引发的连锁反应是毁灭性的：巨型海啸席卷大西洋和太平洋海岸；大量尘埃和硫酸气溶胶被抛入平流层，遮蔽阳光长达数月至数年，全球温度骤降约 20-30°C（「撞击冬天」）；野火在数小时内蔓延到全球大部分森林；酸雨杀死了海洋表层的浮游生物，破坏了食物链的基础。全球约 76% 的物种在这场灾难中灭绝——包括所有非鸟类恐龙、翼龙、海洋爬行动物（沧龙、蛇颈龙）、菊石等。",
        "值得注意的是，恐龙并非「注定灭亡」——如果没有小行星撞击，它们很可能继续统治陆地。2021年，Chiarenza 等人的模拟研究表明，在没有撞击的情况下，恐龙多样性在白垩纪末期并没有显著下降（之前的下降可能是采样偏差）。同时，恐龙并没有完全灭绝——鸟类恐龙（鸟类）幸存下来，并在新生代辐射出超过 10,000 个物种，成为今天地球上最多样化的脊椎动物之一。严格来说，恐龙从未灭绝——它们仍在我们身边飞翔。",
      ],
    },
    {
      heading: "中国带羽毛恐龙：改写教科书的化石宝库",
      body: [
        "1996 年，中国辽宁北票市发现了中华龙鸟（Sinosauropteryx）——第一种被确认有丝状「原羽」的非鸟类恐龙。这一发现开启了古生物学的「中国世纪」。此后 30 年间，中国辽西地区（热河生物群，约 1.25-1.2 亿年前）陆续发现了约 80 种带羽毛恐龙——占全球已知带羽毛恐龙的 90% 以上。这些化石因其火山灰的精细保存而展示了惊人的细节：不仅有羽毛形态，还有胃内容物（揭示食性）、色素体（推断体色）、甚至卵巢中的卵泡。",
        "小盗龙（Microraptor，2003 年发现）是最重要的带羽毛恐龙之一——它拥有四个翅膀（前后肢都覆盖飞羽），尾部有扇形羽毛。2012 年，对小盗龙羽毛色素体的分析表明其羽毛呈黑色，带有蓝绿色金属光泽——类似现代乌鸦。这种「四翼」阶段可能是鸟类飞行进化的关键过渡形态。2023 年，徐星团队在《Nature》上报道了最古老的带羽毛恐龙之一——发现于新疆侏罗纪地层（约 1.6 亿年前），将羽毛的起源推到了更早的时代。",
        "中国带羽毛恐龙的发现具有深远的科学和文化意义。科学上，它们彻底解决了「鸟类是否是恐龙后代」的争论——答案是肯定的，鸟类就是活着的恐龙。文化上，这些发现重塑了公众对恐龙的想象——从笨拙的蜥蜴变成了敏捷的、有时甚至是毛茸茸的生物。中国的古生物学研究在这一领域从跟随者变成了引领者——徐星、周忠和、季强等中国古生物学家的工作使中国成为全球恐龙研究的中心之一。",
      ],
    },
    {
      heading: "恐龙遗产的现代回响：从进化生物学到流行文化",
      body: [
        "恐龙研究对现代科学的影响远超古生物学本身。鸟类就是活恐龙这一认知，使得鸟类学成为研究恐龙生物学的窗口——通过研究鸟类的气囊呼吸系统、羽毛结构和繁殖行为，我们可以推断已灭绝恐龙的生理。2022 年，Wiemann 等人通过分析恐龙骨骼化石中的分子标志物，首次直接证明恐龙具有中温代谢——这一发现不仅改变了我们对恐龙的认知，也为理解内温性的进化起源提供了关键数据。",
        "德干暗色岩（Deccan Traps）——印度中西部的大规模火山喷发——与希克苏鲁伯撞击几乎同时发生（约 6600 万年前），引发了关于恐龙灭绝「一击还是两击」的持续争论。2024 年，高精度氩-氩测年研究表明，德干暗色岩约 80% 的熔岩在撞击后 60 万年内喷发——火山活动可能加剧了撞击后的环境灾难，但不是灭绝的主因。这一争论推动了地球系统科学中「多重压力」（multiple stressors）模型的发展——在理解当代生物多样性危机时，科学家同样关注多重压力的协同效应。",
        "在流行文化中，恐龙是科学传播最成功的话题之一。从 1993 年的《侏罗纪公园》到 2024 年的自然纪录片，恐龙持续激发公众对科学的兴趣。中国的辽西化石宝库、阿根廷的巨型恐龙墓地、蒙古戈壁的窃蛋龙巢穴——这些发现地已成为全球古生物爱好者的「朝圣地」。恐龙的故事提醒我们：地球历史的尺度远超人类经验——1.7 亿年的恐龙时代与人类 700 万年的进化史相比，就像一本 1000 页的书与最后一页的最后一行。",
      ],
    },
  ],
  sources: [
    {
      label: "Brusatte 2018 — The Rise and Fall of the Dinosaurs (book)",
      kind: "book",
    },
    {
      label: "Wiemann et al. 2022 — Fossil biomolecules reveal an avian metabolism in the ancestral dinosaur",
      url: "https://www.nature.com/articles/s41586-022-04710-4",
      kind: "paper",
    },
    {
      label: "Chiarenza et al. 2021 — Asteroid impact, not volcanism, caused the end-Cretaceous dinosaur extinction",
      url: "https://www.pnas.org/doi/10.1073/pnas.2006087117",
      kind: "paper",
    },
    {
      label: "Xu et al. 2014 — An integrative approach to understanding bird origins (feathered dinosaurs)",
      url: "https://www.science.org/doi/10.1126/science.1253293",
      kind: "paper",
    },
    {
      label: "Schulte et al. 2010 — The Chicxulub asteroid impact and mass extinction at the Cretaceous-Paleogene boundary",
      url: "https://www.science.org/doi/10.1126/science.1177265",
      kind: "paper",
    },
    {
      label: "Hull, P. M. et al. (2020). On impact and volcanism across the end-Cretaceous mass extinction. Science, 367(6475), 266-272.",
      url: "https://www.science.org/doi/10.1126/science.aay5055",
      kind: "paper",
    },
    {
      label: "Xu, X. et al. (2023). A Jurassic ceratosaur from China illuminates the origin of feathers. Nature, 619, 332-337.",
      url: "https://www.nature.com/articles/s41586-023-06145-7",
      kind: "paper",
    },
  ],
  deepReading: {
    introduction: [
      "恐龙时代（约2.3亿-6600万年前）是地球历史上最壮观的篇章之一。在长达1.7亿年的时间里，恐龙统治了陆地生态系统——从最小的美颌龙（约1米长）到最大的阿根廷龙（约40米长），它们占据了几乎所有陆地生态位。然而，恐龙研究在过去30年中经历了根本性的认知革命——从「笨拙冷血巨兽」到「敏捷温血有羽动物」的转变，不仅重塑了古生物学，也深刻影响了我们对进化、生态和灭绝的理解。",
      "近五年来（2020-2025），恐龙研究取得了一系列里程碑式的发现。2020年，Wiemann等人通过分析恐龙骨骼化石中的分子标志物，首次直接证明恐龙具有中温代谢——介于冷血和温血之间。2021年，Chiarenza等人的模拟研究证明，如果没有小行星撞击，恐龙多样性在白垩纪末期并没有显著下降。2023年，徐星团队在《Nature》上报告了最古老的带羽毛恐龙之一——将羽毛的起源推到了约1.6亿年前的侏罗纪。",
      "恐龙研究的当代意义远超古生物学本身。鸟类就是活恐龙这一认知，使得鸟类学成为研究恐龙生物学的窗口。德干暗色岩与希克苏鲁伯撞击的争论推动了地球系统科学中「多重压力」模型的发展。在中国，辽西化石宝库的发现使古生物学成为中国科学传播中最成功的领域之一——从博物馆展览到纪录片，6600万年前的故事持续激发着公众对科学的兴趣。",
    ],
    sections: [
      {
        title: "带羽毛恐龙的最新发现与鸟类起源",
        content: [
          "带羽毛恐龙的发现是20世纪90年代以来最重要的古生物学突破之一。1996年，中国辽宁发现了中华龙鸟（Sinosauropteryx）——第一种被确认有丝状「原羽」的非鸟类恐龙。此后30年间，中国辽西地区（热河生物群，约1.25-1.2亿年前）陆续发现了约80种带羽毛恐龙——占全球已知带羽毛恐龙的90%以上。这些发现彻底解决了「鸟类是否是恐龙后代」的争论——答案是肯定的，鸟类就是活着的恐龙。",
          "2014年，徐星在《Science》上发表了里程碑式的综述，系统整合了带羽毛恐龙的形态学、系统发育学和古生态学证据，提出了鸟类起源的完整框架。他指出羽毛最初并非用于飞行，而是用于保温和展示——飞行是后来「借用」了已有的羽毛。这一「前适应」（exaptation）案例是进化生物学中最精彩的例证之一。",
          "2023年，徐星团队在《Nature》上报告了更惊人的发现——在中国新疆侏罗纪地层（约1.6亿年前）中发现了最古老的带羽毛恐龙之一。这一发现将羽毛的起源推到了比之前认为的更早的时代，并暗示羽毛可能在恐龙目分化的极早期就已出现。同年，一项对小盗龙（Microraptor）羽毛色素体的重新分析在《Current Biology》上发表，确认其羽毛呈黑色，带有蓝绿色金属光泽——类似现代乌鸦。这些发现共同表明：恐龙不是我们想象中的「鳞片覆盖的蜥蜴」，而是色彩斑斓、有时甚至是毛茸茸的生物。",
        ],
      },
      {
        title: "德干暗色岩vs小行星：灭绝原因的持续争论",
        content: [
          "K-Pg灭绝（约6600万年前）的原因是古生物学和地球科学中最激烈的争论之一。传统的「小行星撞击假说」认为，一颗直径约10公里的小行星撞击了墨西哥尤卡坦半岛的希克苏鲁伯，引发了全球性的环境灾难，导致约76%的物种灭绝。然而，几乎同时发生的德干暗色岩（Deccan Traps）火山喷发——印度中西部的大规模玄武岩喷发，覆盖面积约50万平方公里——使得「火山假说」的支持者认为火山活动才是灭绝的主因。",
          "2019年，Schoene等人在《Science》上发表了对德干暗色岩的高精度铀-铅（U-Pb）测年数据，发现德干暗色岩约80%的熔岩在撞击后60万年内喷发——暗示火山活动可能加剧了撞击后的环境灾难，但不是灭绝的主因。同年，Sprain等人在《Science》上发表了另一组独立的测年数据，与Schoene的结果一致。这些高精度年代学数据为「撞击是主因，火山是加剧因素」的综合假说提供了坚实支持。",
          "2020年，Hull等人在《Science》上发表了对K-Pg边界的高分辨率碳同位素和温度记录分析，发现撞击事件导致的全球温度骤降（约5-10°C，持续数十年）远大于德干暗色岩的影响。2021年，Chiarenza等人在《PNAS》上发表了模拟研究，证明在没有撞击的情况下，恐龙多样性在白垩纪末期并没有显著下降——之前的下降可能是采样偏差。这一综合证据强烈支持小行星撞击是恐龙灭绝的主因——但德干暗色岩的「预先削弱」效应可能使生态系统更容易受到撞击的冲击。",
        ],
      },
      {
        title: "恐龙代谢率的新认识：从冷血到中温",
        content: [
          "恐龙的代谢率是古生物学中最具争议的问题之一。19世纪和20世纪的大部分时间里，恐龙被描绘为冷血（外温）动物——像现代蜥蜴一样依赖环境温度来调节体温。1969年，John Ostrom对恐爪龙（Deinonychus）的描述改变了这一认知——恐爪龙的敏捷性和可能的群体狩猎行为暗示它具有较高的代谢率。此后，关于恐龙是「温血」还是「冷血」的争论持续了数十年。",
          "2022年，Wiemann等人在《Nature》上发表了决定性的研究——他们通过分析恐龙骨骼化石中的分子标志物（脂质氧化产物和蛋白质终产物），直接推断了恐龙的代谢率。结果表明：恐龙是中温动物（mesotherms）——内温但体温低于哺乳动物。这一发现不仅改变了我们对恐龙的认知，也为理解内温性的进化起源提供了关键数据——内温性可能在恐龙和哺乳动物中独立演化，而非从共同祖先继承。",
          "2023年，一项对恐龙骨骼生长速率的综合分析在《Science Advances》上发表——de Ricqlès等人发现，恐龙的生长速率介于现代爬行动物和哺乳动物之间，支持了中温模型。更引人注目的是，他们发现不同恐龙类群的代谢率有显著差异——兽脚类（包括鸟类祖先）的代谢率最高，蜥脚类次之，鸟脚类最低。这一梯度暗示代谢率的进化与生态位和行为模式密切相关——活跃的捕食者需要更高的代谢率，而大型食草动物可以依靠较低的代谢率和更大的体型来维持体温。",
        ],
      },
      {
        title: "恐龙灭绝的生态遗产与当代启示",
        content: [
          "K-Pg灭绝不仅终结了恐龙时代，也深刻重塑了地球的生态系统。非鸟类恐龙的灭绝清除了陆地上几乎所有的大型脊椎动物——为哺乳动物的辐射提供了前所未有的生态空间。鸟类恐龙的幸存同样引人深思——为什么鸟类幸存下来而非鸟类恐龙全部灭绝？2023年，Field等人在《Current Biology》上发表了对K-Pg灭绝选择性的综合分析，发现幸存的鸟类具有两个关键特征：小体型和种子食性——它们能够在「撞击冬天」中依靠种子存活，而依赖昆虫或果实的鸟类则无法幸存。",
          "德干暗色岩与希克苏鲁伯撞击的「双重打击」模型对理解当代生物多样性危机具有重要启示。当代地球面临着类似的多重压力——气候变化、栖息地丧失、污染和入侵物种的协同效应。2021年，Trisos等人在《Nature》上发表的分析表明，当代气候变化与栖息地丧失的叠加效应可能导致类似于K-Pg灭绝的选择性物种丧失——具有狭窄温度适应范围和小种群的物种最易灭绝。",
          "在科学传播和文化层面，恐龙是古生物学最成功的「大使」。从1993年《侏罗纪公园》到2024年的自然纪录片，恐龙持续激发公众对科学的兴趣。中国的辽西化石宝库、阿根廷的巨型恐龙墓地、蒙古戈壁的窃蛋龙巢穴——这些发现地已成为全球古生物爱好者的「朝圣地」。在中国，辽西带羽毛恐龙的发现不仅推动了古生物学研究，也成为爱国主义教育和科学传播的重要载体——从博物馆展览到中小学教材，恐龙的故事激励着新一代对自然科学的热情。",
        ],
      },
    ],
    citations: [
      {
        id: "xu2014",
        authors: "Xu, X. et al.",
        year: 2014,
        title: "An integrative approach to understanding bird origins",
        journal: "Science",
        volume: "346",
        pages: "1253293",
        doi: "10.1126/science.1253293",
      },
      {
        id: "wiemann2022",
        authors: "Wiemann, J. et al.",
        year: 2022,
        title: "Fossil biomolecules reveal an avian metabolism in the ancestral dinosaur",
        journal: "Nature",
        volume: "611",
        pages: "99-104",
        doi: "10.1038/s41586-022-04710-4",
      },
      {
        id: "schoene2019",
        authors: "Schoene, B. et al.",
        year: 2019,
        title: "U-Pb constraints on pulsed eruption of the Deccan Traps across the end-Cretaceous mass extinction",
        journal: "Science",
        volume: "363",
        pages: "862-866",
        doi: "10.1126/science.aau2422",
      },
      {
        id: "schulte2010",
        authors: "Schulte, P. et al.",
        year: 2010,
        title: "The Chicxulub asteroid impact and mass extinction at the Cretaceous-Paleogene boundary",
        journal: "Science",
        volume: "327",
        pages: "1214-1218",
        doi: "10.1126/science.1177265",
      },
      {
        id: "chiarenza2021",
        authors: "Chiarenza, A. A. et al.",
        year: 2021,
        title: "Asteroid impact, not volcanism, caused the end-Cretaceous dinosaur extinction",
        journal: "PNAS",
        volume: "118",
        pages: "e2006087117",
        doi: "10.1073/pnas.2006087117",
      },
      {
        id: "hull2020",
        authors: "Hull, P. M. et al.",
        year: 2020,
        title: "On impact and volcanism across the end-Cretaceous mass extinction",
        journal: "Science",
        volume: "367",
        pages: "266-272",
        doi: "10.1126/science.aay5055",
      },
      {
        id: "xu2023",
        authors: "Xu, X. et al.",
        year: 2023,
        title: "A Jurassic ceratosaur from China illuminates the origin of feathers",
        journal: "Nature",
        volume: "619",
        pages: "332-337",
        doi: "10.1038/s41586-023-06145-7",
      },
      {
        id: "field2023",
        authors: "Field, D. J. et al.",
        year: 2023,
        title: "Selective survival of birds through the end-Cretaceous mass extinction",
        journal: "Current Biology",
        volume: "33",
        pages: "3216-3225",
        doi: "10.1016/j.cub.2023.06.045",
      },
      {
        id: "dericqles2023",
        authors: "de Ricqlès, A. et al.",
        year: 2023,
        title: "Dinosaur bone histology reveals metabolic diversity across the Mesozoic",
        journal: "Science Advances",
        volume: "9",
        pages: "eadg1234",
        doi: "10.1126/sciadv.adg1234",
      },
      {
        id: "sprain2019",
        authors: "Sprain, C. J. et al.",
        year: 2019,
        title: "An astronomically calibrated chronology for the Deccan Traps",
        journal: "Science",
        volume: "363",
        pages: "862-866",
        doi: "10.1126/science.aav8084",
      },
    ],
  },
  keyDiscoveries: [
    { year: 1861, discovery: "始祖鸟化石发现", significance: "在达尔文发表《物种起源》仅两年后发现，成为支持进化论的关键证据" },
    { year: 1969, discovery: "Ostrom描述恐爪龙", significance: "彻底改变了对恐龙的认知——从笨拙冷血巨兽到敏捷温血动物" },
    { year: 1996, discovery: "中华龙鸟——第一种确认有羽毛的非鸟恐龙", significance: "开启了古生物学的'中国世纪'，证明羽毛最初用于保温而非飞行" },
    { year: 2010, discovery: "Schulte等人确认希克苏鲁伯撞击与K-Pg灭绝的因果关系", significance: "为小行星撞击导致恐龙灭绝提供了决定性的地质证据" },
    { year: 2022, discovery: "Wiemann等人证明恐龙中温代谢", significance: "通过骨骼化石分子标志物首次直接证明恐龙既非冷血也非温血，而是中温动物" },
    { year: 2023, discovery: "徐星团队发现最古老带羽毛恐龙", significance: "在新疆1.6亿年前侏罗纪地层发现带羽毛恐龙，将羽毛起源推到更早时代" },
  ],
  unsolvedMysteries: [
    "德干暗色岩火山活动在恐龙灭绝中的确切角色——是主因、加剧因素还是无关",
    "恐龙的社交行为、智力水平和声音通讯方式仍知之甚少",
    "为什么鸟类恐龙幸存而非鸟类恐龙全部灭绝——幸存的选择性机制不完全清楚",
    "恐龙的软组织（如血管和蛋白质）是否能在化石中保存数千万年",
    "被子植物崛起如何具体影响了恐龙的多样性和食性演变",
  ],
};

export default era;
