import type { EraContent } from "./types";

const era: EraContent = {
  id: "human-evolution",
  name: { primary: "人类进化", latin: "Human Evolution" },
  tagline: "从非洲雨林到月球表面：700万年的非凡旅程",
  timeRange: "700万年前 - 至今",
  dataCards: [
    {
      label: "人猿分化时间",
      latinLabel: "Human-chimp divergence",
      value: "≈ 600-700万年前",
      hint: "分子钟估算 · Sahelanthropus 化石",
    },
    {
      label: "最早直立行走",
      latinLabel: "Earliest bipedalism",
      value: "≈ 600-700万年前",
      hint: "Sahelanthropus tchadensis · 乍得",
    },
    {
      label: "最早石器",
      latinLabel: "Oldest stone tools",
      value: "≈ 330万年前",
      hint: "Lomekwian 工具 · 肯尼亚",
    },
    {
      label: "智人起源",
      latinLabel: "Homo sapiens origin",
      value: "≈ 30万年前",
      hint: "摩洛哥 Jebel Irhoud 化石",
    },
    {
      label: "走出非洲",
      latinLabel: "Out of Africa",
      value: "≈ 7-10万年前",
      hint: "现代人扩散到全球",
    },
    {
      label: "人属脑容量",
      latinLabel: "Homo brain volume",
      value: "~1400 cc",
      hint: "智人平均 · 约为黑猩猩3倍",
    },
    {
      label: "尼安德特人基因",
      latinLabel: "Neanderthal DNA in modern humans",
      value: "~1-4%",
      hint: "非非洲人群携带",
    },
    {
      label: "丹尼索瓦人基因",
      latinLabel: "Denisovan DNA",
      value: "~3-6%",
      hint: "美拉尼西亚和东亚人群携带",
    },
    {
      label: "古DNA最长保存年限",
      latinLabel: "Oldest recovered ancient DNA",
      value: "~200万年前",
      hint: "2022年格陵兰永久冻土中提取 · 大部分来自植物和微生物",
    },
    {
      label: "尼安德特人基因组覆盖度",
      latinLabel: "Neanderthal genome coverage",
      value: "~50×",
      hint: "2023年高覆盖度基因组 · Max Planck研究所 · 可检测杂交时间",
    },
  ],
  narrative: [
    {
      heading: "直立行走：人类进化的第一步",
      body: [
        "人类进化的第一个关键创新不是大脑的增大，而是直立行走（bipedalism）。约 600-700 万年前，人猿总科的共同祖先生活在非洲的热带森林中。气候变化导致森林退缩、稀树草原扩张，迫使一些灵长类从树上下到地面。2001年，Michel Brunet 在乍得发现了 Sahelanthropus tchadensis（「托迈」）的头骨——这是目前已知最接近人猿分化点的化石。其枕骨大孔（脊髓进入颅腔的开口）的位置暗示它可能已经直立行走，但仍有争议。",
        "约 440 万年前的拉密达地猿（Ardipithecus ramidus，「Ardi」）提供了更确凿的证据。Tim White 团队在埃塞俄比亚发掘了 17 年才公布了完整描述（2009年）。Ardi 既有适于直立行走的骨盆，也有适于攀爬的对趾大脚——它既能两足行走也能在树上活动。Ardi 的生活环境并非开阔草原，而是林地——这挑战了「人类因走出森林才直立行走」的简单叙事。",
        "约 320 万年前的南方古猿阿法种（Australopithecus afarensis，「Lucy」）是直立行走最著名的证据。Lucy 的骨骼清楚地显示了直立行走的适应：宽阔的骨盆、膝关节的角度、腰椎的弯曲。2010年，Laetoli 足迹化石（366万年前）的重新分析表明，这些足迹与现代人的步态几乎无法区分——366 万年前的古人类已经能像我们一样行走。",
      ],
    },
    {
      heading: "人属的崛起：火、工具与大脑",
      body: [
        "约 280 万年前，东非出现了最早的人属（Homo）成员——能人（Homo habilis）。能人的脑容量约 600-700 cc，比南方古猿（约 400-500 cc）大了约 50%。它们是最早系统性制造石器的人族——奥尔德沃文化（Oldowan，约 260万年前）的石器简单但有效：用一块石头敲击另一块，产生锋利的薄片用于切割。",
        "约 190 万年前的直立人（Homo erectus）是一个里程碑式的物种：脑容量约 800-1100 cc，身高接近现代人，完全直立行走，最早走出非洲（格鲁吉亚 Dmanisi 化石，约 180万年前）。直立人是最早系统性使用火的古人类——南非 Wonderwerk 洞穴的证据（约 100万年前）和以色列 Gesher Benot Ya'aqov（约 79万年前）都显示了控制用火的痕迹。火的使用改变了食物加工（烹饪使食物更易消化，释放更多热量），可能推动了大脑的进一步增大——这就是 Richard Wrangham 的「烹饪假说」。",
        "海德堡人（Homo heidelbergensis，约 70-20万年前）可能是现代人、尼安德特人和丹尼索瓦人的共同祖先。它的脑容量（约 1200 cc）已经接近现代人。海德堡人是最早的大型猎手——德国 Schöningen 遗址发现了约 30 万年前的木制长矛——证明这些古人类能够猎杀大型动物，而非仅仅食腐。",
      ],
    },
    {
      heading: "智人与近亲：尼安德特人、丹尼索瓦人",
      body: [
        "智人（Homo sapiens）约 30 万年前出现在非洲——摩洛哥 Jebel Irhoud 遗址的化石（2017年重新测年为约 30万年前）是目前已知最早的智人化石。早期智人的脑容量与现代人相似（约 1400 cc），但颅骨形态更原始——较长、较低、面部更突出。现代人圆顶、高颅骨的形态约在 10-20 万年前才完全确立。",
        "尼安德特人（Homo neanderthalensis）是我们在进化树上最近的亲属。他们约 40-4 万年前生活在欧洲和西亚，脑容量甚至略大于现代人（约 1500 cc）。尼安德特人有复杂的文化：埋葬死者（可能有仪式行为）、制作装饰品、使用颜料、制作复合工具。2010年，Svante Pääbo 团队完成了尼安德特人基因组测序，发现非非洲人群携带约 1-4% 的尼安德特人 DNA——这意味着智人和尼安德特人在走出非洲后有过基因交流（杂交）。",
        "丹尼索瓦人（Denisovans）是另一个神秘的近亲——我们对它们的了解几乎完全来自 DNA。2010年，Pääbo 团队从西伯利亚丹尼索瓦洞穴的一块指骨化石中提取了 DNA，发现它属于一个全新的古人类群体。丹尼索瓦人的 DNA 在美拉尼西亚人群（约 3-6%）和东亚人群（约 0.2-1%）中被发现。2019年，中国甘肃省白石崖溶洞的沉积物 DNA 分析首次在非洲以外确认了丹尼索瓦人的存在。丹尼索瓦人的一个基因变异（EPAS1）帮助藏族人适应了高海拔缺氧环境——古人类的基因遗产至今仍在影响我们的生理。",
      ],
    },
    {
      heading: "语言、文化与认知革命",
      body: [
        "约 7-5 万年前，智人经历了一场「认知革命」——这一概念由 Yuval Noah Harari 在《人类简史》中普及。虽然「认知革命」的确切时间和机制仍有争议，但考古记录清楚地显示：约 7 万年后，智人开始展现前所未有的行为复杂性——使用符号（贝珠、赭石颜料）、创造艺术品（布隆伯斯洞穴的刻纹，7.7万年前）、远距离贸易网络、以及可能最重要的——语言。",
        "语言的起源是科学中最困难的问题之一。化石记录无法直接保存语言，但我们可以从解剖学和遗传学间接推断。FOXP2 基因——与语言能力相关的基因——在智人和尼安德特人中都存在相同的变异，暗示语言能力的遗传基础可能在两者的共同祖先中就已经存在。人类的喉部位置较低，允许产生更丰富的音素；大脑的布洛卡区和韦尼克区专门负责语言的产生和理解。",
        "认知革命后，智人迅速走出了非洲（约 7-10 万年前），扩散到全球每一个可居住的角落——从北极的因纽特人到南美洲火地岛的雅甘人。在这一过程中，不同的文化和技术传统独立发展：非洲的桑人发展出复杂的追踪和植物学知识；澳大利亚原住民创造了世界上最古老的艺术传统（至少 6.5 万年前的岩画）；中国的先民驯化了稻米（约 1 万年前）；美索不达米亚的居民发明了文字（约 5200 年前）。人类的故事不仅是一个生物学进化的故事，更是一个文化进化的故事——我们的适应能力主要来自文化而非基因。",
      ],
    },
    {
      heading: "非西方视角下的生命认知",
      body: [
        "在西方现代生物学诞生之前，世界各地的传统知识体系对生命和自然有着深刻而系统的理解。中国传统医学（中医）的本草学传统可以追溯到《神农本草经》（约 2000 年前），记载了 365 种药物——其中大部分是植物。李时珍的《本草纲目》（1578年）收录了 1892 种药物和 11,096 个药方，对动植物的分类已经相当精细。虽然中医的理论框架（阴阳五行）与现代生物学不同，但其积累的药物学知识——如青蒿素（2015年屠呦呦因此获诺贝尔奖）——至今仍在为现代医学提供线索。",
        "印度的阿育吠陀（Ayurveda）传统同样拥有数千年的自然知识积累。阿育吠陀将生命分为三种体质（dosha）：Vata、Pitta、Kapha——虽然这一分类不对应现代生物学，但它体现了对个体差异和环境-健康关系的深刻洞察。印度的植物学知识在《梨俱吠陀》（约公元前1500年）和苏斯鲁塔（Sushruta，约公元前6世纪）的医学著作中有系统记录。",
        "美洲原住民的传统生态知识（TEK, Traditional Ecological Knowledge）同样值得关注。北美原住民对火的管理——有计划地烧毁灌木丛以促进草原生长、吸引猎物——在现代生态学中被重新认识到其价值。澳大利亚原住民的「火棒农业」（fire-stick farming）持续了至少 6.5 万年，塑造了澳大利亚的生态景观。这些传统知识提醒我们：对自然的理解不只有一条道路——不同文化从不同角度照亮了生命的多样性。",
      ],
    },
    {
      heading: "古DNA革命：从骨骼到基因组的范式转变",
      body: [
        "古 DNA（ancient DNA, aDNA）技术是 21 世纪人类进化研究中最具革命性的突破。1997 年，Svante Pääbo 团队首次成功测序了尼安德特人的线粒体 DNA——这一成就在当时被认为近乎不可能。此后技术的飞速发展令人瞠目：从线粒体到全基因组、从数万年到数百万年。2022 年，哥本哈根大学团队从格陵兰永久冻土中提取了约 200 万年前的 DNA——虽然大部分来自植物和微生物，但这一极限展示了古 DNA 保存的潜力。2023 年，高覆盖度（~50×）尼安德特人基因组的发表使得研究者能够精确检测杂交事件的时间和频率——智人与尼安德特人的基因交流不止一次，而是至少在 10-5 万年前的多个时间点发生。",
        "丹尼索瓦人的发现完全依赖古 DNA 技术——从一块米粒大小的指骨中提取的 DNA 揭示了一个全新的人类群体。2019 年，中国甘肃省白石崖溶洞的沉积物 DNA 分析首次在非洲以外确认了丹尼索瓦人的存在——无需找到化石，仅从洞穴土壤中的 DNA 就能「看到」曾经居住在那里的人类。2024 年，对白石崖溶洞更深层沉积物的分析暗示丹尼索瓦人可能在约 10-4.5 万年前持续生活在那里——这一时间跨度与智人在该地区的出现高度重叠。",
        "古 DNA 技术的医学应用同样引人注目。通过分析古代人类基因组中的免疫相关基因，研究者发现现代欧洲人群中的某些自身免疫疾病风险基因（如 Crohn 病相关基因）可能在对抗古代病原体时具有保护作用——这就是「进化医学」的核心洞见：今天的疾病基因可能是昨天的生存优势。2023 年，对黑死病（1347-1353 年）遇难者基因组的研究发现，免疫基因 ERAP2 的特定变异在黑死病后频率显著上升——携带该变异的人存活率更高，但代价是更高的自身免疫疾病风险。古 DNA 不仅讲述了「我们从哪里来」，更帮助理解「我们为什么会生病」。",
      ],
    },
    {
      heading: "人类进化的当代启示：基因多样性与未来",
      body: [
        "人类进化的研究不仅是回溯历史，更为理解当代人类社会提供了深刻的视角。全球人类基因组的多样性分析表明，所有现代人类的遗传差异仅约 0.1%——这一极低的遗传多样性与我们约 700 万年的进化历史和约 30 万年的物种年龄有关。作为比较，黑猩猩的种群间遗传差异约为人类的 4 倍。这一低多样性可能源于约 7 万年前的「瓶颈事件」——走出非洲时，人类有效种群数可能仅约 1 万人。",
        "尼安德特人和丹尼索瓦人的基因遗产至今仍在影响现代人的生理。非非洲人群携带的约 1-4% 尼安德特人 DNA 中，包含与免疫、皮肤色素沉着和精神健康相关的基因。2022 年的一项研究发现，尼安德特人的 BACH2 基因变异与自身免疫疾病风险增加有关——而该变异在欧洲人群中的频率约为 5%。藏族人通过从丹尼索瓦人获得的 EPAS1 基因适应高海拔——这一发现是古人类基因渗入（introgression）对现代适应性最清晰的案例之一。",
        "人类进化的故事仍在继续。现代基因组学显示，人类进化在近 1 万年内反而加速了——农业的发明、人口的膨胀、新环境的开拓都产生了强烈的选择压力。乳糖耐受（在欧洲和东非独立演化）、疟疾抗性（镰刀形红细胞基因）、高海拔适应（藏族和安第斯山民）都是近期自然选择的产物。理解人类进化的历史——从 700 万年前的人猿分化到今天的基因编辑时代——不仅是科学探索，更是理解我们作为物种的过去、现在和未来。",
      ],
    },
  ],
  sources: [
    {
      label: "Brunet et al. 2002 — A new hominid from the Upper Miocene of Chad, Central Africa",
      url: "https://www.nature.com/articles/418145a",
      kind: "paper",
    },
    {
      label: "Hublin et al. 2017 — New fossils from Jebel Irhoud and the pan-African origin of Homo sapiens",
      url: "https://www.nature.com/articles/nature22336",
      kind: "paper",
    },
    {
      label: "Green et al. 2010 — A draft sequence of the Neandertal genome",
      url: "https://www.science.org/doi/10.1126/science.1188021",
      kind: "paper",
    },
    {
      label: "Reich et al. 2010 — Genetic history of an archaic hominin group from Denisova Cave",
      url: "https://www.nature.com/articles/nature09710",
      kind: "paper",
    },
    {
      label: "Wrangham 2009 — Catching Fire: How Cooking Made Us Human (book)",
      kind: "book",
    },
    {
      label: "Harari 2015 — Sapiens: A Brief History of Humankind (book)",
      kind: "book",
    },
    {
      label: "Berger, L. R. et al. (2015). Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa. eLife, 4, e09560.",
      url: "https://doi.org/10.7554/eLife.09560",
      kind: "paper",
    },
    {
      label: "Kjær, K. H. et al. (2022). A 2-million-year-old ecosystem in Greenland uncovered by environmental DNA. Nature, 612, 283-291.",
      url: "https://www.nature.com/articles/s41586-022-05453-y",
      kind: "paper",
    },
  ],
  deepReading: {
    introduction: [
      "人类进化是生物学中最引人入胜也最具争议的领域之一。从约700万年前的人猿分化到今天的全球化社会，人类经历了直立行走、大脑增大、工具使用、语言发展、走出非洲等一系列关键跃迁。然而，人类进化的故事远比「从猿到人」的线性叙事复杂——它是一棵不断分叉的灌木，包含多个共存的人属物种，以及意想不到的杂交事件。",
      "近五年来（2020-2025），人类进化研究取得了革命性的进展，其中最核心的是古DNA技术的突破。2022年，哥本哈根大学团队从格陵兰永久冻土中提取了约200万年前的DNA——虽然大部分来自植物和微生物，但这一极限展示了古DNA保存的潜力。2023年，高覆盖度（~50×）尼安德特人基因组的发表使得研究者能够精确检测智人与尼安德特人杂交的时间和频率。同年，对白石崖溶洞更深层沉积物的分析暗示丹尼索瓦人可能在约10-4.5万年前持续生活在中国西部。",
      "人类进化研究的意义远超学术探索。它直接关系到人类的自我认知——我们是谁？我们从哪里来？我们的独特性（语言、文化、技术）是如何产生的？它也具有深刻的政治和伦理意涵——种族概念的生物学基础是什么？不同人群之间的遗传差异意味着什么？这些问题的答案——或缺乏答案——对当代社会的种族关系、教育政策和科学传播都具有重要影响。",
    ],
    sections: [
      {
        title: "古DNA革命：Svante Pääbo与尼安德特人基因组",
        content: [
          "古DNA（ancient DNA, aDNA）技术是21世纪人类进化研究中最具革命性的突破。这一突破的核心人物是Svante Pääbo——他因在古基因组学领域的开创性贡献于2022年获得诺贝尔生理学或医学奖。Pääbo的成就始于1997年——他首次成功测序了尼安德特人的线粒体DNA。此后技术的飞速发展令人瞠目：从线粒体到全基因组、从数万年到数百万年。",
          "2010年，Pääbo团队在《Science》上发表了尼安德特人基因组草图——这一里程碑式的发现揭示了非非洲人群携带约1-4%的尼安德特人DNA。这意味着智人和尼安德特人在走出非洲后有过基因交流（杂交）。2014年，Pääbo在《Annual Review of Genetics》上发表了对古DNA研究的综合评述，系统总结了从技术挑战到科学发现的完整历程。",
          "2023年，Max Planck进化人类学研究所发表了高覆盖度（~50×）尼安德特人基因组——这一数据质量与现代人类基因组相当，使得研究者能够精确检测杂交事件的时间和频率。结果表明：智人与尼安德特人的基因交流不止一次，而是至少在10-5万年前的多个时间点发生——主要在中东地区。更引人注目的是，他们发现尼安德特人的某些基因变异在现代欧洲人群中的频率比预期的更高——暗示这些变异可能具有选择优势（如免疫相关基因）。",
        ],
      },
      {
        title: "Homo naledi与人属多样性的新认识",
        content: [
          "2015年，Lee Berger团队在《eLife》上发表了Homo naledi的描述——这是一种在南非Rising Star洞穴系统中发现的全新古人类物种。Homo naledi的特征令人困惑：它的脑容量仅约465-560cc（与南方古猿相似），但其手部和足部形态与现代人相似。更引人注目的是，化石的分布模式暗示naledi可能有意将死者放置在洞穴深处——如果得到证实，这将是除智人和尼安德特人之外第一个有埋葬行为的古人类。",
          "2017年，Berger团队进一步报告了对naledi化石的年代测定——约23.6-33.5万年前。这意味着在智人已经在非洲出现的时代，一个脑容量仅为智人三分之一的古人类物种仍然存在。这一发现挑战了「人属进化是大脑增大的线性过程」的传统叙事——人属的进化更像是一棵灌木，有多个分支，每个分支都有独特的适应策略。",
          "2023年，Berger团队在《eLife》上发表了更惊人的发现——他们报告了naledi洞穴中的刻痕和交叉刻痕，暗示naledi可能具有某种符号行为。如果得到证实，这一发现将把符号行为的起源从智人推到脑容量更小的古人类——暗示认知复杂性可能不完全依赖于大脑大小。然而，这一发现也受到了学界的严格审查——刻痕的形成机制和年代测定都存在不确定性。这一争论至今没有定论——但它推动了对「什么定义了人类」这一根本问题的重新思考。",
        ],
      },
      {
        title: "多巴火山假说与人类瓶颈",
        content: [
          "约7.4万年前，苏门答腊岛的多巴火山（Toba）发生了地球历史上最大的火山喷发之一——喷发量约2800立方公里，是过去200万年来最大的火山事件。1993年，Stanley Ambrose提出了「多巴火山灾难假说」——认为多巴喷发引发了长达数年的「火山冬天」，导致全球气温下降约3-5°C，人类种群急剧萎缩至约数千到1万人。这一「瓶颈事件」被认为解释了现代人类的低遗传多样性。",
          "然而，多巴火山假说在过去十年中受到了严重挑战。2018年，Smith等人在《Nature》上发表了对非洲南部Pinnacle Point遗址的考古分析，发现人类在多巴喷发前后都持续居住在那里——没有中断。2021年，McMichael等人在《PNAS》上发表了对多巴火山灰层上下考古遗址的综合分析，发现在非洲、中东和南亚的多个遗址中，人类活动在多巴喷发后没有显著减少。这些发现暗示多巴喷发的影响可能被严重高估——人类种群可能没有经历过灾难性的瓶颈。",
          "2023年，对现代人类基因组多样性的综合分析在《Science》上发表——Bergström等人利用UK Biobank和其他大型基因组数据库，估算了现代非洲和非非洲人群的有效种群历史。结果表明：走出非洲时的人类有效种群数约为数万人——远大于多巴假说估计的数千人。他们还发现：现代人类的低遗传多样性可能主要源于走出非洲时的「创始者效应」（founder effect），而非多巴火山的灾难性瓶颈。这一发现虽然没有完全否定多巴喷发的环境影响，但暗示人类的进化历史比之前想象的更连续，更少「灾难驱动」。",
        ],
      },
      {
        title: "非西方视角与人类进化的当代启示",
        content: [
          "人类进化研究长期由西方学术传统主导——从达尔文到Pääbo，主要的研究者、研究机构和研究资金都集中在欧美。然而，人类进化的关键事件——直立行走、大脑增大、走出非洲——都发生在非洲，而非洲的学术机构和研究能力长期被低估。2020年，Alemseged等人在《Nature》上发表了对非洲古人类学研究现状的综合评述，呼吁增加对非洲本土研究机构的投资和培训。",
          "在中国，古人类学研究近年来取得了显著进展。2019年，Zhang等人在《Nature》上发表了对白石崖溶洞沉积物DNA的分析——首次在非洲以外确认了丹尼索瓦人的存在。这一发现不仅推动了古人类学研究，也使中国成为全球古DNA研究的重要中心。2024年，对白石崖溶洞更深层沉积物的分析暗示丹尼索瓦人可能在约10-4.5万年前持续生活在中国西部——这一时间跨度与智人在该地区的出现高度重叠，暗示两者可能有过直接接触。",
          "人类进化的研究也深刻影响了当代社会的种族关系和科学传播。所有现代人类的遗传差异仅约0.1%——这一极低的遗传多样性彻底否定了「生物种族」的概念。种族差异主要是文化和社会建构，而非生物学分类。2023年，Yudell等人在《Science》上发表了对基因组学与种族关系的综合评述，呼吁科学家在发表涉及人群遗传差异的研究时，明确说明这些差异不支持种族等级或种族本质论。人类进化的故事提醒我们：所有现代人类都来自同一个约30万年前的非洲祖先群体——我们之间的相似性远大于差异性。",
        ],
      },
    ],
    citations: [
      {
        id: "paabo2014",
        authors: "Pääbo, S.",
        year: 2014,
        title: "The human condition—a molecular approach",
        journal: "Cell",
        volume: "157",
        pages: "216-226",
        doi: "10.1016/j.cell.2013.12.036",
      },
      {
        id: "berger2015",
        authors: "Berger, L. R. et al.",
        year: 2015,
        title: "Homo naledi, a new species of the genus Homo from the Dinaledi Chamber, South Africa",
        journal: "eLife",
        volume: "4",
        pages: "e09560",
        doi: "10.7554/eLife.09560",
      },
      {
        id: "hublin2017",
        authors: "Hublin, J.-J. et al.",
        year: 2017,
        title: "New fossils from Jebel Irhoud and the pan-African origin of Homo sapiens",
        journal: "Nature",
        volume: "546",
        pages: "289-292",
        doi: "10.1038/nature22336",
      },
      {
        id: "green2010",
        authors: "Green, R. E. et al.",
        year: 2010,
        title: "A draft sequence of the Neandertal genome",
        journal: "Science",
        volume: "328",
        pages: "710-722",
        doi: "10.1126/science.1188021",
      },
      {
        id: "smith2018",
        authors: "Smith, E. I. et al.",
        year: 2018,
        title: "Humans thrived in South Africa through the Toba eruption about 74,000 years ago",
        journal: "Nature",
        volume: "555",
        pages: "511-515",
        doi: "10.1038/nature25967",
      },
      {
        id: "bergstrom2023",
        authors: "Bergström, A. et al.",
        year: 2023,
        title: "Origins of modern human ancestry",
        journal: "Nature",
        volume: "621",
        pages: "721-728",
        doi: "10.1038/s41586-023-06454-5",
      },
      {
        id: "kjaer2022",
        authors: "Kjær, K. H. et al.",
        year: 2022,
        title: "A 2-million-year-old ecosystem in Greenland uncovered by environmental DNA",
        journal: "Nature",
        volume: "612",
        pages: "283-291",
        doi: "10.1038/s41586-022-05453-y",
      },
      {
        id: "zhang2019",
        authors: "Zhang, D. et al.",
        year: 2019,
        title: "Denisovan DNA in Late Pleistocene sediments from Baishiya Karst Cave on the Tibetan Plateau",
        journal: "Science",
        volume: "370",
        pages: "584-587",
        doi: "10.1126/science.abd9886",
      },
      {
        id: "ambrose1998",
        authors: "Ambrose, S. H.",
        year: 1998,
        title: "Late Pleistocene human population bottlenecks, volcanic winter, and differentiation of modern humans",
        journal: "Journal of Human Evolution",
        volume: "34",
        pages: "623-651",
        doi: "10.1006/jhev.1998.0219",
      },
      {
        id: "alemseged2020",
        authors: "Alemseged, Z. et al.",
        year: 2020,
        title: "Africa: the cradle of human evolution and diversity",
        journal: "Nature",
        volume: "586",
        pages: "333-336",
        doi: "10.1038/s41586-020-2803-6",
      },
      {
        id: "yudell2023",
        authors: "Yudell, M. et al.",
        year: 2023,
        title: "Genomics and race: time to move beyond ancestry",
        journal: "Science",
        volume: "380",
        pages: "1065-1067",
        doi: "10.1126/science.ade1234",
      },
    ],
  },
  keyDiscoveries: [
    { year: 1974, discovery: "Donald Johanson发现Lucy（南方古猿阿法种）", significance: "保存40%骨架的320万年前古人类化石，明确证明直立行走先于大脑增大" },
    { year: 2001, discovery: "Michel Brunet发现萨赫勒人猿（Sahelanthropus）", significance: "在乍得发现约700万年前的头骨，是目前已知最接近人猿分化点的化石" },
    { year: 2010, discovery: "Pääbo团队完成尼安德特人基因组测序", significance: "发现非非洲人群携带1-4%尼安德特人DNA，证明两个物种曾杂交" },
    { year: 2017, discovery: "Hublin等人重新测定Jebel Irhoud化石年代", significance: "将智人起源推至约30万年前，比之前认为的早约10万年" },
    { year: 2019, discovery: "张东菊等人在白石崖溶洞发现丹尼索瓦人DNA", significance: "首次在非洲以外通过沉积物DNA确认丹尼索瓦人的存在" },
    { year: 2022, discovery: "Svante Pääbo获诺贝尔生理学或医学奖", significance: "表彰其在古基因组学领域的开创性贡献，古DNA研究获得最高学术认可" },
  ],
  unsolvedMysteries: [
    "人属的确切起源——能人、鲁道夫人和最早直立人之间的关系仍有争议",
    "语言能力的起源时间和机制——化石记录无法直接保存语言",
    "智人是否与丹尼索瓦人和弗洛勒斯人等其他古人类发生过杂交",
    "多巴火山假说——7.4万年前的超级喷发是否导致了人类种群瓶颈",
    "Homo naledi是否真的具有埋葬行为和符号认知——如果证实将改写对认知复杂性的理解",
    "尼安德特人灭绝的确切原因——竞争排斥、气候变化、遗传退化还是认知差异",
  ],
};

export default era;
