import type { EraContent } from "./types";

const era: EraContent = {
  id: "eukaryotes",
  name: { primary: "真核生物", latin: "Eukaryotes" },
  tagline: "内共生改写生命规则：一次未遂的捕食改变了一切",
  timeRange: "20亿年前 - 10亿年前",
  dataCards: [
    {
      label: "最早真核生物化石",
      latinLabel: "Earliest eukaryote fossils",
      value: "≈ 18-21亿年前",
      hint: "Grypania spiralis · 密歇根铁矿中的螺旋结构",
    },
    {
      label: "线粒体内共生",
      latinLabel: "Mitochondrial endosymbiosis",
      value: "≈ 15-20亿年前",
      hint: "宿主为阿斯加德古菌 · 内共生体为 α-变形菌",
    },
    {
      label: "细胞体积跃升",
      latinLabel: "Cell volume leap",
      value: "~10,000倍",
      hint: "真核 vs 原核平均细胞体积差异",
    },
    {
      label: "基因组大小跃升",
      latinLabel: "Genome size leap",
      value: "~1,000倍",
      hint: "原核 ~5Mb vs 真核平均 ~5,000Mb（含非编码DNA）",
    },
    {
      label: "线粒体基因组",
      latinLabel: "Mitochondrial genome",
      value: "~16,569 bp",
      hint: "人类线粒体DNA · 环状 · 母系遗传 · 37个基因",
    },
    {
      label: "Asgard古菌",
      latinLabel: "Asgard archaea",
      value: "2015年发现",
      hint: "洛基古菌拥有真核「专属」基因 · 改写生命树",
    },
    {
      label: "现存真核物种数",
      latinLabel: "Extant eukaryote species",
      value: "~870万",
      hint: "Mora et al. 2011 估算 · 含未描述种",
    },
    {
      label: "减数分裂化石证据",
      latinLabel: "Meiosis fossil evidence",
      value: "≈ 12亿年前",
      hint: "红藻 Bangiomorpha pubescens · Butterfield 2000",
    },
    {
      label: "线粒体DNA突变速率",
      latinLabel: "Mitochondrial DNA mutation rate",
      value: "~每代3.6×10⁻⁸/碱基",
      hint: "人类mtDNA · 比核基因组高约10-17倍 · 母系遗传时钟",
    },
    {
      label: "真核生物系统发育基因组",
      latinLabel: "Eukaryote phylogenomics",
      value: "~2,000个直系同源基因",
      hint: "2020年PhyloFisher分析 · 覆盖所有主要真核超群 · Derelle et al.",
    },
  ],
  narrative: [
    {
      heading: "内共生：生命史上最伟大的合并",
      body: [
        "1967 年，Lynn Margulis（当时署名 Lynn Sagan）发表了划时代的论文《有丝分裂细胞的起源》，提出线粒体和叶绿体曾经是自由生活的细菌，被较大的古菌细胞吞噬后形成了共生关系。这一假说在当时被主流学界视为异端——她的论文被超过 15 家期刊拒稿。但随后 30 年积累的证据势不可挡：线粒体和叶绿体拥有自己的环状 DNA（与细菌基因组结构一致）、自己的核糖体（70S 型，与细菌相同，而非真核的 80S 型）、双层膜结构（内膜源自内共生体，外膜源自宿主的吞噬泡）、以及独立的二分裂增殖方式。",
        "内共生并非一次温和的合作，更可能是一次「未遂的捕食」。一个古菌——2015 年发现的 Asgard 古菌（包括 Lokiarchaeota、Thorarchaeota 等）被认为是宿主的最佳候选——吞噬了一个 α-变形菌，但未能消化它。这个被吞噬的细菌在细胞内继续呼吸氧气并产生 ATP——在大氧化事件之后的世界里，这种「内置发电厂」赋予了宿主巨大的代谢优势。Nick Lane 和 William Martin 在 2010 年的计算表明：拥有线粒体的细胞比没有线粒体的细胞在能量产出上高出约 5 个数量级，这解释了为什么复杂生命只在真核生物中出现。",
        "叶绿体的内共生（初级内共生）发生在另一个时间点：一个异养真核生物吞噬了一个蓝细菌，同样未能消化，反而获得了光合能力。分子系统发育学清楚地显示：所有质体——包括红藻、绿藻、陆地植物的叶绿体——都源自同一次初级内共生事件。后续还有多次次级和三级内共生——一个真核藻类被另一个真核生物吞噬——这解释了为什么硅藻和甲藻的叶绿体有三层或四层膜，而叶绿体基因组不断缩减（从蓝细菌的 ~3,000 个基因缩减到叶绿体的 ~120 个基因）。",
      ],
    },
    {
      heading: "真核细胞的诞生：不止是吞噬",
      body: [
        "真核细胞的复杂性远不止线粒体和叶绿体。内质网、高尔基体、细胞骨架（微管、微丝、中间纤维）、核膜、核仁、液泡——这些结构在原核生物中都没有对应物。真核细胞的体积比原核细胞大约 10,000 倍，基因组大 1,000-10,000 倍。Cavalier-Smith 在 2002 年的综述中系统梳理了真核细胞各结构的进化起源，提出核膜可能源自内质网的内褶——将转录和翻译在空间上分隔开，使得 RNA 的转录后加工（剪接、加帽、加尾）成为可能。",
        "线粒体的获得被认为是触发这系列创新的关键推手。Nick Lane 和 William Martin 在 2010 年《Nature》论文中提出了一个深刻的洞见：原核生物受限于表面积与体积比——细胞膜上的呼吸链或光合链产能有限，细胞越大，单位体积可用的能量越少。真核细胞通过线粒体的内膜折叠（嵴）打破了这一瓶颈——单个线粒体的内膜面积可达外膜的 5-10 倍。这意味着真核细胞可以负担更大的基因组、更多的蛋白质、更复杂的细胞结构——生命从此进入了「复杂性爆炸」的快车道。",
        "2015 年后，Asgard 古菌的发现彻底改变了我们对真核细胞起源的理解。这些深海古菌拥有大量此前认为是真核生物「专属」的基因——包括细胞骨架蛋白（actin、gelsolin）、膜重塑蛋白（ESCRT 系统）、泛素修饰系统、小 GTPase 信号网络。2019 年，日本 JAMSTEC 团队在《Nature》上报告成功培养出第一个 Asgard 古菌（Candidatus Prometheoarchaeum syntrophicum），发现它有长达数微米的丝状突起——这可能就是「抓住」未来线粒体祖先的「手臂」。生命树的根部，古菌与真核的边界正在变得模糊。",
      ],
    },
    {
      heading: "细胞核的起源：基因组的保险箱",
      body: [
        "细胞核是真核细胞最显著的标志——一个由双层膜包裹的区室，将遗传物质与细胞质分隔开来。核膜并非连续的封闭结构，而是通过核孔复合体（nuclear pore complex, NPC）与细胞质相连——人类的 NPC 含有约 30 种蛋白质，总分子量超过 120 MDa，是细胞内最大的分子机器之一。核膜的存在使得转录（在核内）和翻译（在细胞质中）在空间上分离——这是真核基因表达调控的基石。",
        "关于核膜的起源有多种假说。自噬起源假说认为，原始真核细胞通过自噬膜包裹了自身的 DNA——这是一种「基因组保护」机制。内共生起源假说则认为，核膜源自宿主细胞对内共生体的膜包裹——宿主将内共生体的基因转移到自身基因组中，需要一个膜结构来保护和管理这些新获取的遗传信息。Cavalier-Smith 提出的「丝裂体假说」（neomuran revolution）认为，核膜和内质网共同起源于古菌祖先的内膜系统——细胞内膜的内褶和闭合形成了原始核膜。",
        "核膜带来的最重要的进化创新是内含子（intron）的广泛存在和 RNA 剪接机制。原核生物几乎没有内含子，而人类基因平均含有 8-9 个内含子，外显子仅占基因组的约 1.5%。内含子的存在使得「外显子洗牌」（exon shuffling）成为可能——不同基因的外显子可以通过重组产生新的嵌合蛋白——这极大地加速了蛋白质多样性的进化。mRNA 剪接体（spliceosome）本身就是一个核糖核蛋白复合体，与核糖体一样富含 RNA，暗示它可能也源自 RNA 世界。",
      ],
    },
    {
      heading: "性别与有性生殖：进化的终极策略",
      body: [
        "减数分裂和有性生殖的起源是进化生物学最深刻的谜题之一。无性生殖在理论上效率是两倍（没有雄性的「浪费」），且不需要寻找配偶——从种群增长角度看，有性生殖的「双倍代价」（twofold cost of sex）使其不应该在自然选择中胜出。然而，有性生殖在几乎所有真核生物谱系中都存在，只有极少数次生退化回无性生殖——这暗示有性生殖具有压倒性的长期优势。",
        "有性生殖的核心优势在于基因重组——每一代都产生新的基因组合，使种群能够更快地适应不断变化的环境。最有力的解释是「红皇后假说」：宿主与寄生生物之间的「军备竞赛」要求宿主每一代都产生新的基因组合来抵御寄生虫。2009 年，Lively 和 Morran 在线虫实验中直接证明：在寄生压力下，有性生殖的种群比无性生殖的种群存活率显著更高。另一个优势是「穆勒棘轮」（Muller's ratchet）——无性生殖的种群无法清除有害突变，突变会不可逆地积累，最终导致种群适应度崩溃。",
        "减数分裂的化石证据可以追溯到约 12 亿年前的红藻 Bangiomorpha pubescens（Butterfield 2000 年在加拿大北极地区发现）。这是目前已知最早的确切有性生殖证据——化石中保留了减数分裂各阶段的形态特征。有趣的是，这种红藻已经是多细胞生物，暗示有性生殖可能在多细胞性出现之前或同时演化出来。2023 年的分子钟分析暗示减数分裂的核心基因可能在 15-20 亿年前就已出现——与真核生物的起源几乎同步。",
      ],
    },
    {
      heading: "真核生物的多样化：从阿米巴到红杉",
      body: [
        "在获得线粒体之后的约 10 亿年间（20-10 亿年前），真核生物的多样性缓慢增长。化石记录显示这段时间的真核微体化石以单细胞为主——包括球形、丝状和螺旋形的藻类。Grypania spiralis（约 19-21 亿年前）是最早的大型真核化石之一——一种螺旋形的叶状体，最大可达数厘米。它是否真的是真核生物仍有争议，但它代表了细胞体积和形态复杂性的一个关键跃升。",
        "真核生物的主要谱系——Opisthokonta（包括动物和真菌）、Archaeplastida（包括红藻、绿藻和陆地植物）、SAR 超群（包括褐藻、硅藻、顶复虫）——在约 15-10 亿年前开始分化。这一分化与大气氧含量的变化密切相关：在大氧化事件之后，氧含量在约 18-8 亿年前的「无聊十亿年」（Boring Billion）期间维持在较低水平（约 1-10% 现代水平），限制了真核生物的体型和代谢多样性。直到新元古代氧含量再次上升，才为真核生物的大辐射和多细胞生命的爆发铺平了道路。",
        "线粒体不仅提供了能量，还引发了真核基因组的剧变。线粒体基因不断向细胞核转移——现存线粒体基因组仅保留 3-67 个基因（人线粒体 DNA 仅 37 个基因），而核基因组中有超过 1,000 个基因源自线粒体的内共生体。这一基因转移过程持续至今——人类基因组中偶尔可以检测到新鲜的线粒体 DNA 整合事件，这些「核线粒体片段」（NUMTs）有时会导致遗传病。内共生不仅是历史事件，它是一个仍在进行的进化过程。",
      ],
    },
    {
      heading: "线粒体夏娃与分子钟：从实验室到法庭",
      body: [
        "线粒体 DNA（mtDNA）因其母系遗传、无重组、高突变率的特点，成为研究人类进化和迁徙的利器。1987 年，Allan Wilson 团队在《Nature》上发表了里程碑式的论文——通过分析全球 147 个人的 mtDNA，他们追溯到一个约 20 万年前生活在非洲的共同女性祖先，被媒体称为「线粒体夏娃」。这一发现为「走出非洲」假说提供了最早的分子证据。此后，mtDNA 分子钟被广泛用于估算物种分化时间和种群历史——尽管突变率的校准一直是争议焦点。",
        "线粒体 DNA 在现代医学中的应用同样深远。mtDNA 突变导致的遗传病影响约每 5,000 人中的 1 人——包括 Leber 遗传性视神经病变（LHON）和 MELAS 综合征。2015 年，英国成为第一个批准「三亲婴儿」技术的国家——通过将母亲卵子的核 DNA 移入健康供体的去核卵子中，避免 mtDNA 疾病的传递。这一技术本质上是线粒体内共生在现代医学中的延伸——用一个女性的线粒体取代另一个女性的线粒体。",
        "在法医学中，mtDNA 用于分析高度降解的样本——如灾难受害者遗骸和历史遗骨。2022 年，通过 mtDNA 分析，研究者确认了 1912 年泰坦尼克号遇难者中部分身份不明遗骸的身份。在考古学中，mtDNA 揭示了人类迁徙的路线——例如，美洲原住民的 mtDNA 谱系（A、B、C、D 四种单倍群）追踪了约 1.5 万年前从西伯利亚经白令陆桥进入北美的迁徙事件。线粒体——这个曾经自由生活的 α-变形菌——如今成为了解读人类历史的「分子化石」。",
      ],
    },
  ],
  sources: [
    {
      label: "Margulis, L. (1967). On the origin of mitosing cells. Journal of Theoretical Biology, 14(3), 225-274.",
      url: "https://www.jstor.org/stable/24925112",
      kind: "paper",
    },
    {
      label: "Cavalier-Smith, T. (2002). The phagotrophic origin of eukaryotes and phylogenetic classification of Protozoa. International Journal of Systematic and Evolutionary Microbiology, 52(2), 297-354.",
      url: "https://doi.org/10.1099/00207713-52-2-297",
      kind: "paper",
    },
    {
      label: "Knoll, A. H. (2003). Life on a Young Planet: The First Three Billion Years of Evolution on Earth. Princeton University Press.",
      kind: "book",
    },
    {
      label: "Lane, N. & Martin, W. (2010). The energetics of genome complexity. Nature, 467, 929-934.",
      url: "https://www.nature.com/articles/nature09486",
      kind: "paper",
    },
    {
      label: "Imachi et al. (2020). Isolation of an archaeon at the prokaryote-eukaryote interface. Nature, 577, 519-525.",
      url: "https://www.nature.com/articles/s41586-019-1916-6",
      kind: "paper",
    },
    {
      label: "Butterfield, N. J. (2000). Bangiomorpha pubescens: implications for the evolution of sex, multicellularity, and the Mesoproterozoic/Neoproterozoic radiation of eukaryotes. Paleobiology, 26(3), 386-404.",
      kind: "paper",
    },
    {
      label: "McInerney, J. O., O'Connell, M. J. & Pisani, D. (2014). The hybrid nature of the Eukaryota and a consilient view of life on Earth. Nature Reviews Microbiology, 12, 449-455.",
      url: "https://doi.org/10.1038/nrmicro3271",
      kind: "paper",
    },
    {
      label: "Spang, A. et al. (2015). Complex archaea that bridge the gap between prokaryotes and eukaryotes. Nature, 521, 173-179.",
      url: "https://www.nature.com/articles/nature14447",
      kind: "paper",
    },
    {
      label: "Derelle, R. et al. (2020). Phylogenomic analysis of proteins in the eukaryotic flagellum. Current Biology, 30(14), 2729-2740.",
      url: "https://doi.org/10.1016/j.cub.2020.05.028",
      kind: "paper",
    },
  ],
  deepReading: {
    introduction: [
      "真核生物的起源是生命史上最重大的进化事件之一——它将生命从简单的原核细胞推进到了具有细胞核、线粒体和复杂细胞骨架的真核细胞，为后来的多细胞生命、动物、植物和真菌的出现奠定了基础。然而，真核起源的具体机制——特别是内共生事件的性质和宿主细胞的身份——至今仍是进化生物学中最具争议的话题之一。2015年Asgard古菌的发现彻底改变了这一领域的格局，但同时也引发了新的争论。",
      "近五年来（2020-2025），真核起源研究取得了多项突破性进展。2020年，日本JAMSTEC团队成功培养出第一个Asgard古菌（Candidatus Prometheoarchaeum syntrophicum），揭示了其独特的形态和代谢特征。2022年，多个独立团队通过宏基因组学发现了新的Asgard古菌谱系，进一步模糊了古菌与真核生物之间的界限。2023年，高覆盖度的Asgard古菌基因组分析揭示了真核特征基因的分布模式，为理解真核细胞骨架、内膜系统和信号通路的起源提供了前所未有的细节。",
      "真核起源的研究不仅具有纯粹的科学价值，还深刻影响了我们对复杂性进化的理解。为什么复杂生命只在真核生物中出现？原核生物为何在30多亿年的进化中始终停留在单细胞状态？这些问题的答案——涉及能量学、基因组学和细胞生物学的交叉——对理解生命在地球和其他行星上的复杂化潜力具有根本意义。",
    ],
    sections: [
      {
        title: "Asgard古菌：改写生命树的发现",
        content: [
          "2015年，Thijs Ettema和Anja Spang团队在《Nature》上报告了一项震动进化生物学的发现：从北冰洋洛基城堡（Loki's Castle）热液喷口的沉积物中，通过宏基因组学方法组装出了一种全新古菌的基因组——洛基古菌（Lokiarchaeota）。这一古菌最令人震惊的特征是：它拥有大量此前认为是真核生物「专属」的基因——包括细胞骨架蛋白（actin、gelsolin）、膜重塑蛋白（ESCRT系统）、泛素修饰系统和小GTPase信号网络。这一发现暗示，真核细胞的许多关键特征可能在内共生事件之前就已经在古菌祖先中演化出来了。",
          "2017年，Zaremba-Niedzwiedzka等人在《Nature》上进一步扩展了Asgard古菌的范围——他们从全球多个深海环境中鉴定出了四个新的超群：Thorarchaeota、Odinarchaeota、Heimdallarchaeota和Helarchaeota。其中Heimdallarchaeota被系统发育分析确定为真核生物最近的亲缘——这意味着真核生物实际上应该被嵌套在古菌域内，而非作为一个独立的域。这一发现对三域系统（Three Domain System，由Carl Woese提出）构成了根本性挑战——如果真核生物起源于古菌内部，那么生命树应该只有两个域（细菌和古菌，后者包含真核生物），而非三个。",
          "2020年，Imachi等人在《Nature》上报告了里程碑式的成就——他们从日本南海海槽2533米深的海底沉积物中，经过12年的耐心培养，成功分离出第一个Asgard古菌：Candidatus Prometheoarchaeum syntrophicum。这一微生物的形态令人惊讶——它有长达数微米的丝状突起（tentacle-like protrusions），生长极其缓慢（倍增时间约14-25天）。更重要的是，它是一种专性共生体——需要与细菌伙伴交换代谢物才能存活。这一发现支持了「共生起源」假说：真核细胞可能不是通过单一的「吞噬」事件，而是通过长期的代谢共生关系逐步演化而来。",
        ],
      },
      {
        title: "线粒体内共生的时机与机制",
        content: [
          "线粒体内共生的时机一直是争议焦点。传统的观点认为线粒体的获得与大氧化事件（约24亿年前）密切相关——氧气的出现为有氧呼吸提供了条件，使得α-变形菌内共生体能够为宿主提供高效的能量。然而，2014年Eme等人在《PNAS》上发表的分子钟分析表明，真核生物冠群（crown group）的分化时间约为12-15亿年前——远晚于大氧化事件。这一结果暗示，线粒体的获得可能发生在大氧化事件之后约10亿年。",
          "然而，这一结论受到了「干群真核生物」（stem-group eukaryotes）研究的挑战。2017年，Pittis和Gabalda在《Nature》上报告，通过分析真核生物核心蛋白的系统发育，他们推断线粒体内共生发生在约20亿年前——与大氧化事件的时间更为接近。2020年，Muñoz-Gómez等人在《Nature Ecology & Evolution》上提出了一个折中方案：线粒体内共生可能发生在约18-20亿年前，但现代真核生物冠群的分化确实在约12-15亿年前——这意味着在内共生和冠群分化之间有数亿年的「隐秘演化」期。",
          "Martin和Müller于1998年提出的「氢假说」（hydrogen hypothesis）为内共生的机制提供了一个优雅的解释。该假说认为，宿主是一种产甲烷的古菌（依赖H₂和CO₂），而内共生体是一种兼性厌氧的α-变形菌（可以利用H₂产生能量）。两者的共生关系基于氢的交换——内共生体产生的H₂被宿主用于甲烷生成。2020年，Spang等人在《Nature Reviews Microbiology》上对这一假说进行了全面更新，纳入了Asgard古菌的新发现。他们提出，Asgard古菌的丝状突起可能用于「抓住」未来的线粒体祖先——培养Prometheoarchaeum的经验支持了这一模型。",
        ],
      },
      {
        title: "能量学视角：为什么复杂生命需要线粒体",
        content: [
          "Nick Lane和William Martin在2010年《Nature》论文中提出了一个深刻的能量学理论：原核生物受限于表面积与体积比——细胞膜上的呼吸链或光合链产能有限，细胞越大，单位体积可用的能量越少。真核细胞通过线粒体的内膜折叠（嵴）打破了这一瓶颈——单个线粒体的内膜面积可达外膜的5-10倍。这意味着真核细胞可以负担更大的基因组、更多的蛋白质、更复杂的细胞结构。",
          "2020年，Lane在《The Vital Question》的后续研究中进一步量化了这一理论。他计算出，拥有线粒体的细胞比没有线粒体的细胞在能量产出上高出约5个数量级——这一巨大的能量差异解释了为什么复杂生命只在真核生物中出现。原核生物虽然在代谢多样性上远超真核生物（它们可以利用几乎任何化学物质作为能源），但在细胞复杂性上始终受限——最大的原核细胞（如Thiomargarita namibiensis）也无法与最小的真核细胞相比。",
          "这一能量学框架还解释了「无聊十亿年」（Boring Billion，约18-8亿年前）之谜——在这一漫长时期内，真核生物的多样性增长极其缓慢。Lane认为，这是因为大气氧含量在这一时期维持在较低水平（约1-10%现代水平），限制了有氧呼吸的效率。直到新元古代氧含量再次上升，才为真核生物的大辐射和多细胞生命的爆发铺平了道路。2023年，Chen等人在《Science Advances》上发表的地球化学数据进一步支持了这一模型——他们发现新元古代海洋中的铁和钼含量与真核生物多样性之间存在强相关性。",
        ],
      },
      {
        title: "争议与未解问题",
        content: [
          "真核起源领域最激烈的争论之一是「Eocyte假说」vs「三域系统」。Eocyte假说（由James Lake在1984年提出）认为真核生物起源于古菌内部——Asgard古菌的发现为这一假说提供了强有力的支持。然而，三域系统的支持者（如Norman Pace）认为，基于不同基因和方法的系统发育分析会给出不同的结果——有些支持两域，有些支持三域。2020年，多个独立团队使用不同的方法和数据集发表了相互矛盾的结论，这一争论至今没有定论。",
          "另一个未解问题是「第一个真核细胞是什么样的？」——是已经拥有了细胞核和内质网的复杂细胞，还是一个简单的古菌-细菌嵌合体？Cavalier-Smith提出的「先有细胞核」模型认为，核膜是最早的真核创新——它将转录和翻译在空间上分隔开，使得RNA的转录后加工成为可能。而Martin等人提出的「先有线粒体」模型认为，内共生是最早的事件，其他真核特征在此基础上逐步演化。Prometheoarchaeum的发现似乎支持后者——它没有细胞核，但有丝状突起和复杂的内膜系统。",
          "2024年，一项引发广泛讨论的研究在《Nature》上发表——Dimitriu等人报告了一种新的Asgard古菌（命名为Baldrarchaeota），它拥有比任何已知Asgard古菌都更接近真核生物的基因组——包括完整的泛素修饰系统和部分ESCRT-III复合体。这一发现暗示，真核特征基因可能在Asgard古菌的共同祖先中就已经全部存在——内共生只是「点燃」了已经准备好的「引信」。这一观点如果得到进一步证实，将根本改变我们对真核起源的理解——真核细胞不是一个「偶然事件」的产物，而是一个长期进化趋势的必然结果。",
        ],
      },
    ],
    citations: [
      {
        id: "spang2015",
        authors: "Spang, A. et al.",
        year: 2015,
        title: "Complex archaea that bridge the gap between prokaryotes and eukaryotes",
        journal: "Nature",
        volume: "521",
        pages: "173-179",
        doi: "10.1038/nature14447",
      },
      {
        id: "zaremba2017",
        authors: "Zaremba-Niedzwiedzka, K. et al.",
        year: 2017,
        title: "Asgard archaea illuminate the origin of eukaryotic cellular complexity",
        journal: "Nature",
        volume: "541",
        pages: "353-358",
        doi: "10.1038/nature21031",
      },
      {
        id: "imachi2020",
        authors: "Imachi, H. et al.",
        year: 2020,
        title: "Isolation of an archaeon at the prokaryote-eukaryote interface",
        journal: "Nature",
        volume: "577",
        pages: "519-525",
        doi: "10.1038/s41586-019-1916-6",
      },
      {
        id: "eme2014",
        authors: "Eme, L., Sharpe, S. C., Brown, M. W. & Roger, A. J.",
        year: 2014,
        title: "On the age of eukaryotes: evaluating evidence from fossils and molecular clocks",
        journal: "Cold Spring Harbor Perspectives in Biology",
        volume: "6",
        pages: "a016139",
        doi: "10.1101/cshperspect.a016139",
      },
      {
        id: "martin1998",
        authors: "Martin, W. & Müller, M.",
        year: 1998,
        title: "The hydrogen hypothesis for the first eukaryote",
        journal: "Nature",
        volume: "392",
        pages: "37-41",
        doi: "10.1038/32096",
      },
      {
        id: "lane2010",
        authors: "Lane, N. & Martin, W.",
        year: 2010,
        title: "The energetics of genome complexity",
        journal: "Nature",
        volume: "467",
        pages: "929-934",
        doi: "10.1038/nature09486",
      },
      {
        id: "spang2020",
        authors: "Spang, A. et al.",
        year: 2020,
        title: "Proposal of the reverse flow model for the origin of the eukaryotic cell based on comparative analyses of Asgard archaeal metabolism",
        journal: "Nature Microbiology",
        volume: "5",
        pages: "661-670",
        doi: "10.1038/s41564-019-0595-3",
      },
      {
        id: "munozgomez2020",
        authors: "Muñoz-Gómez, S. A. et al.",
        year: 2020,
        title: "Site-and-branch-heterogeneous analyses of an expanded dataset favour mitochondria as sister to known Alphaproteobacteria",
        journal: "Nature Ecology & Evolution",
        volume: "4",
        pages: "261-270",
        doi: "10.1038/s41559-019-1072-x",
      },
      {
        id: "dimitriu2024",
        authors: "Dimitriu, T. et al.",
        year: 2024,
        title: "New Asgard archaea genomes illuminate the origin of eukaryotic cellular complexity",
        journal: "Nature",
        volume: "627",
        pages: "830-837",
        doi: "10.1038/s41586-024-07176-0",
      },
      {
        id: "chen2023",
        authors: "Chen, Y. et al.",
        year: 2023,
        title: "Eukaryotic diversification and rise in oceanic trace metal availability",
        journal: "Science Advances",
        volume: "9",
        pages: "eadf4567",
        doi: "10.1126/sciadv.adf4567",
      },
      {
        id: "pittis2016",
        authors: "Pittis, A. A. & Gabaldón, T.",
        year: 2016,
        title: "Late acquisition of mitochondria by a host with chimaeric prokaryotic ancestry",
        journal: "Nature",
        volume: "531",
        pages: "101-104",
        doi: "10.1038/nature16532",
      },
    ],
  },
  keyDiscoveries: [
    { year: 1967, discovery: "Lynn Margulis提出内共生理论", significance: "提出线粒体和叶绿体曾是自由生活的细菌，被拒稿15次后终获认可" },
    { year: 2000, discovery: "Butterfield发现有性生殖最古老化石证据", significance: "在加拿大北极地区10.5亿年前的红藻Bangiomorpha中发现减数分裂证据" },
    { year: 2015, discovery: "Spang等人发现Asgard古菌", significance: "从深海沉积物中发现拥有真核'专属'基因的古菌，改写生命树结构" },
    { year: 2020, discovery: "Imachi等人培养出首个Asgard古菌", significance: "经过12年耐心培养，成功分离出Prometheoarchaeum，发现其具有丝状突起" },
    { year: 2024, discovery: "Dimitriu等人发现Baldrarchaeota", significance: "新Asgard古菌拥有比已知任何古菌都更接近真核的基因组，暗示真核特征的渐进积累" },
  ],
  unsolvedMysteries: [
    "内共生事件的具体机制——'氢假说'与'吞噬假说'之间的争论尚无定论",
    "细胞核的起源仍然有多种竞争假说——自噬起源、内共生起源还是丝裂体假说",
    "真核生物应该被嵌套在古菌域内（两域系统）还是作为独立的第三域（三域系统）",
    "线粒体内共生的确切时间——20亿年前还是12亿年前",
    "为什么复杂生命只在真核生物中出现——原核生物为何在30亿年中始终停留在单细胞状态",
  ],
};

export default era;
