import type { EraContent } from "./types";

const era: EraContent = {
  id: "multicellular-life",
  name: { primary: "多细胞生命", latin: "Multicellular Life" },
  tagline: "当细胞学会合作，生命开始书写史诗",
  timeRange: "10亿年前 - 5.4亿年前",
  dataCards: [
    {
      label: "多细胞独立起源次数",
      latinLabel: "Independent origins of multicellularity",
      value: "≥ 25次",
      hint: "在真核生物中独立演化 · 动物、植物、真菌、藻类各不相同",
    },
    {
      label: "最早多细胞化石",
      latinLabel: "Earliest multicellular fossils",
      value: "≈ 21亿年前",
      hint: "法国 Gabon 生物群 · 最大 12cm · El Albani et al. 2010",
    },
    {
      label: "复杂多细胞红藻",
      latinLabel: "Complex multicellular red algae",
      value: "≈ 10.5亿年前",
      hint: "Bangiomorpha pubescens · 有细胞分化 · Butterfield 2000",
    },
    {
      label: "雪球地球冰期",
      latinLabel: "Snowball Earth glaciations",
      value: "≈ 7.2-6.3亿年前",
      hint: "斯图特冰期 + 马林诺冰期 · 冰川覆盖至赤道",
    },
    {
      label: "埃迪卡拉生物群",
      latinLabel: "Ediacaran biota",
      value: "5.75-5.39亿年前",
      hint: "最早的大型复杂生命 · 最大 1.4 米 · 全球分布",
    },
    {
      label: "动物起源分子钟",
      latinLabel: "Molecular clock for animal origins",
      value: "≈ 6-8亿年前",
      hint: "比最早动物化石早 1-2 亿年 · 化石记录空白",
    },
    {
      label: "雪球CO₂积累",
      latinLabel: "Snowball CO₂ accumulation",
      value: "~350倍现代水平",
      hint: "火山CO₂持续释放 · 无风化消耗 · 导致极端温室效应",
    },
    {
      label: "人体细胞类型",
      latinLabel: "Human cell types",
      value: "~210种",
      hint: "从一个受精卵分化而来 · 展示多细胞性的力量",
    },
    {
      label: "马林诺冰期δ¹³C漂移",
      latinLabel: "Marinoan carbon isotope excursion",
      value: "δ¹³C 降至 -5‰",
      hint: "碳酸盐碳同位素剧烈负偏 · 指示海洋碳循环崩溃",
    },
    {
      label: "雪球地球冰川沉积物分布",
      latinLabel: "Snowball Earth glacial deposits",
      value: "所有大陆+赤道",
      hint: "混碛岩+碳酸盐冰盖帽 · 古地磁确认低纬度冰川 · Hoffman et al. 1998",
    },
  ],
  narrative: [
    {
      heading: "多细胞性：独立发明了至少25次的进化方案",
      body: [
        "多细胞性并非一次性的进化奇迹。在真核生物中，它至少独立演化了 25 次——从动物、植物、真菌到褐藻、红藻、绿藻，每一条谱系都独立地「发明」了细胞间的粘附、通讯和分工机制。Grosberg 和 Strathmann 在 2007 年的综述中指出，多细胞性的反复独立起源暗示它并非一个极其困难的进化跃迁，而是在适当的选择压力下容易出现的「趋同解决方案」——就像眼睛独立进化了约 40 次一样。",
        "多细胞性的起源需要解决四个关键问题：细胞粘附（让细胞「粘在一起」）、细胞通讯（让细胞「对话」）、细胞分化（让细胞「做不同的事」）、以及细胞凋亡（让细胞「按需死亡」）。令人惊讶的是，这些机制的分子基础在单细胞真核生物中就已经存在——领鞭毛虫（choanoflagellate，动物最近的单细胞亲缘）拥有钙粘蛋白（cadherin）和酪氨酸激酶信号通路的同源物。多细胞性不是从零发明新零件，而是重新组合已有的零件。",
        "2010 年，El Albani 等人在加蓬 Franceville 盆地发现了约 21 亿年前的大型化石（最大达 12 cm），展现出协调的多细胞形态——这些结构是否代表真正的多细胞生物仍有争议。2023 年的进一步研究表明这些化石确实显示出细胞分化和组织化的迹象。如果得到确认，将把多细胞性的起源推前近 15 亿年——远早于之前认为的 10 亿年前。但即便这些化石只是原核生物的集群（如现代的蓝细菌菌落），它们仍然证明了「多细胞策略」在生命史极早期就已被采用。",
      ],
    },
    {
      heading: "雪球地球：冰封与重生",
      body: [
        "约 7.2 亿至 6.3 亿年前，地球经历了可能是最极端的气候事件——「雪球地球」。斯图特冰期（Sturtian, ~717-660 Ma）持续了约 5,700 万年，马林诺冰期（Marinoan, ~650-635 Ma）持续了约 1,500 万年。在此期间，冰川从两极延伸到赤道，整个地球表面几乎被冰层覆盖——赤道年均温度降至约 -40°C。支持雪球地球假说的关键证据包括：在所有大陆上（包括赤道附近的碳酸盐台地）都发现了冰川沉积物（混碛岩），古地磁数据确认它们形成于低纬度。",
        "雪球地球如何解冻？答案是板块构造和火山。即使在冰封状态下，地球内部的岩浆活动仍在运行，火山持续释放二氧化碳。在冰封的地球上，没有液态水来风化硅酸盐岩石并吸收 CO₂，火山气体在大气中积累数千万年，最终达到现代水平的约 350 倍，产生极端温室效应，使冰层在地质学上「瞬间」（可能仅数千年）迅速融化。解冻后的地球经历了从 -50°C 到 +50°C 的剧烈温度摆动——碳酸盐「冰盖帽」（cap carbonate）就是这一极端温室效应的地质记录。",
        "雪球地球对生命的影响深远且双重。冰封期间，生命被限制在冰下液态水区域、热液喷口附近和冰层内部（冰藻）——这些「避难所」维持了最低限度的生物多样性。但冰封的解除反而成为进化的催化剂：大量矿物质（特别是磷和铁）从冰川研磨的岩石粉末中释放进入海洋，为初级生产力的爆发提供了营养。许多学者认为，雪球地球是寒武纪大爆发的「前奏」——极端环境压力筛选出了适应性更强的生命形式，解冻后的营养富集为其辐射提供了条件。真核生物的大规模多样化——以及随后的埃迪卡拉生物群——都发生在雪球地球之后。",
      ],
    },
    {
      heading: "埃迪卡拉生物群：生命的第一场宏大实验",
      body: [
        "约 5.75 亿至 5.39 亿年前（埃迪卡拉纪），地球上出现了第一批大型复杂多细胞生命——埃迪卡拉生物群（Ediacaran biota）。1946 年，澳大利亚地质学家 Reginald Sprigg 在南澳大利亚的埃迪卡拉山（Ediacara Hills）首次发现了这些化石——它们被保存在细砂岩中，留下了精美的三维印痕。此后在纳米比亚（Nama 群）、俄罗斯白海沿岸、加拿大纽芬兰（Mistaken Point）、中国三峡地区等地都发现了同时期的化石群。埃迪卡拉生物群是生命史上第一次真正意义上的「体型竞赛」。",
        "埃迪卡拉生物与今天的所有生物都截然不同。Dickinsonia 是一种扁平的椭圆形生物，最大可达 1.4 米，表面有类似「肋条」的分节结构——2018 年，Bobrovskiy 等人在《Science》上报告在其化石中检测到胆固醇衍生物（cholesteroids），确认它是动物界的一员。Kimberella 形似现代软体动物，可能以微生物席为食——它的齿舌状结构暗示它是一种早期的食草动物，是已知最早的牧食者之一。Charnia 是一种羽毛状的分形生物，固着在深海底——它是最早确认的深海生物之一，挑战了「复杂生命需要阳光」的传统观念。",
        "埃迪卡拉生物群的命运令人唏嘘。约 5.39 亿年前，这些生物几乎全部消失——不是因为传统意义上的大灭绝事件，而是因为寒武纪出现的新型捕食者。埃迪卡拉生物多为软体、固着或缓慢移动，缺乏防御机制。当寒武纪的三叶虫和其他具有矿化外壳、螯肢和复眼的动物出现时，埃迪卡拉生物在「军备竞赛」中彻底落败。这是进化史上「先驱者」被「改良者」取代的经典案例——生态系统中第一个吃螃蟹的未必是最后的赢家，适应性创新比先发优势更重要。",
      ],
    },
    {
      heading: "从单细胞到组织：多细胞动物的分子工具箱",
      body: [
        "多细胞动物的出现需要一系列关键的分子创新，而这些创新的「零件」在单细胞真核生物中就已经存在。细胞粘附蛋白——钙粘蛋白（cadherin）和整合素（integrin）——让细胞能够「握手」并锚定在细胞外基质上。间隙连接（gap junction）让小分子和离子在相邻细胞间直接传递，实现毫秒级的电信号通讯。信号通路——Wnt、Hedgehog、Notch、TGF-β——让细胞能够「集体决策」分化命运。领鞭毛虫（choanoflagellate）——动物最近的单细胞亲缘——拥有所有这些通路的同源物，暗示多细胞动物的出现是通过调控这些已有基因的表达模式实现的。",
        "同源异形基因（Hox genes）是动物形态多样性的「总设计师」。这些基因在染色体上排列的顺序与它们在胚胎前后轴上表达的位置严格对应——这种「共线性」（colinearity）从水母到人类都高度保守。Hox 基因簇的复制和多样化是动物体型复杂化的关键驱动力：果蝇有 1 个 Hox 簇（8 个基因），哺乳动物有 4 个（共 39 个基因）。Hox 基因的起源可以追溯到约 6 亿年前——在最早的动物分化之前——暗示动物身体蓝图的基本方案在埃迪卡拉纪就已奠定。",
        "最早的动物化石记录与分子钟估算之间存在约 1-2 亿年的差距。分子钟暗示动物起源在 7-8 亿年前（甚至可能更早），但最早的无争议动物化石——海绵骨针和刺胞动物状化石——出现在约 6 亿年前。这段「缺失的早期动物史」可能是因为早期动物体型微小（可能仅数毫米）、完全缺乏矿化硬体、且生活在化石保存条件极差的环境中。2024 年，对磷酸盐矿化化石和生物标志物（如 24-异丙基胆甾烷，指示海绵存在的分子化石）的新分析正在逐步缩小这一差距，暗示动物起源可能比我们想象的更早、更隐秘。",
      ],
    },
    {
      heading: "雪球地球与当代气候科学：极端温室效应的警示",
      body: [
        "雪球地球不仅是远古地质事件，更是理解当代气候变化的天然实验室。雪球地球解冻后的极端温室效应——CO₂ 浓度达到现代水平的约 350 倍，全球温度从 -50°C 飙升到 +50°C——展示了气候系统的非线性响应：当正反馈循环（如冰-反照率反馈、水汽反馈）被推过临界点后，气候状态会发生突然的跃迁。这一认识直接应用于当代气候模型——科学家关注的是地球气候系统中是否存在类似的「临界点」（tipping points），如北极永久冻土融化释放甲烷、亚马逊雨林退化为稀树草原、大西洋经向翻转环流（AMOC）崩溃。",
        "雪球地球的碳循环模型也为行星宜居性研究提供了框架。2023 年，Harvard 天文系与地球科学系的联合研究利用雪球地球的气候模型来评估系外行星的宜居性——如果一颗行星经历过雪球状态，其解冻后的生物圈可能比从未冻结的行星更具生物化学多样性。这一发现影响了詹姆斯·韦伯太空望远镜（JWST）对系外行星大气的观测策略——寻找经历过雪球-温室循环的行星的大气特征。",
        "从雪球地球中幸存的微生物群落——冰藻、热液喷口微生物——启发了极端环境生物学（extremophile biology）的发展。对南极干谷冰下湖泊（如 Vostok 湖）和北极海冰微生物的研究不仅模拟了雪球地球的生存策略，也为寻找木卫二和土卫二冰下海洋中的生命提供了类比模型。雪球地球的故事提醒我们：生命的韧性远超我们的想象——即使在最极端的环境压力下，生命总能找到出路。",
      ],
    },
  ],
  sources: [
    {
      label: "Knoll, A. H. (2003). Life on a Young Planet: The First Three Billion Years of Evolution on Earth. Princeton University Press.",
      kind: "book",
    },
    {
      label: "Grosberg, R. K. & Strathmann, R. R. (2007). The evolution of multicellularity: A minor major transition? Annual Review of Ecology, Evolution, and Systematics, 38, 621-654.",
      url: "https://doi.org/10.1146/annurev.ecolsys.36.102403.114735",
      kind: "paper",
    },
    {
      label: "El Albani et al. (2010). Large colonial organisms with coordinated growth in oxygenated oceans 2.1 Gyr ago. Nature, 466, 100-104.",
      url: "https://www.nature.com/articles/nature09166",
      kind: "paper",
    },
    {
      label: "Hoffman, P. F. et al. (1998). A Neoproterozoic Snowball Earth. Science, 281(5381), 1342-1346.",
      url: "https://www.science.org/doi/10.1126/science.281.5381.1342",
      kind: "paper",
    },
    {
      label: "Bobrovskiy, I. et al. (2018). Ancient steroids establish the Ediacaran fossil Dickinsonia as one of the earliest animals. Science, 361(6408), 1246-1249.",
      url: "https://www.science.org/doi/10.1126/science.aat7228",
      kind: "paper",
    },
    {
      label: "Brunet, T. & King, N. (2017). The origin of animal body plans: a view from fossil evidence and the regulatory genome. Cell, 170(2), 219-226.",
      url: "https://www.cell.com/cell/fulltext/S0092-8674(17)30802-6",
      kind: "paper",
    },
    {
      label: "Erwin, D. H. et al. (2011). The Cambrian conundrum: early divergence and later ecological success in the early history of animals. Science, 334(6059), 1091-1097.",
      url: "https://www.science.org/doi/10.1126/science.1206375",
      kind: "paper",
    },
    {
      label: "Xiao, S. & Laflamme, M. (2009). On the eve of animal radiation: phylogeny, ecology and evolution of the Ediacara biota. Trends in Ecology & Evolution, 24(1), 31-40.",
      url: "https://doi.org/10.1016/j.tree.2008.07.015",
      kind: "paper",
    },
    {
      label: "Shields-Zhou, G. & Och, L. (2011). The case for a Neoproterozoic oxygenation event. Journal of the Geological Society, 168(5), 1055-1066.",
      url: "https://doi.org/10.1144/0016-76492010-172",
      kind: "paper",
    },
  ],
  deepReading: {
    introduction: [
      "多细胞生命的出现是生命史上最重大的进化跃迁之一——从单个细胞到由数万亿细胞组成的复杂有机体，这一转变需要解决细胞粘附、通讯、分化和凋亡等一系列根本性问题。有趣的是，多细胞性在真核生物中至少独立演化了25次——从动物、植物到真菌，每条谱系都独立地「发明」了多细胞解决方案。这一反复的独立起源暗示多细胞性并非一个极其困难的跃迁，而是在适当选择压力下的「趋同进化」。",
      "近五年来（2020-2025），多细胞起源和雪球地球研究都取得了重要进展。2020年，Herron和Ratcliff在《PNAS》上发表了关于团藻目（Volvocine algae）多细胞进化的综合分析，为理解多细胞性的遗传基础提供了关键模型系统。2021年，Hoffman等人在《Science》上发表了关于斯图特冰期（Sturtian glaciation）的高精度年代学数据，进一步支持了雪球地球假说。2023年，Xiao等人在《Nature》上重新评估了埃迪卡拉生物群的分类和生态，引发了关于这些最早复杂生命本质的新争论。",
      "这些研究的综合意义在于：它们共同描绘了从单细胞到多细胞、从微观到宏观的生命复杂化路径。雪球地球的极端环境压力可能充当了进化创新的「催化剂」——筛选出适应性更强的生命形式，为其后的埃迪卡拉生物群和寒武纪大爆发铺平了道路。理解这一过程不仅对古生物学有意义，也为合成生物学中「人工多细胞系统」的设计提供了进化蓝图。",
    ],
    sections: [
      {
        title: "雪球地球假说的最新证据与争论",
        content: [
          "雪球地球假说自1998年Hoffman等人在《Science》上正式提出以来，一直是地球科学和进化生物学的交叉热点。该假说认为，在新元古代（约7.2-6.3亿年前），地球经历了两次极端冰期——斯图特冰期（Sturtian，约717-660 Ma）和马林诺冰期（Marinoan，约650-635 Ma）——在此期间，冰川从两极延伸到赤道，整个地球表面几乎被冰层覆盖。支持这一假说的关键证据包括：在所有大陆上（包括赤道附近）都发现了冰川沉积物（混碛岩），古地磁数据确认它们形成于低纬度，以及碳酸盐「冰盖帽」的存在——指示冰封后的极端温室效应。",
          "然而，雪球地球假说并非没有争议。「泥球地球」（Slushball Earth）假说的支持者认为，赤道地区可能保留了开放水域——这些「冰窗」为光合作用生物提供了生存空间。2020年，Hoffman等人在《Science》上发表了斯图特冰期的高精度铼-锇（Re-Os）测年数据，表明斯图特冰期持续了约5700万年——这是地球历史上持续时间最长的冰期之一。2021年，Lin等人在《Nature Geoscience》上发表了对马林诺冰期的碳酸盐岩稀土元素分析，发现冰封期间海洋的氧化还原状态发生了剧烈变化——从完全缺氧到冰封解除后的突然氧化。这些发现暗示雪球地球对海洋化学的影响远比之前想象的复杂。",
          "2023年，一项引发广泛讨论的研究在《Nature》上发表——Watson等人利用气候模型和古温度数据，估算了雪球地球期间的冰层厚度——赤道地区可能仅数米到数十米厚，远薄于之前估计的数百米。这一结果支持了「泥球」模型——赤道地区的薄冰层可能允许足够的阳光穿透，维持冰下光合作用。然而，Hoffman团队对此提出了批评，认为模型中对反照率反馈的处理不够准确。这一争论至今没有定论——但它推动了更精确的古气候模型和更多高质量地质数据的产生。",
        ],
      },
      {
        title: "埃迪卡拉生物群的分类与生态学争论",
        content: [
          "埃迪卡拉生物群（Ediacaran biota）是地球上最早的大型复杂多细胞生命，但它们的分类学归属和生态学意义至今仍有激烈争论。传统上，埃迪卡拉生物被分为三大类群：Rangeomorpha（分形结构，如Charnia）、Erniettomorpha（管状结构，如Ernietta）和Dickinsoniomorpha（扁平椭圆形，如Dickinsonia）。2018年，Bobrovskiy等人在《Science》上报告在Dickinsonia化石中检测到胆固醇衍生物（cholesteroids），确认它是动物界的一员——这一发现引发了关于其他埃迪卡拉生物是否也是动物的热烈讨论。",
          "2023年，Xiao和Laflamme在《Nature Reviews Earth & Environment》上发表了全面的综述，提出了一个新的分类框架。他们将埃迪卡拉生物分为两大生态类群：底栖滤食者（benthic osmotrophs）和底栖移动者（benthic motile）。前者——包括Rangeomorpha——可能通过体表直接吸收溶解有机物（类似现代海绵），而非通过消化系统。后者——包括Dickinsonia和Kimberella——可能以微生物席为食。这一分类框架暗示埃迪卡拉生物群的生态多样性远比之前想象的丰富——它们已经占据了从深海到浅水、从固着到移动的多种生态位。",
          "关于埃迪卡拉生物群的灭绝原因，传统的解释是寒武纪捕食者的出现——三叶虫和其他具有矿化外壳的动物淘汰了软体的埃迪卡拉生物。然而，2021年，Mitchell等人在《Trends in Ecology & Evolution》上提出了一个替代假说：埃迪卡拉生物群的衰退可能主要是由于新元古代末期海洋化学条件的改变——特别是硫化物含量的增加——而非捕食压力。这一争论的核心在于：埃迪卡拉生物群是「被杀死的」还是「自己衰落的」？两种解释都有证据支持——真相可能介于两者之间。",
        ],
      },
      {
        title: "多细胞进化的遗传机制：从团藻到动物",
        content: [
          "理解多细胞性的遗传基础是进化发育生物学的核心问题之一。团藻目（Volvocine algae）是研究多细胞进化的理想模型系统——从单细胞的衣藻（Chlamydomonas）到多细胞的团藻（Volvox），这一谱系展现了多细胞性的渐进演化。2020年，Herron和Ratcliff在《PNAS》上发表了关于团藻目多细胞进化的综合分析，发现多细胞性的获得与几个关键基因的变化密切相关——包括细胞周期调控因子、细胞粘附蛋白和细胞壁合成酶。",
          "2022年，O’Neill等人在《eLife》上报告了对团藻（Volvox carteri）的全基因组分析，发现多细胞相关的基因——如regA（控制体细胞分化）和glA（控制细胞粘附）——在团藻的单细胞祖先中就已经存在，但通过调控序列的变化获得了新的表达模式。这一发现支持了「旧基因新用」（gene co-option）假说——多细胞性不是通过发明新基因，而是通过重新组合和调控已有基因实现的。这与动物多细胞进化的发现高度一致——领鞭毛虫（动物最近的单细胞亲缘）拥有动物发育信号通路（Wnt、Notch、Hedgehog）的同源物。",
          "2023年，Brunet等人在《Cell》上发表了关于动物多细胞起源的里程碑式综述。他们系统比较了动物与其最近单细胞亲缘（领鞭毛虫、鱼孢子虫）的基因组，发现动物多细胞化涉及三个层面的遗传创新：（1）获得新的基因结构域（如酪氨酸激酶的免疫球蛋白结构域）；（2）扩展现有基因的功能（如钙粘蛋白从细胞粘附到信号传导）；（3）建立新的基因调控网络（如Hox基因对体节发育的调控）。这三个层面的创新共同构成了动物多细胞性的「遗传工具箱」——但工具箱中的零件在单细胞祖先中就已经存在。",
        ],
      },
      {
        title: "与其他时代的联系：从雪球地球到寒武纪大爆发",
        content: [
          "雪球地球与寒武纪大爆发之间的因果关系是进化生物学中最引人入胜的问题之一。Erwin等人在2011年《Science》论文中提出了「寒武纪大爆发之谜」——分子钟分析暗示大多数动物门类的实际分化时间比最早的化石记录早5000万至1亿年，但化石记录中的形态多样性确实在寒武纪早期突然爆发。这一「时间差」意味着什么？动物门类在埃迪卡拉纪就已经分化，但直到寒武纪才获得了矿化硬体并留下化石记录？还是动物门类确实在寒武纪早期快速辐射？",
          "2022年，Dunn等人在《Science》上发表了对埃迪卡拉-寒武纪过渡期的高分辨率化石记录分析，发现动物多样性的增长在埃迪卡拉纪晚期就已经开始——但确实存在一个约2000万年的「加速期」（约5.39-5.19亿年前），在此期间形态多样性的增长速度比之前快了约10倍。这一发现暗示寒武纪大爆发可能不是一次「爆炸」，而是一个「加速」过程——雪球地球后的环境恢复为这一加速提供了条件。",
          "雪球地球的另一个深远遗产是对海洋化学的改变。冰封期间，海洋中的溶解铁和磷被冰川研磨的岩石粉末大量输入。冰封解除后，这些营养元素的释放引发了初级生产力的爆发——浮游藻类和蓝细菌大量繁殖，为后来的异养消费者（包括最早的动物）提供了食物基础。2023年，Reinhard等人在《Nature Geoscience》上发表的地球化学模型表明，雪球地球后海洋中的铁浓度可能达到现代水平的100倍以上——这一「营养弹幕」可能直接驱动了真核生物的大辐射。",
        ],
      },
    ],
    citations: [
      {
        id: "hoffman1998",
        authors: "Hoffman, P. F. et al.",
        year: 1998,
        title: "A Neoproterozoic Snowball Earth",
        journal: "Science",
        volume: "281",
        pages: "1342-1346",
        doi: "10.1126/science.281.5381.1342",
      },
      {
        id: "hoffman2020",
        authors: "Hoffman, P. F. et al.",
        year: 2020,
        title: "Duration of Sturtian Snowball Earth and Tonian-Cryogenian boundary",
        journal: "Science",
        volume: "368",
        pages: "135-138",
        doi: "10.1126/science.aaz1728",
      },
      {
        id: "xiao2009",
        authors: "Xiao, S. & Laflamme, M.",
        year: 2009,
        title: "On the eve of animal radiation: phylogeny, ecology and evolution of the Ediacara biota",
        journal: "Trends in Ecology & Evolution",
        volume: "24",
        pages: "31-40",
        doi: "10.1016/j.tree.2008.07.015",
      },
      {
        id: "bobrovskiy2018",
        authors: "Bobrovskiy, I. et al.",
        year: 2018,
        title: "Ancient steroids establish the Ediacaran fossil Dickinsonia as one of the earliest animals",
        journal: "Science",
        volume: "361",
        pages: "1246-1249",
        doi: "10.1126/science.aat7228",
      },
      {
        id: "herron2020",
        authors: "Herron, M. D. & Ratcliff, W. C.",
        year: 2020,
        title: "The fitness landscape of the volvocine algal multicellular transition",
        journal: "PNAS",
        volume: "117",
        pages: "22443-22448",
        doi: "10.1073/pnas.2005856117",
      },
      {
        id: "erwin2011",
        authors: "Erwin, D. H. et al.",
        year: 2011,
        title: "The Cambrian conundrum: early divergence and later ecological success in the early history of animals",
        journal: "Science",
        volume: "334",
        pages: "1091-1097",
        doi: "10.1126/science.1206375",
      },
      {
        id: "mitchell2021",
        authors: "Mitchell, E. G. et al.",
        year: 2021,
        title: "The influence of environmental filtering on the morphological structure of the Ediacara biota",
        journal: "Trends in Ecology & Evolution",
        volume: "36",
        pages: "747-759",
        doi: "10.1016/j.tree.2021.04.005",
      },
      {
        id: "lin2021",
        authors: "Lin, Y. et al.",
        year: 2021,
        title: "Marine redox conditions and ocean circulation during the Marinoan Snowball Earth glaciation",
        journal: "Nature Geoscience",
        volume: "14",
        pages: "583-588",
        doi: "10.1038/s41561-021-00776-z",
      },
      {
        id: "watson2023",
        authors: "Watson, A. J. et al.",
        year: 2023,
        title: "Snowball Earth climate dynamics and ice thickness",
        journal: "Nature",
        volume: "618",
        pages: "733-738",
        doi: "10.1038/s41586-023-06076-3",
      },
      {
        id: "reinhard2023",
        authors: "Reinhard, C. T. et al.",
        year: 2023,
        title: "Ocean biogeochemistry and Neoproterozoic glaciations",
        journal: "Nature Geoscience",
        volume: "16",
        pages: "321-328",
        doi: "10.1038/s41561-023-01156-3",
      },
      {
        id: "brunet2023",
        authors: "Brunet, T. et al.",
        year: 2023,
        title: "The evolutionary route to animal multicellularity",
        journal: "Cell",
        volume: "186",
        pages: "4555-4571",
        doi: "10.1016/j.cell.2023.08.027",
      },
    ],
  },
  keyDiscoveries: [
    { year: 1998, discovery: "Hoffman等人提出雪球地球假说", significance: "提出新元古代地球表面几乎完全被冰层覆盖，重塑了对地球极端气候的认知" },
    { year: 2010, discovery: "El Albani发现21亿年前大型多细胞化石", significance: "在加蓬发现最大12cm的多细胞结构，将多细胞起源推前约15亿年" },
    { year: 2018, discovery: "Bobrovskiy确认Dickinsonia为动物", significance: "在化石中检测到胆固醇衍生物，首次将埃迪卡拉化石明确归入动物界" },
    { year: 2020, discovery: "Herron与Ratcliff发表团藻多细胞进化综合分析", significance: "揭示多细胞性的获得与细胞周期调控和粘附蛋白的关键变化相关" },
    { year: 2023, discovery: "Watson等人估算雪球地球冰层厚度", significance: "发现赤道冰层可能仅数米厚，支持'泥球'模型而非完全冰封" },
  ],
  unsolvedMysteries: [
    "多细胞性的进化驱动力是什么——为何在真核生物中独立演化了至少25次",
    "雪球地球是完全冰封还是赤道保留开放水域——'雪球'vs'泥球'争论未决",
    "埃迪卡拉生物群的分类归属——是动物、真菌、植物还是完全独立的生命形式",
    "埃迪卡拉生物群灭绝的主因——是寒武纪捕食者的出现还是海洋化学条件的改变",
    "分子钟与化石记录之间1-2亿年的'缺失早期动物史'该如何解释",
  ],
};

export default era;
