import type { TimelineEvent } from "./types";

export const TIMELINE_EVENTS: TimelineEvent[] = [
  {
    id: "earth-formation",
    time: "45.4亿年前",
    title: "地球形成",
    description: "太阳星云中的尘埃和气体通过吸积形成地球，早期经历剧烈的陨石轰炸和熔融状态。",
    era: "pre-life",
    significance: "major",
  },
  {
    id: "moon-formation",
    time: "45亿年前",
    title: "月球形成",
    description: "一颗火星大小的天体（忒伊亚）撞击原始地球，碎片形成月球。潮汐力稳定了地球自转轴。",
    era: "pre-life",
    significance: "moderate",
  },
  {
    id: "ocean-formation",
    time: "44亿年前",
    title: "海洋形成",
    description: "地球冷却至液态水可以稳定存在，最早的海洋出现。为生命起源提供了液态水环境。",
    era: "pre-life",
    significance: "major",
  },
  {
    id: "earliest-life",
    time: "41亿年前",
    title: "最早生命痕迹",
    description: "澳大利亚锆石中发现碳-12富集，可能是地球上最早的生命化学痕迹。",
    era: "origin-of-life",
    significance: "major",
  },
  {
    id: "luca",
    time: "38-42亿年前",
    title: "LUCA（最后共同祖先）",
    description: "所有现存生命的最后共同祖先，拥有355个基因，生活在热液喷口环境中。",
    era: "origin-of-life",
    significance: "major",
  },
  {
    id: "apex-chert-fossils",
    time: "35亿年前",
    title: "最古老化石",
    description: "澳大利亚 Apex 燧石中的丝状微化石，是目前已知最古老的确切生物化石。",
    era: "origin-of-life",
    significance: "moderate",
  },
  {
    id: "anoxygenic-photosynthesis",
    time: "≈35亿年前",
    title: "不产氧光合作用出现",
    description: "最早的光合微生物利用硫化氢等作为电子供体捕获太阳能，为产氧光合作用奠定基础。",
    era: "origin-of-life",
    significance: "major",
  },
  {
    id: "cyanobacteria",
    time: "27亿年前",
    title: "蓝细菌出现",
    description: "最早的产氧光合作用生物出现，利用水分子作为电子供体释放氧气。",
    era: "origin-of-life",
    significance: "major",
  },
  {
    id: "great-oxidation",
    time: "24亿年前",
    title: "大氧化事件",
    description: "大气氧含量显著上升，导致厌氧微生物大规模灭绝，是地球第一次大灭绝事件。",
    era: "origin-of-life",
    significance: "major",
  },
  {
    id: "gabon-biota",
    time: "21亿年前",
    title: "加蓬生物群",
    description: "法国加蓬发现约21亿年前的大型多细胞结构，最大达12厘米，可能是最早多细胞生命证据。",
    era: "eukaryotes",
    significance: "moderate",
  },
  {
    id: "first-eukaryotes",
    time: "18-21亿年前",
    title: "最早真核生物",
    description: "内共生事件产生第一批真核细胞——线粒体来自α-变形菌，叶绿体来自蓝细菌。",
    era: "eukaryotes",
    significance: "major",
  },
  {
    id: "first-eukaryotic-nucleus",
    time: "≈18亿年前",
    title: "细胞核出现",
    description: "真核细胞演化出由双层膜包裹的细胞核，将转录与翻译在空间上分隔，开启复杂基因调控。",
    era: "eukaryotes",
    significance: "major",
  },
  {
    id: "asgard-archaea",
    time: "2015年发现",
    title: "Asgard古菌发现",
    description: "洛基古菌等Asgard超群古菌被发现，拥有大量真核生物专属基因，改写了生命树结构。",
    era: "eukaryotes",
    significance: "major",
  },
  {
    id: "endosymbiosis",
    time: "15-20亿年前",
    title: "线粒体内共生",
    description: "古菌吞噬α-变形菌形成内共生关系，真核细胞获得有氧呼吸能力。",
    era: "eukaryotes",
    significance: "major",
  },
  {
    id: "sexual-reproduction",
    time: "12亿年前",
    title: "有性生殖出现",
    description: "红藻 Bangiomorpha pubescens 的化石中发现减数分裂证据。",
    era: "eukaryotes",
    significance: "major",
  },
  {
    id: "snowball-earth-sturtian",
    time: "7.2亿年前",
    title: "斯图特冰期开始",
    description: "雪球地球事件开始，冰川从两极延伸到赤道，整个地球几乎被冰层覆盖。",
    era: "multicellular-life",
    significance: "major",
  },
  {
    id: "snowball-earth-end",
    time: "6.3亿年前",
    title: "雪球地球结束",
    description: "火山CO₂积累引发极端温室效应，冰层迅速融化，为生命大爆发创造条件。",
    era: "multicellular-life",
    significance: "major",
  },
  {
    id: "ediacaran-biota",
    time: "5.75亿年前",
    title: "埃迪卡拉生物群",
    description: "第一批大型复杂多细胞生命出现——Dickinsonia、Kimberella等奇特生物统治海底。",
    era: "multicellular-life",
    significance: "major",
  },
  {
    id: "cambrian-explosion",
    time: "5.39亿年前",
    title: "寒武纪大爆发",
    description: "约2000万年内，几乎所有现存动物门的体型构架同时出现在化石记录中。",
    era: "cambrian-explosion",
    significance: "major",
  },
  {
    id: "chengjiang-biota",
    time: "5.18亿年前",
    title: "澄江生物群",
    description: "中国云南发现保存精美的软体化石，包括最早的脊椎动物海口鱼和昆明鱼。",
    era: "cambrian-explosion",
    significance: "major",
  },
  {
    id: "burgess-shale",
    time: "5.08亿年前",
    title: "伯吉斯页岩",
    description: "加拿大BC省发现的寒武纪化石库，保存了Anomalocaris等奇异生物。",
    era: "cambrian-explosion",
    significance: "major",
  },
  {
    id: "first-plants-land",
    time: "4.7亿年前",
    title: "植物登陆",
    description: "最早的陆地植物（类似苔类）从绿藻祖先演化，在陆地上建立据点。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "first-land-animals",
    time: "4.5亿年前",
    title: "动物登陆",
    description: "多足类（蜈蚣近亲）的足迹化石显示最早的陆地动物出现。",
    era: "land-colonization",
    significance: "moderate",
  },
  {
    id: "tiktaalik",
    time: "3.75亿年前",
    title: "提塔利克鱼",
    description: "从鱼到四足动物的关键过渡化石——有鱼的鳞片也有可转动的颈部和手腕。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "first-seed-plants",
    time: "3.6亿年前",
    title: "种子植物出现",
    description: "种子的演化让植物能够在干燥环境中繁殖，不再依赖水体。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "carboniferous-forests",
    time: "3.6亿年前",
    title: "石炭纪森林",
    description: "巨型鳞木属森林出现，高达40米。森林遗体形成煤炭，大气O₂达35%。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "amniote-egg",
    time: "≈3.1亿年前",
    title: "羊膜卵出现",
    description: "爬行动物演化出羊膜卵，胚胎在陆地干燥环境中发育，彻底摆脱对水体繁殖的依赖。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "permian-extinction",
    time: "2.52亿年前",
    title: "二叠纪末大灭绝",
    description: "地球史上最严重的大灭绝——约96%海洋物种和70%陆地物种消失。",
    era: "land-colonization",
    significance: "major",
  },
  {
    id: "first-dinosaurs",
    time: "2.3亿年前",
    title: "最早恐龙",
    description: "在南美洲出现最早的恐龙——小型双足动物，生活在盘古大陆上。",
    era: "age-of-dinosaurs",
    significance: "major",
  },
  {
    id: "first-true-mammals",
    time: "≈2.2亿年前",
    title: "最早哺乳动物出现",
    description: "三叠纪晚期出现最早的哺乳形类动物——小型夜行动物，在恐龙阴影下演化出恒温和毛发。",
    era: "age-of-dinosaurs",
    significance: "moderate",
  },
  {
    id: "archaeopteryx",
    time: "1.5亿年前",
    title: "始祖鸟",
    description: "最早确认的鸟类——拥有鸟类的羽毛和恐龙的牙齿，是进化过渡的经典例证。",
    era: "age-of-dinosaurs",
    significance: "major",
  },
  {
    id: "first-flowers",
    time: "1.4亿年前",
    title: "最早开花植物",
    description: "被子植物出现，通过花朵吸引传粉者，迅速成为陆地植物主导。",
    era: "age-of-dinosaurs",
    significance: "major",
  },
  {
    id: "feathered-dinosaurs",
    time: "1.25亿年前",
    title: "带羽毛恐龙",
    description: "中国辽宁发现中华龙鸟等带羽毛恐龙化石，证明羽毛最初用于保温而非飞行。",
    era: "age-of-dinosaurs",
    significance: "major",
  },
  {
    id: "first-grasses",
    time: "≈8000万年前",
    title: "最早禾草出现",
    description: "白垩纪晚期出现最早的禾本科植物，后来塑造了草原生态系统，深刻影响哺乳动物进化。",
    era: "rise-of-mammals",
    significance: "moderate",
  },
  {
    id: "chicxulub-impact",
    time: "6600万年前",
    title: "希克苏鲁伯撞击",
    description: "直径10公里的小行星撞击尤卡坦半岛，引发全球灾难，终结恐龙时代。",
    era: "age-of-dinosaurs",
    significance: "major",
  },
  {
    id: "mammalian-radiation",
    time: "6600万年前",
    title: "哺乳动物大辐射",
    description: "恐龙灭绝后，哺乳动物迅速填补空出的生态位，1000万年内体型增大1000倍。",
    era: "rise-of-mammals",
    significance: "major",
  },
  {
    id: "primate-origins",
    time: "5500-6000万年前",
    title: "灵长类起源",
    description: "最早的灵长目动物在热带雨林中出现——攀爬、立体视觉、抓握手指。",
    era: "rise-of-mammals",
    significance: "moderate",
  },
  {
    id: "whale-evolution",
    time: "5000万年前",
    title: "鲸类返回海洋",
    description: "鲸的祖先从陆地返回海洋——巴基鲸、走鲸展示了从陆生到水生的渐变过程。",
    era: "rise-of-mammals",
    significance: "major",
  },
  {
    id: "grassland-expansion",
    time: "2500万年前",
    title: "草原扩张",
    description: "全球变冷变干，热带森林退缩，草原生态系统形成，驱动了马等动物的进化。",
    era: "rise-of-mammals",
    significance: "moderate",
  },
  {
    id: "ice-ages",
    time: "260万年前",
    title: "冰河时代开始",
    description: "更新世冰期开始，冰盖反复扩张和收缩，巨型动物在寒冷环境中繁荣。",
    era: "rise-of-mammals",
    significance: "major",
  },
  {
    id: "sahelanthropus",
    time: "600-700万年前",
    title: "人猿分化",
    description: "Sahelanthropus tchadensis（托迈）——目前已知最接近人猿分化点的化石。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "homo-erectus-fire",
    time: "≈100万年前",
    title: "直立人控制用火",
    description: "南非Wonderwerk洞穴发现最早的控制用火痕迹，烹饪改变食物加工，推动大脑进一步增大。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "oldest-tools",
    time: "330万年前",
    title: "最早石器",
    description: "肯尼亚 Lomekwian 工具——比人属出现更早的石器文化。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "lucy",
    time: "320万年前",
    title: "Lucy（南方古猿阿法种）",
    description: "最著名的早期人类化石——直立行走的明确证据，身高约1.1米。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "homo-sapiens-origin",
    time: "30万年前",
    title: "智人起源",
    description: "摩洛哥 Jebel Irhoud 化石——目前已知最早的智人化石。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "toba-supervolcano",
    time: "≈7.4万年前",
    title: "多巴超级火山喷发",
    description: "苏门答腊岛多巴火山超级喷发，可能造成人类种群瓶颈，全球人口一度降至数千到数万。",
    era: "human-evolution",
    significance: "moderate",
  },
  {
    id: "cognitive-revolution",
    time: "7万年前",
    title: "认知革命",
    description: "智人开始展现符号思维、艺术创作和复杂语言能力——行为现代性的出现。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "out-of-africa",
    time: "7-10万年前",
    title: "走出非洲",
    description: "现代智人扩散到全球，与尼安德特人和丹尼索瓦人发生基因交流。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "first-cave-art",
    time: "≈4万年前",
    title: "最早洞穴壁画",
    description: "欧洲和东南亚出现最早的洞穴壁画和雕刻艺术，标志着人类符号思维和文化表达的成熟。",
    era: "human-evolution",
    significance: "major",
  },
  {
    id: "agricultural-revolution",
    time: "1.2万年前",
    title: "农业革命",
    description: "人类驯化植物和动物，从游猎走向定居——人类历史上最深刻的变革之一。",
    era: "human-evolution",
    significance: "major",
  },
];
