// AUTO-GENERATED + merge-preserved by scripts/gen-kb-index.ts (pnpm gen-kb).
// Each slug MUST resolve to a real file under content/cosmology/knowledge-base/.
export const COSMOLOGY_KB_DATA = [
  { slug: "大爆炸理论", title: "大爆炸理论", titleEn: "Big Bang Theory", category: "宇宙学基础" },
  {
    slug: "cosmic-inflation",
    title: "宇宙暴胀",
    titleEn: "Cosmic Inflation",
    category: "宇宙学基础",
  },
  {
    slug: "恒星核合成",
    title: "恒星核合成",
    titleEn: "Stellar Nucleosynthesis",
    category: "核天体物理学",
  },
  {
    slug: "宇宙微波背景",
    title: "宇宙微波背景辐射",
    titleEn: "Cosmic Microwave Background",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙的最终命运",
    title: "宇宙的最终命运",
    titleEn: "The Ultimate Fate of the Universe",
    category: "宇宙学前沿",
  },
  {
    slug: "stellar-evolution",
    title: "恒星演化",
    titleEn: "Stellar Evolution",
    category: "天体物理学",
  },
  {
    slug: "中子星与脉冲星",
    title: "中子星与脉冲星",
    titleEn: "Neutron Stars and Pulsars",
    category: "致密天体",
  },
  { slug: "black-holes", title: "黑洞", titleEn: "Black Holes", category: "致密天体" },
  {
    slug: "系外行星探测",
    title: "系外行星探测",
    titleEn: "Exoplanet Detection Methods",
    category: "系外行星科学",
  },
  {
    slug: "宇宙大尺度结构",
    title: "宇宙大尺度结构",
    titleEn: "Large-Scale Structure of the Universe",
    category: "星系天文学",
  },
  {
    slug: "引力波天文学",
    title: "引力波天文学",
    titleEn: "Gravitational Wave Astronomy",
    category: "多信使天文学",
  },
  {
    slug: "星系形成与演化",
    title: "星系形成与演化",
    titleEn: "Galaxy Formation and Evolution",
    category: "星系天文学",
  },
  {
    slug: "黑洞热力学与霍金辐射",
    title: "黑洞热力学与霍金辐射",
    titleEn: "Black Hole Thermodynamics and Hawking Radiation",
    category: "致密天体",
  },
  { slug: "引力透镜", title: "引力透镜", titleEn: "Gravitational Lensing", category: "宇宙学观测" },
  {
    slug: "宇宙距离阶梯",
    title: "宇宙距离阶梯",
    titleEn: "Cosmic Distance Ladder",
    category: "宇宙学观测",
  },
  {
    slug: "重子声学振荡",
    title: "重子声学振荡",
    titleEn: "Baryon Acoustic Oscillations",
    category: "宇宙学观测",
  },
  {
    slug: "第一代恒星与宇宙黎明",
    title: "第一代恒星与宇宙黎明",
    titleEn: "Population III Stars and Cosmic Dawn",
    category: "宇宙学前沿",
  },
  { slug: "多重宇宙假说", title: "多重宇宙假说", titleEn: "", category: "专题" },
  { slug: "暗物质与暗能量", title: "暗物质与暗能量", titleEn: "", category: "专题" },
  {
    slug: "天体生物学--biosignatures",
    title: "生物标志物",
    titleEn: "Biosignatures",
    category: "天体生物学",
  },
  {
    slug: "天体生物学--exoplanet-atmosphere",
    title: "系外行星大气探测",
    titleEn: "Exoplanet Atmosphere Detection",
    category: "天体生物学",
  },
  {
    slug: "天体生物学--fermi-paradox",
    title: "费米悖论",
    titleEn: "Fermi Paradox",
    category: "天体生物学",
  },
  {
    slug: "天体生物学--habitable-zone",
    title: "宜居带",
    titleEn: "Habitable Zone",
    category: "天体生物学",
  },
  {
    slug: "太阳系--asteroid-belt",
    title: "小行星带",
    titleEn: "The Asteroid Belt",
    category: "太阳系",
  },
  { slug: "太阳系--comets", title: "彗星", titleEn: "Comets", category: "太阳系" },
  {
    slug: "太阳系--gas-giants",
    title: "气态巨行星",
    titleEn: "Gas Giant Planets",
    category: "太阳系",
  },
  {
    slug: "太阳系--kuiper-belt-oort-cloud",
    title: "柯伊伯带与奥尔特云",
    titleEn: "Kuiper Belt and Oort Cloud",
    category: "太阳系",
  },
  {
    slug: "太阳系--planetary-moons",
    title: "行星卫星系统",
    titleEn: "Planetary Moon Systems",
    category: "太阳系",
  },
  {
    slug: "太阳系--solar-structure-activity",
    title: "太阳的结构与活动",
    titleEn: "Solar Structure and Activity",
    category: "太阳系",
  },
  {
    slug: "太阳系--terrestrial-planets",
    title: "类地行星",
    titleEn: "Terrestrial Planets",
    category: "太阳系",
  },
  {
    slug: "恒星物理--binary-star-systems",
    title: "双星系统",
    titleEn: "Binary Star Systems",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--cepheids-variable-stars",
    title: "造父变星与变星",
    titleEn: "Cepheid Variables and Variable Stars",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--core-collapse-supernovae",
    title: "核心坍缩超新星",
    titleEn: "Core-Collapse Supernovae",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--hertzsprung-russell-diagram",
    title: "赫罗图",
    titleEn: "Hertzsprung-Russell Diagram",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--main-sequence-stars",
    title: "主序星",
    titleEn: "Main Sequence Stars",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--red-giants-agb",
    title: "红巨星与渐近巨星支",
    titleEn: "Red Giants and the Asymptotic Giant Branch",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--star-formation",
    title: "恒星形成",
    titleEn: "Star Formation",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--stellar-structure-hydrostatic-equilibrium",
    title: "恒星结构与流体静力平衡",
    titleEn: "Stellar Structure and Hydrostatic Equilibrium",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--type-ia-supernovae",
    title: "Ia型超新星",
    titleEn: "Type Ia Supernovae",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--white-dwarfs",
    title: "白矮星",
    titleEn: "White Dwarfs",
    category: "恒星物理",
  },
  {
    slug: "星系天文学--agn-and-quasars",
    title: "活动星系核与类星体",
    titleEn: "Active Galactic Nuclei and Quasars",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--dark-matter-halo",
    title: "暗物质晕与星系旋转曲线",
    titleEn: "Dark Matter Halos and Galaxy Rotation Curves",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--dwarf-galaxies",
    title: "矮星系",
    titleEn: "Dwarf Galaxies",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--elliptical-galaxies",
    title: "椭圆星系",
    titleEn: "Elliptical Galaxies",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--galaxy-clusters",
    title: "星系团与超星系团",
    titleEn: "Galaxy Clusters and Superclusters",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--milky-way-structure",
    title: "银河系结构",
    titleEn: "Structure of the Milky Way",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--spiral-galaxies",
    title: "旋涡星系",
    titleEn: "Spiral Galaxies",
    category: "星系天文学",
  },
  {
    slug: "致密天体--accretion-disks-relativistic-jets",
    title: "黑洞吸积盘与相对论喷流",
    titleEn: "Black Hole Accretion Disks and Relativistic Jets",
    category: "致密天体",
  },
  { slug: "致密天体--magnetars", title: "磁星", titleEn: "Magnetars", category: "致密天体" },
  {
    slug: "致密天体--stellar-mass-black-holes",
    title: "恒星级黑洞",
    titleEn: "Stellar-Mass Black Holes",
    category: "致密天体",
  },
  {
    slug: "致密天体--supermassive-black-holes",
    title: "超大质量黑洞",
    titleEn: "Supermassive Black Holes",
    category: "致密天体",
  },
  {
    slug: "致密天体--tidal-disruption-events",
    title: "潮汐瓦解事件",
    titleEn: "Tidal Disruption Events",
    category: "致密天体",
  },
  {
    slug: "多信使天文学--binary-neutron-star-merger-kilonova",
    title: "双中子星并合与千新星",
    titleEn: "Binary Neutron Star Merger and Kilonova",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--cosmic-rays",
    title: "宇宙射线",
    titleEn: "Cosmic Rays",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--event-horizon-telescope",
    title: "事件视界望远镜",
    titleEn: "Event Horizon Telescope",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--fast-radio-bursts",
    title: "快速射电暴FRB",
    titleEn: "Fast Radio Bursts",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--gamma-ray-bursts",
    title: "伽马射线暴",
    titleEn: "Gamma-Ray Bursts",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--gravitational-wave-detectors-ligo-lisa",
    title: "引力波探测器LIGO与LISA",
    titleEn: "Gravitational Wave Detectors LIGO and LISA",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--kilonova-r-process",
    title: "kilonova与r过程核合成",
    titleEn: "Kilonova and r-Process Nucleosynthesis",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--multimessenger-astronomy-overview",
    title: "多信使天文学",
    titleEn: "Multimessenger Astronomy",
    category: "多信使天文学",
  },
  {
    slug: "多信使天文学--nanograv-pta-gw-background",
    title: "NANOGrav与纳赫兹引力波背景",
    titleEn: "NANOGrav and the Nanohertz Gravitational Wave Background",
    category: "多信使天文学",
  },
  {
    slug: "宇宙学基础--临界密度与宇宙几何",
    title: "临界密度与宇宙几何",
    titleEn: "Critical Density and Cosmic Geometry",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--共动距离与宇宙学红移",
    title: "共动距离与宇宙学红移",
    titleEn: "Comoving Distance and Cosmological Redshift",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--原初引力波与B模式",
    title: "原初引力波与 B 模式偏振",
    titleEn: "Primordial Gravitational Waves and B-mode Polarization",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--复合时期与最后散射面",
    title: "复合时期与最后散射面",
    titleEn: "Recombination and Last Scattering Surface",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--太初核合成",
    title: "太初核合成",
    titleEn: "Big Bang Nucleosynthesis",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--宇宙再电离",
    title: "宇宙再电离",
    titleEn: "Cosmic Reionization",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--宇宙学常数问题",
    title: "宇宙学常数问题",
    titleEn: "Cosmological Constant Problem",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--宇宙的年龄测定",
    title: "宇宙的年龄测定",
    titleEn: "Age of the Universe",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--宇宙网与纤维状结构",
    title: "宇宙网与纤维状结构",
    titleEn: "Cosmic Web and Filamentary Structure",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--宇宙黑暗时代",
    title: "宇宙黑暗时代",
    titleEn: "Cosmic Dark Ages",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--暗物质候选粒子WIMP与轴子",
    title: "暗物质候选粒子：WIMP 与轴子",
    titleEn: "Dark Matter Candidates - WIMPs and Axions",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--暗能量与状态方程",
    title: "暗能量与状态方程",
    titleEn: "Dark Energy and Equation of State",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--暴胀模型比较",
    title: "暴胀模型比较",
    titleEn: "Comparison of Inflationary Models",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--第一代恒星PopulationIII",
    title: "第一代恒星 Population III",
    titleEn: "Population III Stars",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学观测--X射线天文学",
    title: "X射线天文学",
    titleEn: "X-ray Astronomy",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--中微子探测器",
    title: "中微子探测器",
    titleEn: "Neutrino Detectors",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--光学望远镜",
    title: "光学望远镜",
    titleEn: "Optical Telescopes",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--哈勃空间望远镜",
    title: "哈勃空间望远镜",
    titleEn: "Hubble Space Telescope",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--多波段天文学",
    title: "多波段天文学",
    titleEn: "Multi-wavelength Astronomy",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--大型巡天SDSS与DESI",
    title: "大型巡天：SDSS与DESI",
    titleEn: "Large-Scale Surveys — SDSS and DESI",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--天体测量与盖亚卫星",
    title: "天体测量与盖亚卫星",
    titleEn: "Astrometry and Gaia Satellite",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--天文光谱学方法",
    title: "天文光谱学方法",
    titleEn: "Astronomical Spectroscopy",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--射电望远镜",
    title: "射电望远镜",
    titleEn: "Radio Telescopes",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--时域天文学",
    title: "时域天文学",
    titleEn: "Time-Domain Astronomy",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--甚长基线干涉",
    title: "甚长基线干涉测量",
    titleEn: "Very Long Baseline Interferometry",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--红外天文学",
    title: "红外天文学",
    titleEn: "Infrared Astronomy",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--自适应光学",
    title: "自适应光学",
    titleEn: "Adaptive Optics",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--詹姆斯韦伯空间望远镜",
    title: "詹姆斯·韦伯空间望远镜",
    titleEn: "James Webb Space Telescope",
    category: "宇宙学观测",
  },
  {
    slug: "星际介质--星际介质与分子云",
    title: "星际介质与分子云",
    titleEn: "Interstellar Medium and Molecular Clouds",
    category: "星际介质",
  },
  {
    slug: "星际介质--球状星团",
    title: "球状星团",
    titleEn: "Globular Clusters",
    category: "星际介质",
  },
  { slug: "星际介质--疏散星团", title: "疏散星团", titleEn: "Open Clusters", category: "星际介质" },
  {
    slug: "星际介质--行星状星云",
    title: "行星状星云",
    titleEn: "Planetary Nebulae",
    category: "星际介质",
  },
  { slug: "星际介质--褐矮星", title: "褐矮星", titleEn: "Brown Dwarfs", category: "星际介质" },
  {
    slug: "星际介质--超新星遗迹",
    title: "超新星遗迹",
    titleEn: "Supernova Remnants",
    category: "星际介质",
  },
  {
    slug: "系外行星--SETI地外文明搜寻",
    title: "SETI地外文明搜寻",
    titleEn: "SETI — Search for Extraterrestrial Intelligence",
    category: "系外行星",
  },
  { slug: "系外行星--凌星法", title: "凌星法", titleEn: "Transit Method", category: "系外行星" },
  {
    slug: "系外行星--微引力透镜法",
    title: "微引力透镜法",
    titleEn: "Gravitational Microlensing",
    category: "系外行星",
  },
  { slug: "系外行星--热木星", title: "热木星", titleEn: "Hot Jupiters", category: "系外行星" },
  {
    slug: "系外行星--直接成像法",
    title: "直接成像法",
    titleEn: "Direct Imaging",
    category: "系外行星",
  },
  {
    slug: "系外行星--系外行星宜居性",
    title: "系外行星宜居性",
    titleEn: "Exoplanet Habitability",
    category: "系外行星",
  },
  {
    slug: "系外行星--视向速度法",
    title: "视向速度法",
    titleEn: "Radial Velocity Method",
    category: "系外行星",
  },
  {
    slug: "系外行星--超级地球与迷你海王星",
    title: "超级地球与迷你海王星",
    titleEn: "Super-Earths and Mini-Neptunes",
    category: "系外行星",
  },
  {
    slug: "致密天体--black-hole-spin-measurement",
    title: "黑洞自旋测量",
    titleEn: "Black Hole Spin Measurement",
    category: "致密天体",
  },
  {
    slug: "致密天体--magnetar-flares",
    title: "磁星耀发",
    titleEn: "Magnetar Flares",
    category: "致密天体",
  },
  {
    slug: "致密天体--neutron-star-interior-eos",
    title: "中子星内部与状态方程",
    titleEn: "Neutron Star Interior and Equation of State",
    category: "致密天体",
  },
  {
    slug: "致密天体--pulsar-timing-array",
    title: "脉冲星计时阵列",
    titleEn: "Pulsar Timing Array",
    category: "致密天体",
  },
  {
    slug: "致密天体--x-ray-binaries",
    title: "X射线双星",
    titleEn: "X-ray Binaries",
    category: "致密天体",
  },
  {
    slug: "宇宙学前沿--cosmic-neutrino-background",
    title: "宇宙学中微子背景",
    titleEn: "Cosmic Neutrino Background",
    category: "宇宙学前沿",
  },
  {
    slug: "宇宙学前沿--dark-matter-direct-detection",
    title: "暗物质直接探测实验",
    titleEn: "Dark Matter Direct Detection Experiments",
    category: "宇宙学前沿",
  },
  {
    slug: "宇宙学前沿--dark-matter-indirect-detection",
    title: "暗物质间接探测",
    titleEn: "Indirect Detection of Dark Matter",
    category: "宇宙学前沿",
  },
  {
    slug: "宇宙学前沿--modified-gravity-mond",
    title: "修改引力理论MOND",
    titleEn: "Modified Newtonian Dynamics (MOND) and Modified Gravity",
    category: "宇宙学前沿",
  },
  {
    slug: "宇宙学前沿--primordial-black-holes",
    title: "原初黑洞",
    titleEn: "Primordial Black Holes",
    category: "宇宙学前沿",
  },
  {
    slug: "宇宙学基础--cosmic-thermal-history",
    title: "宇宙的热历史",
    titleEn: "Thermal History of the Universe",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学基础--cosmology-history",
    title: "宇宙学简史：从地心说到大爆炸",
    titleEn: "A Brief History of Cosmology",
    category: "宇宙学基础",
  },
  {
    slug: "宇宙学观测--大尺度结构形成",
    title: "大尺度结构形成",
    titleEn: "Large-Scale Structure Formation",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--宇宙距离阶梯",
    title: "宇宙距离阶梯",
    titleEn: "Cosmic Distance Ladder",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--弱引力透镜与宇宙剪切",
    title: "弱引力透镜与宇宙剪切",
    titleEn: "Weak Gravitational Lensing and Cosmic Shear",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--星系际介质",
    title: "星系际介质",
    titleEn: "Intergalactic Medium",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--标准烛光与Ia超新星测距",
    title: "标准烛光与Ia型超新星测距",
    titleEn: "Standard Candles and Type Ia Supernova Distance Measurement",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--红移巡天与宇宙三维制图",
    title: "红移巡天与宇宙三维制图",
    titleEn: "Redshift Surveys and Three-Dimensional Mapping of the Universe",
    category: "宇宙学观测",
  },
  {
    slug: "宇宙学观测--莱曼alpha森林",
    title: "莱曼α森林",
    titleEn: "Lyman-Alpha Forest",
    category: "宇宙学观测",
  },
  {
    slug: "恒星物理--binary-star-evolution",
    title: "双星演化与质量转移",
    titleEn: "Binary Star Evolution and Mass Transfer",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--massive-star-evolution",
    title: "大质量恒星演化",
    titleEn: "Massive Star Evolution",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--red-blue-supergiants",
    title: "红超巨星与蓝超巨星",
    titleEn: "Red Supergiants and Blue Supergiants",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--stellar-metallicity-chemical-evolution",
    title: "恒星金属丰度与化学演化",
    titleEn: "Stellar Metallicity and Chemical Evolution",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--stellar-populations",
    title: "星族I与星族II恒星",
    titleEn: "Population I and Population II Stars",
    category: "恒星物理",
  },
  {
    slug: "恒星物理--wolf-rayet-stars",
    title: "沃尔夫-拉叶星",
    titleEn: "Wolf-Rayet Stars",
    category: "恒星物理",
  },
  {
    slug: "星系天文学--哈勃星系形态序列",
    title: "哈勃星系形态序列",
    titleEn: "Hubble Galaxy Morphological Sequence",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--恒星流与星系晕",
    title: "恒星流与星系晕",
    titleEn: "Stellar Streams and Galactic Halos",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--星暴星系",
    title: "星暴星系",
    titleEn: "Starburst Galaxies",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--星系合并与相互作用",
    title: "星系合并与相互作用",
    titleEn: "Galaxy Mergers and Interactions",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--蝎虎座BL天体",
    title: "蝎虎座BL天体",
    titleEn: "BL Lacertae Objects",
    category: "星系天文学",
  },
  {
    slug: "星系天文学--赛弗特星系",
    title: "赛弗特星系",
    titleEn: "Seyfert Galaxies",
    category: "星系天文学",
  },
  {
    slug: "宇宙学前沿--21cm宇宙学与再电离",
    title: "21cm 宇宙学与再电离",
    titleEn: "21-cm Cosmology and Reionization",
    category: "宇宙学前沿",
  },
];
