// AUTO-GENERATED by scripts/gen-wiki-links-index.ts — do not edit by hand.
// Run `pnpm gen-links` to regenerate. Maps an article URL to the articles that
// reference it through inline `[[wiki-links]]` (the reverse of wiki-link-index).

export interface Backlink {
  url: string;
  title: string;
}

export const BACKLINKS_INDEX: Record<string, Backlink[]> = {
  "/computer-science/algorithms/attention-and-transformers": [
    {
      url: "/computer-science/algorithms/convolutional-neural-networks",
      title: "卷积神经网络",
    },
    {
      url: "/computer-science/algorithms/recurrent-neural-networks",
      title: "循环神经网络",
    },
  ],
  "/computer-science/algorithms/backtracking": [
    {
      url: "/computer-science/algorithms/knapsack-problem",
      title: "背包问题",
    },
    {
      url: "/computer-science/algorithms/sat-solving",
      title: "SAT 求解",
    },
  ],
  "/computer-science/algorithms/bellman-ford": [
    {
      url: "/computer-science/algorithms/floyd-warshall",
      title: "Floyd-Warshall 算法",
    },
  ],
  "/computer-science/algorithms/binary-search": [
    {
      url: "/computer-science/algorithms/sorting-algorithms",
      title: "排序算法",
    },
  ],
  "/computer-science/algorithms/consistent-hashing": [
    {
      url: "/computer-science/algorithms/mapreduce",
      title: "MapReduce",
    },
  ],
  "/computer-science/algorithms/convolutional-neural-networks": [
    {
      url: "/computer-science/algorithms/recurrent-neural-networks",
      title: "循环神经网络",
    },
    {
      url: "/computer-science/algorithms/attention-and-transformers",
      title: "注意力机制与 Transformer",
    },
  ],
  "/computer-science/algorithms/decision-trees": [
    {
      url: "/computer-science/algorithms/random-forests",
      title: "随机森林",
    },
    {
      url: "/computer-science/algorithms/k-means-clustering",
      title: "K-means 聚类",
    },
  ],
  "/computer-science/algorithms/divide-and-conquer": [
    {
      url: "/computer-science/algorithms/fast-fourier-transform",
      title: "快速傅里叶变换",
    },
    {
      url: "/computer-science/algorithms/convex-hull",
      title: "凸包算法",
    },
  ],
  "/computer-science/algorithms/dynamic-programming": [
    {
      url: "/computer-science/algorithms/bellman-ford",
      title: "贝尔曼-福特算法",
    },
    {
      url: "/computer-science/algorithms/knapsack-problem",
      title: "背包问题",
    },
    {
      url: "/computer-science/algorithms/edit-distance-algorithms",
      title: "编辑距离算法",
    },
    {
      url: "/computer-science/algorithms/divide-and-conquer",
      title: "分治算法",
    },
    {
      url: "/computer-science/algorithms/backtracking",
      title: "回溯算法",
    },
    {
      url: "/computer-science/algorithms/topological-sort",
      title: "拓扑排序",
    },
    {
      url: "/computer-science/algorithms/greedy-algorithms",
      title: "贪心算法",
    },
    {
      url: "/computer-science/algorithms/gradient-descent-backprop",
      title: "梯度下降与反向传播",
    },
    {
      url: "/computer-science/algorithms/segment-trees",
      title: "线段树",
    },
    {
      url: "/computer-science/algorithms/linear-programming",
      title: "线性规划",
    },
    {
      url: "/computer-science/algorithms/floyd-warshall",
      title: "Floyd-Warshall 算法",
    },
    {
      url: "/computer-science/algorithms/mapreduce",
      title: "MapReduce",
    },
    {
      url: "/computer-science/algorithms/sat-solving",
      title: "SAT 求解",
    },
  ],
  "/computer-science/algorithms/edit-distance-algorithms": [
    {
      url: "/computer-science/algorithms/suffix-trees-and-arrays",
      title: "后缀树与后缀数组",
    },
  ],
  "/computer-science/algorithms/fast-fourier-transform": [
    {
      url: "/computer-science/algorithms/divide-and-conquer",
      title: "分治算法",
    },
  ],
  "/computer-science/algorithms/floyd-warshall": [
    {
      url: "/computer-science/algorithms/bellman-ford",
      title: "贝尔曼-福特算法",
    },
  ],
  "/computer-science/algorithms/genetic-algorithms": [
    {
      url: "/computer-science/algorithms/simulated-annealing",
      title: "模拟退火",
    },
  ],
  "/computer-science/algorithms/gradient-boosting": [
    {
      url: "/computer-science/algorithms/random-forests",
      title: "随机森林",
    },
  ],
  "/computer-science/algorithms/gradient-descent-backprop": [
    {
      url: "/computer-science/algorithms/decision-trees",
      title: "决策树",
    },
    {
      url: "/computer-science/algorithms/newtons-method-numerical",
      title: "牛顿法与数值求解",
    },
    {
      url: "/computer-science/algorithms/gradient-boosting",
      title: "梯度提升",
    },
    {
      url: "/computer-science/algorithms/support-vector-machines",
      title: "支持向量机",
    },
    {
      url: "/computer-science/algorithms/attention-and-transformers",
      title: "注意力机制与 Transformer",
    },
    {
      url: "/computer-science/algorithms/k-means-clustering",
      title: "K-means 聚类",
    },
    {
      url: "/computer-science/algorithms/q-learning",
      title: "Q 学习与强化学习",
    },
  ],
  "/computer-science/algorithms/graph-traversal": [
    {
      url: "/computer-science/algorithms/topological-sort",
      title: "拓扑排序",
    },
    {
      url: "/computer-science/algorithms/network-flow",
      title: "网络流",
    },
    {
      url: "/computer-science/algorithms/shortest-path-dijkstra",
      title: "最短路径与 Dijkstra 算法",
    },
    {
      url: "/computer-science/algorithms/a-star-search",
      title: "A* 搜索算法",
    },
    {
      url: "/computer-science/algorithms/pagerank",
      title: "PageRank 算法",
    },
  ],
  "/computer-science/algorithms/greedy-algorithms": [
    {
      url: "/computer-science/algorithms/knapsack-problem",
      title: "背包问题",
    },
    {
      url: "/computer-science/algorithms/union-find",
      title: "并查集",
    },
    {
      url: "/computer-science/algorithms/heaps-and-priority-queues",
      title: "堆与优先队列",
    },
    {
      url: "/computer-science/algorithms/huffman-coding",
      title: "霍夫曼编码",
    },
    {
      url: "/computer-science/algorithms/linear-programming",
      title: "线性规划",
    },
    {
      url: "/computer-science/algorithms/a-star-search",
      title: "A* 搜索算法",
    },
  ],
  "/computer-science/algorithms/hashing": [
    {
      url: "/computer-science/algorithms/bloom-filter",
      title: "布隆过滤器",
    },
    {
      url: "/computer-science/algorithms/skip-lists",
      title: "跳表",
    },
    {
      url: "/computer-science/algorithms/consistent-hashing",
      title: "一致性哈希",
    },
    {
      url: "/computer-science/algorithms/string-matching",
      title: "字符串匹配",
    },
    {
      url: "/computer-science/algorithms/lru-cache-eviction",
      title: "LRU 缓存淘汰算法",
    },
    {
      url: "/computer-science/algorithms/public-key-rsa",
      title: "RSA 公钥密码",
    },
  ],
  "/computer-science/algorithms/heaps-and-priority-queues": [
    {
      url: "/computer-science/algorithms/huffman-coding",
      title: "霍夫曼编码",
    },
    {
      url: "/computer-science/algorithms/segment-trees",
      title: "线段树",
    },
  ],
  "/computer-science/algorithms/huffman-coding": [
    {
      url: "/computer-science/algorithms/greedy-algorithms",
      title: "贪心算法",
    },
  ],
  "/computer-science/algorithms/k-means-clustering": [
    {
      url: "/computer-science/algorithms/decision-trees",
      title: "决策树",
    },
    {
      url: "/computer-science/algorithms/principal-component-analysis",
      title: "主成分分析",
    },
  ],
  "/computer-science/algorithms/knapsack-problem": [
    {
      url: "/computer-science/algorithms/backtracking",
      title: "回溯算法",
    },
  ],
  "/computer-science/algorithms/linear-programming": [
    {
      url: "/computer-science/algorithms/network-flow",
      title: "网络流",
    },
  ],
  "/computer-science/algorithms/lru-cache-eviction": [
    {
      url: "/computer-science/algorithms/skip-lists",
      title: "跳表",
    },
  ],
  "/computer-science/algorithms/mapreduce": [
    {
      url: "/computer-science/algorithms/consistent-hashing",
      title: "一致性哈希",
    },
  ],
  "/computer-science/algorithms/minimum-spanning-tree": [
    {
      url: "/computer-science/algorithms/union-find",
      title: "并查集",
    },
    {
      url: "/computer-science/algorithms/greedy-algorithms",
      title: "贪心算法",
    },
    {
      url: "/computer-science/algorithms/graph-traversal",
      title: "图的遍历（BFS 与 DFS）",
    },
  ],
  "/computer-science/algorithms/monte-carlo-methods": [
    {
      url: "/computer-science/algorithms/simulated-annealing",
      title: "模拟退火",
    },
    {
      url: "/computer-science/algorithms/q-learning",
      title: "Q 学习与强化学习",
    },
  ],
  "/computer-science/algorithms/network-flow": [
    {
      url: "/computer-science/algorithms/linear-programming",
      title: "线性规划",
    },
  ],
  "/computer-science/algorithms/principal-component-analysis": [
    {
      url: "/computer-science/algorithms/support-vector-machines",
      title: "支持向量机",
    },
  ],
  "/computer-science/algorithms/public-key-rsa": [
    {
      url: "/computer-science/algorithms/hashing",
      title: "哈希",
    },
    {
      url: "/computer-science/frontier/quantum-algorithms",
      title: "量子算法：Shor 与 Grover 之后的软件边界",
    },
    {
      url: "/computer-science/frontier/zero-knowledge-proofs",
      title: "零知识证明与隐私计算",
    },
  ],
  "/computer-science/algorithms/random-forests": [
    {
      url: "/computer-science/algorithms/gradient-boosting",
      title: "梯度提升",
    },
  ],
  "/computer-science/algorithms/recurrent-neural-networks": [
    {
      url: "/computer-science/algorithms/convolutional-neural-networks",
      title: "卷积神经网络",
    },
    {
      url: "/computer-science/algorithms/attention-and-transformers",
      title: "注意力机制与 Transformer",
    },
  ],
  "/computer-science/algorithms/shortest-path-dijkstra": [
    {
      url: "/computer-science/algorithms/bellman-ford",
      title: "贝尔曼-福特算法",
    },
    {
      url: "/computer-science/algorithms/dynamic-programming",
      title: "动态规划",
    },
    {
      url: "/computer-science/algorithms/heaps-and-priority-queues",
      title: "堆与优先队列",
    },
    {
      url: "/computer-science/algorithms/topological-sort",
      title: "拓扑排序",
    },
    {
      url: "/computer-science/algorithms/graph-traversal",
      title: "图的遍历（BFS 与 DFS）",
    },
    {
      url: "/computer-science/algorithms/network-flow",
      title: "网络流",
    },
    {
      url: "/computer-science/concepts/networking-protocols",
      title: "网络协议栈 TCP/IP",
    },
    {
      url: "/computer-science/algorithms/minimum-spanning-tree",
      title: "最小生成树",
    },
    {
      url: "/computer-science/algorithms/a-star-search",
      title: "A* 搜索算法",
    },
    {
      url: "/computer-science/algorithms/floyd-warshall",
      title: "Floyd-Warshall 算法",
    },
  ],
  "/computer-science/algorithms/simulated-annealing": [
    {
      url: "/computer-science/algorithms/monte-carlo-methods",
      title: "蒙特卡洛方法",
    },
    {
      url: "/computer-science/algorithms/genetic-algorithms",
      title: "遗传算法",
    },
  ],
  "/computer-science/algorithms/skip-lists": [
    {
      url: "/computer-science/algorithms/lru-cache-eviction",
      title: "LRU 缓存淘汰算法",
    },
  ],
  "/computer-science/algorithms/sorting-algorithms": [
    {
      url: "/computer-science/algorithms/heaps-and-priority-queues",
      title: "堆与优先队列",
    },
    {
      url: "/computer-science/algorithms/binary-search",
      title: "二分查找",
    },
    {
      url: "/computer-science/algorithms/divide-and-conquer",
      title: "分治算法",
    },
    {
      url: "/computer-science/algorithms/convex-hull",
      title: "凸包算法",
    },
  ],
  "/computer-science/algorithms/string-matching": [
    {
      url: "/computer-science/algorithms/suffix-trees-and-arrays",
      title: "后缀树与后缀数组",
    },
  ],
  "/computer-science/algorithms/suffix-trees-and-arrays": [
    {
      url: "/computer-science/algorithms/edit-distance-algorithms",
      title: "编辑距离算法",
    },
  ],
  "/computer-science/algorithms/support-vector-machines": [
    {
      url: "/computer-science/algorithms/principal-component-analysis",
      title: "主成分分析",
    },
  ],
  "/computer-science/concepts/abstraction": [
    {
      url: "/computer-science/concepts/type-systems",
      title: "类型系统",
    },
    {
      url: "/computer-science/concepts/object-oriented-programming",
      title: "面向对象编程",
    },
    {
      url: "/computer-science/concepts/design-patterns",
      title: "设计模式",
    },
    {
      url: "/computer-science/concepts/networking-protocols",
      title: "网络协议栈 TCP/IP",
    },
    {
      url: "/computer-science/concepts/virtualization",
      title: "虚拟化与容器",
    },
    {
      url: "/computer-science/concepts/api-design",
      title: "API 设计",
    },
  ],
  "/computer-science/concepts/authentication-authorization": [
    {
      url: "/computer-science/concepts/computer-security-principles",
      title: "计算机安全原则",
    },
    {
      url: "/computer-science/pioneers/ron-rivest",
      title: "罗纳德·里维斯特",
    },
    {
      url: "/computer-science/concepts/web-security-xss-csrf",
      title: "Web 安全：XSS 与 CSRF",
    },
  ],
  "/computer-science/concepts/big-data-systems": [
    {
      url: "/computer-science/concepts/database-indexing-and-query-optimization",
      title: "数据库索引与查询优化",
    },
    {
      url: "/computer-science/concepts/message-queues-and-streaming",
      title: "消息队列与流处理",
    },
  ],
  "/computer-science/concepts/blockchain": [
    {
      url: "/computer-science/pioneers/leslie-lamport",
      title: "莱斯利·兰波特",
    },
  ],
  "/computer-science/concepts/cloud-computing": [
    {
      url: "/computer-science/concepts/distributed-systems",
      title: "分布式系统",
    },
  ],
  "/computer-science/concepts/compilers": [
    {
      url: "/computer-science/concepts/programming-language-design",
      title: "程序设计语言设计",
    },
  ],
  "/computer-science/concepts/computer-architecture": [
    {
      url: "/computer-science/concepts/embedded-systems",
      title: "嵌入式系统",
    },
    {
      url: "/computer-science/pioneers/steve-wozniak",
      title: "史蒂夫·沃兹尼亚克",
    },
    {
      url: "/computer-science/concepts/cpu-pipelining",
      title: "CPU 流水线",
    },
  ],
  "/computer-science/concepts/computer-graphics": [
    {
      url: "/computer-science/concepts/gpu-and-parallel-computing",
      title: "GPU 与并行计算",
    },
  ],
  "/computer-science/concepts/computer-security-principles": [
    {
      url: "/computer-science/concepts/encryption-basics",
      title: "加密基础",
    },
    {
      url: "/computer-science/concepts/authentication-authorization",
      title: "身份验证与授权",
    },
    {
      url: "/computer-science/concepts/dns",
      title: "DNS：互联网的命名系统",
    },
    {
      url: "/computer-science/concepts/web-security-xss-csrf",
      title: "Web 安全：XSS 与 CSRF",
    },
  ],
  "/computer-science/concepts/computer-vision": [
    {
      url: "/computer-science/concepts/deep-learning-architectures",
      title: "深度学习架构",
    },
    {
      url: "/computer-science/pioneers/yann-lecun",
      title: "杨·勒坤",
    },
  ],
  "/computer-science/concepts/concurrency": [
    {
      url: "/computer-science/concepts/operating-systems",
      title: "操作系统",
    },
    {
      url: "/computer-science/concepts/memory-hierarchy-caching",
      title: "存储层级与缓存",
    },
    {
      url: "/computer-science/concepts/distributed-systems",
      title: "分布式系统",
    },
    {
      url: "/computer-science/concepts/real-time-systems",
      title: "实时系统",
    },
    {
      url: "/computer-science/concepts/databases-transactions",
      title: "数据库与事务",
    },
  ],
  "/computer-science/concepts/containers-and-orchestration": [
    {
      url: "/computer-science/concepts/microservices-architecture",
      title: "微服务架构",
    },
  ],
  "/computer-science/concepts/cpu-pipelining": [
    {
      url: "/computer-science/concepts/computer-architecture",
      title: "计算机体系结构",
    },
    {
      url: "/computer-science/concepts/gpu-and-parallel-computing",
      title: "GPU 与并行计算",
    },
  ],
  "/computer-science/concepts/data-structures": [
    {
      url: "/computer-science/concepts/recursion",
      title: "递归",
    },
    {
      url: "/computer-science/algorithms/hashing",
      title: "哈希",
    },
    {
      url: "/computer-science/pioneers/robert-tarjan",
      title: "罗伯特·塔扬",
    },
    {
      url: "/computer-science/concepts/database-indexing-and-query-optimization",
      title: "数据库索引与查询优化",
    },
    {
      url: "/computer-science/algorithms/graph-traversal",
      title: "图的遍历（BFS 与 DFS）",
    },
    {
      url: "/computer-science/algorithms/minimum-spanning-tree",
      title: "最小生成树",
    },
  ],
  "/computer-science/concepts/database-indexing-and-query-optimization": [
    {
      url: "/computer-science/concepts/big-data-systems",
      title: "大数据系统",
    },
    {
      url: "/computer-science/pioneers/robert-tarjan",
      title: "罗伯特·塔扬",
    },
  ],
  "/computer-science/concepts/databases-transactions": [
    {
      url: "/computer-science/concepts/caching-strategies",
      title: "缓存策略",
    },
    {
      url: "/computer-science/pioneers/leslie-lamport",
      title: "莱斯利·兰波特",
    },
    {
      url: "/computer-science/concepts/blockchain",
      title: "区块链",
    },
    {
      url: "/computer-science/concepts/database-indexing-and-query-optimization",
      title: "数据库索引与查询优化",
    },
    {
      url: "/computer-science/concepts/file-systems",
      title: "文件系统",
    },
  ],
  "/computer-science/concepts/deep-learning-architectures": [
    {
      url: "/computer-science/concepts/computer-vision",
      title: "计算机视觉",
    },
    {
      url: "/computer-science/concepts/neural-networks-concept",
      title: "神经网络",
    },
    {
      url: "/computer-science/pioneers/yann-lecun",
      title: "杨·勒坤",
    },
    {
      url: "/computer-science/concepts/natural-language-processing",
      title: "自然语言处理",
    },
  ],
  "/computer-science/concepts/design-patterns": [
    {
      url: "/computer-science/concepts/object-oriented-programming",
      title: "面向对象编程",
    },
    {
      url: "/computer-science/concepts/software-engineering",
      title: "软件工程",
    },
  ],
  "/computer-science/concepts/distributed-systems": [
    {
      url: "/computer-science/pioneers/barbara-liskov",
      title: "芭芭拉·利斯科夫",
    },
    {
      url: "/computer-science/concepts/operating-systems",
      title: "操作系统",
    },
    {
      url: "/computer-science/concepts/big-data-systems",
      title: "大数据系统",
    },
    {
      url: "/computer-science/concepts/firewalls-and-network-security",
      title: "防火墙与网络安全",
    },
    {
      url: "/computer-science/concepts/caching-strategies",
      title: "缓存策略",
    },
    {
      url: "/computer-science/pioneers/leslie-lamport",
      title: "莱斯利·兰波特",
    },
    {
      url: "/computer-science/pioneers/linus-torvalds",
      title: "林纳斯·托瓦兹",
    },
    {
      url: "/computer-science/concepts/routing-and-switching",
      title: "路由与交换",
    },
    {
      url: "/computer-science/pioneers/robert-tarjan",
      title: "罗伯特·塔扬",
    },
    {
      url: "/computer-science/concepts/blockchain",
      title: "区块链",
    },
    {
      url: "/computer-science/concepts/databases-transactions",
      title: "数据库与事务",
    },
    {
      url: "/computer-science/concepts/the-web-and-http",
      title: "万维网与 HTTP",
    },
    {
      url: "/computer-science/concepts/microservices-architecture",
      title: "微服务架构",
    },
    {
      url: "/computer-science/pioneers/vint-cerf",
      title: "文顿·瑟夫",
    },
    {
      url: "/computer-science/concepts/file-systems",
      title: "文件系统",
    },
    {
      url: "/computer-science/concepts/message-queues-and-streaming",
      title: "消息队列与流处理",
    },
    {
      url: "/computer-science/concepts/cloud-computing",
      title: "云计算",
    },
    {
      url: "/computer-science/concepts/dns",
      title: "DNS：互联网的命名系统",
    },
    {
      url: "/computer-science/concepts/gpu-and-parallel-computing",
      title: "GPU 与并行计算",
    },
    {
      url: "/computer-science/concepts/tcp-and-reliable-transport",
      title: "TCP 与可靠传输",
    },
  ],
  "/computer-science/concepts/dns": [
    {
      url: "/computer-science/concepts/the-web-and-http",
      title: "万维网与 HTTP",
    },
  ],
  "/computer-science/concepts/embedded-systems": [
    {
      url: "/computer-science/concepts/real-time-systems",
      title: "实时系统",
    },
    {
      url: "/computer-science/pioneers/steve-wozniak",
      title: "史蒂夫·沃兹尼亚克",
    },
  ],
  "/computer-science/concepts/encryption-basics": [
    {
      url: "/computer-science/concepts/firewalls-and-network-security",
      title: "防火墙与网络安全",
    },
    {
      url: "/computer-science/concepts/computer-security-principles",
      title: "计算机安全原则",
    },
    {
      url: "/computer-science/pioneers/ron-rivest",
      title: "罗纳德·里维斯特",
    },
    {
      url: "/computer-science/concepts/blockchain",
      title: "区块链",
    },
    {
      url: "/computer-science/concepts/authentication-authorization",
      title: "身份验证与授权",
    },
  ],
  "/computer-science/concepts/functional-programming": [
    {
      url: "/computer-science/pioneers/guido-van-rossum",
      title: "吉多·范罗苏姆",
    },
    {
      url: "/computer-science/concepts/garbage-collection",
      title: "垃圾回收",
    },
    {
      url: "/computer-science/concepts/object-oriented-programming",
      title: "面向对象编程",
    },
  ],
  "/computer-science/concepts/gpu-and-parallel-computing": [
    {
      url: "/computer-science/concepts/computer-vision",
      title: "计算机视觉",
    },
    {
      url: "/computer-science/concepts/computer-graphics",
      title: "计算机图形学",
    },
    {
      url: "/computer-science/concepts/deep-learning-architectures",
      title: "深度学习架构",
    },
    {
      url: "/computer-science/concepts/cpu-pipelining",
      title: "CPU 流水线",
    },
  ],
  "/computer-science/concepts/information-retrieval-and-search": [
    {
      url: "/computer-science/pioneers/larry-page-and-sergey-brin",
      title: "拉里·佩奇与谢尔盖·布林",
    },
    {
      url: "/computer-science/concepts/recommender-systems",
      title: "推荐系统",
    },
  ],
  "/computer-science/concepts/machine-learning-overview": [
    {
      url: "/computer-science/concepts/big-data-systems",
      title: "大数据系统",
    },
    {
      url: "/computer-science/pioneers/larry-page-and-sergey-brin",
      title: "拉里·佩奇与谢尔盖·布林",
    },
    {
      url: "/computer-science/concepts/reinforcement-learning-concept",
      title: "强化学习",
    },
    {
      url: "/computer-science/concepts/neural-networks-concept",
      title: "神经网络",
    },
    {
      url: "/computer-science/concepts/recommender-systems",
      title: "推荐系统",
    },
    {
      url: "/computer-science/concepts/information-retrieval-and-search",
      title: "信息检索与搜索",
    },
    {
      url: "/computer-science/pioneers/yoshua-bengio",
      title: "约书亚·本希奥",
    },
  ],
  "/computer-science/concepts/memory-hierarchy-caching": [
    {
      url: "/computer-science/concepts/concurrency",
      title: "并发与并行",
    },
    {
      url: "/computer-science/concepts/operating-systems",
      title: "操作系统",
    },
    {
      url: "/computer-science/concepts/caching-strategies",
      title: "缓存策略",
    },
    {
      url: "/computer-science/concepts/computer-architecture",
      title: "计算机体系结构",
    },
    {
      url: "/computer-science/concepts/garbage-collection",
      title: "垃圾回收",
    },
    {
      url: "/computer-science/concepts/file-systems",
      title: "文件系统",
    },
  ],
  "/computer-science/concepts/message-queues-and-streaming": [
    {
      url: "/computer-science/concepts/microservices-architecture",
      title: "微服务架构",
    },
  ],
  "/computer-science/concepts/microservices-architecture": [
    {
      url: "/computer-science/concepts/containers-and-orchestration",
      title: "容器与容器编排",
    },
    {
      url: "/computer-science/concepts/message-queues-and-streaming",
      title: "消息队列与流处理",
    },
  ],
  "/computer-science/concepts/natural-language-processing": [
    {
      url: "/computer-science/concepts/computer-vision",
      title: "计算机视觉",
    },
    {
      url: "/computer-science/concepts/deep-learning-architectures",
      title: "深度学习架构",
    },
    {
      url: "/computer-science/pioneers/yoshua-bengio",
      title: "约书亚·本希奥",
    },
  ],
  "/computer-science/concepts/networking-protocols": [
    {
      url: "/computer-science/concepts/abstraction",
      title: "抽象与分层",
    },
    {
      url: "/computer-science/concepts/firewalls-and-network-security",
      title: "防火墙与网络安全",
    },
    {
      url: "/computer-science/concepts/routing-and-switching",
      title: "路由与交换",
    },
    {
      url: "/computer-science/concepts/the-web-and-http",
      title: "万维网与 HTTP",
    },
    {
      url: "/computer-science/concepts/virtualization",
      title: "虚拟化与容器",
    },
    {
      url: "/computer-science/concepts/api-design",
      title: "API 设计",
    },
    {
      url: "/computer-science/concepts/dns",
      title: "DNS：互联网的命名系统",
    },
    {
      url: "/computer-science/algorithms/public-key-rsa",
      title: "RSA 公钥密码",
    },
    {
      url: "/computer-science/concepts/tcp-and-reliable-transport",
      title: "TCP 与可靠传输",
    },
    {
      url: "/computer-science/concepts/unicode-and-text-encoding",
      title: "Unicode 与文本编码",
    },
  ],
  "/computer-science/concepts/neural-networks-concept": [
    {
      url: "/computer-science/concepts/machine-learning-overview",
      title: "机器学习概览",
    },
    {
      url: "/computer-science/concepts/reinforcement-learning-concept",
      title: "强化学习",
    },
  ],
  "/computer-science/concepts/object-oriented-programming": [
    {
      url: "/computer-science/pioneers/bjarne-stroustrup",
      title: "比雅尼·斯特劳斯特鲁普",
    },
    {
      url: "/computer-science/concepts/functional-programming",
      title: "函数式编程",
    },
    {
      url: "/computer-science/pioneers/guido-van-rossum",
      title: "吉多·范罗苏姆",
    },
    {
      url: "/computer-science/concepts/design-patterns",
      title: "设计模式",
    },
  ],
  "/computer-science/concepts/operating-systems": [
    {
      url: "/computer-science/pioneers/bill-gates",
      title: "比尔·盖茨",
    },
    {
      url: "/computer-science/concepts/computer-architecture",
      title: "计算机体系结构",
    },
    {
      url: "/computer-science/pioneers/linus-torvalds",
      title: "林纳斯·托瓦兹",
    },
    {
      url: "/computer-science/concepts/embedded-systems",
      title: "嵌入式系统",
    },
    {
      url: "/computer-science/concepts/containers-and-orchestration",
      title: "容器与容器编排",
    },
    {
      url: "/computer-science/concepts/real-time-systems",
      title: "实时系统",
    },
    {
      url: "/computer-science/concepts/file-systems",
      title: "文件系统",
    },
    {
      url: "/computer-science/concepts/unicode-and-text-encoding",
      title: "Unicode 与文本编码",
    },
  ],
  "/computer-science/concepts/programming-language-design": [
    {
      url: "/computer-science/pioneers/bjarne-stroustrup",
      title: "比雅尼·斯特劳斯特鲁普",
    },
    {
      url: "/computer-science/pioneers/guido-van-rossum",
      title: "吉多·范罗苏姆",
    },
  ],
  "/computer-science/concepts/real-time-systems": [
    {
      url: "/computer-science/concepts/embedded-systems",
      title: "嵌入式系统",
    },
  ],
  "/computer-science/concepts/recommender-systems": [
    {
      url: "/computer-science/concepts/information-retrieval-and-search",
      title: "信息检索与搜索",
    },
  ],
  "/computer-science/concepts/recursion": [
    {
      url: "/computer-science/algorithms/dynamic-programming",
      title: "动态规划",
    },
    {
      url: "/computer-science/concepts/functional-programming",
      title: "函数式编程",
    },
    {
      url: "/computer-science/concepts/data-structures",
      title: "数据结构",
    },
  ],
  "/computer-science/concepts/reinforcement-learning-concept": [
    {
      url: "/computer-science/concepts/machine-learning-overview",
      title: "机器学习概览",
    },
  ],
  "/computer-science/concepts/software-engineering": [
    {
      url: "/computer-science/concepts/version-control",
      title: "版本控制",
    },
    {
      url: "/computer-science/pioneers/bill-gates",
      title: "比尔·盖茨",
    },
    {
      url: "/computer-science/concepts/software-testing",
      title: "软件测试",
    },
    {
      url: "/computer-science/concepts/design-patterns",
      title: "设计模式",
    },
    {
      url: "/computer-science/concepts/api-design",
      title: "API 设计",
    },
  ],
  "/computer-science/concepts/software-testing": [
    {
      url: "/computer-science/concepts/software-engineering",
      title: "软件工程",
    },
    {
      url: "/computer-science/concepts/formal-methods-and-verification",
      title: "形式化方法与程序验证",
    },
  ],
  "/computer-science/concepts/the-web-and-http": [
    {
      url: "/computer-science/concepts/web-security-xss-csrf",
      title: "Web 安全：XSS 与 CSRF",
    },
  ],
  "/computer-science/concepts/type-systems": [
    {
      url: "/computer-science/pioneers/bjarne-stroustrup",
      title: "比雅尼·斯特劳斯特鲁普",
    },
    {
      url: "/computer-science/concepts/compilers",
      title: "编译器",
    },
    {
      url: "/computer-science/concepts/programming-language-design",
      title: "程序设计语言设计",
    },
    {
      url: "/computer-science/concepts/functional-programming",
      title: "函数式编程",
    },
    {
      url: "/computer-science/concepts/garbage-collection",
      title: "垃圾回收",
    },
    {
      url: "/computer-science/concepts/software-testing",
      title: "软件测试",
    },
    {
      url: "/computer-science/concepts/formal-methods-and-verification",
      title: "形式化方法与程序验证",
    },
    {
      url: "/computer-science/frontier/formal-verification",
      title: "形式化验证与程序合成",
    },
  ],
  "/computer-science/concepts/version-control": [
    {
      url: "/computer-science/concepts/software-engineering",
      title: "软件工程",
    },
  ],
  "/computer-science/concepts/virtualization": [
    {
      url: "/computer-science/concepts/operating-systems",
      title: "操作系统",
    },
    {
      url: "/computer-science/concepts/abstraction",
      title: "抽象与分层",
    },
    {
      url: "/computer-science/concepts/containers-and-orchestration",
      title: "容器与容器编排",
    },
    {
      url: "/computer-science/concepts/cloud-computing",
      title: "云计算",
    },
  ],
  "/computer-science/frontier/ai-interpretability": [
    {
      url: "/computer-science/frontier/large-language-models",
      title: "大语言模型与基础模型",
    },
  ],
  "/computer-science/frontier/formal-verification": [
    {
      url: "/computer-science/frontier/zero-knowledge-proofs",
      title: "零知识证明与隐私计算",
    },
  ],
  "/computer-science/frontier/large-language-models": [
    {
      url: "/computer-science/frontier/ai-interpretability",
      title: "机制可解释性：理解神经网络内部",
    },
    {
      url: "/computer-science/frontier/formal-verification",
      title: "形式化验证与程序合成",
    },
  ],
  "/computer-science/frontier/zero-knowledge-proofs": [
    {
      url: "/computer-science/frontier/formal-verification",
      title: "形式化验证与程序合成",
    },
  ],
  "/computer-science/pioneers/ada-lovelace": [
    {
      url: "/computer-science/pioneers/charles-babbage",
      title: "查尔斯·巴贝奇",
    },
    {
      url: "/computer-science/pioneers/grace-hopper",
      title: "格蕾丝·霍普",
    },
  ],
  "/computer-science/pioneers/alan-kay": [
    {
      url: "/computer-science/pioneers/douglas-engelbart",
      title: "道格拉斯·恩格尔巴特",
    },
  ],
  "/computer-science/pioneers/alan-turing": [
    {
      url: "/computer-science/pioneers/charles-babbage",
      title: "查尔斯·巴贝奇",
    },
    {
      url: "/computer-science/pioneers/tim-berners-lee",
      title: "蒂姆·伯纳斯-李",
    },
    {
      url: "/computer-science/pioneers/geoffrey-hinton",
      title: "杰弗里·辛顿",
    },
    {
      url: "/computer-science/theory/computability",
      title: "可计算性理论",
    },
    {
      url: "/computer-science/pioneers/claude-shannon",
      title: "克劳德·香农",
    },
    {
      url: "/computer-science/pioneers/ron-rivest",
      title: "罗纳德·里维斯特",
    },
    {
      url: "/computer-science/pioneers/george-boole",
      title: "乔治·布尔",
    },
    {
      url: "/computer-science/pioneers/john-mccarthy",
      title: "约翰·麦卡锡",
    },
  ],
  "/computer-science/pioneers/bill-gates": [
    {
      url: "/computer-science/pioneers/steve-wozniak",
      title: "史蒂夫·沃兹尼亚克",
    },
  ],
  "/computer-science/pioneers/claude-shannon": [
    {
      url: "/computer-science/pioneers/john-von-neumann",
      title: "冯·诺伊曼",
    },
    {
      url: "/computer-science/pioneers/george-boole",
      title: "乔治·布尔",
    },
    {
      url: "/computer-science/pioneers/vint-cerf",
      title: "文顿·瑟夫",
    },
    {
      url: "/computer-science/theory/information-theory",
      title: "信息论",
    },
    {
      url: "/computer-science/pioneers/john-mccarthy",
      title: "约翰·麦卡锡",
    },
  ],
  "/computer-science/pioneers/dennis-ritchie": [
    {
      url: "/computer-science/pioneers/bjarne-stroustrup",
      title: "比雅尼·斯特劳斯特鲁普",
    },
    {
      url: "/computer-science/pioneers/frances-allen",
      title: "弗朗西丝·艾伦",
    },
    {
      url: "/computer-science/pioneers/ken-thompson",
      title: "肯·汤普森",
    },
  ],
  "/computer-science/pioneers/donald-knuth": [
    {
      url: "/computer-science/pioneers/edsger-dijkstra",
      title: "艾兹格·迪科斯彻",
    },
    {
      url: "/computer-science/pioneers/dennis-ritchie",
      title: "丹尼斯·里奇",
    },
  ],
  "/computer-science/pioneers/douglas-engelbart": [
    {
      url: "/computer-science/pioneers/alan-kay",
      title: "艾伦·凯",
    },
  ],
  "/computer-science/pioneers/edsger-dijkstra": [
    {
      url: "/computer-science/pioneers/barbara-liskov",
      title: "芭芭拉·利斯科夫",
    },
    {
      url: "/computer-science/pioneers/donald-knuth",
      title: "唐纳德·克努特",
    },
  ],
  "/computer-science/pioneers/frances-allen": [
    {
      url: "/computer-science/theory/formal-grammars-chomsky-hierarchy",
      title: "形式文法与乔姆斯基谱系",
    },
    {
      url: "/computer-science/pioneers/john-backus",
      title: "约翰·巴克斯",
    },
  ],
  "/computer-science/pioneers/geoffrey-hinton": [
    {
      url: "/computer-science/pioneers/marvin-minsky",
      title: "马文·明斯基",
    },
    {
      url: "/computer-science/pioneers/yann-lecun",
      title: "杨·勒坤",
    },
    {
      url: "/computer-science/pioneers/yoshua-bengio",
      title: "约书亚·本希奥",
    },
  ],
  "/computer-science/pioneers/george-boole": [
    {
      url: "/computer-science/pioneers/charles-babbage",
      title: "查尔斯·巴贝奇",
    },
  ],
  "/computer-science/pioneers/grace-hopper": [
    {
      url: "/computer-science/pioneers/margaret-hamilton",
      title: "玛格丽特·汉密顿",
    },
  ],
  "/computer-science/pioneers/john-backus": [
    {
      url: "/computer-science/pioneers/edgar-codd",
      title: "埃德加·科德",
    },
    {
      url: "/computer-science/pioneers/frances-allen",
      title: "弗朗西丝·艾伦",
    },
  ],
  "/computer-science/pioneers/john-mccarthy": [
    {
      url: "/computer-science/pioneers/marvin-minsky",
      title: "马文·明斯基",
    },
  ],
  "/computer-science/pioneers/john-von-neumann": [
    {
      url: "/computer-science/pioneers/alan-turing",
      title: "艾伦·图灵",
    },
  ],
  "/computer-science/pioneers/ken-thompson": [
    {
      url: "/computer-science/pioneers/dennis-ritchie",
      title: "丹尼斯·里奇",
    },
  ],
  "/computer-science/pioneers/linus-torvalds": [
    {
      url: "/computer-science/pioneers/dennis-ritchie",
      title: "丹尼斯·里奇",
    },
    {
      url: "/computer-science/pioneers/ken-thompson",
      title: "肯·汤普森",
    },
    {
      url: "/computer-science/pioneers/richard-stallman",
      title: "理查德·斯托曼",
    },
  ],
  "/computer-science/pioneers/marvin-minsky": [
    {
      url: "/computer-science/pioneers/alan-kay",
      title: "艾伦·凯",
    },
  ],
  "/computer-science/pioneers/richard-stallman": [
    {
      url: "/computer-science/pioneers/linus-torvalds",
      title: "林纳斯·托瓦兹",
    },
  ],
  "/computer-science/pioneers/steve-wozniak": [
    {
      url: "/computer-science/pioneers/bill-gates",
      title: "比尔·盖茨",
    },
  ],
  "/computer-science/pioneers/tim-berners-lee": [
    {
      url: "/computer-science/pioneers/douglas-engelbart",
      title: "道格拉斯·恩格尔巴特",
    },
    {
      url: "/computer-science/pioneers/vint-cerf",
      title: "文顿·瑟夫",
    },
  ],
  "/computer-science/pioneers/vint-cerf": [
    {
      url: "/computer-science/pioneers/larry-page-and-sergey-brin",
      title: "拉里·佩奇与谢尔盖·布林",
    },
  ],
  "/computer-science/theory/automata-formal-languages": [
    {
      url: "/computer-science/concepts/compilers",
      title: "编译器",
    },
    {
      url: "/computer-science/theory/computability",
      title: "可计算性理论",
    },
    {
      url: "/computer-science/theory/formal-grammars-chomsky-hierarchy",
      title: "形式文法与乔姆斯基谱系",
    },
    {
      url: "/computer-science/algorithms/string-matching",
      title: "字符串匹配",
    },
  ],
  "/computer-science/theory/computability": [
    {
      url: "/computer-science/theory/computational-complexity",
      title: "计算复杂性理论",
    },
    {
      url: "/computer-science/theory/kolmogorov-complexity",
      title: "柯莫哥洛夫复杂度",
    },
    {
      url: "/computer-science/theory/quantum-computing-theory",
      title: "量子计算理论",
    },
    {
      url: "/computer-science/theory/logic-and-computation",
      title: "逻辑与计算",
    },
    {
      url: "/computer-science/theory/formal-grammars-chomsky-hierarchy",
      title: "形式文法与乔姆斯基谱系",
    },
    {
      url: "/computer-science/pioneers/john-mccarthy",
      title: "约翰·麦卡锡",
    },
    {
      url: "/computer-science/theory/automata-formal-languages",
      title: "自动机与形式语言",
    },
    {
      url: "/computer-science/theory/lambda-calculus-type-theory",
      title: "λ演算与类型理论",
    },
  ],
  "/computer-science/theory/computational-complexity": [
    {
      url: "/computer-science/theory/computational-geometry",
      title: "计算几何",
    },
    {
      url: "/computer-science/theory/computability",
      title: "可计算性理论",
    },
    {
      url: "/computer-science/theory/quantum-computing-theory",
      title: "量子计算理论",
    },
    {
      url: "/computer-science/theory/cryptography-foundations",
      title: "密码学基础",
    },
    {
      url: "/computer-science/theory/randomized-algorithms",
      title: "随机算法",
    },
    {
      url: "/computer-science/algorithms/string-matching",
      title: "字符串匹配",
    },
  ],
  "/computer-science/theory/cryptography-foundations": [
    {
      url: "/computer-science/theory/computational-complexity",
      title: "计算复杂性理论",
    },
    {
      url: "/computer-science/theory/error-correcting-codes",
      title: "纠错码理论",
    },
    {
      url: "/computer-science/theory/quantum-computing-theory",
      title: "量子计算理论",
    },
    {
      url: "/computer-science/theory/randomized-algorithms",
      title: "随机算法",
    },
    {
      url: "/computer-science/theory/information-theory",
      title: "信息论",
    },
  ],
  "/computer-science/theory/information-theory": [
    {
      url: "/computer-science/theory/error-correcting-codes",
      title: "纠错码理论",
    },
    {
      url: "/computer-science/theory/kolmogorov-complexity",
      title: "柯莫哥洛夫复杂度",
    },
    {
      url: "/computer-science/theory/quantum-computing-theory",
      title: "量子计算理论",
    },
    {
      url: "/computer-science/theory/cryptography-foundations",
      title: "密码学基础",
    },
    {
      url: "/computer-science/concepts/databases-transactions",
      title: "数据库与事务",
    },
    {
      url: "/computer-science/theory/randomized-algorithms",
      title: "随机算法",
    },
  ],
  "/computer-science/theory/lambda-calculus-type-theory": [
    {
      url: "/computer-science/pioneers/barbara-liskov",
      title: "芭芭拉·利斯科夫",
    },
    {
      url: "/computer-science/concepts/compilers",
      title: "编译器",
    },
    {
      url: "/computer-science/concepts/recursion",
      title: "递归",
    },
    {
      url: "/computer-science/theory/logic-and-computation",
      title: "逻辑与计算",
    },
    {
      url: "/computer-science/pioneers/john-mccarthy",
      title: "约翰·麦卡锡",
    },
    {
      url: "/computer-science/theory/automata-formal-languages",
      title: "自动机与形式语言",
    },
  ],
  "/computer-science/theory/quantum-computing-theory": [
    {
      url: "/computer-science/theory/error-correcting-codes",
      title: "纠错码理论",
    },
    {
      url: "/computer-science/theory/randomized-algorithms",
      title: "随机算法",
    },
  ],
  "/computer-science/theory/randomized-algorithms": [
    {
      url: "/computer-science/theory/computational-geometry",
      title: "计算几何",
    },
  ],
  "/life-science/species/tardigrade": [
    {
      url: "/life-science/scientists/margulis",
      title: "林恩·马古利斯",
    },
  ],
  "/mathematics/concepts/category-theory": [
    {
      url: "/mathematics/concepts/function",
      title: "函数",
    },
  ],
  "/mathematics/concepts/complex-analysis": [
    {
      url: "/mathematics/mathematicians/abel",
      title: "阿贝尔",
    },
    {
      url: "/mathematics/concepts/complex-number",
      title: "复数",
    },
    {
      url: "/mathematics/mathematicians/hua-luogeng",
      title: "华罗庚",
    },
    {
      url: "/mathematics/concepts/trigonometry",
      title: "三角函数",
    },
  ],
  "/mathematics/concepts/derivative": [
    {
      url: "/mathematics/concepts/function",
      title: "函数",
    },
  ],
  "/mathematics/concepts/differential-equation": [
    {
      url: "/mathematics/concepts/trigonometry",
      title: "三角函数",
    },
  ],
  "/mathematics/concepts/differential-geometry": [
    {
      url: "/mathematics/mathematicians/chern",
      title: "陈省身",
    },
    {
      url: "/mathematics/mathematicians/mirzakhani",
      title: "米尔扎哈尼",
    },
  ],
  "/mathematics/concepts/dynamical-systems": [
    {
      url: "/mathematics/mathematicians/mirzakhani",
      title: "米尔扎哈尼",
    },
  ],
  "/mathematics/concepts/function": [
    {
      url: "/mathematics/concepts/trigonometry",
      title: "三角函数",
    },
  ],
  "/mathematics/concepts/group": [
    {
      url: "/mathematics/mathematicians/abel",
      title: "阿贝尔",
    },
  ],
  "/mathematics/concepts/integral": [
    {
      url: "/mathematics/mathematicians/liu-hui",
      title: "刘徽",
    },
  ],
  "/mathematics/concepts/limit": [
    {
      url: "/mathematics/concepts/function",
      title: "函数",
    },
    {
      url: "/mathematics/mathematicians/liu-hui",
      title: "刘徽",
    },
  ],
  "/mathematics/concepts/linear-algebra": [
    {
      url: "/mathematics/concepts/function",
      title: "函数",
    },
  ],
  "/mathematics/concepts/manifold": [
    {
      url: "/mathematics/mathematicians/chern",
      title: "陈省身",
    },
  ],
  "/mathematics/concepts/number-theory": [
    {
      url: "/mathematics/mathematicians/abel",
      title: "阿贝尔",
    },
    {
      url: "/mathematics/mathematicians/hua-luogeng",
      title: "华罗庚",
    },
    {
      url: "/mathematics/mathematicians/sophie-germain",
      title: "索菲·热尔曼",
    },
  ],
  "/mathematics/concepts/optimization": [
    {
      url: "/mathematics/mathematicians/hua-luogeng",
      title: "华罗庚",
    },
  ],
  "/mathematics/concepts/pde": [
    {
      url: "/mathematics/mathematicians/sophie-germain",
      title: "索菲·热尔曼",
    },
  ],
  "/mathematics/concepts/set-theory": [
    {
      url: "/mathematics/concepts/function",
      title: "函数",
    },
  ],
  "/mathematics/concepts/signal-processing": [
    {
      url: "/mathematics/concepts/trigonometry",
      title: "三角函数",
    },
  ],
  "/mathematics/concepts/topology": [
    {
      url: "/mathematics/mathematicians/chern",
      title: "陈省身",
    },
    {
      url: "/mathematics/mathematicians/mirzakhani",
      title: "米尔扎哈尼",
    },
  ],
  "/mathematics/concepts/trigonometry": [
    {
      url: "/mathematics/concepts/complex-number",
      title: "复数",
    },
  ],
  "/mathematics/mathematicians/archimedes": [
    {
      url: "/mathematics/mathematicians/liu-hui",
      title: "刘徽",
    },
  ],
  "/mathematics/mathematicians/euler": [
    {
      url: "/mathematics/concepts/complex-number",
      title: "复数",
    },
  ],
  "/mathematics/mathematicians/fermat": [
    {
      url: "/mathematics/mathematicians/sophie-germain",
      title: "索菲·热尔曼",
    },
  ],
  "/mathematics/mathematicians/galois": [
    {
      url: "/mathematics/mathematicians/abel",
      title: "阿贝尔",
    },
  ],
  "/mathematics/mathematicians/grothendieck": [
    {
      url: "/mathematics/mathematicians/chern",
      title: "陈省身",
    },
  ],
  "/mathematics/mathematicians/hua-luogeng": [
    {
      url: "/mathematics/mathematicians/liu-hui",
      title: "刘徽",
    },
  ],
  "/mathematics/mathematicians/noether": [
    {
      url: "/mathematics/mathematicians/sophie-germain",
      title: "索菲·热尔曼",
    },
  ],
  "/mathematics/mathematicians/riemann": [
    {
      url: "/mathematics/mathematicians/hua-luogeng",
      title: "华罗庚",
    },
    {
      url: "/mathematics/mathematicians/mirzakhani",
      title: "米尔扎哈尼",
    },
  ],
  "/political-science/concepts/citizenship-rights": [
    {
      url: "/political-science/concepts/power",
      title: "权力",
    },
    {
      url: "/political-science/frontier/ai-governance-surveillance",
      title: "AI、算法治理与监控的政治",
    },
  ],
  "/political-science/concepts/hegemony": [
    {
      url: "/political-science/concepts/civil-society",
      title: "公民社会",
    },
  ],
  "/political-science/concepts/justice": [
    {
      url: "/political-science/institutions/rule-of-law",
      title: "法治",
    },
    {
      url: "/political-science/concepts/citizenship-rights",
      title: "公民身份与权利",
    },
    {
      url: "/political-science/institutions/constitutionalism-separation-of-powers",
      title: "宪政与分权",
    },
  ],
  "/political-science/concepts/legitimacy": [
    {
      url: "/political-science/concepts/citizenship-rights",
      title: "公民身份与权利",
    },
    {
      url: "/political-science/concepts/the-state",
      title: "国家",
    },
    {
      url: "/political-science/concepts/justice",
      title: "正义",
    },
    {
      url: "/political-science/concepts/sovereignty",
      title: "主权",
    },
  ],
  "/political-science/concepts/sovereignty": [
    {
      url: "/political-science/concepts/the-state",
      title: "国家",
    },
    {
      url: "/political-science/thinkers/carl-schmitt",
      title: "卡尔·施密特",
    },
    {
      url: "/political-science/international-relations/global-governance",
      title: "全球治理：联合国、WTO 与 IMF",
    },
    {
      url: "/political-science/thinkers/thomas-hobbes",
      title: "托马斯·霍布斯",
    },
  ],
  "/political-science/concepts/the-state": [
    {
      url: "/political-science/concepts/legitimacy",
      title: "合法性与正当性",
    },
  ],
  "/political-science/frontier/ai-governance-surveillance": [
    {
      url: "/political-science/frontier/populism-polarization",
      title: "民粹主义与政治极化的成因之争",
    },
  ],
  "/political-science/frontier/democratic-backsliding": [
    {
      url: "/political-science/frontier/populism-polarization",
      title: "民粹主义与政治极化的成因之争",
    },
    {
      url: "/political-science/frontier/global-governance-crisis",
      title: "全球治理的危机与改革",
    },
    {
      url: "/political-science/institutions/electoral-systems",
      title: "选举制度：多数制与比例制",
    },
    {
      url: "/political-science/frontier/ai-governance-surveillance",
      title: "AI、算法治理与监控的政治",
    },
  ],
  "/political-science/frontier/global-governance-crisis": [
    {
      url: "/political-science/frontier/multipolar-world",
      title: "多极世界与中美战略竞争",
    },
    {
      url: "/political-science/frontier/democratic-backsliding",
      title: "民主衰退：指标、争论与路径",
    },
    {
      url: "/political-science/international-relations/global-governance",
      title: "全球治理：联合国、WTO 与 IMF",
    },
    {
      url: "/political-science/frontier/ai-governance-surveillance",
      title: "AI、算法治理与监控的政治",
    },
  ],
  "/political-science/frontier/multipolar-world": [
    {
      url: "/political-science/international-relations/international-order-hegemony",
      title: "国际秩序与霸权",
    },
    {
      url: "/political-science/frontier/global-governance-crisis",
      title: "全球治理的危机与改革",
    },
  ],
  "/political-science/frontier/populism-polarization": [
    {
      url: "/political-science/frontier/democratic-backsliding",
      title: "民主衰退：指标、争论与路径",
    },
  ],
  "/political-science/institutions/bureaucracy": [
    {
      url: "/political-science/institutions/ombudsman-institutions",
      title: "监察专员制度",
    },
    {
      url: "/political-science/institutions/executive-power",
      title: "行政权与行政首长",
    },
  ],
  "/political-science/institutions/constitutionalism-separation-of-powers": [
    {
      url: "/political-science/institutions/impeachment-and-recall",
      title: "弹劾与罢免",
    },
    {
      url: "/political-science/institutions/rule-of-law",
      title: "法治",
    },
    {
      url: "/political-science/institutions/monarchy",
      title: "君主制",
    },
    {
      url: "/political-science/institutions/federalism",
      title: "联邦制与单一制",
    },
    {
      url: "/political-science/institutions/the-electoral-college",
      title: "美国选举人团制度",
    },
    {
      url: "/political-science/institutions/democracy-authoritarianism",
      title: "民主与威权",
    },
    {
      url: "/political-science/institutions/theocracy",
      title: "神权政治",
    },
    {
      url: "/political-science/institutions/judiciary-and-judicial-review",
      title: "司法机构与司法审查",
    },
    {
      url: "/political-science/institutions/constitutional-courts",
      title: "宪法法院与违宪审查",
    },
    {
      url: "/political-science/institutions/executive-power",
      title: "行政权与行政首长",
    },
    {
      url: "/political-science/institutions/central-bank-independence",
      title: "央行独立性",
    },
    {
      url: "/political-science/institutions/parliamentary-presidential",
      title: "议会制与总统制",
    },
  ],
  "/political-science/institutions/democracy-authoritarianism": [
    {
      url: "/political-science/institutions/impeachment-and-recall",
      title: "弹劾与罢免",
    },
    {
      url: "/political-science/institutions/local-and-municipal-government",
      title: "地方与市政政府",
    },
    {
      url: "/political-science/institutions/referendums-and-direct-democracy",
      title: "公民投票与直接民主",
    },
    {
      url: "/political-science/institutions/bureaucracy",
      title: "官僚制与行政国家",
    },
    {
      url: "/political-science/international-relations/human-rights-regime",
      title: "国际人权体系",
    },
    {
      url: "/political-science/concepts/the-state",
      title: "国家",
    },
    {
      url: "/political-science/institutions/monarchy",
      title: "君主制",
    },
    {
      url: "/political-science/institutions/interest-groups-and-lobbying",
      title: "利益集团与游说",
    },
    {
      url: "/political-science/institutions/theocracy",
      title: "神权政治",
    },
    {
      url: "/political-science/institutions/judiciary-and-judicial-review",
      title: "司法机构与司法审查",
    },
    {
      url: "/political-science/institutions/constitutionalism-separation-of-powers",
      title: "宪政与分权",
    },
    {
      url: "/political-science/institutions/electoral-systems",
      title: "选举制度：多数制与比例制",
    },
    {
      url: "/political-science/institutions/one-party-states",
      title: "一党制国家",
    },
    {
      url: "/political-science/institutions/political-parties",
      title: "政党与政党制度",
    },
  ],
  "/political-science/institutions/electoral-systems": [
    {
      url: "/political-science/institutions/referendums-and-direct-democracy",
      title: "公民投票与直接民主",
    },
    {
      url: "/political-science/institutions/legislatures",
      title: "立法机构",
    },
    {
      url: "/political-science/institutions/coalition-government",
      title: "联合政府",
    },
    {
      url: "/political-science/institutions/the-electoral-college",
      title: "美国选举人团制度",
    },
    {
      url: "/political-science/frontier/populism-polarization",
      title: "民粹主义与政治极化的成因之争",
    },
    {
      url: "/political-science/frontier/democratic-backsliding",
      title: "民主衰退：指标、争论与路径",
    },
    {
      url: "/political-science/institutions/democracy-authoritarianism",
      title: "民主与威权",
    },
    {
      url: "/political-science/institutions/parliamentary-presidential",
      title: "议会制与总统制",
    },
    {
      url: "/political-science/institutions/political-parties",
      title: "政党与政党制度",
    },
  ],
  "/political-science/institutions/executive-power": [
    {
      url: "/political-science/institutions/impeachment-and-recall",
      title: "弹劾与罢免",
    },
    {
      url: "/political-science/institutions/bureaucracy",
      title: "官僚制与行政国家",
    },
  ],
  "/political-science/institutions/federalism": [
    {
      url: "/political-science/institutions/local-and-municipal-government",
      title: "地方与市政政府",
    },
    {
      url: "/political-science/institutions/parliamentary-presidential",
      title: "议会制与总统制",
    },
  ],
  "/political-science/institutions/interest-groups-and-lobbying": [
    {
      url: "/political-science/institutions/local-and-municipal-government",
      title: "地方与市政政府",
    },
  ],
  "/political-science/institutions/judiciary-and-judicial-review": [
    {
      url: "/political-science/institutions/ombudsman-institutions",
      title: "监察专员制度",
    },
    {
      url: "/political-science/institutions/constitutional-courts",
      title: "宪法法院与违宪审查",
    },
  ],
  "/political-science/institutions/legislatures": [
    {
      url: "/political-science/institutions/interest-groups-and-lobbying",
      title: "利益集团与游说",
    },
    {
      url: "/political-science/institutions/political-parties",
      title: "政党与政党制度",
    },
  ],
  "/political-science/institutions/parliamentary-presidential": [
    {
      url: "/political-science/institutions/monarchy",
      title: "君主制",
    },
    {
      url: "/political-science/institutions/legislatures",
      title: "立法机构",
    },
    {
      url: "/political-science/institutions/federalism",
      title: "联邦制与单一制",
    },
    {
      url: "/political-science/institutions/coalition-government",
      title: "联合政府",
    },
    {
      url: "/political-science/institutions/executive-power",
      title: "行政权与行政首长",
    },
    {
      url: "/political-science/institutions/electoral-systems",
      title: "选举制度：多数制与比例制",
    },
  ],
  "/political-science/institutions/political-parties": [
    {
      url: "/political-science/institutions/referendums-and-direct-democracy",
      title: "公民投票与直接民主",
    },
    {
      url: "/political-science/institutions/legislatures",
      title: "立法机构",
    },
    {
      url: "/political-science/institutions/interest-groups-and-lobbying",
      title: "利益集团与游说",
    },
    {
      url: "/political-science/institutions/coalition-government",
      title: "联合政府",
    },
    {
      url: "/political-science/institutions/one-party-states",
      title: "一党制国家",
    },
  ],
  "/political-science/institutions/rule-of-law": [
    {
      url: "/political-science/institutions/bureaucracy",
      title: "官僚制与行政国家",
    },
    {
      url: "/political-science/institutions/ombudsman-institutions",
      title: "监察专员制度",
    },
    {
      url: "/political-science/institutions/judiciary-and-judicial-review",
      title: "司法机构与司法审查",
    },
    {
      url: "/political-science/institutions/constitutional-courts",
      title: "宪法法院与违宪审查",
    },
    {
      url: "/political-science/institutions/constitutionalism-separation-of-powers",
      title: "宪政与分权",
    },
    {
      url: "/political-science/institutions/central-bank-independence",
      title: "央行独立性",
    },
  ],
  "/political-science/international-relations/alliances-and-nato": [
    {
      url: "/political-science/international-relations/containment",
      title: "遏制战略",
    },
    {
      url: "/political-science/international-relations/nuclear-deterrence-strategy",
      title: "核威慑战略",
    },
    {
      url: "/political-science/international-relations/balance-of-power",
      title: "均势理论",
    },
  ],
  "/political-science/international-relations/balance-of-power": [
    {
      url: "/political-science/international-relations/nuclear-deterrence-strategy",
      title: "核威慑战略",
    },
    {
      url: "/political-science/international-relations/alliances-and-nato",
      title: "联盟政治与北约",
    },
  ],
  "/political-science/international-relations/constructivism-ir": [
    {
      url: "/political-science/international-relations/realism-ir",
      title: "国际关系：现实主义",
    },
    {
      url: "/political-science/international-relations/liberalism-ir",
      title: "国际关系：自由主义与制度主义",
    },
  ],
  "/political-science/international-relations/containment": [
    {
      url: "/political-science/international-relations/mutually-assured-destruction",
      title: "相互确保毁灭",
    },
  ],
  "/political-science/international-relations/cyber-warfare": [
    {
      url: "/political-science/international-relations/terrorism-and-counterterrorism",
      title: "恐怖主义与反恐",
    },
    {
      url: "/political-science/international-relations/intelligence-and-espionage",
      title: "情报与间谍",
    },
  ],
  "/political-science/international-relations/economic-sanctions": [
    {
      url: "/political-science/international-relations/foreign-aid-and-development",
      title: "对外援助与发展",
    },
  ],
  "/political-science/international-relations/failed-and-fragile-states": [
    {
      url: "/political-science/international-relations/foreign-aid-and-development",
      title: "对外援助与发展",
    },
    {
      url: "/political-science/international-relations/terrorism-and-counterterrorism",
      title: "恐怖主义与反恐",
    },
    {
      url: "/political-science/international-relations/migration-and-refugee-politics",
      title: "移民与难民政治",
    },
  ],
  "/political-science/international-relations/foreign-aid-and-development": [
    {
      url: "/political-science/international-relations/economic-sanctions",
      title: "经济制裁",
    },
    {
      url: "/political-science/international-relations/failed-and-fragile-states",
      title: "失败国家与脆弱国家",
    },
  ],
  "/political-science/international-relations/global-governance": [
    {
      url: "/political-science/international-relations/foreign-aid-and-development",
      title: "对外援助与发展",
    },
    {
      url: "/political-science/international-relations/constructivism-ir",
      title: "国际关系：建构主义",
    },
    {
      url: "/political-science/international-relations/liberalism-ir",
      title: "国际关系：自由主义与制度主义",
    },
    {
      url: "/political-science/institutions/federalism",
      title: "联邦制与单一制",
    },
    {
      url: "/political-science/international-relations/the-un-system",
      title: "联合国体系",
    },
    {
      url: "/political-science/international-relations/trade-politics-and-wto",
      title: "贸易政治与世界贸易组织",
    },
    {
      url: "/political-science/international-relations/regional-organizations",
      title: "区域组织",
    },
    {
      url: "/political-science/frontier/global-governance-crisis",
      title: "全球治理的危机与改革",
    },
    {
      url: "/political-science/isms/green-political-theory",
      title: "生态政治与绿色政治理论",
    },
  ],
  "/political-science/international-relations/human-rights-regime": [
    {
      url: "/political-science/international-relations/international-law",
      title: "国际法",
    },
    {
      url: "/political-science/international-relations/terrorism-and-counterterrorism",
      title: "恐怖主义与反恐",
    },
    {
      url: "/political-science/international-relations/migration-and-refugee-politics",
      title: "移民与难民政治",
    },
    {
      url: "/political-science/international-relations/just-war-theory",
      title: "正义战争理论",
    },
  ],
  "/political-science/international-relations/intelligence-and-espionage": [
    {
      url: "/political-science/international-relations/terrorism-and-counterterrorism",
      title: "恐怖主义与反恐",
    },
    {
      url: "/political-science/international-relations/cyber-warfare",
      title: "网络战争",
    },
  ],
  "/political-science/international-relations/international-law": [
    {
      url: "/political-science/international-relations/human-rights-regime",
      title: "国际人权体系",
    },
    {
      url: "/political-science/international-relations/the-un-system",
      title: "联合国体系",
    },
    {
      url: "/political-science/international-relations/just-war-theory",
      title: "正义战争理论",
    },
  ],
  "/political-science/international-relations/international-order-hegemony": [
    {
      url: "/political-science/international-relations/security-dilemma-war-peace",
      title: "安全困境、战争与和平",
    },
    {
      url: "/political-science/frontier/multipolar-world",
      title: "多极世界与中美战略竞争",
    },
    {
      url: "/political-science/institutions/rule-of-law",
      title: "法治",
    },
    {
      url: "/political-science/concepts/legitimacy",
      title: "合法性与正当性",
    },
    {
      url: "/political-science/international-relations/balance-of-power",
      title: "均势理论",
    },
    {
      url: "/political-science/international-relations/alliances-and-nato",
      title: "联盟政治与北约",
    },
    {
      url: "/political-science/international-relations/trade-politics-and-wto",
      title: "贸易政治与世界贸易组织",
    },
    {
      url: "/political-science/international-relations/global-governance",
      title: "全球治理：联合国、WTO 与 IMF",
    },
  ],
  "/political-science/international-relations/just-war-theory": [
    {
      url: "/political-science/international-relations/international-law",
      title: "国际法",
    },
    {
      url: "/political-science/international-relations/human-rights-regime",
      title: "国际人权体系",
    },
  ],
  "/political-science/international-relations/liberalism-ir": [
    {
      url: "/political-science/international-relations/security-dilemma-war-peace",
      title: "安全困境、战争与和平",
    },
    {
      url: "/political-science/frontier/multipolar-world",
      title: "多极世界与中美战略竞争",
    },
    {
      url: "/political-science/international-relations/realism-ir",
      title: "国际关系：现实主义",
    },
    {
      url: "/political-science/international-relations/international-order-hegemony",
      title: "国际秩序与霸权",
    },
    {
      url: "/political-science/international-relations/trade-politics-and-wto",
      title: "贸易政治与世界贸易组织",
    },
    {
      url: "/political-science/institutions/democracy-authoritarianism",
      title: "民主与威权",
    },
    {
      url: "/political-science/international-relations/regional-organizations",
      title: "区域组织",
    },
    {
      url: "/political-science/concepts/sovereignty",
      title: "主权",
    },
  ],
  "/political-science/international-relations/migration-and-refugee-politics": [
    {
      url: "/political-science/international-relations/failed-and-fragile-states",
      title: "失败国家与脆弱国家",
    },
  ],
  "/political-science/international-relations/mutually-assured-destruction": [
    {
      url: "/political-science/international-relations/containment",
      title: "遏制战略",
    },
    {
      url: "/political-science/international-relations/nuclear-proliferation",
      title: "核扩散",
    },
  ],
  "/political-science/international-relations/nuclear-deterrence-strategy": [
    {
      url: "/political-science/international-relations/alliances-and-nato",
      title: "联盟政治与北约",
    },
    {
      url: "/political-science/international-relations/mutually-assured-destruction",
      title: "相互确保毁灭",
    },
  ],
  "/political-science/international-relations/nuclear-proliferation": [
    {
      url: "/political-science/international-relations/economic-sanctions",
      title: "经济制裁",
    },
    {
      url: "/political-science/international-relations/mutually-assured-destruction",
      title: "相互确保毁灭",
    },
  ],
  "/political-science/international-relations/realism-ir": [
    {
      url: "/political-science/international-relations/security-dilemma-war-peace",
      title: "安全困境、战争与和平",
    },
    {
      url: "/political-science/frontier/multipolar-world",
      title: "多极世界与中美战略竞争",
    },
    {
      url: "/political-science/international-relations/constructivism-ir",
      title: "国际关系：建构主义",
    },
    {
      url: "/political-science/international-relations/liberalism-ir",
      title: "国际关系：自由主义与制度主义",
    },
    {
      url: "/political-science/international-relations/international-order-hegemony",
      title: "国际秩序与霸权",
    },
    {
      url: "/political-science/international-relations/balance-of-power",
      title: "均势理论",
    },
    {
      url: "/political-science/international-relations/just-war-theory",
      title: "正义战争理论",
    },
    {
      url: "/political-science/concepts/sovereignty",
      title: "主权",
    },
  ],
  "/political-science/international-relations/regional-organizations": [
    {
      url: "/political-science/international-relations/nuclear-proliferation",
      title: "核扩散",
    },
  ],
  "/political-science/international-relations/security-dilemma-war-peace": [
    {
      url: "/political-science/international-relations/containment",
      title: "遏制战略",
    },
    {
      url: "/political-science/international-relations/realism-ir",
      title: "国际关系：现实主义",
    },
    {
      url: "/political-science/international-relations/nuclear-deterrence-strategy",
      title: "核威慑战略",
    },
    {
      url: "/political-science/international-relations/cyber-warfare",
      title: "网络战争",
    },
  ],
  "/political-science/international-relations/terrorism-and-counterterrorism": [
    {
      url: "/political-science/international-relations/intelligence-and-espionage",
      title: "情报与间谍",
    },
    {
      url: "/political-science/international-relations/failed-and-fragile-states",
      title: "失败国家与脆弱国家",
    },
    {
      url: "/political-science/international-relations/cyber-warfare",
      title: "网络战争",
    },
  ],
  "/political-science/international-relations/the-un-system": [
    {
      url: "/political-science/international-relations/international-law",
      title: "国际法",
    },
    {
      url: "/political-science/international-relations/migration-and-refugee-politics",
      title: "移民与难民政治",
    },
  ],
  "/political-science/international-relations/trade-politics-and-wto": [
    {
      url: "/political-science/international-relations/regional-organizations",
      title: "区域组织",
    },
  ],
  "/political-science/isms/authoritarianism": [
    {
      url: "/political-science/concepts/democracy",
      title: "民主",
    },
  ],
  "/political-science/isms/populism": [
    {
      url: "/political-science/institutions/democracy-authoritarianism",
      title: "民主与威权",
    },
  ],
  "/political-science/isms/postcolonialism": [
    {
      url: "/political-science/isms/imperialism",
      title: "帝国主义",
    },
    {
      url: "/political-science/isms/communism",
      title: "共产主义",
    },
    {
      url: "/political-science/isms/islamism",
      title: "伊斯兰主义",
    },
  ],
  "/political-science/thinkers/carl-schmitt": [
    {
      url: "/political-science/concepts/the-state",
      title: "国家",
    },
  ],
  "/political-science/thinkers/francis-fukuyama": [
    {
      url: "/political-science/concepts/the-state",
      title: "国家",
    },
  ],
  "/political-science/thinkers/hannah-arendt": [
    {
      url: "/political-science/concepts/citizenship-rights",
      title: "公民身份与权利",
    },
  ],
  "/political-science/thinkers/thomas-hobbes": [
    {
      url: "/political-science/concepts/sovereignty",
      title: "主权",
    },
  ],
  "/universe-physics/frontier/quantum-error-correction": [
    {
      url: "/computer-science/frontier/quantum-algorithms",
      title: "量子算法：Shor 与 Grover 之后的软件边界",
    },
  ],
};

export function getBacklinks(url: string): Backlink[] {
  return BACKLINKS_INDEX[url] ?? [];
}
