export interface DailyEvent {
  month: number;
  day: number;
  year: number;
  title: string;
  description: string;
  url: string;
}

export const PHILOSOPHY_TODAY: DailyEvent[] = [
  { month: 1, day: 1, year: 1818, title: '《弗兰肯斯坦》出版', description: '玛丽·雪莱出版科幻小说鼻祖', url: '/philosophy/thinkers/mary-shelley' },
  { month: 1, day: 2, year: 1873, title: '萨特出生', description: '存在主义哲学家让-保罗·萨特诞生', url: '/philosophy/thinkers/sartre' },
  { month: 1, day: 3, year: 1892, title: '托尔金出生', description: '《魔戒》作者 J.R.R. 托尔金诞生', url: '/philosophy/thinkers/tolkien' },
  { month: 1, day: 5, year: 1928, title: '马尔科姆·X出生', description: '民权运动领袖诞生', url: '/philosophy/thinkers/malcolm-x' },
  { month: 1, day: 7, year: 1891, title: '左拉发表《我控诉》', description: '为德雷福斯案件辩护', url: '/philosophy/thinkers/zola' },
  { month: 1, day: 8, year: 1942, title: '霍金出生', description: '理论物理学家斯蒂芬·霍金诞生', url: '/philosophy/thinkers/hawking' },
  { month: 1, day: 11, year: 1935, title: '爱因斯坦提出EPR悖论', description: '与波多尔斯基、罗森合作提出量子力学不完备性', url: '/philosophy/thinkers/einstein' },
  { month: 1, day: 12, year: 1876, title: '杰克·伦敦出生', description: '美国作家杰克·伦敦诞生', url: '/philosophy/thinkers/jack-london' },
  { month: 1, day: 15, year: 1929, title: '马丁·路德·金出生', description: '民权运动领袖诞生', url: '/philosophy/thinkers/martin-luther-king' },
  { month: 1, day: 18, year: 1882, title: '米尔恩出生', description: '《小熊维尼》作者诞生', url: '/philosophy/thinkers/milne' },
  { month: 1, day: 19, year: 1809, title: '爱伦·坡出生', description: '美国诗人、作家爱伦·坡诞生', url: '/philosophy/thinkers/poe' },
  { month: 1, day: 21, year: 1924, title: '齐泽克出生', description: '斯洛文尼亚哲学家斯拉沃热·齐泽克诞生', url: '/philosophy/thinkers/zizek' },
  { month: 1, day: 22, year: 1788, title: '拜伦出生', description: '英国浪漫主义诗人拜伦勋爵诞生', url: '/philosophy/thinkers/byron' },
  { month: 1, day: 25, year: 1759, title: '罗伯特·彭斯出生', description: '苏格兰民族诗人诞生', url: '/philosophy/thinkers/burns' },
  { month: 1, day: 27, year: 1756, title: '莫扎特出生', description: '音乐天才沃尔夫冈·莫扎特诞生', url: '/philosophy/thinkers/mozart' },
  { month: 1, day: 29, year: 1860, title: '契诃夫出生', description: '俄国剧作家契诃夫诞生', url: '/philosophy/thinkers/chekhov' },
  { month: 1, day: 30, year: 1882, title: '罗斯福出生', description: '美国总统富兰克林·罗斯福诞生', url: '/philosophy/thinkers/roosevelt' },
  { month: 2, day: 1, year: 1901, title: '克拉克·盖博出生', description: '好莱坞传奇演员诞生', url: '/philosophy/thinkersgable' },
  { month: 2, day: 3, year: 1809, title: '门德尔松出生', description: '德国作曲家门德尔松诞生', url: '/philosophy/thinkers/mendelssohn' },
  { month: 2, day: 6, year: 1895, title: '贝比·鲁斯出生', description: '棒球传奇人物诞生', url: '/philosophy/thinkers/ruth' },
  { month: 2, day: 7, year: 1812, title: '狄更斯出生', description: '英国作家查尔斯·狄更斯诞生', url: '/philosophy/thinkers/dickens' },
  { month: 2, day: 9, year: 1881, title: '陀思妥耶夫斯基去世', description: '俄国文学巨匠逝世', url: '/philosophy/thinkers/dostoevsky' },
  { month: 2, day: 11, year: 1847, title: '爱迪生出生', description: '发明家托马斯·爱迪生诞生', url: '/philosophy/thinkers/edison' },
  { month: 2, day: 12, year: 1809, title: '达尔文出生', description: '进化论奠基人查尔斯·达尔文诞生', url: '/philosophy/thinkers/darwin' },
  { month: 2, day: 14, year: 1929, title: '情人节大屠杀', description: '芝加哥黑帮火并事件', url: '/philosophy/thinkers/chicago' },
  { month: 2, day: 15, year: 1564, title: '伽利略出生', description: '现代物理学之父伽利略·伽利莱诞生', url: '/philosophy/thinkers/galileo' },
  { month: 2, day: 18, year: 1898, title: '恩佐·法拉利出生', description: '法拉利汽车创始人诞生', url: '/philosophy/thinkers/ferrari' },
  { month: 2, day: 19, year: 1473, title: '哥白尼出生', description: '日心说创立者尼古拉·哥白尼诞生', url: '/philosophy/thinkers/copernicus' },
  { month: 2, day: 21, year: 1916, title: '哈耶克出生', description: '自由主义经济学家弗里德里希·哈耶克诞生', url: '/philosophy/thinkers/hayek' },
  { month: 2, day: 22, year: 1732, title: '华盛顿出生', description: '美国首任总统乔治·华盛顿诞生', url: '/philosophy/thinkers/washington' },
  { month: 2, day: 24, year: 1955, title: '乔布斯出生', description: '苹果公司创始人史蒂夫·乔布斯诞生', url: '/philosophy/thinkers/jobs' },
  { month: 2, day: 27, year: 1902, title: '斯坦贝克出生', description: '美国作家约翰·斯坦贝克诞生', url: '/philosophy/thinkers/steinbeck' },
  { month: 2, day: 28, year: 1953, title: 'DNA双螺旋结构发现', description: '沃森和克里克发现DNA双螺旋结构', url: '/philosophy/thinkers/watson-crick' },
  { month: 3, day: 2, year: 1904, title: '苏斯博士出生', description: '儿童文学作家诞生', url: '/philosophy/thinkers/seuss' },
  { month: 3, day: 3, year: 1847, title: '贝尔出生', description: '电话发明家亚历山大·贝尔诞生', url: '/philosophy/thinkers/bell' },
  { month: 3, day: 6, year: 1475, title: '米开朗基罗出生', description: '文艺复兴艺术家诞生', url: '/philosophy/thinkers/michelangelo' },
  { month: 3, day: 9, year: 1934, title: '加加林出生', description: '首位进入太空的宇航员诞生', url: '/philosophy/thinkers/gagarin' },
  { month: 3, day: 12, year: 1947, title: '杜鲁门主义', description: '美国冷战政策开始', url: '/philosophy/thinkers/truman' },
  { month: 3, day: 14, year: 1879, title: '爱因斯坦出生', description: '相对论创立者阿尔伯特·爱因斯坦诞生', url: '/philosophy/thinkers/einstein' },
  { month: 3, day: 15, year: -44, title: '凯撒被刺杀', description: '罗马独裁者在元老院遇刺', url: '/philosophy/thinkers/caesar' },
  { month: 3, day: 17, year: 1901, title: '柏林爱乐成立', description: '世界顶级交响乐团成立', url: '/philosophy/thinkers/berlin-philharmonic' },
  { month: 3, day: 18, year: 1932, title: '库布里克出生', description: '电影导演斯坦利·库布里克诞生', url: '/philosophy/thinkers/kubrick' },
  { month: 3, day: 21, year: 1685, title: '巴赫出生', description: '音乐之父约翰·塞巴斯蒂安·巴赫诞生', url: '/philosophy/thinkers/bach' },
  { month: 3, day: 22, year: 1923, title: '马尔克斯出生', description: '魔幻现实主义作家加西亚·马尔克斯诞生', url: '/philosophy/thinkers/marquez' },
  { month: 3, day: 26, year: 1874, title: '罗伯特·弗罗斯特出生', description: '美国诗人罗伯特·弗罗斯特诞生', url: '/philosophy/thinkers/frost' },
  { month: 3, day: 28, year: 1936, title: '阿连德出生', description: '智利总统萨尔瓦多·阿连德诞生', url: '/philosophy/thinkers/allende' },
  { month: 3, day: 31, year: 1596, title: '笛卡尔出生', description: '法国哲学家勒内·笛卡尔诞生', url: '/philosophy/thinkers/descartes' },
  { month: 4, day: 1, year: 1929, title: '米兰·昆德拉出生', description: '捷克作家米兰·昆德拉诞生', url: '/philosophy/thinkers/kundera' },
  { month: 4, day: 2, year: 1805, title: '安徒生出生', description: '童话作家汉斯·安徒生诞生', url: '/philosophy/thinkers/andersen' },
  { month: 4, day: 3, year: 1924, title: '马龙·白兰度出生', description: '好莱坞传奇演员诞生', url: '/philosophy/thinkers/brando' },
  { month: 4, day: 5, year: 1908, title: '赫鲁晓夫出生', description: '苏联领导人赫鲁晓夫诞生', url: '/philosophy/thinkers/khrushchev' },
  { month: 4, day: 9, year: 1821, title: '波德莱尔出生', description: '法国诗人波德莱尔诞生', url: '/philosophy/thinkers/baudelaire' },
  { month: 4, day: 11, year: 1903, title: '赫鲁晓夫出生', description: '苏联领导人赫鲁晓夫诞生', url: '/philosophy/thinkers/khrushchev' },
  { month: 4, day: 13, year: 1743, title: '杰斐逊出生', description: '美国第三任总统托马斯·杰斐逊诞生', url: '/philosophy/thinkers/jefferson' },
  { month: 4, day: 15, year: 1452, title: '达芬奇出生', description: '文艺复兴天才列奥纳多·达芬奇诞生', url: '/philosophy/thinkers/da-vinci' },
  { month: 4, day: 17, year: 1955, title: '《麦田里的守望者》出版', description: 'J.D. 塞林格的小说出版', url: '/philosophy/thinkers/salinger' },
  { month: 4, day: 18, year: 1906, title: '旧金山大地震', description: '美国历史上最严重的自然灾害之一', url: '/philosophy/thinkers/san-francisco' },
  { month: 4, day: 20, year: 1889, title: '希特勒出生', description: '纳粹德国元首阿道夫·希特勒诞生', url: '/philosophy/thinkers/hitler' },
  { month: 4, day: 21, year: -753, title: '罗马建城', description: '传说中罗马城建立之日', url: '/philosophy/thinkers/rome' },
  { month: 4, day: 22, year: 1724, title: '康德出生', description: '德国哲学家伊曼努尔·康德诞生', url: '/philosophy/thinkers/kant' },
  { month: 4, day: 23, year: 1564, title: '莎士比亚出生', description: '英国剧作家威廉·莎士比亚诞生', url: '/philosophy/thinkers/shakespeare' },
  { month: 4, day: 25, year: 1917, title: 'Ella Fitzgerald 出生', description: '爵士乐女王诞生', url: '/philosophy/thinkers/fitzgerald' },
  { month: 4, day: 26, year: 1564, title: '莎士比亚受洗', description: '威廉·莎士比亚受洗记录', url: '/philosophy/thinkers/shakespeare' },
  { month: 4, day: 28, year: 1758, title: '门罗出生', description: '美国第五任总统詹姆斯·门罗诞生', url: '/philosophy/thinkers/monroe' },
  { month: 4, day: 29, year: 1936, title: '祖宾·梅塔出生', description: '印度指挥家祖宾·梅塔诞生', url: '/philosophy/thinkers/mehta' },
  { month: 5, day: 1, year: 1923, title: '《了不起的盖茨比》出版', description: '菲茨杰拉德的小说出版', url: '/philosophy/thinkers/fitzgerald' },
  { month: 5, day: 2, year: 1729, title: '叶卡捷琳娜大帝出生', description: '俄国女沙皇诞生', url: '/philosophy/thinkers/catherine' },
  { month: 5, day: 5, year: 1818, title: '马克思出生', description: '共产主义理论创始人卡尔·马克思诞生', url: '/philosophy/thinkers/marx' },
  { month: 5, day: 6, year: 1856, title: '弗洛伊德出生', description: '精神分析学创始人西格蒙德·弗洛伊德诞生', url: '/philosophy/thinkers/freud' },
  { month: 5, day: 7, year: 1840, title: '柴可夫斯基出生', description: '俄国作曲家柴可夫斯基诞生', url: '/philosophy/thinkers/tchaikovsky' },
  { month: 5, day: 8, year: 1884, title: '杜鲁门出生', description: '美国总统哈里·杜鲁门诞生', url: '/philosophy/thinkers/truman' },
  { month: 5, day: 9, year: 1860, title: '巴里出生', description: '《彼得·潘》作者 J.M. 巴里诞生', url: '/philosophy/thinkers/barrie' },
  { month: 5, day: 11, year: 1904, title: '达利出生', description: '超现实主义画家萨尔瓦多·达利诞生', url: '/philosophy/thinkers/dali' },
  { month: 5, day: 12, year: 1820, title: '南丁格尔出生', description: '现代护理学创始人南丁格尔诞生', url: '/philosophy/thinkers/nightingale' },
  { month: 5, day: 13, year: 1950, title: '斯蒂芬·金出生', description: '恐怖小说大师诞生', url: '/philosophy/thinkers/king' },
  { month: 5, day: 14, year: 1925, title: '《了不起的盖茨比》出版', description: '美国文学经典出版', url: '/philosophy/thinkers/fitzgerald' },
  { month: 5, day: 15, year: 1859, title: '柯南·道尔出生', description: '福尔摩斯之父诞生', url: '/philosophy/thinkers/doyle' },
  { month: 5, day: 18, year: 1920, title: '约翰·保罗二世出生', description: '教皇约翰·保罗二世诞生', url: '/philosophy/thinkers/john-paul-ii' },
  { month: 5, day: 19, year: 1925, title: '马尔科姆·X出生', description: '民权运动领袖马尔科姆·X诞生', url: '/philosophy/thinkers/malcolm-x' },
  { month: 5, day: 20, year: 1799, title: '巴尔扎克出生', description: '法国作家巴尔扎克诞生', url: '/philosophy/thinkers/balzac' },
  { month: 5, day: 21, year: 1921, title: '苏联新经济政策', description: '列宁推行新经济政策', url: '/philosophy/thinkers/lenin' },
  { month: 5, day: 22, year: 1859, title: '柯南·道尔出生', description: '福尔摩斯之父阿瑟·柯南·道尔诞生', url: '/philosophy/thinkers/doyle' },
  { month: 5, day: 23, year: 1921, title: '格里高利·派克出生', description: '好莱坞传奇演员诞生', url: '/philosophy/thinkers/peck' },
  { month: 5, day: 25, year: 1921, title: '杰克·尼克劳斯出生', description: '高尔夫传奇球手诞生', url: '/philosophy/thinkers/nicklaus' },
  { month: 5, day: 26, year: 1907, title: '约翰·韦恩出生', description: '好莱坞西部片明星诞生', url: '/philosophy/thinkers/wayne' },
  { month: 5, day: 27, year: 1923, title: '亨利·基辛格出生', description: '美国国务卿基辛格诞生', url: '/philosophy/thinkers/kissinger' },
  { month: 5, day: 28, year: 1908, title: '伊恩·弗莱明出生', description: '詹姆斯·邦德之父诞生', url: '/philosophy/thinkers/fleming' },
  { month: 5, day: 29, year: 1917, title: '约翰·肯尼迪出生', description: '美国第35任总统诞生', url: '/philosophy/thinkers/kennedy' },
  { month: 5, day: 31, year: 1912, title: '《洛丽塔》作者纳博科夫出生', description: '俄裔美国作家弗拉基米尔·纳博科夫诞生', url: '/philosophy/thinkers/nabokov' },
  { month: 6, day: 1, year: 1926, title: '玛丽莲·梦露出生', description: '好莱坞传奇女星诞生', url: '/philosophy/thinkers/monroe' },
  { month: 6, day: 3, year: 1906, title: '贝克特出生', description: '爱尔兰剧作家塞缪尔·贝克特诞生', url: '/philosophy/thinkers/beckett' },
  { month: 6, day: 5, year: 1928, title: '《美丽新世界》出版', description: '赫胥黎的反乌托邦小说出版', url: '/philosophy/thinkers/huxley' },
  { month: 6, day: 6, year: 1903, title: '阿拉姆·哈恰图良出生', description: '亚美尼亚作曲家诞生', url: '/philosophy/thinkers/khachaturian' },
  { month: 6, day: 7, year: 1917, title: '迪恩·马丁出生', description: '美国歌手、演员诞生', url: '/philosophy/thinkers/martin' },
  { month: 6, day: 9, year: 1963, title: '约翰尼·德普出生', description: '好莱坞演员约翰尼·德普诞生', url: '/philosophy/thinkers/depp' },
  { month: 6, day: 10, year: 1922, title: '朱迪·加兰出生', description: '《绿野仙踪》女主角诞生', url: '/philosophy/thinkers/garland' },
  { month: 6, day: 11, year: 1910, title: '雅克·库斯托出生', description: '海洋探险家诞生', url: '/philosophy/thinkers/cousteau' },
  { month: 6, day: 13, year: 1865, title: '叶芝出生', description: '爱尔兰诗人威廉·巴特勒·叶芝诞生', url: '/philosophy/thinkers/yeats' },
  { month: 6, day: 14, year: 1946, title: '特朗普出生', description: '美国第45任总统唐纳德·特朗普诞生', url: '/philosophy/thinkers/trump' },
  { month: 6, day: 15, year: 1937, title: '《尤利西斯》解禁', description: '乔伊斯的小说在美国解禁', url: '/philosophy/thinkers/joyce' },
  { month: 6, day: 16, year: 1907, title: '杰克·凯鲁亚克出生', description: '垮掉的一代作家诞生', url: '/philosophy/thinkers/kerouac' },
  { month: 6, day: 17, year: 1943, title: '牛顿出生', description: '艾萨克·牛顿诞生（儒略历）', url: '/philosophy/thinkers/newton' },
  { month: 6, day: 18, year: 1942, title: '保罗·麦卡特尼出生', description: '披头士成员保罗·麦卡特尼诞生', url: '/philosophy/thinkers/mccartney' },
  { month: 6, day: 19, year: 1903, title: '卢·格里克出生', description: '棒球传奇人物诞生', url: '/philosophy/thinkers/gehrig' },
  { month: 6, day: 20, year: 1949, title: '莱昂内尔·里奇出生', description: '美国歌手、作曲家诞生', url: '/philosophy/thinkers/ richie' },
  { month: 6, day: 21, year: 1905, title: '萨特出生', description: '存在主义哲学家让-保罗·萨特诞生', url: '/philosophy/thinkers/sartre' },
  { month: 6, day: 22, year: 1906, title: '比利·怀尔德出生', description: '电影导演比利·怀尔德诞生', url: '/philosophy/thinkers/wilder' },
  { month: 6, day: 23, year: 1912, title: '图灵出生', description: '计算机科学之父阿兰·图灵诞生', url: '/philosophy/thinkers/turing' },
  { month: 6, day: 24, year: 1987, title: '梅西出生', description: '足球巨星利昂内尔·梅西诞生', url: '/philosophy/thinkers/messi' },
  { month: 6, day: 25, year: 1903, title: '奥威尔出生', description: '《1984》作者乔治·奥威尔诞生', url: '/philosophy/thinkers/orwell' },
  { month: 6, day: 26, year: 1909, title: '格雷厄姆·格林出生', description: '英国作家格雷厄姆·格林诞生', url: '/philosophy/thinkers/greene' },
  { month: 6, day: 28, year: 1921, title: '《美丽新世界》出版', description: '赫胥黎的反乌托邦小说出版', url: '/philosophy/thinkers/huxley' },
  { month: 6, day: 29, year: 1900, title: '安托万·德·圣-埃克苏佩里出生', description: '《小王子》作者诞生', url: '/philosophy/thinkers/saint-exupery' },
  { month: 6, day: 30, year: 1985, title: '迈克尔·菲尔普斯出生', description: '奥运游泳冠军诞生', url: '/philosophy/thinkers/phelps' },
  { month: 7, day: 1, year: 1961, title: '戴安娜王妃出生', description: '英国王妃戴安娜诞生', url: '/philosophy/thinkers/diana' },
  { month: 7, day: 2, year: 1986, title: '林赛·罗韩出生', description: '美国女演员诞生', url: '/philosophy/thinkers/lohan' },
  { month: 7, day: 3, year: 1962, title: '汤姆·克鲁斯出生', description: '好莱坞演员汤姆·克鲁斯诞生', url: '/philosophy/thinkers/cruise' },
  { month: 7, day: 4, year: 1872, title: '卡尔文·柯立芝出生', description: '美国第30任总统诞生', url: '/philosophy/thinkers/coolidge' },
  { month: 7, day: 5, year: 1996, title: '《哈利·波特》出版', description: 'J.K.罗琳的魔法小说出版', url: '/philosophy/thinkers/rowling' },
  { month: 7, day: 6, year: 1946, title: '西尔维斯特·史泰龙出生', description: '好莱坞动作巨星诞生', url: '/philosophy/thinkers/stallone' },
  { month: 7, day: 7, year: 1940, title: '理查德·Star出生', description: '披头士成员理查德·斯塔诞生', url: '/philosophy/thinkers/star' },
  { month: 7, day: 8, year: 1998, title: '《楚门的世界》上映', description: '金·凯瑞主演的电影上映', url: '/philosophy/thinkers/truman-show' },
  { month: 7, day: 9, year: 1947, title: 'O.J.辛普森出生', description: '橄榄球运动员辛普森诞生', url: '/philosophy/thinkers/simpson' },
  { month: 7, day: 10, year: 1856, title: '尼古拉·特斯拉出生', description: '发明家尼古拉·特斯拉诞生', url: '/philosophy/thinkers/tesla' },
  { month: 7, day: 11, year: 1934, title: '乔治亚·奥基夫去世', description: '美国画家乔治亚·奥基夫逝世', url: '/philosophy/thinkers/okeeffe' },
  { month: 7, day: 12, year: 1997, title: '《心灵捕手》上映', description: '马特·达蒙主演的电影上映', url: '/philosophy/thinkers/good-will-hunting' },
  { month: 7, day: 13, year: 1942, title: '哈里森·福特出生', description: '好莱坞演员哈里森·福特诞生', url: '/philosophy/thinkers/ford' },
  { month: 7, day: 14, year: 1918, title: '英格玛·伯格曼出生', description: '瑞典电影导演诞生', url: '/philosophy/thinkers/bergman' },
  { month: 7, day: 15, year: 1961, title: '《局外人》出版', description: '加缪的小说出版', url: '/philosophy/thinkers/camus' },
  { month: 7, day: 16, year: 1941, title: '丹泽尔·华盛顿出生', description: '好莱坞演员丹泽尔·华盛顿诞生', url: '/philosophy/thinkers/washington' },
  { month: 7, day: 17, year: 1935, title: '唐纳德·萨瑟兰出生', description: '加拿大演员诞生', url: '/philosophy/thinkers/sutherland' },
  { month: 7, day: 18, year: 1918, title: '纳尔逊·曼德拉出生', description: '南非反种族隔离领袖诞生', url: '/philosophy/thinkers/mandela' },
  { month: 7, day: 19, year: 1947, title: '布莱恩·梅出生', description: '皇后乐队吉他手诞生', url: '/philosophy/thinkers/may' },
  { month: 7, day: 20, year: 1938, title: '娜塔莉·伍德出生', description: '好莱坞女演员诞生', url: '/philosophy/thinkers/wood' },
  { month: 7, day: 21, year: 1951, title: '罗宾·威廉姆斯出生', description: '喜剧演员罗宾·威廉姆斯诞生', url: '/philosophy/thinkers/williams' },
  { month: 7, day: 22, year: 1992, title: '赛琳娜·戈麦斯出生', description: '美国歌手、演员诞生', url: '/philosophy/thinkers/gomez' },
  { month: 7, day: 23, year: 1989, title: '丹尼尔·雷德克里夫出生', description: '哈利·波特演员诞生', url: '/philosophy/thinkers/radcliffe' },
  { month: 7, day: 24, year: 1969, title: '詹妮弗·洛佩兹出生', description: '美国歌手、演员诞生', url: '/philosophy/thinkers/lopez' },
  { month: 7, day: 25, year: 1965, title: '马特·勒布朗出生', description: '《老友记》演员诞生', url: '/philosophy/thinkers/leblanc' },
  { month: 7, day: 26, year: 1943, title: '米克·贾格尔出生', description: '滚石乐队主唱诞生', url: '/philosophy/thinkers/jagger' },
  { month: 7, day: 27, year: 1948, title: '贝蒂·戴维斯去世', description: '好莱坞传奇女星逝世', url: '/philosophy/thinkers/davis' },
  { month: 7, day: 28, year: 1929, title: '杰奎琳·肯尼迪出生', description: '美国第一夫人诞生', url: '/philosophy/thinkers/kennedy' },
  { month: 7, day: 29, year: 1981, title: '费尔南多·阿隆索出生', description: 'F1赛车手诞生', url: '/philosophy/thinkers/alonso' },
  { month: 7, day: 30, year: 1947, title: '阿诺德·施瓦辛格出生', description: '好莱坞动作巨星诞生', url: '/philosophy/thinkers/schwarzenegger' },
  { month: 7, day: 31, year: 1965, title: 'J.K.罗琳出生', description: '《哈利·波特》作者诞生', url: '/philosophy/thinkers/rowling' },
  { month: 8, day: 1, year: 1936, title: '伊夫·圣罗兰出生', description: '时尚设计师诞生', url: '/philosophy/thinkers/saint-laurent' },
  { month: 8, day: 2, year: 1924, title: '詹姆斯·鲍德温出生', description: '美国作家、民权活动家诞生', url: '/philosophy/thinkers/baldwin' },
  { month: 8, day: 3, year: 1940, title: '马丁·辛出生', description: '好莱坞演员马丁·辛诞生', url: '/philosophy/thinkers/sheen' },
  { month: 8, day: 4, year: 1961, title: '巴拉克·奥巴马出生', description: '美国第44任总统诞生', url: '/philosophy/thinkers/obama' },
  { month: 8, day: 5, year: 1930, title: '尼尔·阿姆斯特朗出生', description: '首位登月宇航员诞生', url: '/philosophy/thinkers/armstrong' },
  { month: 8, day: 6, year: 1911, title: '露西尔·鲍尔出生', description: '美国喜剧女演员诞生', url: '/philosophy/thinkers/ball' },
  { month: 8, day: 7, year: 1975, title: '查理兹·塞隆出生', description: '南非女演员诞生', url: '/philosophy/thinkers/theron' },
  { month: 8, day: 8, year: 1981, title: '罗杰·费德勒出生', description: '网球传奇罗杰·费德勒诞生', url: '/philosophy/thinkers/federer' },
  { month: 8, day: 9, year: 1963, title: '惠特尼·休斯顿出生', description: '美国歌手惠特尼·休斯顿诞生', url: '/philosophy/thinkers/houston' },
  { month: 8, day: 10, year: 1928, title: '艾迪·费舍出生', description: '美国歌手、演员诞生', url: '/philosophy/thinkers/fisher' },
  { month: 8, day: 11, year: 1950, title: '史蒂夫·沃兹尼亚克出生', description: '苹果联合创始人诞生', url: '/philosophy/thinkers/wozniak' },
  { month: 8, day: 12, year: 1990, title: '马里奥·巴洛特利出生', description: '意大利足球运动员诞生', url: '/philosophy/thinkers/balotelli' },
  { month: 8, day: 13, year: 1926, title: '菲德尔·卡斯特罗出生', description: '古巴革命领袖诞生', url: '/philosophy/thinkers/castro' },
  { month: 8, day: 14, year: 1945, title: '史蒂夫·马丁出生', description: '美国喜剧演员、作家诞生', url: '/philosophy/thinkers/martin' },
  { month: 8, day: 15, year: 1972, title: '本·阿弗莱克出生', description: '好莱坞演员、导演诞生', url: '/philosophy/thinkersaffleck' },
  { month: 8, day: 16, year: 1958, title: '麦当娜出生', description: '流行音乐女王诞生', url: '/philosophy/thinkers/madonna' },
  { month: 8, day: 17, year: 1943, title: '罗伯特·德尼罗出生', description: '好莱坞传奇演员诞生', url: '/philosophy/thinkersdeniro' },
  { month: 8, day: 18, year: 1936, title: '罗伯特·雷德福出生', description: '好莱坞演员、导演诞生', url: '/philosophy/thinkers/redford' },
  { month: 8, day: 19, year: 1946, title: '比尔·克林顿出生', description: '美国第42任总统诞生', url: '/philosophy/thinkers/clinton' },
  { month: 8, day: 20, year: 1948, title: '罗伯特·普兰特出生', description: '齐柏林飞艇乐队主唱诞生', url: '/philosophy/thinkers/plant' },
  { month: 8, day: 21, year: 1938, title: '肯尼·罗杰斯出生', description: '美国乡村歌手诞生', url: '/philosophy/thinkers/rogers' },
  { month: 8, day: 22, year: 1920, title: '雷·布莱德伯里出生', description: '科幻作家雷·布莱德伯里诞生', url: '/philosophy/thinkers/bradbury' },
  { month: 8, day: 23, year: 1978, title: '科比·布莱恩特出生', description: '篮球传奇科比·布莱恩特诞生', url: '/philosophy/thinkers/bryant' },
  { month: 8, day: 24, year: 1947, title: '保拉·阿卜杜勒出生', description: '美国歌手、舞者诞生', url: '/philosophy/thinkers/abdul' },
  { month: 8, day: 25, year: 1918, title: '伦纳德·伯恩斯坦出生', description: '美国作曲家、指挥家诞生', url: '/philosophy/thinkers/bernstein' },
  { month: 8, day: 26, year: 1910, title: '特蕾莎修女出生', description: '诺贝尔和平奖得主诞生', url: '/philosophy/thinkers/mother-teresa' },
  { month: 8, day: 27, year: 1908, title: '林登·约翰逊出生', description: '美国第36任总统诞生', url: '/philosophy/thinkers/johnson' },
  { month: 8, day: 28, year: 1969, title: '杰克·布莱克出生', description: '美国喜剧演员诞生', url: '/philosophy/thinkers/black' },
  { month: 8, day: 29, year: 1958, title: '迈克尔·杰克逊出生', description: '流行音乐之王诞生', url: '/philosophy/thinkers/jackson' },
  { month: 8, day: 30, year: 1930, title: '沃伦·巴菲特出生', description: '投资大师巴菲特诞生', url: '/philosophy/thinkers/buffett' },
  { month: 8, day: 31, year: 1945, title: '范·莫里森出生', description: '爱尔兰歌手、作曲家诞生', url: '/philosophy/thinkers/morrison' },
  { month: 9, day: 1, year: 1946, title: '罗西·奥唐纳出生', description: '美国喜剧女演员诞生', url: '/philosophy/thinkers/odonnell' },
  { month: 9, day: 2, year: 1964, title: '基努·里维斯出生', description: '好莱坞演员基努·里维斯诞生', url: '/philosophy/thinkers/reeves' },
  { month: 9, day: 3, year: 1965, title: '查理·辛出生', description: '好莱坞演员查理·辛诞生', url: '/philosophy/thinkers/sheen-jr' },
  { month: 9, day: 4, year: 1981, title: '碧昂丝出生', description: '美国歌手碧昂丝诞生', url: '/philosophy/thinkers/beyonce' },
  { month: 9, day: 5, year: 1946, title: '弗莱迪·默丘里出生', description: '皇后乐队主唱诞生', url: '/philosophy/thinkers/mercury' },
  { month: 9, day: 6, year: 1972, title: '伊德瑞斯·艾尔巴出生', description: '英国演员诞生', url: '/philosophy/thinkers/elba' },
  { month: 9, day: 7, year: 1936, title: '巴迪·霍利出生', description: '摇滚先驱巴迪·霍利诞生', url: '/philosophy/thinkers/holly' },
  { month: 9, day: 8, year: 1941, title: '伯尼·桑德斯出生', description: '美国参议员桑德斯诞生', url: '/philosophy/thinkers/sanders' },
  { month: 9, day: 9, year: 1966, title: '亚当·桑德勒出生', description: '美国喜剧演员诞生', url: '/philosophy/thinkers/sandler' },
  { month: 9, day: 10, year: 1960, title: '科林·费尔斯出生', description: '英国演员科林·费尔斯诞生', url: '/philosophy/thinkers/firth' },
  { month: 9, day: 11, year: 1967, title: '哈里·康尼克 Jr. 出生', description: '美国歌手、演员诞生', url: '/philosophy/thinkers/connick' },
  { month: 9, day: 12, year: 1973, title: '保罗·沃克出生', description: '好莱坞演员保罗·沃克诞生', url: '/philosophy/thinkers/walker' },
  { month: 9, day: 13, year: 1916, title: '罗尔德·达尔出生', description: '儿童文学作家诞生', url: '/philosophy/thinkers/dahl' },
  { month: 9, day: 14, year: 1983, title: '艾米·怀恩豪斯出生', description: '英国歌手艾米·怀恩豪斯诞生', url: '/philosophy/thinkers/winehouse' },
  { month: 9, day: 15, year: 1984, title: '哈里王子出生', description: '英国王子哈里诞生', url: '/philosophy/thinkers/prince-harry' },
  { month: 9, day: 16, year: 1925, title: 'B.B. King 出生', description: '蓝调之王诞生', url: '/philosophy/thinkers/bb-king' },
  { month: 9, day: 17, year: 1931, title: '安妮·班克罗夫特出生', description: '好莱坞女演员诞生', url: '/philosophy/thinkers/bancroft' },
  { month: 9, day: 18, year: 1905, title: '格蕾塔·嘉宝出生', description: '好莱坞传奇女星诞生', url: '/philosophy/thinkers/garbo' },
  { month: 9, day: 19, year: 1928, title: '亚当·威est出生', description: '美国演员诞生', url: '/philosophy/thinkers/west' },
  { month: 9, day: 20, year: 1934, title: '索菲亚·罗兰出生', description: '意大利女演员索菲亚·罗兰诞生', url: '/philosophy/thinkers/loren' },
  { month: 9, day: 21, year: 1947, title: '斯蒂芬·金出生', description: '恐怖小说大师斯蒂芬·金诞生', url: '/philosophy/thinkers/king' },
  { month: 9, day: 22, year: 1958, title: '安德rea·波切利出生', description: '意大利盲人歌唱家诞生', url: '/philosophy/thinkers/bocelli' },
  { month: 9, day: 23, year: 1949, title: '布鲁斯·斯普林斯汀出生', description: '美国摇滚歌手诞生', url: '/philosophy/thinkers/springsteen' },
  { month: 9, day: 24, year: 1936, title: '吉姆·亨森出生', description: '布偶之父诞生', url: '/philosophy/thinkers/henson' },
  { month: 9, day: 25, year: 1968, title: '威尔·史密斯出生', description: '好莱坞演员威尔·史密斯诞生', url: '/philosophy/thinkers/smith' },
  { month: 9, day: 26, year: 1981, title: '赛琳娜·威廉姆斯出生', description: '网球巨星小威廉姆斯诞生', url: '/philosophy/thinkers/williams-s' },
  { month: 9, day: 27, year: 1972, title: '格温妮丝·帕特洛出生', description: '好莱坞女演员诞生', url: '/philosophy/thinkers/paltrow' },
  { month: 9, day: 28, year: 1968, title: '米拉·乔沃维奇出生', description: '乌克兰裔美国女演员诞生', url: '/philosophy/thinkers/jovovich' },
  { month: 9, day: 29, year: 1988, title: '凯文·杜兰特出生', description: 'NBA球星杜兰特诞生', url: '/philosophy/thinkers/durant' },
  { month: 9, day: 30, year: 1921, title: '德博拉·克尔出生', description: '英国女演员诞生', url: '/philosophy/thinkers/kerr' },
  { month: 10, day: 1, year: 1924, title: '吉米·卡特出生', description: '美国第39任总统诞生', url: '/philosophy/thinkers/carter' },
  { month: 10, day: 2, year: 1869, title: '甘地出生', description: '印度独立运动领袖圣雄甘地诞生', url: '/philosophy/thinkers/gandhi' },
  { month: 10, day: 3, year: 1954, title: '斯蒂奇·斯蒂奇出生', description: '美国演员诞生', url: '/philosophy/thinkers/stiers' },
  { month: 10, day: 4, year: 1946, title: '苏珊·萨兰登出生', description: '好莱坞女演员诞生', url: '/philosophy/thinkers/sarandon' },
  { month: 10, day: 5, year: 1975, title: '凯特·温斯莱特出生', description: '英国女演员凯特·温斯莱特诞生', url: '/philosophy/thinkers/winslet' },
  { month: 10, day: 6, year: 1946, title: '托尼·亚当斯出生', description: '英国足球运动员诞生', url: '/philosophy/thinkers/adams' },
  { month: 10, day: 7, year: 1952, title: '弗拉基米尔·普京出生', description: '俄罗斯总统普京诞生', url: '/philosophy/thinkers/putin' },
  { month: 10, day: 8, year: 1943, title: 'R.L.斯蒂恩出生', description: '美国作家 R.L.斯蒂恩诞生', url: '/philosophy/thinkers/stine' },
  { month: 10, day: 9, year: 1940, title: '约翰·列侬出生', description: '披头士成员约翰·列侬诞生', url: '/philosophy/thinkers/lennon' },
  { month: 10, day: 10, year: 1930, title: '哈罗德·品特出生', description: '英国剧作家哈罗德·品特诞生', url: '/philosophy/thinkers/pinter' },
  { month: 10, day: 11, year: 1942, title: '阿米塔布·巴强出生', description: '印度电影巨星诞生', url: '/philosophy/thinkers/bachchan' },
  { month: 10, day: 12, year: 1968, title: '休·杰克曼出生', description: '澳大利亚演员休·杰克曼诞生', url: '/philosophy/thinkers/jackman' },
  { month: 10, day: 13, year: 1925, title: '玛格丽特·撒切尔出生', description: '英国首相撒切尔夫人诞生', url: '/philosophy/thinkers/thatcher' },
  { month: 10, day: 14, year: 1940, title: '克利夫·理查德出生', description: '英国歌手诞生', url: '/philosophy/thinkers/richard' },
  { month: 10, day: 15, year: 1943, title: '彭妮·马歇尔出生', description: '美国女演员、导演诞生', url: '/philosophy/thinkers/marshall' },
  { month: 10, day: 16, year: 1947, title: '鲍勃·韦尔出生', description: '感恩而死乐队成员诞生', url: '/philosophy/thinkers/weir' },
  { month: 10, day: 17, year: 1972, title: '埃minem出生', description: '美国说唱歌手埃minem诞生', url: '/philosophy/thinkers/eminem' },
  { month: 10, day: 18, year: 1926, title: '查克·贝里出生', description: '摇滚乐之父查克·贝里诞生', url: '/philosophy/thinkers/berry' },
  { month: 10, day: 19, year: 1962, title: '特雷acy·查普曼出生', description: '美国歌手、作曲家诞生', url: '/philosophy/thinkers/chapman' },
  { month: 10, day: 20, year: 1958, title: '维iggo Mortensen 出生', description: '丹麦裔美国演员诞生', url: '/philosophy/thinkers/mortensen' },
  { month: 10, day: 21, year: 1942, title: '朱迪·柯林斯出生', description: '美国民谣歌手诞生', url: '/philosophy/thinkers/collins' },
  { month: 10, day: 22, year: 1952, title: '杰夫·高布伦出生', description: '好莱坞演员杰夫·高布伦诞生', url: '/philosophy/thinkers/goldblum' },
  { month: 10, day: 23, year: 1940, title: '贝利出生', description: '足球传奇贝利诞生', url: '/philosophy/thinkers/pele' },
  { month: 10, day: 24, year: 1936, title: '比尔·怀斯出生', description: '美国歌手、作曲家诞生', url: '/philosophy/thinkers/wise' },
  { month: 10, day: 25, year: 1881, title: '毕加索出生', description: '西班牙画家巴勃罗·毕加索诞生', url: '/philosophy/thinkers/picasso' },
  { month: 10, day: 26, year: 1947, title: '希拉里·克林顿出生', description: '美国前国务卿希拉里诞生', url: '/philosophy/thinkers/clinton-h' },
  { month: 10, day: 27, year: 1932, title: '西尔维娅·普拉斯出生', description: '美国诗人西尔维娅·普拉斯诞生', url: '/philosophy/thinkers/plath' },
  { month: 10, day: 28, year: 1955, title: '比尔·盖茨出生', description: '微软创始人比尔·盖茨诞生', url: '/philosophy/thinkers/gates' },
  { month: 10, day: 29, year: 1971, title: '薇诺娜·瑞德出生', description: '好莱坞女演员诞生', url: '/philosophy/thinkers/ryder' },
  { month: 10, day: 30, year: 1935, title: '阿gatha Christie 的《东方快车谋杀案》出版', description: '侦探小说女王作品出版', url: '/philosophy/thinkers/christie' },
  { month: 10, day: 31, year: 1961, title: '彼得·杰克逊出生', description: '《指环王》导演彼得·杰克逊诞生', url: '/philosophy/thinkers/jackson-p' },
  { month: 11, day: 1, year: 1972, title: '艾丽西亚·凯斯出生', description: '美国歌手艾丽西亚·凯斯诞生', url: '/philosophy/thinkers/keys' },
  { month: 11, day: 2, year: 1966, title: '大卫·施维默出生', description: '《老友记》演员大卫·施维默诞生', url: '/philosophy/thinkers/schwimmer' },
  { month: 11, day: 3, year: 1949, title: '安娜·温图尔出生', description: '《Vogue》主编安娜·温图尔诞生', url: '/philosophy/thinkers/wintour' },
  { month: 11, day: 4, year: 1969, title: '马修·麦康纳出生', description: '好莱坞演员马修·麦康纳诞生', url: '/philosophy/thinkers/conaughey' },
  { month: 11, day: 5, year: 1943, title: '山姆·谢泼德出生', description: '美国演员山姆·谢泼德诞生', url: '/philosophy/thinkers/shepard' },
  { month: 11, day: 6, year: 1988, title: '艾玛·斯通出生', description: '好莱坞女演员艾玛·斯通诞生', url: '/philosophy/thinkers/stone' },
  { month: 11, day: 7, year: 1943, title: '乔恩i Mitchell 出生', description: '加拿大歌手、作曲家诞生', url: '/philosophy/thinkers/mitchell' },
  { month: 11, day: 8, year: 1935, title: '阿兰·德龙出生', description: '法国演员阿兰·德龙诞生', url: '/philosophy/thinkers/delon' },
  { month: 11, day: 9, year: 1934, title: '卡尔·萨根出生', description: '天文学家卡尔·萨根诞生', url: '/philosophy/thinkers/sagan' },
  { month: 11, day: 10, year: 1960, title: '尼尔·杨出生', description: '加拿大摇滚歌手尼尔·杨诞生', url: '/philosophy/thinkers/young' },
  { month: 11, day: 11, year: 1922, title: '库尔特·冯内古特出生', description: '美国作家库尔特·冯内古特诞生', url: '/philosophy/thinkers/vonnegut' },
  { month: 11, day: 12, year: 1929, title: '格ace Kelly 出生', description: '好莱坞女演员、摩纳哥王妃诞生', url: '/philosophy/thinkers/kelly' },
  { month: 11, day: 13, year: 1955, title: '乌pi Goldberg 出生', description: '美国喜剧女演员诞生', url: '/philosophy/thinkers/goldberg' },
  { month: 11, day: 14, year: 1954, title: '康doleezza Rice 出生', description: '美国前国务卿康多莉扎·赖斯诞生', url: '/philosophy/thinkers/rice' },
  { month: 11, day: 15, year: 1932, title: '阿laine Delon 出生', description: '法国演员阿兰·德龙诞生', url: '/philosophy/thinkers/delon' },
  { month: 11, day: 16, year: 1958, title: '玛格丽特·米切尔的《飘》出版', description: '美国文学经典出版', url: '/philosophy/thinkers/mitchell-gone' },
  { month: 11, day: 17, year: 1944, title: '丹anny DeVito 出生', description: '美国演员、导演丹anny DeVito诞生', url: '/philosophy/thinkers/devito' },
  { month: 11, day: 18, year: 1939, title: '玛格aret Atwood 出生', description: '加拿大作家玛格丽特·阿特伍德诞生', url: '/philosophy/thinkers/atwood' },
  { month: 11, day: 19, year: 1961, title: '梅格·瑞恩出生', description: '好莱坞女演员梅格·瑞恩诞生', url: '/philosophy/thinkers/ryan' },
  { month: 11, day: 20, year: 1942, title: '乔·拜登出生', description: '美国第46任总统乔·拜登诞生', url: '/philosophy/thinkers/biden' },
  { month: 11, day: 21, year: 1965, title: '比约克出生', description: '冰岛歌手比约克诞生', url: '/philosophy/thinkers/bjork' },
  { month: 11, day: 22, year: 1967, title: '马克·鲁法洛出生', description: '好莱坞演员马克·鲁法洛诞生', url: '/philosophy/thinkers/ruffalo' },
  { month: 11, day: 23, year: 1992, title: '麦莉·赛勒斯出生', description: '美国歌手麦莉·赛勒斯诞生', url: '/philosophy/thinkers/cyrus' },
  { month: 11, day: 24, year: 1946, title: '泰德·邦迪出生', description: '美国连环杀手泰德·邦迪诞生', url: '/philosophy/thinkers/bundy' },
  { month: 11, day: 25, year: 1915, title: '奥gusto Pinochet 出生', description: '智利独裁者皮诺切特诞生', url: '/philosophy/thinkers/pinochet' },
  { month: 11, day: 26, year: 1939, title: '蒂na Turner 出生', description: '美国摇滚女王蒂娜·特纳诞生', url: '/philosophy/thinkers/turner' },
  { month: 11, day: 27, year: 1940, title: '布鲁斯·李出生', description: '武术家、演员李小龙诞生', url: '/philosophy/thinkers/lee' },
  { month: 11, day: 28, year: 1962, title: '乔恩 Stewart 出生', description: '美国喜剧演员、主持人诞生', url: '/philosophy/thinkers/stewart' },
  { month: 11, day: 29, year: 1932, title: '雅克·希拉克出生', description: '法国总统雅克·希拉克诞生', url: '/philosophy/thinkers/chirac' },
  { month: 11, day: 30, year: 1874, title: '丘吉尔出生', description: '英国首相温斯顿·丘吉尔诞生', url: '/philosophy/thinkers/churchill' },
  { month: 12, day: 1, year: 1945, title: '贝蒂·戴维斯获得奥斯卡', description: '好莱坞女星贝蒂·戴维斯获奖', url: '/philosophy/thinkers/davis' },
  { month: 12, day: 2, year: 1981, title: '布兰妮·斯皮尔斯出生', description: '美国流行歌手布兰妮诞生', url: '/philosophy/thinkers/spears' },
  { month: 12, day: 3, year: 1948, title: '奥西·奥斯本出生', description: '重金属歌手奥西·奥斯本诞生', url: '/philosophy/thinkers/osbourne' },
  { month: 12, day: 4, year: 1973, title: '泰拉·班克斯出生', description: '美国超模、电视制作人诞生', url: '/philosophy/thinkers/banks' },
  { month: 12, day: 5, year: 1901, title: '沃alt Disney 出生', description: '迪士尼创始人沃尔特·迪士尼诞生', url: '/philosophy/thinkers/disney' },
  { month: 12, day: 6, year: 1920, title: '戴夫·布鲁贝克出生', description: '美国爵士钢琴家诞生', url: '/philosophy/thinkers/brubeck' },
  { month: 12, day: 7, year: 1956, title: '拉arry Bird 出生', description: 'NBA传奇球星拉里·伯德诞生', url: '/philosophy/thinkers/bird' },
  { month: 12, day: 8, year: 1943, title: '吉米·莫里森出生', description: '大门乐队主唱吉米·莫里森诞生', url: '/philosophy/thinkers/morrison-j' },
  { month: 12, day: 9, year: 1916, title: '柯k Douglas 出生', description: '好莱坞演员柯克·道格拉斯诞生', url: '/philosophy/thinkers/douglas' },
  { month: 12, day: 10, year: 1830, title: '艾米莉·狄金森出生', description: '美国诗人艾米莉·狄金森诞生', url: '/philosophy/thinkers/dickinson' },
  { month: 12, day: 11, year: 1918, title: '亚历山大·索尔仁尼琴出生', description: '俄国作家索尔仁尼琴诞生', url: '/philosophy/thinkers/solzhenitsyn' },
  { month: 12, day: 12, year: 1915, title: '弗兰克·辛纳屈出生', description: '美国歌手弗兰克·辛纳屈诞生', url: '/philosophy/thinkers/sinatra' },
  { month: 12, day: 13, year: 1989, title: '泰勒·斯威夫特出生', description: '美国乡村音乐歌手泰勒·斯威夫特诞生', url: '/philosophy/thinkers/swift' },
  { month: 12, day: 14, year: 1946, title: '帕蒂·史密斯出生', description: '朋克摇滚教母帕蒂·史密斯诞生', url: '/philosophy/thinkers/smith-p' },
  { month: 12, day: 15, year: 1949, title: '唐·约翰逊出生', description: '美国演员唐·约翰逊诞生', url: '/philosophy/thinkers/johnson-d' },
  { month: 12, day: 16, year: 1775, title: '简·奥斯汀出生', description: '英国作家简·奥斯汀诞生', url: '/philosophy/thinkers/austen' },
  { month: 12, day: 17, year: 1936, title: '教皇方济各出生', description: '现任教皇方济各诞生', url: '/philosophy/thinkers/francis' },
  { month: 12, day: 18, year: 1946, title: '史蒂ven Spielberg 出生', description: '好莱坞导演史蒂文·斯皮尔伯格诞生', url: '/philosophy/thinkers/spielberg' },
  { month: 12, day: 19, year: 1944, title: '理查德·利基出生', description: '古人类学家理查德·利基诞生', url: '/philosophy/thinkers/leakey' },
  { month: 12, day: 20, year: 1946, title: '乌ri Geller 出生', description: '以色列魔术师尤里·盖勒诞生', url: '/philosophy/thinkers/geller' },
  { month: 12, day: 21, year: 1940, title: '弗兰克·扎帕出生', description: '美国摇滚音乐家弗兰克·扎帕诞生', url: '/philosophy/thinkers/zappa' },
  { month: 12, day: 22, year: 1949, title: '莫里斯·吉b出', description: '美国歌手、作曲家诞生', url: '/philosophy/thinkers/gibb' },
  { month: 12, day: 23, year: 1935, title: '阿qaba Emperor 出生', description: '日本天皇诞生', url: '/philosophy/thinkers/emperor-akihito' },
  { month: 12, day: 24, year: 1922, title: '阿va Gardner 出生', description: '好莱坞女演员艾娃·加德纳诞生', url: '/philosophy/thinkers/gardner' },
  { month: 12, day: 25, year: 1642, title: '牛顿出生', description: '艾萨克·牛顿诞生（儒略历）', url: '/philosophy/thinkers/newton' },
  { month: 12, day: 26, year: 1893, title: '毛泽东出生', description: '中华人民共和国缔造者毛泽东诞生', url: '/philosophy/thinkers/mao' },
  { month: 12, day: 27, year: 1901, title: '玛lène Dietrich 出生', description: '德国女演员玛琳·黛德丽诞生', url: '/philosophy/thinkers/dietrich' },
  { month: 12, day: 28, year: 1954, title: '丹zel Washington 出生', description: '好莱坞演员丹泽尔·华盛顿诞生', url: '/philosophy/thinkers/washington-d' },
  { month: 12, day: 29, year: 1936, title: '玛丽·泰勒·摩尔出生', description: '美国女演员玛丽·泰勒·摩尔诞生', url: '/philosophy/thinkers/moore' },
  { month: 12, day: 30, year: 1975, title: '泰格·伍兹出生', description: '高尔夫传奇球星泰格·伍兹诞生', url: '/philosophy/thinkers/woods' },
  { month: 12, day: 31, year: 1943, title: '约翰·丹佛出生', description: '美国乡村歌手约翰·丹佛诞生', url: '/philosophy/thinkers/denver' },
];
