export type DailyEvent = {
  year: number;
  month: number;
  day: number;
  title: string;
  description: string;
  url: string;
};

export const PHYSICS_TODAY: DailyEvent[] = [
  { year: 1643, month: 1, day: 4, title: '牛顿出生', description: '艾萨克·牛顿出生于英格兰林肯郡，后来提出了万有引力定律和三大运动定律。', url: '/universe-physics' },
  { year: 1879, month: 3, day: 14, title: '爱因斯坦出生', description: '阿尔伯特·爱因斯坦出生于德国乌尔姆，后来提出了狭义和广义相对论。', url: '/universe-physics' },
  { year: 1905, month: 3, day: 14, title: '爱因斯坦发表狭义相对论', description: '爱因斯坦发表了改变物理学的论文《论动体的电动力学》。', url: '/universe-physics' },
  { year: 2018, month: 3, day: 14, title: '霍金逝世', description: '斯蒂芬·霍金在剑桥去世，享年76岁。他关于黑洞和宇宙起源的研究改变了现代物理学。', url: '/universe-physics' },
  { year: 1990, month: 2, day: 14, title: '旅行者1号拍摄地球照片', description: '旅行者1号在64亿公里外拍摄了著名的"暗淡蓝点"照片。', url: '/universe-physics' },
  { year: 1946, month: 2, day: 14, title: 'ENIAC诞生', description: '世界上第一台通用电子数字计算机ENIAC在宾夕法尼亚大学公布。', url: '/universe-physics' },
  { year: 1880, month: 1, day: 27, title: '爱迪生获得电灯专利', description: 'Thomas Edison获得了实用白炽灯泡的美国专利。', url: '/universe-physics' },
  { year: 1967, month: 1, day: 27, title: '阿波罗1号火灾', description: '三名宇航员在发射台测试中遇难，推动了NASA安全改革。', url: '/universe-physics' },
  { year: 1953, month: 4, day: 25, title: 'DNA双螺旋结构发现', description: '沃森和克里克在《自然》杂志上发表了DNA双螺旋结构的论文。', url: '/universe-physics' },
  { year: 1986, month: 4, day: 26, title: '切尔诺贝利核事故', description: '切尔诺贝利核电站发生史上最严重的核事故。', url: '/universe-physics' },
  { year: 1961, month: 5, day: 5, title: '美国首次载人航天', description: '艾伦·谢泼德成为第一个进入太空的美国人。', url: '/universe-physics' },
  { year: 1936, month: 5, day: 28, title: '图灵提出图灵机', description: '阿兰·图灵发表了关于可计算数的论文，奠定了计算机科学基础。', url: '/universe-physics' },
  { year: 1919, month: 5, day: 29, title: '爱因斯坦广义相对论验证', description: '亚瑟·爱丁顿在日食观测中验证了爱因斯坦广义相对论的预测。', url: '/universe-physics' },
  { year: 1752, month: 6, day: 15, title: '富兰克林风筝实验', description: '本杰明·富兰克林进行了著名的风筝实验，证明了闪电是电。', url: '/universe-physics' },
  { year: 2012, month: 7, day: 4, title: '希格斯玻色子被发现', description: 'CERN宣布发现了希格斯玻色子，证实了标准模型的最后一块拼图。', url: '/universe-physics' },
  { year: 1687, month: 7, day: 5, title: '牛顿发表《原理》', description: '牛顿的划时代巨著《自然哲学的数学原理》正式出版。', url: '/universe-physics' },
  { year: 1969, month: 7, day: 20, title: '人类首次登月', description: '阿波罗11号宇航员尼尔·阿姆斯特朗成为第一个踏上月球的人。', url: '/universe-physics' },
  { year: 1957, month: 10, day: 4, title: '斯普特尼克1号发射', description: '苏联发射了第一颗人造地球卫星，开启了太空时代。', url: '/universe-physics' },
  { year: 1964, month: 10, day: 16, title: '中国第一颗原子弹', description: '中国成功试爆了第一颗原子弹。', url: '/universe-physics' },
  { year: 1947, month: 10, day: 14, title: '查克·耶格尔突破音障', description: '查克·耶格尔驾驶X-1首次突破音障。', url: '/universe-physics' },
  { year: 1609, month: 8, day: 21, title: '伽利略展示望远镜', description: '伽利略向威尼斯商人展示了他的望远镜，开创了天文观测新时代。', url: '/universe-physics' },
  { year: 1831, month: 8, day: 29, title: '法拉第发现电磁感应', description: '迈克尔·法拉第发现了电磁感应现象，奠定了电力时代的基础。', url: '/universe-physics' },
  { year: 1928, month: 9, day: 15, title: '弗莱明发现青霉素', description: '亚历山大·弗莱明发现了青霉素，开创了抗生素时代。', url: '/universe-physics' },
  { year: 1977, month: 9, day: 5, title: '旅行者1号发射', description: 'NASA发射了旅行者1号深空探测器，它是飞得最远的人造物体。', url: '/universe-physics' },
  { year: 1895, month: 11, day: 8, title: '伦琴发现X射线', description: '威廉·伦琴发现了X射线，为医学影像学奠定了基础。', url: '/universe-physics' },
  { year: 1971, month: 11, day: 15, title: '英特尔4004发布', description: '英特尔发布了第一款商用微处理器4004。', url: '/universe-physics' },
  { year: 1968, month: 12, day: 24, title: '阿波罗8号绕月', description: '阿波罗8号成为第一艘绕月飞行的载人飞船。', url: '/universe-physics' },
  { year: 1903, month: 12, day: 17, title: '莱特兄弟首次飞行', description: '莱特兄弟在基蒂霍克实现了人类首次动力飞行。', url: '/universe-physics' },
  { year: 1895, month: 12, day: 28, title: '卢米埃尔兄弟首次放映电影', description: '卢米埃尔兄弟在巴黎进行了首次公开电影放映。', url: '/universe-physics' },
  { year: 1947, month: 12, day: 29, title: '香农发表信息论', description: '克劳德·香农发表了信息论的奠基论文。', url: '/universe-physics' },
  { year: 1887, month: 8, day: 12, title: '薛定谔出生', description: '量子力学奠基人之一埃尔温·薛定谔出生。', url: '/universe-physics' },
  { year: 1949, month: 8, day: 29, title: '苏联第一颗原子弹', description: '苏联成功试爆了第一颗原子弹。', url: '/universe-physics' },
  { year: 1883, month: 8, day: 27, title: '喀拉喀托火山爆发', description: '印尼喀拉喀托火山发生史上最猛烈的火山爆发之一。', url: '/universe-physics' },
  { year: 1959, month: 10, day: 7, title: '月球3号拍到月球背面', description: '苏联月球3号探测器首次拍到了月球背面的照片。', url: '/universe-physics' },
  { year: 1961, month: 10, day: 27, title: '苏联试爆沙皇炸弹', description: '苏联试爆了人类历史上最大的核武器——沙皇炸弹。', url: '/universe-physics' },
  { year: 1955, month: 11, day: 25, title: '爱因斯坦广义相对论', description: '爱因斯坦发表了广义相对论的最终形式。', url: '/universe-physics' },
  { year: 1783, month: 11, day: 21, title: '首次载人热气球飞行', description: '蒙特戈尔菲耶兄弟在巴黎进行了首次载人热气球飞行。', url: '/universe-physics' },
  { year: 1895, month: 11, day: 27, title: '诺贝尔奖设立', description: '阿尔弗雷德·诺贝尔签署遗嘱，设立诺贝尔奖。', url: '/universe-physics' },
  { year: 1901, month: 12, day: 12, title: '马可尼首次跨大西洋无线电传输', description: '古列尔莫·马可尼实现了首次跨大西洋无线电传输。', url: '/universe-physics' },
  { year: 1846, month: 9, day: 23, title: '海王星被发现', description: '天文学家约翰·加勒发现了海王星。', url: '/universe-physics' },
  { year: 1905, month: 9, day: 27, title: '爱因斯坦发表质能方程', description: '爱因斯坦发表了E=mc²质能等价关系。', url: '/universe-physics' },
  { year: 1967, month: 10, day: 18, title: '苏联金星4号', description: '苏联金星4号成为第一个在金星大气层中发送数据的探测器。', url: '/universe-physics' },
  { year: 1954, month: 9, day: 20, title: '第一台计算机FORTRAN', description: 'IBM发布了第一种高级编程语言FORTRAN。', url: '/universe-physics' },
  { year: 1962, month: 9, day: 12, title: '肯尼迪发表登月演说', description: '肯尼迪总统在莱斯大学发表著名的登月演说。', url: '/universe-physics' },
  { year: 1958, month: 9, day: 11, title: '第一款集成电路', description: '杰克·基尔比发明了第一块集成电路。', url: '/universe-physics' },
  { year: 1959, month: 9, day: 14, title: '月球2号撞击月球', description: '苏联月球2号成为第一个到达月球表面的人造物体。', url: '/universe-physics' },
  { year: 1998, month: 9, day: 4, title: '谷歌公司成立', description: '拉里·佩奇和谢尔盖·布林创立了谷歌。', url: '/universe-physics' },
  { year: 1976, month: 9, day: 3, title: '维京2号登陆火星', description: 'NASA的维京2号探测器成功在火星着陆。', url: '/universe-physics' },
  { year: 1945, month: 9, day: 10, title: 'V-2火箭首次发射', description: 'V-2火箭成为第一个到达太空边缘的人造物体。', url: '/universe-physics' },
  { year: 1957, month: 11, day: 3, title: '莱卡太空狗', description: '苏联发射了第一只进入太空的动物——莱卡犬。', url: '/universe-physics' },
  { year: 1971, month: 11, day: 14, title: '水手9号进入火星轨道', description: 'NASA的水手9号成为第一个绕另一颗行星运行的人造卫星。', url: '/universe-physics' },
  { year: 1998, month: 11, day: 20, title: '国际空间站第一个组件', description: '俄罗斯发射了国际空间站的第一个组件——曙光号功能货舱。', url: '/universe-physics' },
  { year: 1969, month: 11, day: 19, title: '阿波罗12号登月', description: '阿波罗12号宇航员在月球着陆。', url: '/universe-physics' },
  { year: 1959, month: 8, day: 7, title: '探索者6号拍地球照片', description: '探索者6号卫星拍摄了第一张从太空看地球的照片。', url: '/universe-physics' },
];
