export interface OnThisDayEvent {
  month: number;
  day: number;
  year: number;
  title: string;
  description: string;
  domain: string;
  domainColor: string;
  url: string;
}

export const ON_THIS_DAY: OnThisDayEvent[] = [
  {
    month: 1,
    day: 1,
    year: 1912,
    title: "中华民国成立",
    description: "孙中山就任临时大总统",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 1,
    day: 4,
    year: 2004,
    title: "勇气号火星车着陆",
    description: "NASA火星探测器成功着陆",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 1,
    day: 15,
    year: 2001,
    title: "维基百科上线",
    description: "免费在线百科全书诞生",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 2,
    day: 1,
    year: 2003,
    title: "哥伦比亚号航天飞机解体",
    description: "返回大气层时失事，7名宇航员遇难",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 2,
    day: 14,
    year: 1990,
    title: '旅行者1号拍摄"暗淡蓝点"',
    description: "从60亿公里外拍摄地球照片",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 3,
    day: 14,
    year: 2018,
    title: "霍金去世",
    description: "理论物理学家斯蒂芬·霍金辞世",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 4,
    day: 12,
    year: 1961,
    title: "加加林首次进入太空",
    description: "人类首次太空飞行",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 4,
    day: 22,
    year: 1970,
    title: "第一个地球日",
    description: "全球环保运动的开端",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 5,
    day: 2,
    year: 1952,
    title: "喷气式客机首航",
    description: "彗星号客机首飞",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 6,
    day: 6,
    year: 1944,
    title: "诺曼底登陆",
    description: "D-Day，盟军登陆法国",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 7,
    day: 20,
    year: 1969,
    title: "阿波罗11号登月",
    description: "人类首次登上月球",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 8,
    day: 6,
    year: 1945,
    title: "广岛原子弹",
    description: "人类首次在战争中使用核武器",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 9,
    day: 11,
    year: 2001,
    title: "九一一事件",
    description: "美国遭受恐怖袭击",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 10,
    day: 1,
    year: 1949,
    title: "中华人民共和国成立",
    description: "毛泽东在天安门城楼宣告",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 11,
    day: 9,
    year: 1989,
    title: "柏林墙倒塌",
    description: "冷战结束的象征",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 12,
    day: 25,
    year: 1991,
    title: "苏联解体",
    description: "戈尔巴乔夫辞职，苏联正式解体",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 1,
    day: 27,
    year: 1945,
    title: "奥斯维辛解放",
    description: "纳粹集中营被苏联红军解放",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 3,
    day: 8,
    year: 1910,
    title: "第一个国际妇女节",
    description: "全球妇女权益运动的里程碑",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 5,
    day: 4,
    year: 1979,
    title: "撒切尔夫人当选",
    description: "英国首位女首相",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 7,
    day: 4,
    year: 1776,
    title: "美国独立宣言",
    description: "美利坚合众国宣告独立",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 9,
    day: 2,
    year: 1945,
    title: "日本投降",
    description: "第二次世界大战正式结束",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 11,
    day: 24,
    year: 1859,
    title: "《物种起源》出版",
    description: "达尔文的进化论改变世界",
    domain: "人类历史",
    domainColor: "#f59e0b",
    url: "/human-history/timeline",
  },
  {
    month: 4,
    day: 26,
    year: 1986,
    title: "切尔诺贝利核事故",
    description: "史上最严重的核电站事故",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 6,
    day: 30,
    year: 1908,
    title: "通古斯大爆炸",
    description: "西伯利亚神秘大爆炸",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 4,
    day: 10,
    year: 1815,
    title: "坦博拉火山喷发",
    description: "VEI-7 喷发，导致 1816「无夏之年」",
    domain: "地球科学",
    domainColor: "#4f9d76",
    url: "/earth-science/events/tambora-1815",
  },
  {
    month: 11,
    day: 1,
    year: 1755,
    title: "里斯本大地震",
    description: "地震、海啸、火灾同袭，催生地震学与启蒙思考",
    domain: "地球科学",
    domainColor: "#4f9d76",
    url: "/earth-science/events/lisbon-1755",
  },
  {
    month: 8,
    day: 27,
    year: 1883,
    title: "喀拉喀托火山爆发",
    description: "爆发声 4800 公里外可闻，海啸夺去数万生命",
    domain: "地球科学",
    domainColor: "#4f9d76",
    url: "/earth-science/events/krakatoa-1883",
  },
  {
    month: 12,
    day: 26,
    year: 2004,
    title: "印度洋大海啸",
    description: "苏门答腊 9.1 级地震引发史上最致命海啸之一",
    domain: "地球科学",
    domainColor: "#4f9d76",
    url: "/earth-science/events/indian-ocean-tsunami-2004",
  },
  {
    month: 12,
    day: 25,
    year: 2021,
    title: "詹姆斯·韦伯空间望远镜发射",
    description: "人类迄今最强大的太空望远镜升空",
    domain: "宇宙学",
    domainColor: "#a88adf",
    url: "/cosmology",
  },
  {
    month: 4,
    day: 24,
    year: 1990,
    title: "哈勃空间望远镜发射",
    description: "改变人类宇宙观的太空之眼",
    domain: "宇宙学",
    domainColor: "#a88adf",
    url: "/cosmology",
  },
  {
    month: 4,
    day: 25,
    year: 1953,
    title: "DNA 双螺旋结构发表",
    description: "沃森与克里克在《自然》揭示遗传密码的形态",
    domain: "生命科学",
    domainColor: "#6bae6b",
    url: "/life-science",
  },
  {
    month: 2,
    day: 12,
    year: 1809,
    title: "达尔文诞生",
    description: "提出自然选择、奠定演化论的博物学家",
    domain: "生命科学",
    domainColor: "#6bae6b",
    url: "/life-science",
  },
  {
    month: 12,
    day: 22,
    year: 1887,
    title: "拉马努金诞生",
    description: "自学成才、直觉惊人的印度数学天才",
    domain: "数学",
    domainColor: "#5fb3a3",
    url: "/mathematics",
  },
  {
    month: 11,
    day: 8,
    year: 1895,
    title: "伦琴发现 X 射线",
    description: "开启医学影像与近代物理的新纪元",
    domain: "宇宙物理",
    domainColor: "#6366f1",
    url: "/universe-physics",
  },
  {
    month: 3,
    day: 9,
    year: 1776,
    title: "《国富论》出版",
    description: "亚当·斯密奠定古典经济学的基石",
    domain: "经济学",
    domainColor: "#c8a45a",
    url: "/economics/economists/adam-smith",
  },
  {
    month: 10,
    day: 29,
    year: 1929,
    title: "黑色星期二",
    description: "美股崩盘，大萧条的标志性一天",
    domain: "经济学",
    domainColor: "#c8a45a",
    url: "/economics/case-studies/great-depression",
  },
  {
    month: 5,
    day: 6,
    year: 1856,
    title: "弗洛伊德诞生",
    description: "精神分析的奠基者，重塑了对无意识的理解",
    domain: "心理学",
    domainColor: "#c678dd",
    url: "/psychology",
  },
  {
    month: 6,
    day: 23,
    year: 1912,
    title: "图灵诞生",
    description: "用一台纸上机器定义了「计算」的边界",
    domain: "计算机科学",
    domainColor: "#4f9cf0",
    url: "/computer-science/pioneers/alan-turing",
  },
  {
    month: 12,
    day: 9,
    year: 1968,
    title: "「演示之母」",
    description: "恩格尔巴特一次演示展现了鼠标、超文本与图形界面",
    domain: "计算机科学",
    domainColor: "#4f9cf0",
    url: "/computer-science/concepts/human-computer-interaction",
  },
  {
    month: 4,
    day: 22,
    year: 1724,
    title: "康德诞生",
    description: "调和理性与经验、重写认识论的哲学巨人",
    domain: "哲学",
    domainColor: "#c8956a",
    url: "/philosophy/thinkers/kant",
  },
];
