// Generated by `pnpm gen-site-stats` (inside gen-all) — the only place the site
// reads counts from. Never print a hand-typed number of articles or entities.
import SITE_STATS from "@/generated/site-stats.json";

export type SiteStatsCollection = { label: string; unit: string; count: number };

export type GraphHub = { label: string; url: string; degree: number };

/** Inline wiki-links crossing to another domain, and the article they most often meet at. */
export type DomainBridge = { domain: string; links: number; via: { title: string; url: string } };

type DomainStats = {
  articles: number;
  collections: SiteStatsCollection[];
  graphNodes: number;
  hubs: GraphHub[];
  bridges: DomainBridge[];
};

const DOMAIN_STATS = SITE_STATS.domains as Record<string, DomainStats>;

export const SITE_TOTALS = {
  domains: SITE_STATS.domainCount,
  articles: SITE_STATS.articles,
  documents: SITE_STATS.documents,
  graphNodes: SITE_STATS.graphNodes,
} as const;

export function getDomainStats(domainId: string): DomainStats {
  return (
    DOMAIN_STATS[domainId] ?? { articles: 0, collections: [], graphNodes: 0, hubs: [], bridges: [] }
  );
}

export function formatCollection({ count, unit, label }: SiteStatsCollection): string {
  return `${count} ${unit}${label}`;
}

/** Looks up one named collection, e.g. `domainCollectionCount("philosophy", "哲学家")`. */
export function domainCollectionCount(domainId: string, label: string): number {
  return getDomainStats(domainId).collections.find((c) => c.label === label)?.count ?? 0;
}
