export const APP_URLS = {
  "universe-physics": "/universe-physics",
  cosmology: "/cosmology",
  "human-history": "/human-history",
  philosophy: "/philosophy",
  "life-science": "/life-science",
  mathematics: "/mathematics",
  economics: "/economics",
  psychology: "/psychology",
  "computer-science": "/computer-science",
  "political-science": "/political-science",
  "earth-science": "/earth-science",
  medicine: "/medicine",
  chemistry: "/chemistry",
  sociology: "/sociology",
  "knowledge-graph": "/knowledge-graph",
} as const;
