import type { CrossLink } from "./types";

export const LINKS_PSYCHOLOGY: CrossLink[] = [
  // Psychology ↔ Philosophy
  {
    sourceApp: "psychology",
    sourceId: "sigmund-freud",
    sourceTitle: "弗洛伊德",
    targetApp: "philosophy",
    targetId: "nietzsche",
    targetTitle: "尼采",
    relationship: "弗洛伊德承认尼采对无意识理论的先见之明",
  },
  {
    sourceApp: "psychology",
    sourceId: "cognitive-dissonance",
    sourceTitle: "认知失调",
    targetApp: "philosophy",
    targetId: "determinism",
    targetTitle: "决定论",
    relationship: "认知失调理论挑战了完全理性决策的决定论观点",
  },
  {
    sourceApp: "psychology",
    sourceId: "positive-psychology",
    sourceTitle: "积极心理学",
    targetApp: "philosophy",
    targetId: "eudaimonia",
    targetTitle: "幸福论",
    relationship: "积极心理学的幸福研究与亚里士多德幸福论的对话",
  },
  {
    sourceApp: "psychology",
    sourceId: "behaviorism",
    sourceTitle: "行为主义",
    targetApp: "philosophy",
    targetId: "philosophy-of-mind",
    targetTitle: "心灵哲学",
    relationship: "行为主义对心灵哲学的还原论挑战",
  },
  {
    sourceApp: "philosophy",
    sourceId: "nietzsche",
    sourceTitle: "尼采",
    targetApp: "psychology",
    targetId: "sigmund-freud",
    targetTitle: "弗洛伊德",
    relationship: "尼采的权力意志理论预见了弗洛伊德的精神分析",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-mind",
    sourceTitle: "心灵哲学",
    targetApp: "psychology",
    targetId: "behaviorism",
    targetTitle: "行为主义",
    relationship: "心灵哲学对行为主义的逻辑批判",
  },

  // Psychology ↔ Human History
  {
    sourceApp: "psychology",
    sourceId: "social-psychology",
    sourceTitle: "社会心理学",
    targetApp: "human-history",
    targetId: "enlightenment",
    targetTitle: "启蒙运动",
    relationship: "启蒙运动对人类理性与社会行为的探讨为社会心理学奠基",
  },
  {
    sourceApp: "psychology",
    sourceId: "cognitive-bias",
    sourceTitle: "认知偏误",
    targetApp: "human-history",
    targetId: "wwii-codebreaking",
    targetTitle: "二战密码破译",
    relationship: "认知偏误研究影响了战时决策分析方法",
  },
  {
    sourceApp: "psychology",
    sourceId: "milgram-experiment",
    sourceTitle: "米尔格拉姆实验",
    targetApp: "human-history",
    targetId: "holocaust",
    targetTitle: "大屠杀",
    relationship: "米尔格拉姆实验揭示了服从权威的心理机制",
  },
  {
    sourceApp: "human-history",
    sourceId: "enlightenment",
    sourceTitle: "启蒙运动",
    targetApp: "psychology",
    targetId: "social-psychology",
    targetTitle: "社会心理学",
    relationship: "启蒙运动的理性人假设影响了社会心理学的发展方向",
  },

  // Psychology ↔ Life Science
  {
    sourceApp: "psychology",
    sourceId: "neuroscience",
    sourceTitle: "神经科学",
    targetApp: "life-science",
    targetId: "consciousness-studies",
    targetTitle: "意识研究",
    relationship: "神经科学为意识研究提供了生物学基础",
  },
  {
    sourceApp: "psychology",
    sourceId: "evolutionary-psychology",
    sourceTitle: "进化心理学",
    targetApp: "life-science",
    targetId: "evolution-theory",
    targetTitle: "进化论",
    relationship: "进化心理学将自然选择理论应用于人类心理机制",
  },
  {
    sourceApp: "psychology",
    sourceId: "neuroscience",
    sourceTitle: "神经科学",
    targetApp: "life-science",
    targetId: "human-evolution",
    targetTitle: "人类进化",
    relationship: "大脑容量的增加是人类进化的关键标志",
  },
  {
    sourceApp: "life-science",
    sourceId: "consciousness-studies",
    sourceTitle: "意识研究",
    targetApp: "psychology",
    targetId: "neuroscience",
    targetTitle: "神经科学",
    relationship: "意识研究依赖神经科学的实验方法",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution-theory",
    sourceTitle: "进化论",
    targetApp: "psychology",
    targetId: "evolutionary-psychology",
    targetTitle: "进化心理学",
    relationship: "进化论为进化心理学提供了理论框架",
  },
  {
    sourceApp: "life-science",
    sourceId: "human-evolution",
    sourceTitle: "人类进化",
    targetApp: "psychology",
    targetId: "neuroscience",
    targetTitle: "神经科学",
    relationship: "人类进化过程中大脑神经结构的演变",
  },

  // Psychology ↔ Mathematics
  {
    sourceApp: "psychology",
    sourceId: "psychometrics",
    sourceTitle: "心理测量学",
    targetApp: "mathematics",
    targetId: "statistics",
    targetTitle: "统计学",
    relationship: "心理测量学依赖统计学方法进行量表开发与验证",
  },
  {
    sourceApp: "mathematics",
    sourceId: "statistics",
    sourceTitle: "统计学",
    targetApp: "psychology",
    targetId: "psychometrics",
    targetTitle: "心理测量学",
    relationship: "统计学为心理测量提供信效度分析方法",
  },

  // Psychoanalysis ↔ Philosophy
  {
    sourceApp: "psychology",
    sourceId: "sigmund-freud",
    sourceTitle: "弗洛伊德",
    targetApp: "philosophy",
    targetId: "schopenhauer",
    targetTitle: "叔本华",
    relationship: "弗洛伊德的无意识理论深受叔本华意志哲学的影响",
  },
  {
    sourceApp: "psychology",
    sourceId: "defense-mechanisms",
    sourceTitle: "防御机制",
    targetApp: "philosophy",
    targetId: "stoicism",
    targetTitle: "斯多葛主义",
    relationship: "斯多葛学派的情绪调节策略与现代防御机制理论的对话",
  },

  // Attachment Theory ↔ Life Science
  {
    sourceApp: "psychology",
    sourceId: "attachment-styles",
    sourceTitle: "依恋类型",
    targetApp: "life-science",
    targetId: "evolution-theory",
    targetTitle: "进化论",
    relationship: "依恋理论的生物学基础源于进化论对亲代投资的解释",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution-theory",
    sourceTitle: "进化论",
    targetApp: "psychology",
    targetId: "attachment-styles",
    targetTitle: "依恋类型",
    relationship: "进化论为依恋行为的适应性功能提供了解释框架",
  },
  {
    sourceApp: "philosophy",
    sourceId: "schopenhauer",
    sourceTitle: "叔本华",
    targetApp: "psychology",
    targetId: "sigmund-freud",
    targetTitle: "弗洛伊德",
    relationship: "叔本华的意志理论为弗洛伊德的力比多概念奠定了哲学基础",
  },
  {
    sourceApp: "philosophy",
    sourceId: "stoicism",
    sourceTitle: "斯多葛主义",
    targetApp: "psychology",
    targetId: "defense-mechanisms",
    targetTitle: "防御机制",
    relationship: "斯多葛哲学中的情感疏离策略可被视为早期防御机制描述",
  },

  // New knowledge-base cross-links
  {
    sourceApp: "psychology",
    sourceId: "neuroplasticity",
    sourceTitle: "神经可塑性",
    targetApp: "life-science",
    targetId: "brain-evolution",
    targetTitle: "大脑进化",
    relationship: "神经可塑性是大脑进化过程中形成的关键适应机制",
  },
  {
    sourceApp: "life-science",
    sourceId: "brain-evolution",
    sourceTitle: "大脑进化",
    targetApp: "psychology",
    targetId: "neuroplasticity",
    targetTitle: "神经可塑性",
    relationship: "大脑进化赋予了人类高度的神经可塑性能力",
  },
  {
    sourceApp: "psychology",
    sourceId: "evolutionary-psychology",
    sourceTitle: "进化心理学",
    targetApp: "life-science",
    targetId: "evolution",
    targetTitle: "进化论",
    relationship: "进化心理学以自然选择理论解释人类心理机制的起源",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution",
    sourceTitle: "进化论",
    targetApp: "psychology",
    targetId: "evolutionary-psychology",
    targetTitle: "进化心理学",
    relationship: "进化论为进化心理学提供了核心理论框架",
  },
  {
    sourceApp: "psychology",
    sourceId: "metacognition",
    sourceTitle: "元认知",
    targetApp: "philosophy",
    targetId: "epistemology",
    targetTitle: "认识论",
    relationship: "元认知研究与认识论共享对知识本质与认知过程的反思",
  },
  {
    sourceApp: "philosophy",
    sourceId: "epistemology",
    sourceTitle: "认识论",
    targetApp: "psychology",
    targetId: "metacognition",
    targetTitle: "元认知",
    relationship: "认识论的哲学传统为元认知研究提供了概念基础",
  },
];
