import type { CrossLink } from "./types";

export const LINKS_ROUND2: CrossLink[] = [
  // History ↔ Life Science (Round 2 expansion)
  {
    sourceApp: "human-history",
    sourceId: "black-death",
    sourceTitle: "黑死病",
    targetApp: "life-science",
    targetId: "plague-bacteriology",
    targetTitle: "鼠疫细菌学",
    relationship: "黑死病的大流行推动了瘟疫细菌学的研究",
  },
  {
    sourceApp: "life-science",
    sourceId: "plague-bacteriology",
    sourceTitle: "鼠疫细菌学",
    targetApp: "human-history",
    targetId: "black-death",
    targetTitle: "黑死病",
    relationship: "鼠疫杆菌的发现解释了黑死病的病因",
  },
  {
    sourceApp: "human-history",
    sourceId: "agricultural-revolution",
    sourceTitle: "农业革命",
    targetApp: "life-science",
    targetId: "plant-domestication",
    targetTitle: "植物驯化",
    relationship: "农业革命的核心是野生植物的驯化",
  },
  {
    sourceApp: "life-science",
    sourceId: "plant-domestication",
    sourceTitle: "植物驯化",
    targetApp: "human-history",
    targetId: "agricultural-revolution",
    targetTitle: "农业革命",
    relationship: "植物驯化是农业革命的生物学基础",
  },
  {
    sourceApp: "human-history",
    sourceId: "scientific-revolution",
    sourceTitle: "科学革命",
    targetApp: "life-science",
    targetId: "microscope-invention",
    targetTitle: "显微镜发明",
    relationship: "科学革命期间显微镜的发明开启了微观世界",
  },
  {
    sourceApp: "life-science",
    sourceId: "microscope-invention",
    sourceTitle: "显微镜发明",
    targetApp: "human-history",
    targetId: "scientific-revolution",
    targetTitle: "科学革命",
    relationship: "显微镜的发明是科学革命中最重要的技术突破之一",
  },
  {
    sourceApp: "human-history",
    sourceId: "darwin-origin",
    sourceTitle: "《物种起源》出版",
    targetApp: "life-science",
    targetId: "origin-of-species",
    targetTitle: "物种起源",
    relationship: "1859年《物种起源》出版改变了科学史进程",
  },
  {
    sourceApp: "life-science",
    sourceId: "origin-of-species",
    sourceTitle: "物种起源",
    targetApp: "human-history",
    targetId: "darwin-origin",
    targetTitle: "《物种起源》出版",
    relationship: "《物种起源》的出版是人类思想史上的里程碑",
  },
  {
    sourceApp: "human-history",
    sourceId: "covid-19",
    sourceTitle: "新冠疫情",
    targetApp: "life-science",
    targetId: "pandemic-history",
    targetTitle: "瘟疫史",
    relationship: "新冠疫情是人类瘟疫史的最新篇章",
  },
  {
    sourceApp: "life-science",
    sourceId: "pandemic-history",
    sourceTitle: "瘟疫史",
    targetApp: "human-history",
    targetId: "covid-19",
    targetTitle: "新冠疫情",
    relationship: "瘟疫史的研究为应对新冠疫情提供了历史借鉴",
  },

  // Philosophy ↔ Life Science (Round 2 expansion)
  {
    sourceApp: "philosophy",
    sourceId: "aristotle",
    sourceTitle: "亚里士多德",
    targetApp: "life-science",
    targetId: "biology-classification",
    targetTitle: "生物分类学",
    relationship: "亚里士多德建立了最早的生物分类体系",
  },
  {
    sourceApp: "life-science",
    sourceId: "biology-classification",
    sourceTitle: "生物分类学",
    targetApp: "philosophy",
    targetId: "aristotle",
    targetTitle: "亚里士多德",
    relationship: "生物分类学的起源可以追溯到亚里士多德",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-mind",
    sourceTitle: "心灵哲学",
    targetApp: "life-science",
    targetId: "consciousness-studies",
    targetTitle: "意识研究",
    relationship: "心灵哲学为意识研究提供概念框架",
  },
  {
    sourceApp: "life-science",
    sourceId: "consciousness-studies",
    sourceTitle: "意识研究",
    targetApp: "philosophy",
    targetId: "philosophy-of-mind",
    targetTitle: "心灵哲学",
    relationship: "意识研究的科学发现挑战了心灵哲学的传统理论",
  },
  {
    sourceApp: "philosophy",
    sourceId: "bioethics",
    sourceTitle: "生命伦理学",
    targetApp: "life-science",
    targetId: "genetic-engineering",
    targetTitle: "基因工程",
    relationship: "生命伦理学审视基因工程技术的道德边界",
  },
  {
    sourceApp: "life-science",
    sourceId: "genetic-engineering",
    sourceTitle: "基因工程",
    targetApp: "philosophy",
    targetId: "bioethics",
    targetTitle: "生命伦理学",
    relationship: "基因工程技术的发展推动了生命伦理学的演进",
  },
  {
    sourceApp: "philosophy",
    sourceId: "environmental-ethics",
    sourceTitle: "环境伦理学",
    targetApp: "life-science",
    targetId: "ecology",
    targetTitle: "生态学",
    relationship: "环境伦理学为生态保护提供道德论证",
  },
  {
    sourceApp: "life-science",
    sourceId: "ecology",
    sourceTitle: "生态学",
    targetApp: "philosophy",
    targetId: "environmental-ethics",
    targetTitle: "环境伦理学",
    relationship: "生态学的发现深化了环境伦理学的理论基础",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-science",
    sourceTitle: "科学哲学",
    targetApp: "life-science",
    targetId: "evolution-theory",
    targetTitle: "进化论",
    relationship: "科学哲学对进化论的方法论分析",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution-theory",
    sourceTitle: "进化论",
    targetApp: "philosophy",
    targetId: "philosophy-of-science",
    targetTitle: "科学哲学",
    relationship: "进化论是科学哲学研究科学理论结构的经典案例",
  },

  // Philosophy ↔ Physics (Round 2 expansion)
  {
    sourceApp: "philosophy",
    sourceId: "aristotle",
    sourceTitle: "亚里士多德",
    targetApp: "universe-physics",
    targetId: "natural-philosophy",
    targetTitle: "自然哲学",
    relationship: "亚里士多德的自然哲学是物理学的前身",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "natural-philosophy",
    sourceTitle: "自然哲学",
    targetApp: "philosophy",
    targetId: "aristotle",
    targetTitle: "亚里士多德",
    relationship: "自然哲学从亚里士多德开始成为系统学科",
  },
  {
    sourceApp: "philosophy",
    sourceId: "kant",
    sourceTitle: "康德",
    targetApp: "universe-physics",
    targetId: "nebular-hypothesis",
    targetTitle: "星云假说",
    relationship: "康德提出了太阳系起源的星云假说",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "nebular-hypothesis",
    sourceTitle: "星云假说",
    targetApp: "philosophy",
    targetId: "kant",
    targetTitle: "康德",
    relationship: "星云假说是康德自然哲学的重要贡献",
  },
  {
    sourceApp: "philosophy",
    sourceId: "logical-positivism",
    sourceTitle: "逻辑实证主义",
    targetApp: "universe-physics",
    targetId: "quantum-mechanics",
    targetTitle: "量子力学",
    relationship: "逻辑实证主义对量子力学的诠释产生了深远影响",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "quantum-mechanics",
    sourceTitle: "量子力学",
    targetApp: "philosophy",
    targetId: "logical-positivism",
    targetTitle: "逻辑实证主义",
    relationship: "量子力学的测量问题推动了逻辑实证主义的发展",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-time",
    sourceTitle: "时间哲学",
    targetApp: "universe-physics",
    targetId: "relativity",
    targetTitle: "相对论",
    relationship: "相对论的时空观革命性地改变了时间哲学",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "relativity",
    sourceTitle: "相对论",
    targetApp: "philosophy",
    targetId: "philosophy-of-time",
    targetTitle: "时间哲学",
    relationship: "相对论为时间哲学提供了全新的物理学基础",
  },
  {
    sourceApp: "philosophy",
    sourceId: "determinism",
    sourceTitle: "决定论",
    targetApp: "universe-physics",
    targetId: "chaos-theory",
    targetTitle: "混沌理论",
    relationship: "混沌理论揭示了决定论系统中的不可预测性",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "chaos-theory",
    sourceTitle: "混沌理论",
    targetApp: "philosophy",
    targetId: "determinism",
    targetTitle: "决定论",
    relationship: "混沌理论对经典决定论提出了新的挑战",
  },
];
