import type { CrossLink } from "./types";

export const LINKS_COSMOLOGY: CrossLink[] = [
  // Cosmology ↔ Physics
  {
    sourceApp: "cosmology",
    sourceId: "big-bang",
    sourceTitle: "大爆炸",
    targetApp: "universe-physics",
    targetId: "thermodynamics",
    targetTitle: "热力学",
    relationship: "大爆炸理论中熵的演化与热力学第二定律",
  },
  {
    sourceApp: "cosmology",
    sourceId: "dark-energy",
    sourceTitle: "暗能量",
    targetApp: "universe-physics",
    targetId: "quantum-mechanics",
    targetTitle: "量子力学",
    relationship: "暗能量与量子真空能的关联",
  },
  {
    sourceApp: "cosmology",
    sourceId: "cmb",
    sourceTitle: "宇宙微波背景辐射",
    targetApp: "universe-physics",
    targetId: "optics",
    targetTitle: "电磁学",
    relationship: "CMB是电磁辐射的宇宙学遗迹",
  },
  {
    sourceApp: "cosmology",
    sourceId: "black-holes",
    sourceTitle: "黑洞",
    targetApp: "universe-physics",
    targetId: "relativity",
    targetTitle: "相对论",
    relationship: "黑洞是广义相对论预言的极端天体",
  },
  {
    sourceApp: "cosmology",
    sourceId: "neutrinos",
    sourceTitle: "中微子",
    targetApp: "universe-physics",
    targetId: "nuclear-physics",
    targetTitle: "核物理",
    relationship: "宇宙中微子源于核反应过程",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "thermodynamics",
    sourceTitle: "热力学",
    targetApp: "cosmology",
    targetId: "big-bang",
    targetTitle: "大爆炸",
    relationship: "热力学定律支配大爆炸后的宇宙演化",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "quantum-mechanics",
    sourceTitle: "量子力学",
    targetApp: "cosmology",
    targetId: "dark-energy",
    targetTitle: "暗能量",
    relationship: "量子场论的真空能是暗能量的候选解释",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "optics",
    sourceTitle: "电磁学",
    targetApp: "cosmology",
    targetId: "cmb",
    targetTitle: "宇宙微波背景辐射",
    relationship: "电磁学理论解释CMB的黑体辐射谱",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "relativity",
    sourceTitle: "相对论",
    targetApp: "cosmology",
    targetId: "black-holes",
    targetTitle: "黑洞",
    relationship: "相对论引力场方程预言了黑洞的存在",
  },
  {
    sourceApp: "universe-physics",
    sourceId: "nuclear-physics",
    sourceTitle: "核物理",
    targetApp: "cosmology",
    targetId: "neutrinos",
    targetTitle: "中微子",
    relationship: "核物理揭示了中微子在恒星核聚变中的角色",
  },

  // Cosmology ↔ Life Science
  {
    sourceApp: "cosmology",
    sourceId: "earth-formation",
    sourceTitle: "地球形成",
    targetApp: "life-science",
    targetId: "earth-formation",
    targetTitle: "地球形成",
    relationship: "地球的宇宙学起源为生命起源提供了物质条件",
  },
  {
    sourceApp: "cosmology",
    sourceId: "stellar-nucleosynthesis",
    sourceTitle: "恒星核合成",
    targetApp: "life-science",
    targetId: "evolution-theory",
    targetTitle: "进化论",
    relationship: "恒星核合成产生了碳等生命必需元素",
  },
  {
    sourceApp: "cosmology",
    sourceId: "habitable-zone",
    sourceTitle: "宜居带",
    targetApp: "life-science",
    targetId: "ecology",
    targetTitle: "生态学",
    relationship: "宜居带条件决定了生命演化的环境基础",
  },
  {
    sourceApp: "life-science",
    sourceId: "earth-formation",
    sourceTitle: "地球形成",
    targetApp: "cosmology",
    targetId: "earth-formation",
    targetTitle: "地球形成",
    relationship: "地球形成是宇宙学与生命科学的交汇点",
  },
  {
    sourceApp: "life-science",
    sourceId: "evolution-theory",
    sourceTitle: "进化论",
    targetApp: "cosmology",
    targetId: "stellar-nucleosynthesis",
    targetTitle: "恒星核合成",
    relationship: "碳基生命依赖恒星核合成产生的重元素",
  },
  {
    sourceApp: "life-science",
    sourceId: "ecology",
    sourceTitle: "生态学",
    targetApp: "cosmology",
    targetId: "habitable-zone",
    targetTitle: "宜居带",
    relationship: "生态系统的演化受宜居带天体物理条件约束",
  },

  // Cosmology ↔ History
  {
    sourceApp: "cosmology",
    sourceId: "copernican-revolution",
    sourceTitle: "哥白尼革命",
    targetApp: "human-history",
    targetId: "scientific-revolution",
    targetTitle: "科学革命",
    relationship: "哥白尼日心说引发了天文学和世界观的革命",
  },
  {
    sourceApp: "cosmology",
    sourceId: "space-race",
    sourceTitle: "太空竞赛",
    targetApp: "human-history",
    targetId: "space-race",
    targetTitle: "太空竞赛",
    relationship: "太空竞赛推动了宇宙学观测技术的飞跃",
  },
  {
    sourceApp: "human-history",
    sourceId: "scientific-revolution",
    sourceTitle: "科学革命",
    targetApp: "cosmology",
    targetId: "copernican-revolution",
    targetTitle: "哥白尼革命",
    relationship: "科学革命以哥白尼宇宙观变革为起点",
  },
  {
    sourceApp: "human-history",
    sourceId: "space-race",
    sourceTitle: "太空竞赛",
    targetApp: "cosmology",
    targetId: "space-race",
    targetTitle: "太空竞赛",
    relationship: "冷战太空竞赛为宇宙学研究提供了资源与动力",
  },

  // Cosmology ↔ Philosophy
  {
    sourceApp: "cosmology",
    sourceId: "anthropic-principle",
    sourceTitle: "人择原理",
    targetApp: "philosophy",
    targetId: "philosophy-of-science",
    targetTitle: "科学哲学",
    relationship: "人择原理引发了关于宇宙目的性的科学哲学讨论",
  },
  {
    sourceApp: "cosmology",
    sourceId: "multiverse",
    sourceTitle: "多重宇宙",
    targetApp: "philosophy",
    targetId: "epistemology",
    targetTitle: "认识论",
    relationship: "多重宇宙假说挑战了可证伪性的认识论标准",
  },
  {
    sourceApp: "philosophy",
    sourceId: "philosophy-of-science",
    sourceTitle: "科学哲学",
    targetApp: "cosmology",
    targetId: "anthropic-principle",
    targetTitle: "人择原理",
    relationship: "科学哲学审视人择原理的解释力与方法论地位",
  },
  {
    sourceApp: "philosophy",
    sourceId: "epistemology",
    sourceTitle: "认识论",
    targetApp: "cosmology",
    targetId: "multiverse",
    targetTitle: "多重宇宙",
    relationship: "认识论探讨多重宇宙假说的认知地位",
  },

  // Cosmology ↔ Mathematics
  {
    sourceApp: "cosmology",
    sourceId: "curved-spacetime",
    sourceTitle: "弯曲时空",
    targetApp: "mathematics",
    targetId: "riemann",
    targetTitle: "黎曼",
    relationship: "弯曲时空的描述依赖黎曼微分几何",
  },
  {
    sourceApp: "cosmology",
    sourceId: "cosmic-expansion",
    sourceTitle: "宇宙膨胀",
    targetApp: "mathematics",
    targetId: "newton-calculus",
    targetTitle: "牛顿微积分",
    relationship: "宇宙膨胀的数学描述需要微积分工具",
  },
  {
    sourceApp: "mathematics",
    sourceId: "riemann",
    sourceTitle: "黎曼",
    targetApp: "cosmology",
    targetId: "curved-spacetime",
    targetTitle: "弯曲时空",
    relationship: "黎曼几何为弯曲时空的宇宙学模型提供数学基础",
  },
  {
    sourceApp: "mathematics",
    sourceId: "newton-calculus",
    sourceTitle: "牛顿微积分",
    targetApp: "cosmology",
    targetId: "cosmic-expansion",
    targetTitle: "宇宙膨胀",
    relationship: "微积分是描述宇宙膨胀动力学的核心数学工具",
  },
];
