export const DIALOGUES = [
  { slug: "the-republic", title: "理想国", title_en: "The Republic", field: "政治哲学", era: "古代", participants: ["苏格拉底", "格劳孔", "阿德曼托斯", "色拉叙马霍斯"] },
  { slug: "apology", title: "申辩篇", title_en: "Apology", field: "伦理学", era: "古代", participants: ["苏格拉底"] },
  { slug: "symposium", title: "会饮篇", title_en: "Symposium", field: "美学", era: "古代", participants: ["苏格拉底", "阿里斯托芬", "阿伽松"] },
  { slug: "phaedo", title: "斐多篇", title_en: "Phaedo", field: "形而上学", era: "古代", participants: ["苏格拉底", "斐多", "西米亚斯", "克贝"] },
  { slug: "phaedrus", title: "斐德罗篇", title_en: "Phaedrus", field: "美学", era: "古代", participants: ["苏格拉底", "斐德罗"] },
  { slug: "meno", title: "美诺篇", title_en: "Meno", field: "认识论", era: "古代", participants: ["苏格拉底", "美诺"] },
  { slug: "euthyphro", title: "欧绪弗罗篇", title_en: "Euthyphro", field: "伦理学", era: "古代", participants: ["苏格拉底", "欧绪弗罗"] },
  { slug: "crito", title: "克力同篇", title_en: "Crito", field: "伦理学", era: "古代", participants: ["苏格拉底", "克力同"] },
  { slug: "gorgias", title: "理想国对话录（第二部分）", title_en: "Gorgias", field: "政治哲学", era: "古代", participants: ["苏格拉底", "高尔吉亚", "波洛斯", "卡里克勒斯"] },
  { slug: "theaetetus", title: "泰阿泰德篇", title_en: "Theaetetus", field: "认识论", era: "古代", participants: ["苏格拉底", "泰阿泰德"] },
  { slug: "sophist", title: "智者篇", title_en: "Sophist", field: "形而上学", era: "古代", participants: ["爱利亚陌生人", "塞奥多洛斯"] },
  { slug: "statesman", title: "泰阿泰德篇（续）", title_en: "Statesman", field: "政治哲学", era: "古代", participants: ["爱利亚陌生人", "小苏格拉底"] },
  { slug: "parmenides", title: "巴门尼德篇", title_en: "Parmenides", field: "形而上学", era: "古代", participants: ["巴门尼德", "苏格拉底", "芝诺"] },
  { slug: "timaeus", title: "蒂迈欧篇", title_en: "Timaeus", field: "形而上学", era: "古代", participants: ["蒂迈欧", "苏格拉底"] },
  { slug: "philebus", title: "斐莱布篇", title_en: "Philebus", field: "伦理学", era: "古代", participants: ["苏格拉底", "斐莱布", "普罗塔库斯"] },
  { slug: "laws", title: "法律篇", title_en: "Laws", field: "政治哲学", era: "古代", participants: ["雅典陌生人", "克列尼亚斯", "米吉洛斯"] },
  { slug: "natural-religion", title: "自然宗教对话录", title_en: "Dialogues Concerning Natural Religion", field: "宗教哲学", era: "近代", participants: ["克里安提斯", "德米亚", "斐洛"] },
  { slug: "three-dialogues", title: "海拉斯与斐洛诺斯三篇对话", title_en: "Three Dialogues between Hylas and Philonous", field: "认识论", era: "近代", participants: ["海拉斯", "斐洛诺斯"] },
  { slug: "two-new-sciences", title: "关于两门新科学的对话", title_en: "Dialogues Concerning Two New Sciences", field: "科学哲学", era: "近代", participants: ["萨尔维亚蒂", "萨格雷多", "辛普里丘"] },
  { slug: "gettier-dialogue", title: "人类理解论对话", title_en: "Dialogues on the Way to the Stanford Encyclopedia", field: "认识论", era: "当代", participants: ["阿尔基维亚德", "苏格拉底"] },
  { slug: "berkeley-dialogues", title: "海拉斯与斐洛诺斯", title_en: "Hylas and Philonous", field: "认识论", era: "近代", participants: ["海拉斯", "斐洛诺斯"] },
  { slug: "leibniz-dialogues", title: "斐拉里与斐拉德斯的对话", title_en: "New Essays on Human Understanding", field: "认识论", era: "近代", participants: ["斐拉里", "斐拉德斯"] },
  { slug: "wittgenstein-dialogue", title: "维也纳学派对话", title_en: "Conversations on Vienna Circle", field: "逻辑学", era: "现代", participants: ["维特根斯坦", "石里克"] },
  { slug: "sartre-dialogue", title: "存在与虚无对话", title_en: "Dialogue on Being and Nothingness", field: "形而上学", era: "现代", participants: ["萨特", "波伏瓦"] },
  { slug: "rawls-dialogue", title: "正义论对话", title_en: "Dialogue on Justice", field: "政治哲学", era: "当代", participants: ["罗尔斯", "诺齐克"] },
] as const;
