// AUTO-GENERATED by scripts/gen-psych-index.ts (pnpm gen-psych) — do not edit by hand.
// Search mirror of content/psychology/*/*.mdx.
export const PSYCHOLOGY_DIALOGUES_DATA = [
  {
    slug: "bowlby-psychoanalysis",
    title: "鲍尔比与精神分析的对话",
    title_en: "Bowlby and Psychoanalysis",
    field: "依恋理论",
    participants: ["鲍尔比", "安娜·弗洛伊德"],
  },
  {
    slug: "freud-jung-divergence",
    title: "弗洛伊德与荣格的分歧",
    title_en: "The Freud-Jung Divergence",
    field: "精神分析",
    participants: ["弗洛伊德", "荣格"],
  },
  {
    slug: "freud-jung-unconscious",
    title: "弗洛伊德vs荣格：无意识的本质",
    title_en: "Freud vs. Jung: The Nature of the Unconscious",
    field: "精神分析",
    participants: ["Sigmund Freud", "Carl Jung"],
  },
  {
    slug: "kahneman-gladwell-intuition",
    title: "卡尼曼vs格拉德威尔：直觉可靠吗",
    title_en: "Kahneman vs. Gladwell: Is Intuition Reliable?",
    field: "认知心理学",
    participants: ["Daniel Kahneman", "Malcolm Gladwell"],
  },
  {
    slug: "klein-winnicott-play",
    title: "克莱因与温尼科特论游戏",
    title_en: "Klein-Winnicott on Play",
    field: "客体关系",
    participants: ["克莱因", "温尼科特"],
  },
  {
    slug: "kohut-kernberg-narcissism",
    title: "科胡特与科恩伯格论自恋",
    title_en: "Kohut-Kernberg on Narcissism",
    field: "自体心理学",
    participants: ["科胡特", "科恩伯格"],
  },
  {
    slug: "seligman-csikszentmihalyi-happiness",
    title: "塞利格曼vs契克森米哈赖：幸福是什么",
    title_en: "Seligman vs. Csikszentmihalyi: What Is Happiness?",
    field: "积极心理学",
    participants: ["Martin Seligman", "Mihaly Csikszentmihalyi"],
  },
  {
    slug: "skinner-chomsky-language",
    title: "斯金纳vs乔姆斯基：语言是学习的吗",
    title_en: "Skinner vs. Chomsky: Is Language Learned?",
    field: "认知心理学",
    participants: ["B. F. Skinner", "Noam Chomsky"],
  },
];
