// AUTO-GENERATED by scripts/gen-psych-index.ts (pnpm gen-psych) — do not edit by hand.
// Search mirror of content/psychology/*/*.mdx.
export const PSYCHOLOGY_KB_DATA = [
  {
    slug: "brain-plasticity-guide",
    title: "大脑可塑性实用指南",
    titleEn: "Brain Plasticity Practical Guide",
    category: "神经科学",
  },
  {
    slug: "cbt-self-help",
    title: "CBT自助工具箱",
    titleEn: "CBT Self-Help Toolkit",
    category: "实用心理学",
  },
  {
    slug: "cooperation-science",
    title: "合作的科学",
    titleEn: "The Science of Cooperation",
    category: "进化心理学",
  },
  {
    slug: "emotional-intelligence-practice",
    title: "情绪智力的科学与实践",
    titleEn: "The Science and Practice of Emotional Intelligence",
    category: "实用心理学",
  },
  {
    slug: "evolutionary-psychology-guide",
    title: "进化心理学入门：为什么我们这样做",
    titleEn: "Evolutionary Psychology Guide: Why We Do What We Do",
    category: "进化心理学",
  },
  {
    slug: "intelligence-theories",
    title: "智力理论：一个数字能装下一个人吗",
    titleEn: "Theories of Intelligence: Can One Number Hold a Whole Mind?",
    category: "认知心理学",
  },
  {
    slug: "metacognition-training",
    title: "元认知：思考你的思考",
    titleEn: "Metacognition: Thinking About Your Thinking",
    category: "实用心理学",
  },
  {
    slug: "mindfulness-science",
    title: "正念的神经科学",
    titleEn: "The Neuroscience of Mindfulness",
    category: "实用心理学",
  },
  {
    slug: "psychology-of-decisions",
    title: "决策心理学：如何做出更好的选择",
    titleEn: "The Psychology of Decision-Making",
    category: "实用心理学",
  },
  {
    slug: "psychometrics-reliability-validity",
    title: "心理测量学：信度、效度与如何相信一个测验",
    titleEn: "Psychometrics: Reliability, Validity, and How to Trust a Test",
    category: "研究方法",
  },
  {
    slug: "relationship-psychology",
    title: "关系心理学",
    titleEn: "Relationship Psychology",
    category: "实用心理学",
  },
  {
    slug: "resilience-science",
    title: "心理韧性的科学",
    titleEn: "The Science of Psychological Resilience",
    category: "实用心理学",
  },
  {
    slug: "self-analysis-guide",
    title: "自我分析入门指南",
    titleEn: "A Guide to Self-Analysis",
    category: "实用心理学",
  },
  {
    slug: "sleep-and-mind",
    title: "睡眠与心智",
    titleEn: "Sleep and the Mind",
    category: "认知神经科学",
  },
  {
    slug: "stress-and-brain",
    title: "压力如何改变你的大脑",
    titleEn: "How Stress Changes Your Brain",
    category: "神经科学",
  },
];
