export const PHENOMENA_DATA = [
  { slug: "anchoring-bias", title: "锚定效应", subtitle: "Anchoring Bias", category: "认知" },
  {
    slug: "availability-heuristic",
    title: "可得性启发",
    subtitle: "Availability Heuristic",
    category: "认知",
  },
  { slug: "bystander-effect", title: "旁观者效应", subtitle: "Bystander Effect", category: "社会" },
  { slug: "change-blindness", title: "变化盲视", subtitle: "Change Blindness", category: "感知" },
  {
    slug: "cognitive-dissonance",
    title: "认知失调",
    subtitle: "Cognitive Dissonance",
    category: "社会",
  },
  { slug: "confirmation-bias", title: "确认偏误", subtitle: "Confirmation Bias", category: "认知" },
  {
    slug: "dunning-kruger",
    title: "邓宁-克鲁格效应",
    subtitle: "Dunning-Kruger Effect",
    category: "认知",
  },
  { slug: "false-memory", title: "虚假记忆", subtitle: "False Memory", category: "记忆" },
  { slug: "flow-state", title: "心流状态", subtitle: "Flow State", category: "情绪" },
  { slug: "framing-effect", title: "框架效应", subtitle: "Framing Effect", category: "决策" },
  { slug: "groupthink", title: "群体思维", subtitle: "Groupthink", category: "社会" },
  {
    slug: "mere-exposure-effect",
    title: "曝光效应",
    subtitle: "Mere Exposure Effect",
    category: "社会",
  },
  { slug: "peak-end-rule", title: "峰终定律", subtitle: "Peak-End Rule", category: "记忆" },
  {
    slug: "self-fulfilling-prophecy",
    title: "自我实现预言",
    subtitle: "Self-Fulfilling Prophecy",
    category: "社会",
  },
  {
    slug: "serial-position-effect",
    title: "序列位置效应",
    subtitle: "Serial Position Effect",
    category: "记忆",
  },
  {
    slug: "sunk-cost-fallacy",
    title: "沉没成本谬误",
    subtitle: "Sunk Cost Fallacy",
    category: "决策",
  },
  { slug: "transference", title: "移情", subtitle: "Transference", category: "精神分析" },
  {
    slug: "defense-mechanisms",
    title: "防御机制",
    subtitle: "Defense Mechanisms",
    category: "精神分析",
  },
  { slug: "unconscious", title: "无意识", subtitle: "The Unconscious", category: "精神分析" },
  {
    slug: "dream-interpretation",
    title: "梦的解析",
    subtitle: "Dream Interpretation",
    category: "精神分析",
  },
  {
    slug: "oedipus-complex",
    title: "俄狄浦斯情结",
    subtitle: "Oedipus Complex",
    category: "精神分析",
  },
  {
    slug: "id-ego-superego",
    title: "本我·自我·超我",
    subtitle: "Id, Ego, and Superego",
    category: "精神分析",
  },
  {
    slug: "countertransference",
    title: "反移情",
    subtitle: "Countertransference",
    category: "精神分析",
  },
  {
    slug: "object-relations",
    title: "客体关系",
    subtitle: "Object Relations",
    category: "精神分析",
  },
  { slug: "attachment-styles", title: "依恋类型", subtitle: "Attachment Styles", category: "发展" },
  { slug: "narcissism", title: "自恋", subtitle: "Narcissism", category: "精神分析" },
  {
    slug: "repetition-compulsion",
    title: "强迫性重复",
    subtitle: "Repetition Compulsion",
    category: "精神分析",
  },
  {
    slug: "psychic-causality",
    title: "心理因果律",
    subtitle: "Psychic Causality",
    category: "精神分析",
  },
  {
    slug: "big-five-personality",
    title: "大五人格模型",
    subtitle: "Big Five Personality Traits (OCEAN)",
    category: "人格",
  },
  { slug: "memory-systems", title: "记忆系统", subtitle: "Memory Systems", category: "认知" },
  {
    slug: "emotion-theories",
    title: "情绪理论",
    subtitle: "Theories of Emotion",
    category: "情绪",
  },
  {
    slug: "intelligence-theories",
    title: "智力理论",
    subtitle: "Theories of Intelligence",
    category: "认知",
  },
] as const;
