// AUTO-GENERATED by scripts/gen-psych-index.ts (pnpm gen-psych) — do not edit by hand.
// Search mirror of content/psychology/*/*.mdx.
export const PSYCHOLOGY_SCHOOLS_DATA = [
  {
    slug: "behaviorism",
    title: "行为主义学派",
    subtitle: "Behaviorism",
    era: "1913-至今",
    founder: "华生",
  },
  {
    slug: "cognitive",
    title: "认知心理学",
    subtitle: "Cognitive Psychology",
    era: "现代",
    founder: "乌尔里克·奈瑟",
  },
  {
    slug: "cognitive-behavioral-therapy",
    title: "认知行为疗法",
    subtitle: "Cognitive Behavioral Therapy",
    era: "现代",
    founder: "阿伦·贝克",
  },
  {
    slug: "evolutionary-psychology",
    title: "进化心理学",
    subtitle: "Evolutionary Psychology",
    era: "当代",
    founder: "Leda Cosmides & John Tooby",
  },
  {
    slug: "gestalt",
    title: "格式塔学派",
    subtitle: "Gestalt Psychology",
    era: "1912-至今",
    founder: "韦特海默",
  },
  {
    slug: "humanistic",
    title: "人本主义学派",
    subtitle: "Humanistic Psychology",
    era: "1950s-至今",
    founder: "马斯洛",
  },
  {
    slug: "positive-psychology",
    title: "积极心理学",
    subtitle: "Positive Psychology",
    era: "当代",
    founder: "马丁·塞利格曼",
  },
  {
    slug: "psychoanalysis",
    title: "精神分析学派",
    subtitle: "Psychoanalysis",
    era: "1896-至今",
    founder: "弗洛伊德",
  },
  {
    slug: "social-psychology",
    title: "社会心理学",
    subtitle: "Social Psychology",
    era: "现代",
    founder: "Kurt Lewin",
  },
];
