import type { Species } from "./types";

export const ANCIENT_SPECIES: Species[] = [
  {
    id: "stromatolite",
    story:
      "现今仍在澳大利亚鲨鱼湾的高盐海湾里生长——地球最古老的生命形态至今未断的活见证，它们释放的氧气最终改写了整个大气。",
    name: "叠层石",
    nameEn: "Stromatolite",
    era: "太古宙",
    period: "35亿年前",
    keyTraits: ["最早的光合生物群落", "产氧改变大气"],
    taxonomy: { kingdom: "原核生物界", phylum: "蓝藻门" },
    extinct: false,
  },
  {
    id: "charnia",
    story:
      "它是人类确认的第一块前寒武纪复杂生物化石，由一名 15 岁的中学生在英国查恩伍德森林发现，一举推翻了“复杂生命始于寒武纪”的旧观念，为埃迪卡拉生物群的研究奠定了基础。",
    name: "查恩海笔",
    nameEn: "Charnia",
    era: "元古宙",
    period: "5.6亿年前",
    keyTraits: ["埃迪卡拉生物群代表", "最早确认的复杂生命"],
    taxonomy: { kingdom: "动物界" },
    extinct: true,
  },
  {
    id: "dickinsonia",
    story:
      "争论了 75 年它究竟是动物、地衣还是巨型变形虫，直到 2018 年科学家在 5.58 亿年的化石里检出胆固醇分子——这种动物专属的脂肪，把它钉成了地球已知最古老的动物之一。",
    name: "狄更逊水母",
    nameEn: "Dickinsonia",
    era: "元古宙",
    period: "5.5亿年前",
    keyTraits: ["埃迪卡拉生物群", "可能是最早动物"],
    taxonomy: { kingdom: "动物界" },
    extinct: true,
  },
  {
    id: "cambrian-explosion-fauna",
    story:
      "在仅仅两三千万年的地质瞬间里，二十到三十多个动物门几乎同时登场——今天几乎所有动物的身体蓝图，都是在这场“寒武纪大爆发”中奠定的。",
    name: "寒武纪生物群",
    nameEn: "Cambrian Fauna",
    era: "古生代",
    period: "5.4亿年前",
    keyTraits: ["几乎所有动物门类同时出现", "生物多样性爆发"],
    taxonomy: { kingdom: "动物界", phylum: "多门类" },
    extinct: true,
  },
  {
    id: "trilobite",
    story:
      "它长着用方解石矿物晶体造的眼睛——可能是化石记录中最古老的成像眼睛之一；正因镜片是“石头”做的，常被完好保存。三叶虫在地球上繁衍了约 2.7 亿年才灭绝。",
    name: "三叶虫",
    nameEn: "Trilobite",
    era: "古生代",
    period: "5.21亿年前",
    keyTraits: ["复眼结构", "外骨骼", "海洋底栖"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门", class: "三叶虫纲" },
    extinct: true,
  },
  {
    id: "anomalocaris",
    story:
      "寒武纪海洋的顶级掠食者，体长可达半米。它的圆形口器化石曾被误认作水母、前肢被当成虾的身体，“奇虾”之名正源于这场百年误会。",
    name: "奇虾",
    nameEn: "Anomalocaris",
    era: "古生代",
    period: "5.2亿年前",
    keyTraits: ["寒武纪顶级掠食者", "环形口器"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "marrella",
    story:
      "它是沃尔科特在伯吉斯页岩采到的第一块化石，也是那里最常见的物种——已采集出两万多枚标本，因纤巧的轮廓被昵称为“花边蟹”。",
    name: "马尔三叶形虫",
    nameEn: "Marrella",
    era: "古生代",
    period: "5.08亿年前",
    keyTraits: ["伯吉斯页岩最常见化石", "寒武纪节肢动物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "pikaia",
    story: "只有几厘米长，却带有一条脊索——它是包括人类在内所有脊椎动物已知最古老的近亲之一。",
    name: "皮卡虫",
    nameEn: "Pikaia",
    era: "古生代",
    period: "5.08亿年前",
    keyTraits: ["最早的脊索动物之一", "脊索动物门祖先"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "hallucigenia",
    story:
      "化石让古生物学家足足搞反了两次——先把背刺当成腿，再把头尾颠倒，直到 2015 年才确认哪端是头。",
    name: "怪诞虫",
    nameEn: "Hallucigenia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["寒武纪奇异生物", "长棘防御", "曾被上下颠倒研究"],
    taxonomy: { kingdom: "动物界", phylum: "叶足动物门" },
    extinct: true,
  },
  {
    id: "opabinia",
    story:
      "五只眼睛配一根末端带爪的长鼻子，模样太离奇——1972 年惠廷顿在牛津的会议上展示复原图时，台下学者当场哄堂大笑。",
    name: "欧巴宾海蝎",
    nameEn: "Opabinia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["五只眼睛", "灵活的前附肢", "寒武纪奇异生物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "wiwaxia",
    story:
      "全身覆满鳞片状骨片和背刺，像披了铠甲的小刺猬；它究竟该归入软体动物还是环节动物，古生物学家至今仍争论不休。",
    name: "威瓦西亚虫",
    nameEn: "Wiwaxia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["鳞片覆盖", "寒武纪底栖生物"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门" },
    extinct: true,
  },
  {
    id: "sanctacaris",
    story:
      "因头部那对抓握爪，野外考察时被戏称为“圣诞老人之爪（Santa Claws）”，这个玩笑后来直接定格为它的拉丁学名 Sanctacaris（意为“神圣之虾”）；它可能是螯肢动物的早期亲戚，即蜘蛛和鲎的远祖一系。",
    name: "圣诞虾",
    nameEn: "Sanctacaris",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["寒武纪捕食者", "多对附肢"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "aegirocassis",
    story:
      "奥陶纪海洋中体长超过 2 米的巨兽，是已知最大的射齿动物（奇虾近亲），却从凶猛掠食者演化成温和的滤食者——比鲸和鲸鲨提前了数亿年走上同一条“滤食巨化”之路。",
    name: "埃吉尔虾",
    nameEn: "Aegirocassis",
    era: "古生代",
    period: "4.8亿年前",
    keyTraits: ["已知最大寒武纪动物", "滤食性"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
];
