import type { Species } from "./types";

export const ANCIENT_SPECIES: Species[] = [
  {
    id: "stromatolite",
    name: "叠层石",
    nameEn: "Stromatolite",
    era: "太古宙",
    period: "35亿年前",
    keyTraits: ["最早的光合生物群落", "产氧改变大气"],
    taxonomy: { kingdom: "原核生物界", phylum: "蓝藻门" },
    extinct: false,
  },
  {
    id: "charnia",
    name: "查恩海笔",
    nameEn: "Charnia",
    era: "元古宙",
    period: "5.6亿年前",
    keyTraits: ["埃迪卡拉生物群代表", "最早确认的复杂生命"],
    taxonomy: { kingdom: "动物界" },
    extinct: true,
  },
  {
    id: "dickinsonia",
    name: "狄更逊水母",
    nameEn: "Dickinsonia",
    era: "元古宙",
    period: "5.5亿年前",
    keyTraits: ["埃迪卡拉生物群", "可能是最早动物"],
    taxonomy: { kingdom: "动物界" },
    extinct: true,
  },
  {
    id: "cambrian-explosion-fauna",
    name: "寒武纪生物群",
    nameEn: "Cambrian Fauna",
    era: "古生代",
    period: "5.4亿年前",
    keyTraits: ["几乎所有动物门类同时出现", "生物多样性爆发"],
    taxonomy: { kingdom: "动物界", phylum: "多门类" },
    extinct: true,
  },
  {
    id: "trilobite",
    name: "三叶虫",
    nameEn: "Trilobite",
    era: "古生代",
    period: "5.21亿年前",
    keyTraits: ["复眼结构", "外骨骼", "海洋底栖"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门", class: "三叶虫纲" },
    extinct: true,
  },
  {
    id: "anomalocaris",
    name: "奇虾",
    nameEn: "Anomalocaris",
    era: "古生代",
    period: "5.2亿年前",
    keyTraits: ["寒武纪顶级掠食者", "环形口器"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "marrella",
    name: "马尔三叶形虫",
    nameEn: "Marrella",
    era: "古生代",
    period: "5.08亿年前",
    keyTraits: ["伯吉斯页岩最常见化石", "寒武纪节肢动物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "pikaia",
    name: "皮卡虫",
    nameEn: "Pikaia",
    era: "古生代",
    period: "5.08亿年前",
    keyTraits: ["最早的脊索动物之一", "脊索动物门祖先"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "hallucigenia",
    name: "怪诞虫",
    nameEn: "Hallucigenia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["寒武纪奇异生物", "长棘防御", "曾被上下颠倒研究"],
    taxonomy: { kingdom: "动物界", phylum: "叶足动物门" },
    extinct: true,
  },
  {
    id: "opabinia",
    name: "欧巴宾海蝎",
    nameEn: "Opabinia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["五只眼睛", "灵活的前附肢", "寒武纪奇异生物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "wiwaxia",
    name: "威瓦西亚虫",
    nameEn: "Wiwaxia",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["鳞片覆盖", "寒武纪底栖生物"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门" },
    extinct: true,
  },
  {
    id: "sanctacaris",
    name: "圣诞虾",
    nameEn: "Sanctacaris",
    era: "古生代",
    period: "5.05亿年前",
    keyTraits: ["寒武纪捕食者", "多对附肢"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "aegirocassis",
    name: "埃吉尔虾",
    nameEn: "Aegirocassis",
    era: "古生代",
    period: "4.8亿年前",
    keyTraits: ["已知最大寒武纪动物", "滤食性"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
];
