import type { Species } from "./types";

export const CENOZOIC_MODERN_SPECIES: Species[] = [
  {
    id: "megalodon",
    story: "史上最大的掠食性鲨鱼，牙齿可达 18 厘米，体长估计 15–18 米，约在 360 万年前灭绝。",
    name: "巨齿鲨",
    nameEn: "Megalodon",
    era: "新生代",
    period: "2300万年前",
    keyTraits: ["已知最大鲨鱼", "长达18米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "软骨鱼纲" },
    extinct: true,
  },
  {
    id: "livyatan",
    story:
      "利维坦鲸的牙齿长达 36 厘米，是已知动物中最大的咬合牙——比霸王龙的牙还长一倍多，它甚至以其他鲸类为食。",
    name: "利维坦鲸",
    nameEn: "Livyatan",
    era: "新生代",
    period: "1300万年前",
    keyTraits: ["已知最大齿鲸", "顶级海洋掠食者"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "terror-bird",
    story:
      "恐鹤靠巨大的钩状喙撕咬猎物，其中凯伦肯鹤的头骨长达 71 厘米，是已知最大的鸟类头骨，几乎和马头一样大。",
    name: "恐鹤",
    nameEn: "Terror Bird",
    era: "新生代",
    period: "2000万年前",
    keyTraits: ["不能飞的巨型掠食鸟", "高达3米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "proconsul",
    story:
      "原康修尔猿是非洲发现的第一种化石猿，它的名字意为“在 Consul 之前”——Consul 是 20 世纪初一只会骑车演杂技的著名表演黑猩猩。",
    name: "原康修尔猿",
    nameEn: "Proconsul",
    era: "新生代",
    period: "2300万年前",
    keyTraits: ["早期类人猿", "无尾"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "basilosaurus",
    story:
      "龙王鲸的学名意为“帝王蜥蜴”——发现者最初误以为这具蛇形巨骨属于一条远古海洋爬行动物，后来才认出它其实是一头早期鲸。",
    name: "龙王鲸",
    nameEn: "Basilosaurus",
    era: "新生代",
    period: "4000万年前",
    keyTraits: ["早期鲸类", "长达18米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "ambulocetus",
    story:
      "游走鲸的学名意为“会走路的鲸”，它有四条能撑地的腿和带蹼的脚，是记录鲸类从陆地走向海洋的关键过渡化石。",
    name: "游走鲸",
    nameEn: "Ambulocetus",
    era: "新生代",
    period: "4900万年前",
    keyTraits: ["鲸鱼陆地祖先", "半水生"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "blue-whale",
    story:
      "地球有史以来已知最大的动物，体长超 30 米、重达 170 吨，心脏就有一辆小汽车大——比任何恐龙都大。",
    name: "蓝鲸",
    nameEn: "Blue Whale",
    era: "新生代",
    period: "500万年前",
    keyTraits: ["地球有史以来最大动物", "长达30米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "platypus",
    story:
      "少数会下蛋的哺乳动物之一，还能用喙感知猎物的电场；首批标本送到欧洲时，博物学家一度以为是有人把鸭嘴缝在兽身上的骗局。",
    name: "鸭嘴兽",
    nameEn: "Platypus",
    era: "新生代",
    period: "1亿年前",
    keyTraits: ["产卵哺乳动物", "电感受器"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "pangolin",
    story:
      "穿山甲是世界上唯一一种全身覆盖鳞片的哺乳动物，鳞片由角蛋白构成（和人的指甲一样），也因此成为全球被走私最多的野生哺乳动物。",
    name: "穿山甲",
    nameEn: "Pangolin",
    era: "新生代",
    period: "8000万年前",
    keyTraits: ["全身鳞甲", "最被偷猎的哺乳动物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "tardigrade",
    story:
      "能在脱水后进入“隐生”状态，挺过真空、极端辐射甚至太空暴露——2007 年它成为首批被证实能在外太空存活的动物。",
    name: "水熊虫",
    nameEn: "Tardigrade",
    era: "新生代",
    period: "5亿年前",
    keyTraits: ["极端环境生存", "太空真空耐受"],
    taxonomy: { kingdom: "动物界", phylum: "缓步动物门" },
    extinct: false,
  },
  {
    id: "sivatherium",
    story:
      "西瓦兽是有史以来体型最大的长颈鹿科动物之一，体重可达一吨，却长着鹿一样粗短的脖子和宽大的鹿角状骨突。",
    name: "西瓦兽",
    nameEn: "Sivatherium",
    era: "新生代",
    period: "100万年前",
    keyTraits: ["已知最大长颈鹿科", "巨型哺乳动物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "megatherium",
    story:
      "大地懒站起来有大象那么大、重达约 4 吨；达尔文在小猎犬号航行途中亲手挖到它的化石，这正是促使他思考演化的线索之一。",
    name: "大地懒",
    nameEn: "Megatherium",
    era: "新生代",
    period: "1万年前",
    keyTraits: ["大象般大小的树懒", "可达6米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "glyptodon",
    story:
      "雕齿兽是甲壳虫汽车般大小的史前犰狳，背上顶着上千块骨板拼成的圆顶硬壳，有些种类的尾巴还带着布满骨刺的狼牙棒般的尾锤。",
    name: "雕齿兽",
    nameEn: "Glyptodon",
    era: "新生代",
    period: "1万年前",
    keyTraits: ["巨型装甲哺乳动物", "龟壳般的背甲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "smilodon",
    story: "犬齿长达 28 厘米却很脆，靠强壮的前肢按住猎物再精准切入要害——并非靠蛮力撕咬。",
    name: "剑齿虎",
    nameEn: "Smilodon",
    era: "新生代",
    period: "250万年前",
    keyTraits: ["20厘米长的剑齿", "伏击型掠食者", "冰河时期猛兽"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "食肉目" },
    extinct: true,
  },
  {
    id: "mammoth",
    story:
      "西伯利亚永久冻土里的遗骸如此完整，连胃中的食物都还在——这使它成为“去灭绝”基因工程最热门的候选。",
    name: "猛犸象",
    nameEn: "Woolly Mammoth",
    era: "新生代",
    period: "40万年前",
    keyTraits: ["厚毛御寒", "长弯曲象牙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "长鼻目" },
    extinct: true,
  },
  {
    id: "columbian-mammoth",
    story:
      "哥伦比亚猛犸象比披毛的猛犸象更大，肩高近 4 米、象牙可弯曲伸展到约 5 米长，生活在北美较温暖的开阔草原上。",
    name: "哥伦比亚猛犸象",
    nameEn: "Columbian Mammoth",
    era: "第四纪",
    period: "100万年前",
    keyTraits: ["比猛犸象更大的近亲", "北美"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "australopithecus",
    story:
      "最著名的标本“露西”1974 年在埃塞俄比亚出土，团队当晚反复播放披头士的《Lucy in the Sky with Diamonds》庆祝，名字由此而来。",
    name: "南方古猿",
    nameEn: "Australopithecus",
    era: "第四纪",
    period: "390万年前",
    keyTraits: ["直立行走的早期人科", "露西化石", "脑容量较小"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "ardipithecus",
    story:
      "约 440 万年前的“阿尔迪”脚上还长着像拇指一样能抓握的大脚趾，能直立行走又能攀树，说明人类祖先是在林地里、而非草原上学会直立的。",
    name: "地猿",
    nameEn: "Ardipithecus",
    era: "第四纪",
    period: "440万年前",
    keyTraits: ["早期人科", "可能直立行走"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "woolly-rhinoceros",
    story:
      "披毛犀前角扁平如铲，化石上的磨损痕迹显示它会左右摆头、用角扫开积雪去吃下面的草——西伯利亚冻土里还出土过保存完好的木乃伊。",
    name: "披毛犀",
    nameEn: "Woolly Rhinoceros",
    era: "第四纪",
    period: "350万年前",
    keyTraits: ["厚毛御寒", "冰河时期"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-habilis",
    story:
      "能人的学名意为“手巧的人”，正是因为在它的化石旁发现了人类最早的奥杜威石器——最早被命名为“人属”的成员之一。",
    name: "能人",
    nameEn: "Homo Habilis",
    era: "第四纪",
    period: "200万年前",
    keyTraits: ["最早使用石器的人属", "脑容量增大"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "homo-erectus",
    story:
      "直立人是已知最早走出非洲、并最早学会用火的人属，作为一个物种存续了约 170 万年，是迄今最长寿的人类种。",
    name: "直立人",
    nameEn: "Homo Erectus",
    era: "第四纪",
    period: "180万年前",
    keyTraits: ["最早使用火的人属", "走出非洲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "saber-tooth-cat",
    story:
      "洛杉矶拉布雷亚沥青坑里出土的刃齿虎化石超过 16 万件、代表两千多个个体，是世界上最大的剑齿虎标本库。",
    name: "刃齿虎",
    nameEn: "Smilodon fatalis",
    era: "第四纪",
    period: "160万年前",
    keyTraits: ["致命剑齿", "拉布雷亚沥青坑化石"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "gigantopithecus",
    story:
      "巨猿是有史以来最大的灵长类，身高可达 3 米、体重约 200–300 公斤；它最早是 1935 年从香港一家药铺当作“龙骨”出售的巨大牙齿中被发现的。",
    name: "巨猿",
    nameEn: "Gigantopithecus",
    era: "第四纪",
    period: "100万年前",
    keyTraits: ["已知最大的灵长类", "身高可达3米", "与大熊猫共存"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "neanderthalensis",
    story:
      "今天非非洲裔人类基因组里仍带着约 1–2% 的尼安德特 DNA——他们并未完全消失，而是活在我们体内。",
    name: "尼安德特人",
    nameEn: "Homo Neanderthalensis",
    era: "第四纪",
    period: "40万年前",
    keyTraits: ["与智人杂交", "脑容量大于智人"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "cave-bear",
    story:
      "洞熊虽体型比棕熊更大，主食却几乎都是植物；瑞士的龙洞一处遗址就出土过三万多具洞熊骨骸，是它们世代越冬留下的。",
    name: "洞熊",
    nameEn: "Cave Bear",
    era: "第四纪",
    period: "30万年前",
    keyTraits: ["比棕熊更大", "欧洲洞穴化石"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "denisovan",
    story:
      "最初仅凭西伯利亚一根指骨的 DNA 被发现，却揭示出一个全新人类支系；藏族人的高原适应基因 EPAS1 正来自他们。",
    name: "丹尼索瓦人",
    nameEn: "Denisovan",
    era: "第四纪",
    period: "30万年前",
    keyTraits: ["与智人杂交", "高海拔适应基因"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "homo-floresiensis",
    story:
      "弗洛勒斯人身高仅约 1 米，绰号“霍比特人”，是岛屿隔离导致体型缩小的产物；它们在岛上猎捕同样矮化的侏儒象，还要躲避巨型科莫多巨蜥。",
    name: "弗洛勒斯人",
    nameEn: "Homo Floresiensis",
    era: "第四纪",
    period: "10万年前",
    keyTraits: ["矮小人种", "霍比特人"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "irish-elk",
    story:
      "大角鹿长着鹿类有史以来最大的角，跨度超过 3.6 米、重达约 40 公斤；这对夸张巨角很可能是雌性择偶的性选择压力一路“吹大”的。",
    name: "大角鹿",
    nameEn: "Irish Elk",
    era: "第四纪",
    period: "7700年前灭绝",
    keyTraits: ["已知最大鹿角", "翼展可达3.6米"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-sapiens",
    story:
      "目前已知最古老的智人化石出土于摩洛哥的杰贝尔伊罗，距今约 30 万年——把我们这个物种的起源时间一下子往前推了约 10 万年。",
    name: "智人",
    nameEn: "Homo Sapiens",
    era: "全新世",
    period: "30万年前",
    keyTraits: ["抽象思维", "语言", "工具制造", "文明建设"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: false,
  },
  {
    id: "moa",
    story: "新西兰的恐鸟最高可达 3.6 米，在毛利人抵达后约一两百年内被猎至灭绝。",
    name: "恐鸟",
    nameEn: "Moa",
    era: "全新世",
    period: "600年前灭绝",
    keyTraits: ["新西兰巨型不会飞的鸟", "高达3.6米", "人类活动导致灭绝"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "dodo",
    story:
      "在毛里求斯没有天敌、不惧人类，水手登岛后不到一个世纪就将其猎杀殆尽，从此“渡渡鸟”成了灭绝的代名词。",
    name: "渡渡鸟",
    nameEn: "Dodo",
    era: "全新世",
    period: "1662年灭绝",
    keyTraits: ["不会飞的鸟", "人类导致灭绝"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "stellers-sea-cow",
    story: "1741 年才被科学描述，仅 27 年后就被毛皮猎人捕杀殆尽。",
    name: "斯特拉大海牛",
    nameEn: "Steller's Sea Cow",
    era: "全新世",
    period: "1768年灭绝",
    keyTraits: ["长达8米的海牛", "北太平洋"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "great-auk",
    story:
      "最后一对大海雀 1844 年在冰岛被捕杀，连同它们正在孵的蛋——人类亲手终结了北大西洋的“企鹅”。",
    name: "大海雀",
    nameEn: "Great Auk",
    era: "全新世",
    period: "1844年灭绝",
    keyTraits: ["不会飞的海鸟", "北极物种"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "quagga",
    story:
      "斑驴只有前半身有斑马条纹、后半身则是纯棕色；1984 年它成为史上第一种被成功测出 DNA 的灭绝动物，由此开创了古 DNA 研究。",
    name: "斑驴",
    nameEn: "Quagga",
    era: "全新世",
    period: "1883年灭绝",
    keyTraits: ["半身斑马半身马", "南非特有"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "thylacine",
    story:
      "最后一只袋狼 1936 年死于霍巴特动物园，距它被列为保护动物仅 59 天——人为灭绝的标志性悲剧。",
    name: "袋狼",
    nameEn: "Thylacine",
    era: "全新世",
    period: "1936年灭绝",
    keyTraits: ["有袋类掠食者", "塔斯马尼亚虎"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "homo-naledi",
    story:
      "纳莱迪人脑容量很小，遗骸却密集出现在南非“新星”洞系极深的暗室里，引发了一场至今未决的争论：它们是否会有意处理同伴的遗体。",
    name: "纳莱迪人",
    nameEn: "Homo Naledi",
    era: "第四纪",
    period: "33万年前",
    keyTraits: ["脑容量较小", "可能有埋葬行为", "南非发现"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲", order: "灵长目" },
    extinct: true,
  },
  {
    id: "elasmotherium",
    story:
      "板齿犀被称为“西伯利亚独角兽”，额头上可能顶着一根近 1 米长的巨角，而且它一直存活到约 3.9 万年前，曾与早期人类共处一片大陆。",
    name: "板齿犀",
    nameEn: "Elasmotherium",
    era: "第四纪",
    period: "2.9万年前灭绝",
    keyTraits: ["巨型独角兽", "可能单角", "体重可达4吨"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: true,
  },
  {
    id: "haasts-eagle",
    story:
      "哈斯特鹰是已知最大的鹰，利爪长达约 9 厘米、堪比老虎的爪，能俯冲扑杀比自己重得多的恐鸟；随着毛利人猎尽恐鸟，它也在约 1445 年随之灭绝。",
    name: "哈斯特鹰",
    nameEn: "Haast's Eagle",
    era: "全新世",
    period: "1400年灭绝",
    keyTraits: ["已知最大飞鸟之一", "翼展3米", "新西兰顶级掠食者"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "okapi",
    story:
      "霍加狓是长颈鹿在世上唯一的现存近亲，直到 1901 年才被科学界正式认识，被称为“非洲独角兽”；它那条约 30 厘米长的灵活舌头，足以舔到自己的眼睛和耳朵。",
    name: "霍加狓",
    nameEn: "Okapi",
    era: "新生代",
    period: "2000万年前",
    keyTraits: ["长颈鹿唯一近亲", "刚果雨林特有", "斑马纹腿"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "哺乳纲" },
    extinct: false,
  },
  {
    id: "coelacanth-living",
    story:
      "曾被认为随恐龙一同灭绝，直到 1938 年南非渔民在渔获中发现一条活体——20 世纪最轰动的“活化石”发现，证明这一支系默默存续了上亿年。",
    name: "腔棘鱼",
    nameEn: "Coelacanth",
    era: "新生代",
    period: "4亿年前",
    keyTraits: ["活化石", "曾被认为已灭绝6500万年", "叶状鳍"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "腔棘鱼纲" },
    extinct: false,
  },
];
