import type { Species } from "./types";

export const MESOZOIC_SPECIES: Species[] = [
  {
    id: "ichthyosaur",
    name: "鱼龙",
    nameEn: "Ichthyosaur",
    era: "中生代",
    period: "2.5亿年前",
    keyTraits: ["海洋爬行动物", "流线型身体"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "tuatara",
    name: "楔齿蜥",
    nameEn: "Tuatara",
    era: "中生代",
    period: "2.5亿年前",
    keyTraits: ["活化石爬行动物", "新西兰特有"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "爬行纲" },
    extinct: false,
  },
  {
    id: "plateosaurus",
    name: "板龙",
    nameEn: "Plateosaurus",
    era: "中生代",
    period: "2.1亿年前",
    keyTraits: ["最早的大型植食恐龙之一", "三叠纪"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "plesiosaur",
    name: "蛇颈龙",
    nameEn: "Plesiosaur",
    era: "中生代",
    period: "2亿年前",
    keyTraits: ["长颈海洋爬行动物", "四个鳍状肢"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "ginkgo",
    name: "银杏",
    nameEn: "Ginkgo",
    era: "中生代",
    period: "2亿年前",
    keyTraits: ["活化石植物", "落叶乔木"],
    taxonomy: { kingdom: "植物界", phylum: "银杏门" },
    extinct: false,
  },
  {
    id: "ammonite",
    name: "菊石",
    nameEn: "Ammonite",
    era: "中生代",
    period: "4亿年前",
    keyTraits: ["螺旋形外壳", "海洋头足类"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: true,
  },
  {
    id: "archaeopteryx",
    name: "始祖鸟",
    nameEn: "Archaeopteryx",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["恐龙到鸟类的过渡", "有羽毛和牙齿"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "stegosaurus",
    name: "剑龙",
    nameEn: "Stegosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["背板散热防御", "尾部骨刺"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "brachiosaurus",
    name: "腕龙",
    nameEn: "Brachiosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["极长的颈部", "前肢比后肢长"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "pliosaurus",
    name: "上龙",
    nameEn: "Pliosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["侏罗纪海洋顶级掠食者", "短颈大头"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "welwitschia",
    name: "百岁兰",
    nameEn: "Welwitschia",
    era: "中生代",
    period: "1.1亿年前",
    keyTraits: ["沙漠活化石", "一生只长两片叶"],
    taxonomy: { kingdom: "植物界", phylum: "裸子植物门" },
    extinct: false,
  },
  {
    id: "spinosaurus",
    name: "棘龙",
    nameEn: "Spinosaurus",
    era: "中生代",
    period: "1亿年前",
    keyTraits: ["背帆", "半水生掠食者", "已知最大肉食恐龙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "parasaurolophus",
    name: "副栉龙",
    nameEn: "Parasaurolophus",
    era: "中生代",
    period: "7600万年前",
    keyTraits: ["管状头冠", "可能用于发声"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "velociraptor",
    name: "伶盗龙",
    nameEn: "Velociraptor",
    era: "中生代",
    period: "7500万年前",
    keyTraits: ["羽毛覆盖", "镰刀状爪", "群居猎食"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "pteranodon",
    name: "无齿翼龙",
    nameEn: "Pteranodon",
    era: "中生代",
    period: "8500万年前",
    keyTraits: ["翼展可达7米", "飞行爬行动物", "无齿喙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "翼龙目" },
    extinct: true,
  },
  {
    id: "tyrannosaurus",
    name: "霸王龙",
    nameEn: "Tyrannosaurus Rex",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["最大陆地掠食者之一", "强大咬合力"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "triceratops",
    name: "三角龙",
    nameEn: "Triceratops",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["三只角和颈盾", "白垩纪植食恐龙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "ankylosaurus",
    name: "甲龙",
    nameEn: "Ankylosaurus",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["全身骨甲", "尾部骨锤"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "edselosaurus",
    name: "埃德蒙顿龙",
    nameEn: "Edmontosaurus",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["大型鸭嘴龙", "群居迁徙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
];
