import type { Species } from "./types";

export const MESOZOIC_SPECIES: Species[] = [
  {
    id: "ichthyosaur",
    story:
      "鱼龙演化出酷似海豚的流线型身体，却是不折不扣的爬行动物；最大的萨斯特鱼龙体长可达 21 米，几乎逼近蓝鲸。",
    name: "鱼龙",
    nameEn: "Ichthyosaur",
    era: "中生代",
    period: "2.5亿年前",
    keyTraits: ["海洋爬行动物", "流线型身体"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "tuatara",
    story:
      "喙头目唯一的现存代表，这一支系可追溯到 2.5 亿年前；它头顶还保留着一只能感光的“第三只眼”。",
    name: "楔齿蜥",
    nameEn: "Tuatara",
    era: "中生代",
    period: "2.5亿年前",
    keyTraits: ["活化石爬行动物", "新西兰特有"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "爬行纲" },
    extinct: false,
  },
  {
    id: "plateosaurus",
    story:
      "板龙是三叠纪晚期最常见的恐龙，是欧洲出土化石最多的恐龙之一（逾百具）；德国特罗辛根的“恐龙墓地”历经多次发掘累计出土数十具骨架。",
    name: "板龙",
    nameEn: "Plateosaurus",
    era: "中生代",
    period: "2.1亿年前",
    keyTraits: ["最早的大型植食恐龙之一", "三叠纪"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "plesiosaur",
    story:
      "薄板龙的脖子由多达 72 节颈椎组成，是所有已知脊椎动物中最多的；1869 年古生物学家科普误把头装到了尾巴一端，成了“骨头战争”里最著名的乌龙。",
    name: "蛇颈龙",
    nameEn: "Plesiosaur",
    era: "中生代",
    period: "2亿年前",
    keyTraits: ["长颈海洋爬行动物", "四个鳍状肢"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "ginkgo",
    story:
      "真正的“活化石”，与 2 亿年前侏罗纪的化石几乎无异；野生种群一度近乎灭绝，靠中国寺庙的栽培才幸存至今。",
    name: "银杏",
    nameEn: "Ginkgo",
    era: "中生代",
    period: "2亿年前",
    keyTraits: ["活化石植物", "落叶乔木"],
    taxonomy: { kingdom: "植物界", phylum: "银杏门" },
    extinct: false,
  },
  {
    id: "ammonite",
    story:
      "菊石演化极快、分布极广，是地质学家给中生代岩层断代的“标准化石”；它们熬过了多次大灭绝，最终却和恐龙一起消失在 6600 万年前的白垩纪末。",
    name: "菊石",
    nameEn: "Ammonite",
    era: "中生代",
    period: "4亿年前",
    keyTraits: ["螺旋形外壳", "海洋头足类"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: true,
  },
  {
    id: "archaeopteryx",
    story:
      "兼具恐龙的牙齿、爪和长尾，又有鸟类的羽毛。1861 年的发现恰在达尔文《物种起源》出版两年后，成为演化论最著名的过渡化石。",
    name: "始祖鸟",
    nameEn: "Archaeopteryx",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["恐龙到鸟类的过渡", "有羽毛和牙齿"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟纲" },
    extinct: true,
  },
  {
    id: "stegosaurus",
    story:
      "剑龙身长可达 9 米、体重数吨，脑子却只有约 80 克，是脑体比最低的恐龙之一；背上的骨板布满血管，可能用来散热或炫耀求偶。",
    name: "剑龙",
    nameEn: "Stegosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["背板散热防御", "尾部骨刺"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "brachiosaurus",
    story:
      "和大多数恐龙相反，腕龙的前肢比后肢更长，加上超长的脖子，让它像长颈鹿一样昂首，能把头探到离地 9 米以上的高处取食。",
    name: "腕龙",
    nameEn: "Brachiosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["极长的颈部", "前肢比后肢长"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "pliosaurus",
    story:
      "上龙是侏罗纪海洋的顶级杀手，绰号“掠食者X”的芬氏上龙体长约 10–12 米，光头骨就有 2 米多长，2009 年在北极斯瓦尔巴群岛被发现。",
    name: "上龙",
    nameEn: "Pliosaurus",
    era: "中生代",
    period: "1.5亿年前",
    keyTraits: ["侏罗纪海洋顶级掠食者", "短颈大头"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "welwitschia",
    story: "一生只长两片叶子，却能在纳米布沙漠存活上千年。",
    name: "百岁兰",
    nameEn: "Welwitschia",
    era: "中生代",
    period: "1.1亿年前",
    keyTraits: ["沙漠活化石", "一生只长两片叶"],
    taxonomy: { kingdom: "植物界", phylum: "裸子植物门" },
    extinct: false,
  },
  {
    id: "spinosaurus",
    story:
      "棘龙是已知最大的肉食恐龙，背帆由约 1.65 米长的骨棘撑起；它最初的化石 1944 年毁于盟军对慕尼黑的轰炸，如今只剩绘图与照片为证。",
    name: "棘龙",
    nameEn: "Spinosaurus",
    era: "中生代",
    period: "1亿年前",
    keyTraits: ["背帆", "半水生掠食者", "已知最大肉食恐龙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "parasaurolophus",
    story:
      "副栉龙头顶那根长管其实是中空的，内部弯折的气道与鼻腔相通；CT 扫描显示它像一件天然管乐器，能发出低沉如号角的共鸣声。",
    name: "副栉龙",
    nameEn: "Parasaurolophus",
    era: "中生代",
    period: "7600万年前",
    keyTraits: ["管状头冠", "可能用于发声"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "velociraptor",
    story:
      "真实的伶盗龙只有火鸡大小、全身披羽，远非电影里的庞然大物；蒙古曾出土一具与原角龙“扭打中”同归于尽的化石，把它的镰刀爪永远定格在猎物颈间。",
    name: "伶盗龙",
    nameEn: "Velociraptor",
    era: "中生代",
    period: "7500万年前",
    keyTraits: ["羽毛覆盖", "镰刀状爪", "群居猎食"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "pteranodon",
    story:
      "无齿翼龙的喙完全没有牙齿，雄性翼展可达 7 米；它由“骨头战争”名将马什于 19 世纪 70 年代在美国堪萨斯的白垩沉积中首次发现，以捕鱼为生。",
    name: "无齿翼龙",
    nameEn: "Pteranodon",
    era: "中生代",
    period: "8500万年前",
    keyTraits: ["翼展可达7米", "飞行爬行动物", "无齿喙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "翼龙目" },
    extinct: true,
  },
  {
    id: "tyrannosaurus",
    story:
      "霸王龙的咬合力估计高达近 1.3 万磅，是已知陆地动物中最强的；它那一口又粗又弯的牙齿被古生物学家戏称为“致命香蕉”，足以咬碎骨头。",
    name: "霸王龙",
    nameEn: "Tyrannosaurus Rex",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["最大陆地掠食者之一", "强大咬合力"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "蜥臀目" },
    extinct: true,
  },
  {
    id: "triceratops",
    story:
      "三角龙的头骨连同颈盾可长达 2.5 米，是所有陆生动物中最大的头骨之一；作为白垩纪末最后的恐龙之一，它一直生存到 6600 万年前那场大灭绝。",
    name: "三角龙",
    nameEn: "Triceratops",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["三只角和颈盾", "白垩纪植食恐龙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "ankylosaurus",
    story:
      "甲龙浑身披着骨板铠甲，连眼皮上都有一块护骨；尾端融合成的骨锤挥动起来足以击碎掠食者的骨头——它的名字在希腊语里正是“融合的蜥蜴”。",
    name: "甲龙",
    nameEn: "Ankylosaurus",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["全身骨甲", "尾部骨锤"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
  {
    id: "edselosaurus",
    story:
      "埃德蒙顿龙的颌中密布上千颗牙齿组成的“齿系”，专磨坚韧植物；1908 年出土的著名“木乃伊”化石保留了皮肤印痕，还有标本头骨里嵌着霸王龙的断牙。",
    name: "埃德蒙顿龙",
    nameEn: "Edmontosaurus",
    era: "中生代",
    period: "6800万年前",
    keyTraits: ["大型鸭嘴龙", "群居迁徙"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "鸟臀目" },
    extinct: true,
  },
];
