import type { Species } from "./types";

export const PALEOZOIC_SPECIES: Species[] = [
  {
    id: "coral",
    story:
      "每只珊瑚虫只有米粒大小，却能层层堆叠出地球上最大的生命建筑——大堡礁绵延 2000 多公里，是唯一能从太空肉眼看见的生物结构。",
    name: "珊瑚",
    nameEn: "Coral",
    era: "古生代",
    period: "5亿年前",
    keyTraits: ["造礁生物", "共生光合作用"],
    taxonomy: { kingdom: "动物界", phylum: "刺胞动物门" },
    extinct: false,
  },
  {
    id: "nautilus",
    story:
      "鹦鹉螺的外壳是一条完美的对数螺线，内部隔成数十个气室，靠调节气体浮沉于深海——这套设计已沿用五亿多年几乎未变。",
    name: "鹦鹉螺",
    nameEn: "Nautilus",
    era: "古生代",
    period: "5亿年前",
    keyTraits: ["活化石", "珍珠层外壳"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: false,
  },
  {
    id: "eurypterid",
    story: "广翅鲎是史上最大的节肢动物之一，最大的莱茵蝎体长超过 2.5 米，是古生代海洋的恐怖猎手。",
    name: "广翅鲎",
    nameEn: "Eurypterid",
    era: "古生代",
    period: "4.6亿年前",
    keyTraits: ["已知最大节肢动物之一", "海蝎子"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "horseshoe-crab",
    story:
      "鲎的蓝色血液含独特的凝血因子，至今仍被制药业用来检测疫苗与注射剂中的细菌内毒素——几乎每一支上市疫苗都受过这种 4 亿年古老血液的检验。",
    name: "鲎",
    nameEn: "Horseshoe Crab",
    era: "古生代",
    period: "4.5亿年前",
    keyTraits: ["活化石", "蓝色血液", "四亿年未大变"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: false,
  },
  {
    id: "coelacanth",
    story:
      "学界以为腔棘鱼随恐龙在 6600 万年前一同灭绝，直到 1938 年一条活体在南非渔获中被认出——这被誉为 20 世纪最轰动的动物学发现。",
    name: "腔棘鱼",
    nameEn: "Coelacanth",
    era: "古生代",
    period: "4亿年前",
    keyTraits: ["活化石", "肉鳍鱼类", "被认为已灭绝后重新发现"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: false,
  },
  {
    id: "austColobus",
    story:
      "澳洲肺鱼所属的属一亿多年来几乎没有改变，是地球上最古老的脊椎动物属之一，水质恶化时它还能用一片单肺直接呼吸空气。",
    name: "澳洲肺鱼",
    nameEn: "Australian Lungfish",
    era: "古生代",
    period: "4亿年前",
    keyTraits: ["活化石", "能用肺呼吸空气"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: false,
  },
  {
    id: "octopus",
    story:
      "章鱼约三分之二的神经元不在脑中，而是分散在八条腕里，每条腕几乎能独立感知与决策——相当于身上带着九个互相协作的“大脑”。",
    name: "章鱼",
    nameEn: "Octopus",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["极高智力", "三颗心脏", "蓝色血液"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: false,
  },
  {
    id: "jaekelopterus",
    story:
      "科学家仅凭德国出土的一只 46 厘米长的螯肢化石，便推算出莱茵蝎体长可达 2.5 米——它一度被认定为有史以来最大的节肢动物。",
    name: "莱茵蝎",
    nameEn: "Jaekelopterus",
    era: "古生代",
    period: "3.9亿年前",
    keyTraits: ["已知最大节肢动物", "2.5米长"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "bothriolepis",
    story:
      "沟鳞鱼是史上分布最广的盾皮鱼，超过 100 个种的化石几乎遍布每一块大陆，连南极洲也有它的踪迹，胸鳍还包在一对骨质长管里。",
    name: "沟鳞鱼",
    nameEn: "Bothriolepis",
    era: "古生代",
    period: "3.8亿年前",
    keyTraits: ["甲胄鱼类", "泥盆纪"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "tiktaalik",
    story:
      "“鱼类登陆”的关键过渡化石：既有鳃和鳞，又长出能撑起身体的肢状鳍。2004 年在加拿大北极的发现，完美填补了水生到陆生的演化空缺。",
    name: "提塔利克鱼",
    nameEn: "Tiktaalik",
    era: "古生代",
    period: "3.75亿年前",
    keyTraits: ["鱼类到四足类的过渡物种", "有肺和鳍肢"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: true,
  },
  {
    id: "ichthyostega",
    story:
      "鱼石螈是最早长出四肢的脊椎动物之一，但它其实还不会真正“走路”——桨状的四肢更适合划水，上岸时只能像海豹一样拖着身子蹭行。",
    name: "鱼石螈",
    nameEn: "Ichthyostega",
    era: "古生代",
    period: "3.65亿年前",
    keyTraits: ["最早登陆的四足动物之一", "鱼类到两栖类的过渡"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "两栖纲" },
    extinct: true,
  },
  {
    id: "dunkleosteus",
    story:
      "邓氏鱼没有真正的牙齿，靠上下颌两对自我磨锐的骨质刃片像断头台一样剪碎猎物，是泥盆纪海洋当之无愧的顶级杀手。",
    name: "邓氏鱼",
    nameEn: "Dunkleosteus",
    era: "古生代",
    period: "3.6亿年前",
    keyTraits: ["泥盆纪顶级掠食者", "装甲头甲", "强大咬合力"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "盾皮鱼纲" },
    extinct: true,
  },
  {
    id: "dunkleosteus-terrelli",
    story:
      "泰瑞尔邓氏鱼咬合力约 5300 牛顿，是已测得最强的鱼类咬合，可与大型鳄鱼乃至霸王龙相提并论，能瞬间把猎物拦腰咬断。",
    name: "邓氏鱼（泰瑞尔种）",
    nameEn: "Dunkleosteus terrelli",
    era: "古生代",
    period: "3.6亿年前",
    keyTraits: ["泥盆纪海洋霸主", "装甲头部"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "盾皮鱼纲" },
    extinct: true,
  },
  {
    id: "carboniferous-scorpion",
    story:
      "石炭纪的肺蝎体长可达 70 厘米，是当时巨型陆地掠食者之一——石炭纪富氧的大气支持了节肢动物的巨型化，让蝎子也能长到如此惊人的尺寸。",
    name: "石炭纪蝎子",
    nameEn: "Carboniferous Scorpion",
    era: "古生代",
    period: "3.3亿年前",
    keyTraits: ["高氧环境下的巨型节肢动物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "lepidodendron",
    story:
      "鳞木其实不是真正的树，而是一种高达数十米的巨型石松，体内几乎没有木质、全靠软组织支撑，它们倒下堆积成了今天大量的煤炭。",
    name: "鳞木",
    nameEn: "Lepidodendron",
    era: "古生代",
    period: "3.2亿年前",
    keyTraits: ["石炭纪巨型蕨类", "高达40米"],
    taxonomy: { kingdom: "植物界", phylum: "石松门" },
    extinct: true,
  },
  {
    id: "meganeura",
    story:
      "石炭纪的高氧大气催生了翼展近 70 厘米的巨脉蜻蜓——史上最大的飞行昆虫，它的体型本身就是远古氧气浓度的活记录。",
    name: "巨脉蜻蜓",
    nameEn: "Meganeura",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["翼展可达70厘米", "石炭纪巨型昆虫"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门", class: "昆虫纲" },
    extinct: true,
  },
  {
    id: "arthropleura",
    story:
      "节胸蜈蚣是史上最大的陆地无脊椎动物，体长约 2.6 米、体重近 50 公斤，几乎和一辆小汽车一样长，超越海蝎成为这一纪录的保持者。",
    name: "节胸蜈蚣",
    nameEn: "Arthropleura",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["已知最大陆地节肢动物", "长达2.5米"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "edaphosaurus",
    story:
      "基龙是最早的大型植食性陆生脊椎动物之一，背帆上还长着异齿龙没有的横向小棘——它代表了哺乳类祖先里最早“吃素”的一批先驱。",
    name: "基龙",
    nameEn: "Edaphosaurus",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["帆状背棘", "植食性合弓纲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
  {
    id: "dimetrodon",
    story:
      "异齿龙常被误当成恐龙，其实它是更接近哺乳动物的合弓纲，而且早在第一批恐龙登场前约 4000 万年就已灭绝。",
    name: "异齿龙",
    nameEn: "Dimetrodon",
    era: "古生代",
    period: "2.95亿年前",
    keyTraits: ["帆状背棘调节体温", "非恐龙的合弓纲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
  {
    id: "helicoprion",
    story: "下颌长着一圈螺旋排列的牙齿“齿轮”，其复原方式曾困惑学界整整一个世纪。",
    name: "旋齿鲨",
    nameEn: "Helicoprion",
    era: "古生代",
    period: "2.7亿年前",
    keyTraits: ["螺旋形齿列", "神秘的古生物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "gorgonopsid",
    story:
      "丽齿兽是地球上最早演化出剑齿的掠食者，犬齿长达十几厘米，称霸二叠纪末，最终随“大灭绝”——史上最惨烈的物种灭绝事件——一同消失。",
    name: "丽齿兽",
    nameEn: "Gorgonopsid",
    era: "古生代",
    period: "2.6亿年前",
    keyTraits: ["二叠纪顶级掠食者", "犬齿发达"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
];
