import type { Species } from "./types";

export const PALEOZOIC_SPECIES: Species[] = [
  {
    id: "coral",
    name: "珊瑚",
    nameEn: "Coral",
    era: "古生代",
    period: "5亿年前",
    keyTraits: ["造礁生物", "共生光合作用"],
    taxonomy: { kingdom: "动物界", phylum: "刺胞动物门" },
    extinct: false,
  },
  {
    id: "nautilus",
    name: "鹦鹉螺",
    nameEn: "Nautilus",
    era: "古生代",
    period: "5亿年前",
    keyTraits: ["活化石", "珍珠层外壳"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: false,
  },
  {
    id: "eurypterid",
    story: "广翅鲎是史上最大的节肢动物之一，最大的莱茵蝎体长超过 2.5 米，是古生代海洋的恐怖猎手。",
    name: "广翅鲎",
    nameEn: "Eurypterid",
    era: "古生代",
    period: "4.6亿年前",
    keyTraits: ["已知最大节肢动物之一", "海蝎子"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "horseshoe-crab",
    story:
      "鲎的蓝色血液含独特的凝血因子，至今仍被制药业用来检测疫苗与注射剂中的细菌内毒素——几乎每一支上市疫苗都受过这种 4 亿年古老血液的检验。",
    name: "鲎",
    nameEn: "Horseshoe Crab",
    era: "古生代",
    period: "4.5亿年前",
    keyTraits: ["活化石", "蓝色血液", "四亿年未大变"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: false,
  },
  {
    id: "coelacanth",
    name: "腔棘鱼",
    nameEn: "Coelacanth",
    era: "古生代",
    period: "4亿年前",
    keyTraits: ["活化石", "肉鳍鱼类", "被认为已灭绝后重新发现"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: false,
  },
  {
    id: "austColobus",
    name: "澳洲肺鱼",
    nameEn: "Australian Lungfish",
    era: "古生代",
    period: "4亿年前",
    keyTraits: ["活化石", "能用肺呼吸空气"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: false,
  },
  {
    id: "octopus",
    name: "章鱼",
    nameEn: "Octopus",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["极高智力", "三颗心脏", "蓝色血液"],
    taxonomy: { kingdom: "动物界", phylum: "软体动物门", class: "头足纲" },
    extinct: false,
  },
  {
    id: "jaekelopterus",
    name: "莱茵蝎",
    nameEn: "Jaekelopterus",
    era: "古生代",
    period: "3.9亿年前",
    keyTraits: ["已知最大节肢动物", "2.5米长"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "bothriolepis",
    name: "沟鳞鱼",
    nameEn: "Bothriolepis",
    era: "古生代",
    period: "3.8亿年前",
    keyTraits: ["甲胄鱼类", "泥盆纪"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "tiktaalik",
    story:
      "“鱼类登陆”的关键过渡化石：既有鳃和鳞，又长出能撑起身体的肢状鳍。2004 年在加拿大北极的发现，完美填补了水生到陆生的演化空缺。",
    name: "提塔利克鱼",
    nameEn: "Tiktaalik",
    era: "古生代",
    period: "3.75亿年前",
    keyTraits: ["鱼类到四足类的过渡物种", "有肺和鳍肢"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "肉鳍鱼纲" },
    extinct: true,
  },
  {
    id: "ichthyostega",
    name: "鱼石螈",
    nameEn: "Ichthyostega",
    era: "古生代",
    period: "3.65亿年前",
    keyTraits: ["最早登陆的四足动物之一", "鱼类到两栖类的过渡"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "两栖纲" },
    extinct: true,
  },
  {
    id: "dunkleosteus",
    name: "邓氏鱼",
    nameEn: "Dunkleosteus",
    era: "古生代",
    period: "3.6亿年前",
    keyTraits: ["泥盆纪顶级掠食者", "装甲头甲", "强大咬合力"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "盾皮鱼纲" },
    extinct: true,
  },
  {
    id: "dunkleosteus-terrelli",
    name: "邓氏鱼（泰瑞尔种）",
    nameEn: "Dunkleosteus terrelli",
    era: "古生代",
    period: "3.6亿年前",
    keyTraits: ["泥盆纪海洋霸主", "装甲头部"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "盾皮鱼纲" },
    extinct: true,
  },
  {
    id: "carboniferous-scorpion",
    name: "石炭纪蝎子",
    nameEn: "Carboniferous Scorpion",
    era: "古生代",
    period: "3.3亿年前",
    keyTraits: ["高氧环境下的巨型节肢动物"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "lepidodendron",
    name: "鳞木",
    nameEn: "Lepidodendron",
    era: "古生代",
    period: "3.2亿年前",
    keyTraits: ["石炭纪巨型蕨类", "高达40米"],
    taxonomy: { kingdom: "植物界", phylum: "石松门" },
    extinct: true,
  },
  {
    id: "meganeura",
    story:
      "石炭纪的高氧大气催生了翼展近 70 厘米的巨脉蜻蜓——史上最大的飞行昆虫，它的体型本身就是远古氧气浓度的活记录。",
    name: "巨脉蜻蜓",
    nameEn: "Meganeura",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["翼展可达70厘米", "石炭纪巨型昆虫"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门", class: "昆虫纲" },
    extinct: true,
  },
  {
    id: "arthropleura",
    name: "节胸蜈蚣",
    nameEn: "Arthropleura",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["已知最大陆地节肢动物", "长达2.5米"],
    taxonomy: { kingdom: "动物界", phylum: "节肢动物门" },
    extinct: true,
  },
  {
    id: "edaphosaurus",
    name: "基龙",
    nameEn: "Edaphosaurus",
    era: "古生代",
    period: "3亿年前",
    keyTraits: ["帆状背棘", "植食性合弓纲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
  {
    id: "dimetrodon",
    name: "异齿龙",
    nameEn: "Dimetrodon",
    era: "古生代",
    period: "2.95亿年前",
    keyTraits: ["帆状背棘调节体温", "非恐龙的合弓纲"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
  {
    id: "helicoprion",
    story: "下颌长着一圈螺旋排列的牙齿“齿轮”，其复原方式曾困惑学界整整一个世纪。",
    name: "旋齿鲨",
    nameEn: "Helicoprion",
    era: "古生代",
    period: "2.7亿年前",
    keyTraits: ["螺旋形齿列", "神秘的古生物"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门" },
    extinct: true,
  },
  {
    id: "gorgonopsid",
    name: "丽齿兽",
    nameEn: "Gorgonopsid",
    era: "古生代",
    period: "2.6亿年前",
    keyTraits: ["二叠纪顶级掠食者", "犬齿发达"],
    taxonomy: { kingdom: "动物界", phylum: "脊索动物门", class: "合弓纲" },
    extinct: true,
  },
];
