export const ECONOMICS_CONCEPTS_DATA = [
  {
    slug: "creative-destruction",
    title: "创造性破坏",
    subtitle: "Creative Destruction",
    field: "经济发展与创新",
  },
  { slug: "elasticity", title: "弹性", subtitle: "Elasticity", field: "微观经济学" },
  {
    slug: "environmental-economics",
    title: "环境经济学",
    subtitle: "Environmental Economics",
    field: "微观经济学",
  },
  { slug: "externalities", title: "外部性", subtitle: "Externalities", field: "微观经济学" },
  {
    slug: "gdp",
    title: "GDP（国内生产总值）",
    subtitle: "Gross Domestic Product",
    field: "宏观经济学",
  },
  {
    slug: "gini-coefficient",
    title: "基尼系数",
    subtitle: "Gini Coefficient",
    field: "收入分配与不平等",
  },
  {
    slug: "industrial-organization",
    title: "产业组织理论",
    subtitle: "Industrial Organization",
    field: "微观经济学",
  },
  { slug: "inflation", title: "通货膨胀", subtitle: "Inflation", field: "宏观经济学" },
  {
    slug: "labor-economics",
    title: "劳动经济学",
    subtitle: "Labor Economics",
    field: "微观经济学",
  },
  { slug: "moral-hazard", title: "道德风险", subtitle: "Moral Hazard", field: "信息经济学" },
  { slug: "nash-equilibrium", title: "纳什均衡", subtitle: "Nash Equilibrium", field: "博弈论" },
  {
    slug: "opportunity-cost",
    title: "机会成本",
    subtitle: "Opportunity Cost",
    field: "微观经济学",
  },
  {
    slug: "public-choice-theory",
    title: "公共选择理论",
    subtitle: "Public Choice Theory",
    field: "政治经济学",
  },
  {
    slug: "tragedy-of-commons",
    title: "公地悲剧",
    subtitle: "Tragedy of the Commons",
    field: "环境经济学",
  },
] as const;
