// AUTO-GENERATED by scripts/gen-econ-index.ts (pnpm gen-econ) — do not edit by hand.
// Search mirror of content/economics/*/*.mdx.
export const ECONOMICS_DEBATES_DATA = [
  {
    slug: "basic-income-vs-job-guarantee",
    title: "基本收入还是就业保障：社会应当保证钱还是工作",
    titleEn: "Universal Basic Income vs. Job Guarantee",
    field: "",
    sides: [],
  },
  {
    slug: "carbon-tax-vs-cap-and-trade",
    title: "碳税还是总量交易：给污染定价的两条路",
    titleEn: "Carbon Tax vs. Cap and Trade",
    field: "",
    sides: [],
  },
  {
    slug: "cryptocurrency-debate",
    title: "加密货币：革命还是骗局？",
    titleEn: "Cryptocurrency: Revolution or Scam?",
    field: "",
    sides: [],
  },
  {
    slug: "free-market-vs-intervention",
    title: "自由市场 vs 政府干预",
    titleEn: "Free Market vs Government Intervention",
    field: "",
    sides: [],
  },
  {
    slug: "free-trade-fair-trade",
    title: "自由贸易vs公平贸易",
    titleEn: "Free Trade vs Fair Trade",
    field: "",
    sides: [],
  },
  {
    slug: "inequality-growth",
    title: "不平等与增长：皮凯蒂争论",
    titleEn: "Inequality and Growth: The Piketty Debate",
    field: "",
    sides: [],
  },
  {
    slug: "keynes-vs-hayek",
    title: "凯恩斯vs哈耶克：政府干预之争",
    titleEn: "Keynes vs Hayek: The Debate on Government Intervention",
    field: "",
    sides: [],
  },
  {
    slug: "rational-expectations",
    title: "理性预期vs适应性预期",
    titleEn: "Rational Expectations vs Adaptive Expectations",
    field: "",
    sides: [],
  },
  {
    slug: "rent-control-affordability-supply",
    title: "租金管制之争：可负担性、居住稳定与住房供给",
    titleEn: "Rent Control: Affordability, Stability, and Housing Supply",
    field: "",
    sides: [],
  },
];
