// AUTO-GENERATED by scripts/gen-econ-index.ts (pnpm gen-econ) — do not edit by hand.
// Search mirror of content/economics/*/*.mdx.
export const ECONOMICS_DIALOGUES_DATA = [
  {
    slug: "friedman-kaldor-monetarism",
    title: "弗里德曼 vs 卡尔多论货币主义",
    titleEn: "Friedman vs Kaldor: The Monetarism Debate",
    field: "",
    participants: [],
  },
  {
    slug: "hardin-ostrom-commons",
    title: "哈丁vs奥斯特罗姆：公地一定会毁灭吗",
    titleEn: "Hardin vs. Ostrom: Must the Commons Collapse",
    field: "",
    participants: [],
  },
  {
    slug: "kahneman-thaler-nudge",
    title: "卡尼曼vs塞勒：助推的伦理",
    titleEn: "Kahneman vs Thaler: The Ethics of Nudging",
    field: "",
    participants: [],
  },
  {
    slug: "keynes-hayek-intervention",
    title: "凯恩斯vs哈耶克：政府应该干预吗",
    titleEn: "Keynes vs Hayek: Should the Government Intervene",
    field: "",
    participants: [],
  },
  {
    slug: "minsky-fama-financial-stability",
    title: "明斯基与法玛对话：价格有效，金融为何仍会崩溃",
    titleEn: "Minsky and Fama: Efficient Prices and Financial Instability",
    field: "",
    participants: [],
  },
  {
    slug: "pigou-coase-externalities",
    title: "庇古vs科斯：污染应该由谁付钱",
    titleEn: "Pigou vs. Coase: Who Should Pay for Externalities",
    field: "",
    participants: [],
  },
  {
    slug: "piketty-mankiw-inequality",
    title: "皮凯蒂 vs 曼昆论不平等",
    titleEn: "Piketty vs Mankiw: Inequality Debate",
    field: "",
    participants: [],
  },
  {
    slug: "piketty-milanovic-inequality",
    title: "皮凯蒂vs米拉诺维奇：全球不平等的未来",
    titleEn: "Piketty vs Milanovic: The Future of Global Inequality",
    field: "",
    participants: [],
  },
  {
    slug: "smith-marx-capitalism",
    title: "亚当·斯密vs马克思：资本主义的本质",
    titleEn: "Adam Smith vs Karl Marx: The Nature of Capitalism",
    field: "",
    participants: [],
  },
];
