// AUTO-GENERATED by scripts/gen-econ-index.ts (pnpm gen-econ) — do not edit by hand.
// Search mirror of content/economics/*/*.mdx.
export const THEORIES_DATA = [
  {
    slug: "behavioral-economics-theory",
    title: "行为经济学理论",
    subtitle: "Behavioral Economics Theory",
    category: "行为",
  },
  {
    slug: "comparative-advantage",
    title: "比较优势理论",
    subtitle: "Comparative Advantage Theory",
    category: "国际",
  },
  {
    slug: "development-economics",
    title: "发展经济学",
    subtitle: "Development Economics",
    category: "发展经济学",
  },
  {
    slug: "economic-growth",
    title: "经济增长理论",
    subtitle: "Economic Growth Theory",
    category: "宏观",
  },
  {
    slug: "game-theory-basics",
    title: "博弈论基础",
    subtitle: "Game Theory Basics",
    category: "博弈论",
  },
  {
    slug: "heckscher-ohlin-model",
    title: "赫克歇尔-俄林模型",
    subtitle: "Heckscher-Ohlin Model",
    category: "国际",
  },
  {
    slug: "information-asymmetry",
    title: "信息不对称理论",
    subtitle: "Information Asymmetry Theory",
    category: "微观",
  },
  {
    slug: "institutional-economics",
    title: "制度经济学",
    subtitle: "Institutional Economics",
    category: "制度",
  },
  {
    slug: "keynesian-economics",
    title: "凯恩斯主义经济学",
    subtitle: "Keynesian Economics",
    category: "宏观",
  },
  {
    slug: "market-failures",
    title: "市场失灵理论",
    subtitle: "Market Failure Theory",
    category: "微观",
  },
  { slug: "monetarism", title: "货币主义", subtitle: "Monetarism", category: "宏观" },
  {
    slug: "prospect-theory-econ",
    title: "前景理论与经济学",
    subtitle: "Prospect Theory and Economics",
    category: "行为",
  },
  {
    slug: "supply-demand",
    title: "供需理论",
    subtitle: "Supply and Demand Theory",
    category: "微观",
  },
  {
    slug: "trade-theory",
    title: "国际贸易理论",
    subtitle: "International Trade Theory",
    category: "国际",
  },
];
