export type SoundKind = "consonant" | "vowel";
export type Voicing = "voiced" | "voiceless";

export interface IpaSound {
  symbol: string;
  kind: SoundKind;
  name: string;
  articulation: string;
  place: string;
  manner: string;
  voicing: Voicing;
  example: string;
  exampleLanguage: string;
  contrast: string;
  cue: string;
  x: number;
  y: number;
}

export const IPA_SOUNDS: readonly IpaSound[] = [
  {
    symbol: "p",
    kind: "consonant",
    name: "清双唇塞音",
    articulation: "双唇完全闭合积压气流，再突然释放；声带不持续振动。",
    place: "双唇",
    manner: "塞音",
    voicing: "voiceless",
    example: "英语 spin /spɪn/ 中的 /p/",
    exampleLanguage: "英语",
    contrast: "与 /b/ 共享部位和方法，主要差别是声带状态。",
    cue: "闭住双唇，再让气流短促释放。把手放在喉部，比较 /b/。",
    x: 18,
    y: 54,
  },
  {
    symbol: "b",
    kind: "consonant",
    name: "浊双唇塞音",
    articulation: "双唇完全闭合并释放；典型发音伴随声带振动。",
    place: "双唇",
    manner: "塞音",
    voicing: "voiced",
    example: "西班牙语 beso /ˈbeso/ 的词首 /b/",
    exampleLanguage: "西班牙语",
    contrast: "与 /p/ 的对比说明一个特征变化可以参与区别词项。",
    cue: "闭唇时尝试保持喉部振动，再释放气流。",
    x: 18,
    y: 54,
  },
  {
    symbol: "t",
    kind: "consonant",
    name: "清齿龈塞音",
    articulation: "舌尖或舌叶在齿龈附近形成完全闭塞，然后释放。",
    place: "齿龈",
    manner: "塞音",
    voicing: "voiceless",
    example: "西班牙语 todo /ˈtodo/ 中的 /t/",
    exampleLanguage: "西班牙语",
    contrast: "不同语言的 /t/ 可更靠牙齿或更靠齿龈，宽式符号隐藏了部分差异。",
    cue: "让舌尖接近上齿后方的隆起，短暂封住气流。",
    x: 38,
    y: 42,
  },
  {
    symbol: "d",
    kind: "consonant",
    name: "浊齿龈塞音",
    articulation: "舌尖或舌叶形成闭塞并释放，同时维持声带振动。",
    place: "齿龈",
    manner: "塞音",
    voicing: "voiced",
    example: "英语 day /deɪ/ 的词首 /d/",
    exampleLanguage: "英语",
    contrast: "与 /t/ 的清浊差异不是音量大小，而是喉部振动组织不同。",
    cue: "保持舌位不变，只比较喉部是否持续振动。",
    x: 38,
    y: 42,
  },
  {
    symbol: "k",
    kind: "consonant",
    name: "清软腭塞音",
    articulation: "舌背抬向软腭形成闭塞，再释放口腔气流。",
    place: "软腭",
    manner: "塞音",
    voicing: "voiceless",
    example: "西班牙语 casa /ˈkasa/ 的词首 /k/",
    exampleLanguage: "西班牙语",
    contrast: "实际接触位置会随相邻元音前后移动，这属于协同发音。",
    cue: "舌尖保持放松，注意舌背与口腔后部的接触。",
    x: 69,
    y: 39,
  },
  {
    symbol: "m",
    kind: "consonant",
    name: "浊双唇鼻音",
    articulation: "双唇闭合，软腭下降，使有声气流主要从鼻腔通过。",
    place: "双唇",
    manner: "鼻音",
    voicing: "voiced",
    example: "斯瓦希里语 mtoto /mtoto/ 的词首 /m/",
    exampleLanguage: "斯瓦希里语",
    contrast: "与 /b/ 都闭唇，但鼻音开放鼻腔通道。",
    cue: "持续发音时轻触鼻翼，可感到振动；捏鼻会明显改变声音。",
    x: 18,
    y: 54,
  },
  {
    symbol: "n",
    kind: "consonant",
    name: "浊齿龈鼻音",
    articulation: "舌尖在齿龈附近闭塞，软腭下降，让气流从鼻腔通过。",
    place: "齿龈",
    manner: "鼻音",
    voicing: "voiced",
    example: "日语 neko /neko/ 的词首 /n/",
    exampleLanguage: "日语",
    contrast: "与 /m/ 的主要差别在口腔闭塞位置，而非鼻腔是否开放。",
    cue: "保持鼻腔通气，把闭塞从双唇移到上齿后方。",
    x: 38,
    y: 42,
  },
  {
    symbol: "ŋ",
    kind: "consonant",
    name: "浊软腭鼻音",
    articulation: "舌背接触软腭，软腭同时下降，形成后部鼻音。",
    place: "软腭",
    manner: "鼻音",
    voicing: "voiced",
    example: "普通话 英 yīng /iŋ/ 的韵尾",
    exampleLanguage: "普通话",
    contrast: "许多语言允许 /ŋ/ 在词尾，却不一定允许它在词首。",
    cue: "从 /n/ 开始，把闭塞位置向后移到舌背。",
    x: 69,
    y: 39,
  },
  {
    symbol: "f",
    kind: "consonant",
    name: "清唇齿擦音",
    articulation: "下唇接近上齿，窄缝使气流产生持续摩擦噪声。",
    place: "唇齿",
    manner: "擦音",
    voicing: "voiceless",
    example: "法语 feu /fø/ 的词首 /f/",
    exampleLanguage: "法语",
    contrast: "擦音保持窄缝，塞音则先完全封闭气流。",
    cue: "不要咬紧下唇；保留窄缝，让气流持续通过。",
    x: 25,
    y: 49,
  },
  {
    symbol: "s",
    kind: "consonant",
    name: "清齿龈擦音",
    articulation: "舌尖附近形成狭窄通道，气流朝牙齿方向产生高频噪声。",
    place: "齿龈",
    manner: "擦音",
    voicing: "voiceless",
    example: "斯瓦希里语 sasa /sasa/ 中的 /s/",
    exampleLanguage: "斯瓦希里语",
    contrast: "与 /ʃ/ 的区别包含舌位、唇形和噪声频谱变化。",
    cue: "保持通道狭窄但不要完全堵住，观察声音能否持续。",
    x: 40,
    y: 44,
  },
  {
    symbol: "ʃ",
    kind: "consonant",
    name: "清龈后擦音",
    articulation: "舌叶在齿龈后方形成窄缝，通常伴随一定的唇部收拢。",
    place: "龈后",
    manner: "擦音",
    voicing: "voiceless",
    example: "英语 ship /ʃɪp/ 的词首 /ʃ/",
    exampleLanguage: "英语",
    contrast: "相对 /s/，主要收窄位置更靠后，噪声重心通常更低。",
    cue: "从 /s/ 开始把舌叶略向后移，比较噪声质感。",
    x: 49,
    y: 40,
  },
  {
    symbol: "x",
    kind: "consonant",
    name: "清软腭擦音",
    articulation: "舌背接近软腭但不完全闭塞，让气流在后部形成摩擦。",
    place: "软腭",
    manner: "擦音",
    voicing: "voiceless",
    example: "德语 Bach /bax/ 的词尾 /x/",
    exampleLanguage: "德语",
    contrast: "与 /k/ 部位接近，但 /x/ 保留窄缝并可持续。",
    cue: "让舌背靠近软腭，维持气流而不要形成完整闭塞。",
    x: 69,
    y: 39,
  },
  {
    symbol: "i",
    kind: "vowel",
    name: "闭前不圆唇元音",
    articulation: "舌身前部抬高，嘴唇不圆；口腔保持开放而无摩擦。",
    place: "前",
    manner: "闭",
    voicing: "voiced",
    example: "西班牙语 sí /si/ 中的 /i/",
    exampleLanguage: "西班牙语",
    contrast: "与 /u/ 都是闭元音，但舌位前后和圆唇状态不同。",
    cue: "舌前部抬高但不接触上腭，保持嘴唇舒展。",
    x: 35,
    y: 35,
  },
  {
    symbol: "y",
    kind: "vowel",
    name: "闭前圆唇元音",
    articulation: "保持接近 /i/ 的舌位，同时把嘴唇收圆。",
    place: "前",
    manner: "闭",
    voicing: "voiced",
    example: "法语 tu /ty/ 中的 /y/",
    exampleLanguage: "法语",
    contrast: "与 /i/ 的关键对比是圆唇，与 /u/ 的关键对比是舌位前后。",
    cue: "先保持 /i/ 的舌位，再只改变唇形。",
    x: 35,
    y: 35,
  },
  {
    symbol: "ə",
    kind: "vowel",
    name: "中央元音",
    articulation: "舌位接近口腔中央，常见于非重读或弱化位置，但分布因语言而异。",
    place: "中央",
    manner: "中",
    voicing: "voiced",
    example: "英语 about /əˈbaʊt/ 的词首元音",
    exampleLanguage: "英语",
    contrast: "它不是所有语言共有的“懒音”；有些语言把中央元音用于稳定对立。",
    cue: "放松舌身和嘴唇，注意不要把它等同于某个汉字读音。",
    x: 53,
    y: 49,
  },
  {
    symbol: "a",
    kind: "vowel",
    name: "开前不圆唇元音",
    articulation: "舌身较低且偏前，口腔开放，嘴唇通常不圆。",
    place: "前",
    manner: "开",
    voicing: "voiced",
    example: "西班牙语 casa /ˈkasa/ 中的 /a/",
    exampleLanguage: "西班牙语",
    contrast: "IPA 元音图的位置是约定的发音空间，不是舌头轮廓的精确照片。",
    cue: "降低舌身并打开下颌，避免产生咽部摩擦。",
    x: 40,
    y: 65,
  },
  {
    symbol: "ɯ",
    kind: "vowel",
    name: "闭后不圆唇元音",
    articulation: "舌身后部抬高，但嘴唇保持不圆。",
    place: "后",
    manner: "闭",
    voicing: "voiced",
    example: "土耳其语 kız /kɯz/ 中的 /ɯ/",
    exampleLanguage: "土耳其语",
    contrast: "与 /u/ 舌位相近，主要区别是唇形。",
    cue: "先尝试 /u/ 的舌位，再展开嘴唇而尽量不移动舌头。",
    x: 67,
    y: 35,
  },
  {
    symbol: "u",
    kind: "vowel",
    name: "闭后圆唇元音",
    articulation: "舌身后部抬高，嘴唇收圆，口腔无明显阻塞。",
    place: "后",
    manner: "闭",
    voicing: "voiced",
    example: "日语 数 sū /sɯː/ 常转写为接近 /ɯ/；西班牙语 tú /tu/ 展示 /u/",
    exampleLanguage: "西班牙语（对照日语）",
    contrast: "宽式 /u/ 覆盖的实际音质会随语言和说话者变化。",
    cue: "抬高舌后部并收圆嘴唇，避免形成摩擦。",
    x: 67,
    y: 35,
  },
];

export function getIpaSounds(kind: SoundKind): readonly IpaSound[] {
  return IPA_SOUNDS.filter((sound) => sound.kind === kind);
}
