export type WritingTimelineEraId = "origins" | "networks" | "community" | "digital";
export type WritingTimelineRelation =
  | "emergence"
  | "adaptation"
  | "institution"
  | "community-invention"
  | "digital-encoding";

export type WritingTimelineEvent = {
  id: string;
  year: number;
  dateLabel: string;
  title: string;
  localLabel?: string;
  region: string;
  era: WritingTimelineEraId;
  relation: WritingTimelineRelation;
  summary: string;
  relationSummary: string;
  evidence: string;
  caution: string;
  sourceLabel: string;
  sourceUrl: string;
};

export const WRITING_TIMELINE_ERAS: readonly {
  id: WritingTimelineEraId;
  label: string;
  span: string;
  thesis: string;
}[] = [
  {
    id: "origins",
    label: "早期形成",
    span: "约前 3400—前 500",
    thesis: "多个地区把语言、数量与制度记忆转成可重复的视觉记录。",
  },
  {
    id: "networks",
    label: "传播与改造",
    span: "前 499—1499",
    thesis: "文字沿贸易、宗教和国家网络传播，并为不同语言重组。",
  },
  {
    id: "community",
    label: "社群创制",
    span: "1500—1986",
    thesis: "社群在殖民、教育与身份压力中主动创造和标准化文字。",
  },
  {
    id: "digital",
    label: "数字基础设施",
    span: "1987—现在",
    thesis: "编码只是起点，字体、键盘、塑形和平台治理决定实际可用性。",
  },
] as const;

export const WRITING_RELATION_LABELS: Record<WritingTimelineRelation, string> = {
  emergence: "早期形成",
  adaptation: "谱系改造",
  institution: "制度标准化",
  "community-invention": "社群创制",
  "digital-encoding": "数字编码",
};

export const WRITING_TIMELINE_EVENTS: readonly WritingTimelineEvent[] = [
  {
    id: "uruk-protocuneiform",
    year: -3400,
    dateLabel: "约前 3400",
    title: "乌鲁克原始楔形文字",
    region: "西亚",
    era: "origins",
    relation: "emergence",
    summary: "泥板上的数量、物品和行政记号逐步形成可记录语言的楔形传统。",
    relationSummary: "从记账与行政分类进入稳定符号序列，后续发展为苏美尔语、阿卡德语等书写系统。",
    evidence: "乌鲁克晚期分层出土泥板、符号序列与后续楔形文献提供连续证据。",
    caution: "最早泥板能在多大程度上编码完整语言仍有争论，不能把会计标记直接等同成熟文字。",
    sourceLabel: "CDLI · Proto-cuneiform",
    sourceUrl: "https://cdli.mpiwg-berlin.mpg.de/",
  },
  {
    id: "early-egyptian",
    year: -3200,
    dateLabel: "约前 3200",
    title: "早期埃及文字",
    region: "东北非",
    era: "origins",
    relation: "emergence",
    summary: "标签、器物和墓葬材料展示图形符号向语音与词语记录系统发展。",
    relationSummary: "埃及传统形成语词符号、辅音符号与限定符协作的系统，并长期跨越碑铭与草写媒介。",
    evidence: "阿拜多斯等遗址的可断代标签和早王朝铭文构成主要材料。",
    caution: "与美索不达米亚是否存在刺激扩散仍未定论，不应画成已证明的单向借用箭头。",
    sourceLabel: "The British Museum · Egyptian writing",
    sourceUrl: "https://www.britishmuseum.org/collection/galleries/egyptian-sculpture",
  },
  {
    id: "oracle-bone-writing",
    year: -1250,
    dateLabel: "约前 1250",
    title: "商代晚期甲骨文",
    localLabel: "甲骨文",
    region: "东亚",
    era: "origins",
    relation: "emergence",
    summary: "占卜记录显示成熟汉字系统，已系统结合意义、读音与句法表达。",
    relationSummary: "它不是现代汉字的图画清单，而是形声、借用和语词记录已经运作的历史层。",
    evidence: "安阳殷墟出土甲骨的考古语境、成组卜辞和后世字形对应支持释读。",
    caution: "现存成熟材料不是汉字发明时刻，更早发展阶段仍受材料保存限制。",
    sourceLabel: "UNESCO Memory of the World · Oracle Bone Inscriptions",
    sourceUrl: "https://www.unesco.org/en/memory-world",
  },
  {
    id: "phoenician-consonantal",
    year: -1050,
    dateLabel: "约前 1050",
    title: "腓尼基辅音字母传统",
    region: "东地中海",
    era: "origins",
    relation: "adaptation",
    summary: "约二十余个辅音字母支持跨城市书写，并影响多条地中海与西亚字母谱系。",
    relationSummary: "它继承更早西北闪米特字母传统，不是由象形文字一步跳成现代字母。",
    evidence: "比布鲁斯、腓尼基城市与殖民网络中的碑铭可比较字母形体和顺序。",
    caution: "“第一个字母”取决于如何定义字母和材料年代；更早原始西奈与乌加里特传统不能忽略。",
    sourceLabel: "Unicode · Early alphabetic scripts",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/",
  },
  {
    id: "greek-vowel-letters",
    year: -800,
    dateLabel: "约前 800",
    title: "希腊字母重分配元音",
    region: "地中海",
    era: "origins",
    relation: "adaptation",
    summary: "希腊使用者改造腓尼基字母，把部分不需要的辅音符号重新用于元音。",
    relationSummary: "改造服务希腊语音系，并经多条地区字母传统影响伊特鲁里亚和拉丁文字。",
    evidence: "公元前八世纪地区碑铭展示不同字母形体、方向与逐步标准化。",
    caution: "元音书写不是文字复杂度的普遍终点；辅音文字和元音附标文字同样能完整服务语言。",
    sourceLabel: "Unicode · European alphabetic scripts",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/",
  },
  {
    id: "mesoamerican-writing",
    year: -500,
    dateLabel: "约前 500 及更早候选",
    title: "中部美洲文字传统",
    region: "美洲",
    era: "origins",
    relation: "emergence",
    summary: "萨波特克、地峡与玛雅等传统以不同方式记录名称、日期、政治与语言。",
    relationSummary: "中部美洲展示与旧大陆文字无已知谱系联系的本地形成和区域互动。",
    evidence: "有考古语境的碑铭、历法符号与可读玛雅语词提供不同强度证据。",
    caution: "各传统不能压成一套“玛雅文字”；最早候选材料的年代和是否构成文字仍有争论。",
    sourceLabel: "Maya Decipherment resources",
    sourceUrl: "https://www.mesoweb.com/",
  },
  {
    id: "ashokan-brahmi",
    year: -250,
    dateLabel: "前 3 世纪",
    title: "阿育王敕令中的婆罗米文",
    region: "南亚",
    era: "networks",
    relation: "institution",
    summary: "跨广大地区的敕令提供婆罗米文字最早成组长篇证据，并展示地区变体。",
    relationSummary: "婆罗米系后来分化为南亚和东南亚众多元音附标文字。",
    evidence: "可定位石柱、岩刻和语言变体支持字形、方向与行政传播研究。",
    caution: "婆罗米的形成过程及与闪米特文字的关系仍有争论，敕令年代不是必然发明日期。",
    sourceLabel: "Unicode · South and Central Asia",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-14/",
  },
  {
    id: "ethiopic-abugida",
    year: 350,
    dateLabel: "约 4 世纪",
    title: "埃塞俄比亚文字元音化",
    localLabel: "Fidäl",
    region: "非洲之角",
    era: "networks",
    relation: "adaptation",
    summary: "吉兹文字从辅音传统发展出按系列改变基本字形来表示元音的系统。",
    relationSummary: "后续服务吉兹礼仪与阿姆哈拉语、提格利尼亚语等现代语言。",
    evidence: "阿克苏姆碑铭与手稿展示从未元音化到元音系列的历史变化。",
    caution: "结构变化不能仅归因宗教转换，地区书写和语言需求也参与塑造。",
    sourceLabel: "Unicode · Ethiopic",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/",
  },
  {
    id: "arabic-standardization",
    year: 650,
    dateLabel: "7—8 世纪",
    title: "阿拉伯文字扩展与附标",
    region: "西亚与北非",
    era: "networks",
    relation: "institution",
    summary: "早期伊斯兰文书、古兰经抄本与行政网络推动字形、点和读音附标发展。",
    relationSummary: "阿拉伯文字随后被波斯语、乌尔都语及许多非洲和亚洲语言持续改造。",
    evidence: "有年代抄本、碑铭、纸草与后续正字法传统可交叉比较。",
    caution: "标准化不是一次完成，早期抄本的点、元音和字形存在显著差异。",
    sourceLabel: "Unicode · Arabic",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-9/",
  },
  {
    id: "japanese-kana",
    year: 850,
    dateLabel: "约 8—10 世纪",
    title: "日本假名从汉字用法中形成",
    region: "东亚",
    era: "networks",
    relation: "adaptation",
    summary: "万叶假名的表音使用经草写和部件化发展为平假名、片假名传统。",
    relationSummary: "汉字与两套假名共同适配日语词汇、形态和语体，而非由假名完全取代汉字。",
    evidence: "歌集、佛教注音和书写风格展示不同路径与使用群体。",
    caution: "把平假名简单称为“女性文字”、片假名称为“男性文字”会固化复杂历史中的语体关联。",
    sourceLabel: "Unicode · Hiragana and Katakana",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-18/",
  },
  {
    id: "hangul-promulgation",
    year: 1446,
    dateLabel: "1446",
    title: "《训民正音》颁布",
    localLabel: "훈민정음",
    region: "东亚",
    era: "networks",
    relation: "institution",
    summary: "朝鲜王朝公布新文字，以发音特征组织辅音和元音，并组合成音节方块。",
    relationSummary: "国家设计、学者说明与后续社会采用共同形成今天的韩文传统。",
    evidence: "《训民正音》解例本明确记录设计原则、字母和使用目标。",
    caution: "颁布不等于立即普及；汉字、阶层、性别和出版制度长期影响使用范围。",
    sourceLabel: "UNESCO Memory of the World · Hunminjeongeum",
    sourceUrl: "https://www.unesco.org/en/memory-world",
  },
  {
    id: "cherokee-syllabary",
    year: 1821,
    dateLabel: "1821",
    title: "切罗基音节文字投入教学",
    localLabel: "ᏣᎳᎩ",
    region: "北美",
    era: "community",
    relation: "community-invention",
    summary: "Sequoyah 与切罗基社群建立并传播音节文字，迅速进入报刊、通信与公共生活。",
    relationSummary: "字符外形部分受印刷字母启发，语言单位与读值由切罗基语系统重新组织。",
    evidence: "早期教学、手稿和《Cherokee Phoenix》报纸记录采用过程。",
    caution: "个人创制叙事不能遮蔽社群试用、教师、印刷和政治制度的共同作用。",
    sourceLabel: "Unicode · Cherokee",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/",
  },
  {
    id: "vai-syllabary",
    year: 1833,
    dateLabel: "约 1830 年代",
    title: "Vai 音节文字形成",
    localLabel: "ꕙꔤ",
    region: "西非",
    era: "community",
    relation: "community-invention",
    summary: "利比里亚与塞拉利昂的 Vai 使用者发展音节文字，用于通信、记账与文学。",
    relationSummary: "它在多文字贸易环境中形成，并经社群使用与二十世纪标准化持续调整。",
    evidence: "十九世纪记录、手稿、使用者叙述和后续字符表提供材料。",
    caution: "准确年份和个人贡献叙事存在版本差异，不应抹去集体传播。",
    sourceLabel: "Unicode · Vai",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/",
  },
  {
    id: "bamum-script",
    year: 1896,
    dateLabel: "约 1896—1910",
    title: "Bamum 文字连续改革",
    region: "中非",
    era: "community",
    relation: "community-invention",
    summary: "喀麦隆 Bamum 王国在 Njoya 统治时期多次调整符号，发展出教学和行政书写。",
    relationSummary: "系统从较多图形符号向更规则音节表演变，展示文字设计也会版本迭代。",
    evidence: "王国记录、字符表、学校与保存手稿可比较多个阶段。",
    caution: "殖民中断影响使用；今天的复兴不能只按历史宫廷规范衡量。",
    sourceLabel: "Unicode · Bamum",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/",
  },
  {
    id: "nko-creation",
    year: 1949,
    dateLabel: "1949",
    title: "N’Ko 为曼丁语言创制",
    localLabel: "ߒߞߏ",
    region: "西非",
    era: "community",
    relation: "community-invention",
    summary: "Solomana Kanté 设计从右向左的字母系统，随后形成跨国出版、教育和数字社群。",
    relationSummary: "字符与声调、元音设计回应曼丁语言需求，并通过学习网络获得生命。",
    evidence: "早期教材、出版物、使用者网络和现代数字文本记录传播。",
    caution: "N’Ko 与拉丁、Ajami 实践并存，不应把文字选择化约为传统与现代二选一。",
    sourceLabel: "Unicode · N’Ko",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/",
  },
  {
    id: "adlam-creation",
    year: 1989,
    dateLabel: "1989",
    title: "Adlam 在富拉尼社群中形成",
    localLabel: "𞤀𞤣𞤤𞤢𞤥",
    region: "西非",
    era: "digital",
    relation: "community-invention",
    summary: "Abdoulaye 与 Ibrahima Barry 为富拉语设计字母，并由家族与跨国社群扩展。",
    relationSummary: "从手写、教材进入字体、键盘和 Unicode，展示社群创制与数字编码的连续链。",
    evidence: "创制者档案、教学材料、社群出版和编码提案记录发展。",
    caution: "2016 年进入 Unicode 不等于 1989 年前不存在，也不表示所有平台已完整支持。",
    sourceLabel: "Unicode · Adlam",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/chapter-19/",
  },
  {
    id: "unicode-1",
    year: 1991,
    dateLabel: "1991",
    title: "Unicode 1.0 发布",
    region: "全球基础设施",
    era: "digital",
    relation: "digital-encoding",
    summary: "统一字符编码项目发布首个标准版本，试图让不同系统交换多文字文本。",
    relationSummary: "标准把字符身份与具体字体分开，并在后续与 ISO/IEC 10646 协调码位。",
    evidence: "版本标准、字符数据库与技术委员会记录可追踪编码变化。",
    caution: "早期覆盖远不完整，“统一”也不消除语言、字形和输入法差异。",
    sourceLabel: "Unicode · Version 1.0",
    sourceUrl: "https://www.unicode.org/versions/Unicode1.0.0/",
  },
  {
    id: "unicode-iso-alignment",
    year: 1993,
    dateLabel: "1993 起",
    title: "Unicode 与 ISO/IEC 10646 协调",
    region: "全球基础设施",
    era: "digital",
    relation: "digital-encoding",
    summary: "两个标准保持共同字符表和码点对应，降低竞争编码造成的文本碎裂。",
    relationSummary: "统一编码模型逐步扩展补充平面、历史文字、emoji 与属性规范。",
    evidence: "ISO 标准、Unicode 版本与稳定性政策提供正式版本链。",
    caution: "码点兼容不保证字体、排序、分词或辅助技术一致，这些仍需独立实现。",
    sourceLabel: "Unicode · About the standard",
    sourceUrl: "https://www.unicode.org/standard/standard.html",
  },
  {
    id: "unicode-17",
    year: 2025,
    dateLabel: "2025",
    title: "Unicode 17.0 扩展文字覆盖",
    region: "全球基础设施",
    era: "digital",
    relation: "digital-encoding",
    summary: "版本 17.0 继续加入历史和现用文字字符，并更新算法与属性数据。",
    relationSummary: "编码由长期提案、证据审查和版本稳定政策维护，不是一次完成的世界文字清单。",
    evidence: "Unicode 17.0 核心规范、字符数据库、提案与版本说明可公开复核。",
    caution: "进入标准只是可用性的必要条件；字体、键盘、平台与社群培训仍决定实际访问。",
    sourceLabel: "Unicode 17.0 Core Specification",
    sourceUrl: "https://www.unicode.org/versions/Unicode17.0.0/core-spec/",
  },
] as const;
