const {readFileSync,readdirSync,statSync}=require("fs"); const {join}=require("path");
function cjk(rel){const t=readFileSync("content/"+rel,"utf8"); const end=t.indexOf("\n---",3); const body=t.startsWith("---")&&end!==-1?t.slice(end+4):t; return (body.match(/[\u4e00-\u9fff]/g)||[]).length;}
function walk(dir,acc=[]){for(const name of readdirSync(dir)){const p=join(dir,name); if(statSync(p).isDirectory()) walk(p,acc); else if(/\.(md|mdx)$/.test(name)) acc.push(p);} return acc;}
const kpg=walk("content").find(p=>p.includes("\u767d\u4e9a\u7eaa")&&p.includes("\u5927\u706d\u7edd")).replace(/^content\//,"");
const w59=["universe-physics/knowledge-base/\u91cf\u5b50\u7269\u7406/pauli-exclusion-principle.md","universe-physics/knowledge-base/\u5149\u5b66/optical-fiber-and-total-internal-reflection.md","universe-physics/knowledge-base/\u76f8\u5bf9\u8bba/\u9ed1\u6d1e.md","psychology/methods/qualitative-methods-psychology.mdx","psychology/methods/machine-learning-psychology.mdx",kpg,"computer-science/pioneers/guido-van-rossum.mdx","mathematics/mathematicians/euclid.mdx","psychology/experiments/simons-levin-1998.mdx","economics/knowledge-base/understanding-bubbles.mdx","cosmology/knowledge-base/\u592a\u9633\u7cfb/asteroid-belt.md","computer-science/algorithms/principal-component-analysis.mdx","psychology/theorists/solomon-asch.mdx","computer-science/pioneers/alan-kay.mdx","computer-science/pioneers/linus-torvalds.mdx"];
console.log("=== W59 ==="); for(const rel of w59){const n=cjk(rel); console.log(rel+"|"+n+(n<3800?" UNDER":n>4800?" OVER":" OK"));}
const SIX=new Set(["linguistics","arts","law","engineering","sociology","literature"]);
const DOMAIN_OK=new Set("philosophy psychology universe-physics human-history computer-science political-science mathematics economics cosmology medicine earth-science life-science chemistry".split(" "));
const skip=["/dialogues/","\u514b\u9686\u6280\u672f","terrorism","medical-futility","hiv-aids","vaccine-policy","tuskegee","vaccination.mdx","\u4e8c\u6218.md","reproductive-system","placebo-deception","\u4e8c\u6218\u7206\u53d1","dissociative","adhd.mdx","/assets/","\u7d22\u5f15.md","\u5f00\u53d1\u89c4\u8303","\u5185\u5bb9\u6df1\u5ea6\u89c4\u8303","\u5de5\u7a0b\u5b88\u5219","\u9879\u76ee\u89c4\u5212","README","CREDITS","working-through","psychoanalysis","countertransference","psychic-causality","medicinal-chemistry","free-association","object-relations","semaglutide","freud-wars","lecanemab","bnt162b2","trial-analyses","schizophrenia","splitting","hesitancy","ptsd","unconscious","covid"];
const thin=[]; for(const p of walk("content")){let rel=p.slice(8).replace(/\\/g,"/"); if(rel.endsWith(".narration.md")||rel.endsWith("CREDITS.md")) continue; if(rel.includes("/frontier/")) continue; const d=rel.split("/")[0]; if(SIX.has(d)||!DOMAIN_OK.has(d)) continue; if(skip.some(s=>rel.includes(s))) continue; const n=cjk(rel); if(n<3800&&n>1500) thin.push([n,rel,d]);}
thin.sort((a,b)=>a[0]-b[0]); console.log("REMNANT",thin.length);
const phys=thin.filter(x=>x[2]==="universe-physics"); const picks=[]; const used=new Set();
for(const x of phys){ if(picks.length>=3) break; picks.push(x); used.add(x[1]); }
for(const x of thin){ if(picks.length>=15) break; if(used.has(x[1])) continue; picks.push(x); used.add(x[1]); }
console.log("=== W60 ==="); for(const [n,rel,d] of picks) console.log(n+"|"+d+"|"+rel);
