import { createRequire } from "node:module";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const esbuild = require("esbuild") as typeof import("esbuild");

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

async function main() {
  await esbuild.build({
    absWorkingDir: root,
    entryPoints: ["lib/search/search.worker.ts"],
    bundle: true,
    format: "iife",
    platform: "browser",
    target: "es2022",
    outfile: "public/search.worker.js",
    banner: {
      js: "/* generated by pnpm gen-search-worker; do not edit */\n",
    },
    logLevel: "warning",
  });
  console.log("✅ search worker → public/search.worker.js");
}

main().catch((error: unknown) => {
  console.error(error);
  process.exit(1);
});
