/**
 * Regenerates the philosophy search mirrors (concepts-data.ts and
 * dialogues/index.ts) from the actual .mdx source files.
 *
 * The search index runs client-side and can't read the filesystem, so it
 * consumes these precomputed data arrays. They had drifted badly out of sync
 * with the .mdx routes — emitting dozens of 404 search results and omitting
 * most real articles. This keeps the mirror == the route set.
 *
 * Run: pnpm gen-philo
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import prettier from "prettier";

const CONTENT = join(process.cwd(), "content", "philosophy");

/** Format with the repo's prettier config so output is commit-stable (idempotent). */
async function writeFormatted(filePath: string, source: string): Promise<void> {
  const config = await prettier.resolveConfig(filePath);
  writeFileSync(filePath, await prettier.format(source, { ...config, parser: "typescript" }));
}

function readFrontmatter(dir: string): Array<{ slug: string; data: Record<string, unknown> }> {
  return readdirSync(join(CONTENT, dir))
    .filter((f) => f.endsWith(".mdx"))
    .map((f) => ({
      slug: f.replace(/\.mdx$/, ""),
      data: matter(readFileSync(join(CONTENT, dir, f), "utf8")).data,
    }))
    .sort((a, b) => a.slug.localeCompare(b.slug));
}

const str = (v: unknown): string => (typeof v === "string" ? v : "");
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);
const json = (v: string): string => JSON.stringify(v);
const jsonArr = (v: string[]): string => `[${v.map(json).join(", ")}]`;

// ── Concepts ────────────────────────────────────────────────────────────
const concepts = readFrontmatter("concepts").map(({ slug, data }) => ({
  slug,
  title: str(data.title) || slug,
  title_en: str(data.title_en),
  field: str(data.field),
  key_figures: arr(data.key_figures),
}));

const conceptsOut =
  `// AUTO-GENERATED by scripts/gen-philo-index.ts — do not edit by hand.\n` +
  `// Search mirror of content/philosophy/concepts/*.mdx. Run \`pnpm gen-philo\`.\n` +
  `export const CONCEPTS = [\n` +
  concepts
    .map(
      (c) =>
        `  { slug: ${json(c.slug)}, title: ${json(c.title)}, title_en: ${json(c.title_en)}, field: ${json(c.field)}, key_figures: ${jsonArr(c.key_figures)} },`
    )
    .join("\n") +
  `\n];\n`;

// ── Dialogues ───────────────────────────────────────────────────────────
const dialogues = readFrontmatter("dialogues").map(({ slug, data }) => ({
  slug,
  title: str(data.title) || slug,
  title_en: str(data.title_en),
  field: str(data.field),
  era: str(data.era),
  participants: arr(data.participants),
}));

const dialoguesOut =
  `// AUTO-GENERATED by scripts/gen-philo-index.ts — do not edit by hand.\n` +
  `// Search mirror of content/philosophy/dialogues/*.mdx. Run \`pnpm gen-philo\`.\n` +
  `export const DIALOGUES = [\n` +
  dialogues
    .map(
      (d) =>
        `  { slug: ${json(d.slug)}, title: ${json(d.title)}, title_en: ${json(d.title_en)}, field: ${json(d.field)}, era: ${json(d.era)}, participants: ${jsonArr(d.participants)} },`
    )
    .join("\n") +
  `\n];\n`;

async function main(): Promise<void> {
  await writeFormatted(join(CONTENT, "concepts-data.ts"), conceptsOut);
  await writeFormatted(join(CONTENT, "dialogues", "index.ts"), dialoguesOut);
  console.log(`✅ Wrote ${concepts.length} concepts, ${dialogues.length} dialogues.`);
}

void main();
