/**
 * Regenerates the economics search mirrors from the .mdx source files.
 * Same MERGE-preserve strategy as gen-philo (see that file). Only the data
 * arrays the search index actually consumes are regenerated; KB and case-studies
 * are out of scope here.
 *
 * Run: pnpm gen-econ
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import prettier from "prettier";
import { ECONOMISTS_DATA } from "../content/economics/economists-data.ts";
import { ECONOMICS_SCHOOLS_DATA } from "../content/economics/schools-data.ts";
import { THEORIES_DATA } from "../content/economics/theories-data.ts";
import { ECONOMICS_CONCEPTS_DATA } from "../content/economics/concepts-data.ts";
import { ECONOMICS_DEBATES_DATA } from "../content/economics/debates-data.ts";
import { ECONOMICS_DIALOGUES_DATA } from "../content/economics/dialogues-data.ts";

const CONTENT = join(process.cwd(), "content", "economics");

type Entry = Record<string, unknown> & { slug: string };
const str = (v: unknown): string => (typeof v === "string" ? v : "");
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);

function frontmatter(dir: string): Map<string, Record<string, unknown>> {
  const map = new Map<string, Record<string, unknown>>();
  for (const f of readdirSync(join(CONTENT, dir))) {
    if (!f.endsWith(".mdx") && !f.endsWith(".md")) continue;
    map.set(f.replace(/\.mdx?$/, ""), matter(readFileSync(join(CONTENT, dir, f), "utf8")).data);
  }
  return map;
}

/** Keep live existing entries, drop dead ones, append new files from frontmatter. */
function merge(
  dir: string,
  existing: readonly { slug: string }[],
  build: (slug: string, fm: Record<string, unknown>) => Entry
): Entry[] {
  const fm = frontmatter(dir);
  const kept = (existing as readonly Entry[]).filter((e) => fm.has(e.slug));
  const known = new Set(kept.map((e) => e.slug));
  const added: Entry[] = [];
  for (const [slug, data] of fm) if (!known.has(slug)) added.push(build(slug, data));
  return [...kept, ...added].sort((a, b) => a.slug.localeCompare(b.slug));
}

async function emit(file: string, exportName: string, entries: Entry[]): Promise<void> {
  const body = entries.map((e) => "  " + JSON.stringify(e) + ",").join("\n");
  const src =
    `// AUTO-GENERATED by scripts/gen-econ-index.ts (pnpm gen-econ) — do not edit by hand.\n` +
    `// Search mirror of content/economics/*/*.mdx.\n` +
    `export const ${exportName} = [\n${body}\n];\n`;
  const path = join(CONTENT, file);
  const config = await prettier.resolveConfig(path);
  writeFileSync(path, await prettier.format(src, { ...config, parser: "typescript" }));
}

async function main(): Promise<void> {
  const economists = merge("economists", ECONOMISTS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.economist),
    era: str(fm.era),
  }));
  const schools = merge("schools", ECONOMICS_SCHOOLS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.titleEn),
    era: str(fm.era),
  }));
  const theories = merge("theories", THEORIES_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.titleEn),
    category: str(fm.category),
  }));
  const concepts = merge("concepts", ECONOMICS_CONCEPTS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.titleEn),
    field: str(fm.category),
  }));
  const debates = merge("debates", ECONOMICS_DEBATES_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    titleEn: str(fm.titleEn),
    field: str(fm.field),
    sides: arr(fm.sides),
  }));
  const dialogues = merge("dialogues", ECONOMICS_DIALOGUES_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    titleEn: str(fm.titleEn),
    field: str(fm.field),
    participants: arr(fm.participants),
  }));

  await emit("economists-data.ts", "ECONOMISTS_DATA", economists);
  await emit("schools-data.ts", "ECONOMICS_SCHOOLS_DATA", schools);
  await emit("theories-data.ts", "THEORIES_DATA", theories);
  await emit("concepts-data.ts", "ECONOMICS_CONCEPTS_DATA", concepts);
  await emit("debates-data.ts", "ECONOMICS_DEBATES_DATA", debates);
  await emit("dialogues-data.ts", "ECONOMICS_DIALOGUES_DATA", dialogues);

  console.log(
    `✅ economists ${economists.length}, schools ${schools.length}, theories ${theories.length}, ` +
      `concepts ${concepts.length}, debates ${debates.length}, dialogues ${dialogues.length}`
  );
}

void main();
