/**
 * Regenerates the psychology search mirrors from the .mdx source files.
 * Same MERGE-preserve strategy as gen-philo. Only the data arrays the search
 * index consumes are regenerated (KB and debates are out of scope).
 *
 * Run: pnpm gen-psych
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import prettier from "prettier";
import { PSYCHOLOGY_THEORISTS_DATA } from "../content/psychology/theorists-data.ts";
import { PSYCHOLOGY_EXPERIMENTS_DATA } from "../content/psychology/experiments-data.ts";
import { PHENOMENA_DATA } from "../content/psychology/phenomena-data.ts";
import { DISORDERS_DATA } from "../content/psychology/disorders-data.ts";
import { PSYCHOLOGY_SCHOOLS_DATA } from "../content/psychology/schools-data.ts";
import { PSYCHOLOGY_DIALOGUES_DATA } from "../content/psychology/dialogues-data.ts";
import { PSYCHOLOGY_KB_DATA } from "../content/psychology/knowledge-base-data.ts";

const CONTENT = join(process.cwd(), "content", "psychology");

type Entry = Record<string, unknown> & { slug: string };
const str = (v: unknown): string => (typeof v === "string" ? v : "");
const num = (v: unknown): number => (typeof v === "number" ? v : 0);
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);
/** schools/disorders use `titleEn`; phenomena/dialogues use mixed casing. */
const titleEn = (fm: Record<string, unknown>): string => str(fm.titleEn) || str(fm.title_en);

function frontmatter(dir: string): Map<string, Record<string, unknown>> {
  const map = new Map<string, Record<string, unknown>>();
  for (const f of readdirSync(join(CONTENT, dir))) {
    if (!f.endsWith(".mdx") && !f.endsWith(".md")) continue;
    map.set(f.replace(/\.mdx?$/, ""), matter(readFileSync(join(CONTENT, dir, f), "utf8")).data);
  }
  return map;
}

/** Keep live existing entries, drop dead ones, append new files from frontmatter. */
function merge(
  dir: string,
  existing: readonly { slug: string }[],
  build: (slug: string, fm: Record<string, unknown>) => Entry
): Entry[] {
  const fm = frontmatter(dir);
  const kept = (existing as readonly Entry[]).filter((e) => fm.has(e.slug));
  const known = new Set(kept.map((e) => e.slug));
  const added: Entry[] = [];
  for (const [slug, data] of fm) if (!known.has(slug)) added.push(build(slug, data));
  return [...kept, ...added].sort((a, b) => a.slug.localeCompare(b.slug));
}

async function emit(file: string, exportName: string, entries: Entry[]): Promise<void> {
  const body = entries.map((e) => "  " + JSON.stringify(e) + ",").join("\n");
  const src =
    `// AUTO-GENERATED by scripts/gen-psych-index.ts (pnpm gen-psych) — do not edit by hand.\n` +
    `// Search mirror of content/psychology/*/*.mdx.\n` +
    `export const ${exportName} = [\n${body}\n];\n`;
  const path = join(CONTENT, file);
  const config = await prettier.resolveConfig(path);
  writeFileSync(path, await prettier.format(src, { ...config, parser: "typescript" }));
}

async function main(): Promise<void> {
  const theorists = merge("theorists", PSYCHOLOGY_THEORISTS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.psychologist),
    era: str(fm.era),
  }));
  const experiments = merge("experiments", PSYCHOLOGY_EXPERIMENTS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: titleEn(fm),
    researcher: str(fm.researcher),
    year: num(fm.year),
  }));
  const phenomena = merge("phenomena", PHENOMENA_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: titleEn(fm),
    category: str(fm.category),
  }));
  const disorders = merge("disorders", DISORDERS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: titleEn(fm),
    category: str(fm.category),
  }));
  const schools = merge("schools", PSYCHOLOGY_SCHOOLS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: titleEn(fm),
    era: str(fm.era),
    founder: str(fm.founder),
  }));
  const dialogues = merge("dialogues", PSYCHOLOGY_DIALOGUES_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    title_en: titleEn(fm),
    field: str(fm.field),
    participants: arr(fm.participants),
  }));
  const knowledgeBase = merge("knowledge-base", PSYCHOLOGY_KB_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    titleEn: titleEn(fm),
    category: str(fm.category),
  }));

  await emit("theorists-data.ts", "PSYCHOLOGY_THEORISTS_DATA", theorists);
  await emit("experiments-data.ts", "PSYCHOLOGY_EXPERIMENTS_DATA", experiments);
  await emit("phenomena-data.ts", "PHENOMENA_DATA", phenomena);
  await emit("disorders-data.ts", "DISORDERS_DATA", disorders);
  await emit("schools-data.ts", "PSYCHOLOGY_SCHOOLS_DATA", schools);
  await emit("dialogues-data.ts", "PSYCHOLOGY_DIALOGUES_DATA", dialogues);
  await emit("knowledge-base-data.ts", "PSYCHOLOGY_KB_DATA", knowledgeBase);

  console.log(
    `✅ theorists ${theorists.length}, experiments ${experiments.length}, phenomena ${phenomena.length}, ` +
      `disorders ${disorders.length}, schools ${schools.length}, dialogues ${dialogues.length}, ` +
      `knowledge-base ${knowledgeBase.length}`
  );
}

void main();
