/**
 * Regenerates the philosophy search mirrors from the .mdx source files.
 *
 * The search index runs client-side and can't read the filesystem, so it
 * consumes precomputed data arrays. These had drifted badly from the .mdx
 * routes they mirror — emitting 404 search results (slugs with no file) and
 * omitting most real articles (files with no entry).
 *
 * MERGE strategy (like gen-kb): every existing entry whose slug still has a
 * live .mdx file is preserved verbatim (keeps hand-authored fields such as the
 * English subtitle, which isn't in school frontmatter); entries with no file
 * are dropped; one entry per new file is derived from its frontmatter. Output
 * is prettier-formatted so re-running is idempotent and commit-clean.
 *
 * Run: pnpm gen-philo
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import prettier from "prettier";
import { THINKERS_DATA } from "../content/philosophy/thinkers-data.ts";
import { SCHOOLS_DATA } from "../content/philosophy/schools-data.ts";
import { ISMS } from "../content/philosophy/isms-data.ts";
import { QUESTIONS } from "../content/philosophy/questions-data.ts";
import { CONCEPTS } from "../content/philosophy/concepts-data.ts";
import { PHILOSOPHY_EXPERIMENTS } from "../content/philosophy/philosophy-experiments-data.ts";
import { DIALOGUES } from "../content/philosophy/dialogues/index.ts";

const CONTENT = join(process.cwd(), "content", "philosophy");

type Entry = Record<string, unknown> & { slug: string };

const str = (v: unknown): string => (typeof v === "string" ? v : "");
const num = (v: unknown): number => (typeof v === "number" ? v : 0);
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);

function frontmatter(dir: string): Map<string, Record<string, unknown>> {
  const map = new Map<string, Record<string, unknown>>();
  for (const f of readdirSync(join(CONTENT, dir))) {
    if (!f.endsWith(".mdx")) continue;
    map.set(f.replace(/\.mdx$/, ""), matter(readFileSync(join(CONTENT, dir, f), "utf8")).data);
  }
  return map;
}

/** Keep live existing entries, drop dead ones, append new files from frontmatter. */
function merge(
  dir: string,
  existing: readonly { slug: string }[],
  build: (slug: string, fm: Record<string, unknown>) => Entry
): Entry[] {
  const fm = frontmatter(dir);
  const kept = (existing as readonly Entry[]).filter((e) => fm.has(e.slug));
  const known = new Set(kept.map((e) => e.slug));
  const added: Entry[] = [];
  for (const [slug, data] of fm) {
    if (!known.has(slug)) added.push(build(slug, data));
  }
  return [...kept, ...added].sort((a, b) => a.slug.localeCompare(b.slug));
}

async function emit(file: string, exportName: string, entries: Entry[]): Promise<void> {
  const body = entries.map((e) => "  " + JSON.stringify(e) + ",").join("\n");
  const src =
    `// AUTO-GENERATED by scripts/gen-philo-index.ts (pnpm gen-philo) — do not edit by hand.\n` +
    `// Search mirror of content/philosophy/${file.includes("/") ? file.split("/")[0] : file.replace(/-data\.ts$/, "")}/*.mdx.\n` +
    `export const ${exportName} = [\n${body}\n];\n`;
  const path = join(CONTENT, file);
  const config = await prettier.resolveConfig(path);
  writeFileSync(path, await prettier.format(src, { ...config, parser: "typescript" }));
}

async function main(): Promise<void> {
  const thinkers = merge("thinkers", THINKERS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: str(fm.philosopher),
    era: str(fm.era),
  }));
  const schools = merge("schools", SCHOOLS_DATA, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    subtitle: "",
    era: str(fm.era),
  }));
  const isms = merge("isms", ISMS, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    title_en: str(fm.title_en),
    category: str(fm.category),
    era: str(fm.era),
    key_figures: arr(fm.key_figures),
  }));
  const questions = merge("questions", QUESTIONS, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    field: str(fm.field),
    key_figures: arr(fm.key_figures),
    tags: arr(fm.tags),
  }));
  const concepts = merge("concepts", CONCEPTS, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    title_en: str(fm.title_en),
    field: str(fm.field),
    key_figures: arr(fm.key_figures),
  }));
  const experiments = merge("experiments", PHILOSOPHY_EXPERIMENTS, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    title_en: str(fm.title_en),
    philosopher: str(fm.philosopher),
    year: num(fm.year),
    field: str(fm.field),
  }));
  const dialogues = merge("dialogues", DIALOGUES, (slug, fm) => ({
    slug,
    title: str(fm.title) || slug,
    title_en: str(fm.title_en),
    field: str(fm.field),
    era: str(fm.era),
    participants: arr(fm.participants),
  }));

  await emit("thinkers-data.ts", "THINKERS_DATA", thinkers);
  await emit("schools-data.ts", "SCHOOLS_DATA", schools);
  await emit("isms-data.ts", "ISMS", isms);
  await emit("questions-data.ts", "QUESTIONS", questions);
  await emit("concepts-data.ts", "CONCEPTS", concepts);
  await emit("philosophy-experiments-data.ts", "PHILOSOPHY_EXPERIMENTS", experiments);
  await emit("dialogues/index.ts", "DIALOGUES", dialogues);

  console.log(
    `✅ thinkers ${thinkers.length}, schools ${schools.length}, isms ${isms.length}, ` +
      `questions ${questions.length}, concepts ${concepts.length}, experiments ${experiments.length}, ` +
      `dialogues ${dialogues.length}`
  );
}

void main();
