import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { ERAS } from "../content/human-history/data/eras.js";
import { EVENTS } from "../content/human-history/data/events.js";
import { EVENT_DETAILS } from "../content/human-history/data/event-details.js";
import { EXTRA_DETAILS } from "../content/human-history/data/extra-details.js";
import { FINAL_DETAILS } from "../content/human-history/data/final-details.js";
import { FIGURES } from "../content/human-history/data/figures.js";
import { GEO_ENRICHMENT_1 } from "../content/human-history/data/geo-enrichment-ancient.js";
import { GEO_ENRICHMENT_2 } from "../content/human-history/data/geo-enrichment-modern.js";
import { GEO_EVENTS } from "../content/human-history/data/geo-events.js";
import { LAST_DETAILS } from "../content/human-history/data/last-details.js";
import { PARALLEL_EVENTS } from "../content/human-history/data/parallel-events.js";
import { REFERENCES } from "../content/human-history/data/references.js";
import {
  getEventRelationships,
  getFigureEventLinks,
} from "../subjects/history/lib/event-relationships";

type EraId =
  | "prehistoric"
  | "classical"
  | "medieval"
  | "earlyModern"
  | "modern"
  | "contemporary"
  | "future";

type RawEvent = {
  year: number;
  title: string;
  desc: string;
  longDesc?: string;
  era: EraId;
  region: string;
  cat: string;
  references?: string[];
  source?: string;
};

type GeoEvent = Omit<RawEvent, "desc">;

type EventDetail = {
  pages?: { title: string; body: string }[];
  facts?: string[];
  quote?: { text: string; author: string };
};

type Figure = {
  name: string;
  birth: number | null;
  death: number | null;
  title: string;
  desc: string;
  longDesc: string;
  era: EraId;
  region: string;
  domain: string;
  quote: string;
  impact: string[];
  achievements: string[];
  controversies: string[];
  keyEvents: { year: number; title: string }[];
  references: string[];
};

type Reference = {
  author: string;
  title: string;
  titleEn?: string;
  year: number;
};

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUTPUT_DIR = join(ROOT, "content/human-history/data/generated");
const ERA_IDS = (ERAS as { id: EraId }[]).map((era) => era.id);

const allDetails = {
  ...(EVENT_DETAILS as Record<string, EventDetail>),
  ...(EXTRA_DETAILS as Record<string, EventDetail>),
  ...(FINAL_DETAILS as Record<string, EventDetail>),
  ...(LAST_DETAILS as Record<string, EventDetail>),
  ...(GEO_ENRICHMENT_1 as Record<string, EventDetail>),
  ...(GEO_ENRICHMENT_2 as Record<string, EventDetail>),
};

function truncateText(text: string, length = 92): string {
  const cleaned = text.replace(/\s+/g, " ").trim();
  return cleaned.length > length ? `${cleaned.slice(0, length)}...` : cleaned;
}

function buildGeoDescription(event: GeoEvent): string {
  const detail = allDetails[event.title];
  const firstBody = detail?.pages?.[0]?.body;
  if (firstBody) return truncateText(firstBody);
  return `${event.region} · ${event.cat}节点，用于补足世界历史地图与时间线的连续性。`;
}

function buildTimelineEvents(): RawEvent[] {
  const base = (EVENTS as RawEvent[]).map((event) => ({
    ...event,
    source: event.source ?? "timeline",
  }));
  const seenTitles = new Set(base.map((event) => event.title));
  for (const event of PARALLEL_EVENTS as RawEvent[]) {
    if (seenTitles.has(event.title)) continue;
    seenTitles.add(event.title);
    base.push({ ...event, source: event.source ?? "timeline" });
  }
  const additions = (GEO_EVENTS as GeoEvent[])
    .filter((event) => !seenTitles.has(event.title))
    .map((event) => ({
      ...event,
      desc: buildGeoDescription(event),
      source: "map",
    }));

  return [...base, ...additions].sort((left, right) => left.year - right.year);
}

function pageCount(detail: EventDetail | undefined): number {
  if (!detail) return 0;
  return (
    (detail.pages?.length ?? 1) +
    (detail.facts?.length ? 1 : 0) +
    (detail.quote ? 1 : 0)
  );
}

function exportModule(name: string, value: unknown): string {
  return `// Generated by scripts/gen-history-route-data.ts. Do not edit.\nexport const ${name} = ${JSON.stringify(value, null, 2)};\n`;
}

async function writeGenerated(path: string, content: string): Promise<void> {
  let current = "";
  try {
    current = await readFile(path, "utf8");
  } catch {
    // A missing generated file is expected on the first run.
  }
  if (current !== content) await writeFile(path, content);
}

function assertUnique(values: string[], label: string): void {
  const unique = new Set(values);
  if (unique.size !== values.length) {
    throw new Error(`${label} contains duplicate identifiers`);
  }
}

async function main(): Promise<void> {
  await mkdir(OUTPUT_DIR, { recursive: true });

  const events = EVENTS as RawEvent[];
  const figures = FIGURES as Figure[];
  const timelineEvents = buildTimelineEvents();
  const eraById = new Map(
    (ERAS as { id: EraId; name: string; color: string }[]).map((era) => [
      era.id,
      era,
    ]),
  );
  const referenceById = REFERENCES as Record<string, Reference>;
  const eventRelations = getEventRelationships();
  const figureEventLinks = getFigureEventLinks();

  assertUnique(events.map((event) => event.title), "EVENTS");
  assertUnique(figures.map((figure) => figure.name), "FIGURES");
  assertUnique(timelineEvents.map((event) => event.title), "timeline events");

  const eventCatalog = events.map(
    ({ year, title, desc, era, region, cat, references = [] }) => ({
      year,
      title,
      desc,
      era,
      region,
      cat,
      references,
    }),
  );
  const figureCatalog = figures.map(
    ({
      name,
      birth,
      death,
      title,
      desc,
      era,
      region,
      domain,
      quote,
      impact,
    }) => ({
      name,
      birth,
      death,
      title,
      desc,
      era,
      region,
      domain,
      quote,
      impact: impact.slice(0, 3),
    }),
  );
  const timelineCatalog = timelineEvents.map(
    ({ year, title, desc, era, region, cat, source }) => {
      const detail = allDetails[title];
      return {
        year,
        title,
        desc,
        era,
        region,
        cat,
        source,
        hasDetail: Boolean(detail),
        detailPageCount: pageCount(detail),
      };
    },
  );

  await Promise.all([
    writeGenerated(
      join(OUTPUT_DIR, "event-catalog.js"),
      exportModule("EVENT_CATALOG", eventCatalog),
    ),
    writeGenerated(
      join(OUTPUT_DIR, "event-catalog.d.ts"),
      "export const EVENT_CATALOG: unknown[];\n",
    ),
    writeGenerated(
      join(OUTPUT_DIR, "figure-catalog.js"),
      exportModule("FIGURE_CATALOG", figureCatalog),
    ),
    writeGenerated(
      join(OUTPUT_DIR, "figure-catalog.d.ts"),
      "export const FIGURE_CATALOG: unknown[];\n",
    ),
    writeGenerated(
      join(OUTPUT_DIR, "timeline-catalog.js"),
      exportModule("TIMELINE_EVENT_CATALOG", timelineCatalog),
    ),
    writeGenerated(
      join(OUTPUT_DIR, "timeline-catalog.d.ts"),
      "export const TIMELINE_EVENT_CATALOG: unknown[];\n",
    ),
  ]);

  for (const eraId of ERA_IDS) {
    const era = eraById.get(eraId);
    if (!era) throw new Error(`Unknown era ${eraId}`);

    const eventRouteRecords = Object.fromEntries(
      events
        .filter((event) => event.era === eraId)
        .map((event) => {
          const resolvedReferences = (event.references ?? []).map((id) => ({
            id,
            ...(referenceById[id] ?? { author: "", title: id, year: 0 }),
          }));
          return [
            event.title,
            {
              ...event,
              longDesc: event.longDesc ?? "",
              references: event.references ?? [],
              detail:
                (EVENT_DETAILS as Record<string, EventDetail>)[event.title] ??
                null,
              eraName: era.name,
              eraColor: era.color,
              relatedEvents: eventRelations.filter(
                (relation) =>
                  relation.source === event.title ||
                  relation.target === event.title,
              ),
              figureLinks: figureEventLinks
                .filter((link) => link.eventId === event.title)
                .map((link) => ({
                  figureId: link.figureId,
                  role: link.role,
                })),
              resolvedReferences,
            },
          ];
        }),
    );
    const timelineDetailRecords = Object.fromEntries(
      timelineEvents
        .filter((event) => event.era === eraId)
        .map((event) => [
          event.title,
          {
            longDesc: event.longDesc ?? "",
            detail: allDetails[event.title] ?? null,
          },
        ]),
    );
    const figureRouteRecords = Object.fromEntries(
      figures
        .filter((figure) => figure.era === eraId)
        .map((figure) => [figure.name, figure]),
    );

    await writeGenerated(
      join(OUTPUT_DIR, `event-route-${eraId}.js`),
      exportModule("EVENT_ROUTE_RECORDS", eventRouteRecords),
    );
    await writeGenerated(
      join(OUTPUT_DIR, `event-route-${eraId}.d.ts`),
      "export const EVENT_ROUTE_RECORDS: Record<string, unknown>;\n",
    );
    await writeGenerated(
      join(OUTPUT_DIR, `timeline-details-${eraId}.js`),
      exportModule("TIMELINE_DETAIL_RECORDS", timelineDetailRecords),
    );
    await writeGenerated(
      join(OUTPUT_DIR, `timeline-details-${eraId}.d.ts`),
      "export const TIMELINE_DETAIL_RECORDS: Record<string, unknown>;\n",
    );
    await writeGenerated(
      join(OUTPUT_DIR, `figure-route-${eraId}.js`),
      exportModule("FIGURE_ROUTE_RECORDS", figureRouteRecords),
    );
    await writeGenerated(
      join(OUTPUT_DIR, `figure-route-${eraId}.d.ts`),
      "export const FIGURE_ROUTE_RECORDS: Record<string, unknown>;\n",
    );
  }

  console.log(
    `History route data: ${eventCatalog.length} events, ${timelineCatalog.length} timeline nodes, ${figureCatalog.length} figures, ${ERA_IDS.length} era shards`,
  );
}

main().catch((error: unknown) => {
  console.error(error);
  process.exitCode = 1;
});
