/**
 * Regenerates the life-science dialogue search mirror from the .mdx source.
 * The search index runs client-side and can't read the filesystem, so it
 * consumes this precomputed metadata array (no body). Same prettier-idempotent
 * pattern as gen-philo/econ/psych.
 *
 * Run: pnpm gen-life
 */
import { readdirSync, readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import prettier from "prettier";

const DIR = join(process.cwd(), "content", "life-science", "dialogues");

const str = (v: unknown): string => (typeof v === "string" ? v : "");
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);

const entries = readdirSync(DIR)
  .filter((f) => f.endsWith(".mdx"))
  .map((f) => {
    const slug = f.replace(/\.mdx$/, "");
    const { data } = matter(readFileSync(join(DIR, f), "utf8"));
    return {
      slug,
      title: str(data.title) || slug,
      participants: arr(data.participants),
      question: str(data.question),
      field: str(data.field),
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const body = entries.map((e) => "  " + JSON.stringify(e) + ",").join("\n");
const src =
  `// AUTO-GENERATED by scripts/gen-life-index.ts (pnpm gen-life) — do not edit by hand.\n` +
  `// Search mirror of content/life-science/dialogues/*.mdx (metadata only, no body).\n` +
  `export const LIFE_SCIENCE_DIALOGUES = [\n${body}\n];\n`;

const outPath = join(process.cwd(), "content", "life-science", "dialogues-data.ts");

async function main(): Promise<void> {
  const config = await prettier.resolveConfig(outPath);
  writeFileSync(outPath, await prettier.format(src, { ...config, parser: "typescript" }));
  console.log(`✅ Wrote ${entries.length} life-science dialogues.`);
}

void main();
