import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { KNOWLEDGE_DOMAINS } from "../lib/new-domains.ts";
import { writeFormattedTs } from "./format-ts";

/**
 * Mirrors the section content of engine-driven domains (computer-science,
 * political-science) into a typed module for the client-side search index —
 * generated from the same frontmatter the routes read, so the two cannot drift.
 * Re-run after adding section articles:  pnpm gen-domain
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CONTENT_ROOT = path.resolve(__dirname, "..", "content");
const OUT = path.resolve(__dirname, "..", "lib", "search-index", "domain-data.ts");

interface Entry {
  slug: string;
  title: string;
  titleEn: string;
  domain: string;
  section: string;
  sectionLabel: string;
  category: string;
}

function collect(): Entry[] {
  const entries: Entry[] = [];
  for (const config of Object.values(KNOWLEDGE_DOMAINS)) {
    for (const section of config.sections) {
      const dir = path.join(CONTENT_ROOT, config.domain, section.key);
      if (!fs.existsSync(dir)) continue;
      for (const file of fs.readdirSync(dir).sort()) {
        if (!file.endsWith(".md") && !file.endsWith(".mdx")) continue;
        if (file.endsWith(".narration.md")) continue; // spoken companion, not an article
        const raw = fs.readFileSync(path.join(dir, file), "utf-8");
        let data: Record<string, unknown> = {};
        try {
          data = matter(raw).data;
        } catch {
          continue;
        }
        entries.push({
          slug: file.replace(/\.mdx?$/, ""),
          title: typeof data.title === "string" ? data.title : file,
          titleEn: typeof data.title_en === "string" ? data.title_en : "",
          domain: config.domain,
          section: section.key,
          sectionLabel: section.label,
          category: typeof data.category === "string" ? data.category : section.label,
        });
      }
    }
  }
  return entries;
}

function serialize(entries: Entry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  { slug: ${JSON.stringify(e.slug)}, title: ${JSON.stringify(e.title)}, titleEn: ${JSON.stringify(e.titleEn)}, domain: ${JSON.stringify(e.domain)}, section: ${JSON.stringify(e.section)}, sectionLabel: ${JSON.stringify(e.sectionLabel)}, category: ${JSON.stringify(e.category)} },`
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/gen-domain-index.ts — do not edit by hand.
// Regenerate with: pnpm gen-domain
export const DOMAIN_DATA = [
${rows}
] as const;
`;
}

async function main(): Promise<void> {
  const entries = collect();
  await writeFormattedTs(OUT, serialize(entries));
  console.log(`Wrote ${entries.length} domain entries to ${path.relative(process.cwd(), OUT)}`);
}

void main();
