import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { writeFormattedTs } from "./format-ts";

/**
 * Mathematics content is filesystem-driven (no per-subtype data module), so it
 * was never in the client-side global search. This mirrors its frontmatter into
 * a typed module the search index can bundle. Re-run after adding math content:
 *   pnpm gen-math
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const MATH_ROOT = path.resolve(__dirname, "..", "content", "mathematics");
const OUT = path.resolve(__dirname, "..", "lib", "search-index", "mathematics-data.ts");

const SUBTYPES = ["mathematicians", "theorems", "concepts", "paradoxes", "dialogues"] as const;

interface Entry {
  slug: string;
  title: string;
  titleEn: string;
  subtype: string;
  field: string;
}

function str(v: unknown): string {
  return typeof v === "string" ? v : "";
}

function collect(): Entry[] {
  const entries: Entry[] = [];
  for (const subtype of SUBTYPES) {
    const dir = path.join(MATH_ROOT, subtype);
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).sort()) {
      if (!file.endsWith(".mdx") && !file.endsWith(".md")) continue;
      let data: Record<string, unknown> = {};
      try {
        data = matter(fs.readFileSync(path.join(dir, file), "utf-8")).data;
      } catch {
        continue;
      }
      const slug = file.replace(/\.mdx?$/, "");
      entries.push({
        slug,
        title: str(data.title) || slug,
        titleEn: str(data.title_en) || str(data.titleEn),
        subtype,
        field: str(data.field) || str(data.nationality) || "数学",
      });
    }
  }
  return entries;
}

function serialize(entries: Entry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  { slug: ${JSON.stringify(e.slug)}, title: ${JSON.stringify(e.title)}, titleEn: ${JSON.stringify(e.titleEn)}, subtype: ${JSON.stringify(e.subtype)}, field: ${JSON.stringify(e.field)} },`
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/gen-math-index.ts — do not edit by hand.
// Regenerate with: pnpm gen-math
export const MATHEMATICS_DATA = [
${rows}
] as const;
`;
}

async function main(): Promise<void> {
  const entries = collect();
  await writeFormattedTs(OUT, serialize(entries));
  console.log(
    `Wrote ${entries.length} mathematics entries to ${path.relative(process.cwd(), OUT)}`
  );
}

void main();
