/**
 * Regenerates lib/wiki-link-index.ts — the slug → URL map that turns inline
 * `[[wiki-links]]` in prose into clickable cross-references.
 *
 * Content authors write `[[distributed-systems]]` to reference another article;
 * MarkdownRenderer (a client component) can't read the filesystem, so it
 * consumes this precomputed map. We only emit a slug when the section it lives
 * in is actually routable (an `app/<domain>/<section>/[slug]/page.tsx` exists),
 * so a resolved wiki-link can never 404. When the same slug exists in more than
 * one domain (e.g. `justice` in philosophy and political-science) the value is
 * a { domain: url } map and the renderer prefers the reader's current domain.
 *
 * Output is prettier-formatted so re-running is idempotent and commit-clean.
 *
 * Run: pnpm gen-links
 */
import { readdirSync, existsSync, statSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import prettier from "prettier";

const ROOT = process.cwd();
const CONTENT = join(ROOT, "content");
const APP = join(ROOT, "app");
const OUT = join(ROOT, "lib", "wiki-link-index.ts");

const isDir = (p: string): boolean => existsSync(p) && statSync(p).isDirectory();
const isAsciiSlug = (s: string): boolean => /^[a-z][a-z0-9-]*$/.test(s);

/** slug → (domain → url). A slug routable in one domain collapses to a string. */
function build(): Record<string, string | Record<string, string>> {
  const bySlug = new Map<string, Map<string, string>>();

  for (const domain of readdirSync(CONTENT)) {
    const domainDir = join(CONTENT, domain);
    if (!isDir(domainDir)) continue;

    for (const section of readdirSync(domainDir)) {
      const sectionDir = join(domainDir, section);
      if (!isDir(sectionDir)) continue;
      // Only sections whose detail pages exist — guarantees no dead links.
      if (!existsSync(join(APP, domain, section, "[slug]", "page.tsx"))) continue;

      for (const file of readdirSync(sectionDir)) {
        const m = file.match(/^(.+)\.(mdx|md)$/);
        if (!m) continue;
        const slug = m[1]!;
        if (!isAsciiSlug(slug)) continue; // CJK / data-only files aren't link targets

        const domainMap = bySlug.get(slug) ?? new Map<string, string>();
        domainMap.set(domain, `/${domain}/${section}/${slug}`);
        bySlug.set(slug, domainMap);
      }
    }
  }

  const index: Record<string, string | Record<string, string>> = {};
  for (const [slug, domainMap] of [...bySlug.entries()].sort()) {
    index[slug] =
      domainMap.size === 1
        ? [...domainMap.values()][0]!
        : Object.fromEntries([...domainMap.entries()].sort());
  }
  return index;
}

async function main(): Promise<void> {
  const index = build();
  const body = `// AUTO-GENERATED by scripts/gen-wiki-links-index.ts — do not edit by hand.
// Run \`pnpm gen-links\` to regenerate. Maps a wiki-link slug to its article
// URL; a { domain: url } value means the slug is routable in several domains.

export type WikiLinkTarget = string | Record<string, string>;

export const WIKI_LINK_INDEX: Record<string, WikiLinkTarget> = ${JSON.stringify(index, null, 2)};

/** Resolve a \`[[slug]]\` to a URL, preferring the reader's current domain. */
export function resolveWikiLink(slug: string, domain?: string): string | null {
  const entry = WIKI_LINK_INDEX[slug];
  if (!entry) return null;
  if (typeof entry === "string") return entry;
  return (domain && entry[domain]) || Object.values(entry)[0] || null;
}
`;

  const formatted = await prettier.format(body, { parser: "typescript" });
  writeFileSync(OUT, formatted);

  const total = Object.keys(index).length;
  const collisions = Object.values(index).filter((v) => typeof v !== "string").length;
  console.log(`✅ wiki-link index: ${total} slugs (${collisions} multi-domain) → ${OUT}`);
}

void main();
