/**
 * Generates the universe-physics dialogue search mirror from .mdx source.
 * The search index needs a client-safe (fs-free) data array; previously the
 * physics dialogue branch was wired to the KB module by mistake and threw
 * (UNIVERSE_PHYSICS_DIALOGUES_DATA was undefined), which zeroed the ENTIRE
 * search index. This mirror fixes that.
 *
 * Run: pnpm gen-physics-dialogues
 */
import { readdirSync, readFileSync } from "node:fs";
import { join } from "node:path";
import matter from "gray-matter";
import { writeFormattedTs } from "./format-ts";

const DIR = join(process.cwd(), "content", "universe-physics", "dialogues");

const str = (v: unknown): string => (typeof v === "string" ? v : "");
const arr = (v: unknown): string[] => (Array.isArray(v) ? v.map(String) : []);

const entries = readdirSync(DIR)
  .filter((f) => f.endsWith(".mdx"))
  .map((f) => {
    const slug = f.replace(/\.mdx$/, "");
    const { data } = matter(readFileSync(join(DIR, f), "utf8"));
    return {
      slug,
      title: str(data.title) || slug,
      description: str(data.question) || str(data.field),
      participants: arr(data.participants),
      tags: arr(data.tags),
    };
  })
  .sort((a, b) => a.slug.localeCompare(b.slug));

const body = entries.map((e) => "  " + JSON.stringify(e) + ",").join("\n");
const src =
  `// AUTO-GENERATED by scripts/gen-physics-dialogues-index.ts (pnpm gen-physics-dialogues).\n` +
  `// Search mirror of content/universe-physics/dialogues/*.mdx — each slug MUST resolve.\n` +
  `export const UNIVERSE_PHYSICS_DIALOGUES_DATA = [\n${body}\n];\n`;

const outPath = join(process.cwd(), "content", "universe-physics", "dialogues-data.ts");

async function main(): Promise<void> {
  await writeFormattedTs(outPath, src);
  console.log(`✅ Wrote ${entries.length} universe-physics dialogues.`);
}

void main();
