import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import matter from "gray-matter";
import { FRONTIER_DOMAINS } from "../lib/frontier.ts";
import { writeFormattedTs } from "./format-ts";

/**
 * The global search index runs in the client bundle and cannot read the
 * filesystem, so routable content is mirrored into a typed data module. Rather
 * than hand-maintain that mirror (the exact source of the ~180 dead-link slugs
 * the content audit found), we generate it from the same frontmatter the route
 * pages read — so the two can never drift. Re-run after adding frontier files:
 *   pnpm gen-frontier
 */
const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const CONTENT_ROOT = path.resolve(__dirname, "..", "content");
const OUT = path.resolve(__dirname, "..", "lib", "search-index", "frontier-data.ts");

interface Entry {
  slug: string;
  title: string;
  titleEn: string;
  domain: string;
  category: string;
}

function collect(): Entry[] {
  const entries: Entry[] = [];
  for (const domain of FRONTIER_DOMAINS) {
    const dir = path.join(CONTENT_ROOT, domain, "frontier");
    if (!fs.existsSync(dir)) continue;
    for (const file of fs.readdirSync(dir).sort()) {
      if (!file.endsWith(".md")) continue;
      if (file.endsWith(".narration.md")) continue; // spoken companion, not an article
      const raw = fs.readFileSync(path.join(dir, file), "utf-8");
      let data: Record<string, unknown> = {};
      try {
        data = matter(raw).data;
      } catch {
        continue;
      }
      const slug = file.replace(/\.md$/, "");
      entries.push({
        slug,
        title: typeof data.title === "string" ? data.title : slug,
        titleEn: typeof data.title_en === "string" ? data.title_en : "",
        domain,
        category: typeof data.category === "string" ? data.category : "前沿",
      });
    }
  }
  return entries;
}

function serialize(entries: Entry[]): string {
  const rows = entries
    .map(
      (e) =>
        `  { slug: ${JSON.stringify(e.slug)}, title: ${JSON.stringify(e.title)}, titleEn: ${JSON.stringify(e.titleEn)}, domain: ${JSON.stringify(e.domain)}, category: ${JSON.stringify(e.category)} },`
    )
    .join("\n");
  return `// AUTO-GENERATED by scripts/gen-frontier-index.ts — do not edit by hand.
// Regenerate with: pnpm gen-frontier
export const FRONTIER_DATA = [
${rows}
] as const;
`;
}

async function main(): Promise<void> {
  const entries = collect();
  await writeFormattedTs(OUT, serialize(entries));
  console.log(`Wrote ${entries.length} frontier entries to ${path.relative(process.cwd(), OUT)}`);
}

void main();
