import type { Scientist } from "./types";

const SCIENTISTS: Scientist[] = [
  {
    id: "darwin",
    name: "查尔斯·达尔文",
    nameEn: "Charles Darwin",
    era: "近代",
    birthYear: 1809,
    deathYear: 1882,
    keyContribution: "提出自然选择学说，奠定进化论基础",
    famousWork: "《物种起源》",
    field: "进化生物学",
  },
  {
    id: "wallace",
    name: "阿尔弗雷德·华莱士",
    nameEn: "Alfred Russel Wallace",
    era: "近代",
    birthYear: 1823,
    deathYear: 1913,
    keyContribution: "独立提出自然选择理论，生物地理学之父",
    famousWork: "《马来群岛》",
    field: "生物地理学",
  },
  {
    id: "mendel",
    name: "格雷戈尔·孟德尔",
    nameEn: "Gregor Mendel",
    era: "近代",
    birthYear: 1822,
    deathYear: 1884,
    keyContribution: "发现遗传定律，现代遗传学之父",
    famousWork: "《植物杂交实验》",
    field: "遗传学",
  },
  {
    id: "huxley",
    name: "托马斯·赫胥黎",
    nameEn: "Thomas Henry Huxley",
    era: "近代",
    birthYear: 1825,
    deathYear: 1895,
    keyContribution: "达尔文理论的坚定捍卫者，比较解剖学先驱",
    famousWork: "《人类在自然界中的位置》",
    field: "比较解剖学",
  },
  {
    id: "lyell",
    name: "查尔斯·莱尔",
    nameEn: "Charles Lyell",
    era: "近代",
    birthYear: 1797,
    deathYear: 1875,
    keyContribution: "均变论奠基人，地质学革命先驱",
    famousWork: "《地质学原理》",
    field: "地质学",
  },
  {
    id: "margulis",
    name: "林恩·马古利斯",
    nameEn: "Lynn Margulis",
    era: "现代",
    birthYear: 1938,
    deathYear: 2011,
    keyContribution: "内共生理论，线粒体和叶绿体起源",
    famousWork: "《真核细胞的起源》",
    field: "细胞生物学",
  },
  {
    id: "watson",
    name: "詹姆斯·沃森",
    nameEn: "James Watson",
    era: "现代",
    birthYear: 1928,
    deathYear: null,
    keyContribution: "DNA双螺旋结构的发现者之一",
    famousWork: "《双螺旋》",
    field: "分子生物学",
  },
  {
    id: "crick",
    name: "弗朗西斯·克里克",
    nameEn: "Francis Crick",
    era: "现代",
    birthYear: 1916,
    deathYear: 2004,
    keyContribution: "DNA双螺旋结构的发现者之一，中心法则提出者",
    famousWork: "《生命本质》",
    field: "分子生物学",
  },
  {
    id: "gould",
    name: "斯蒂芬·杰·古尔德",
    nameEn: "Stephen Jay Gould",
    era: "现代",
    birthYear: 1941,
    deathYear: 2002,
    keyContribution: "间断平衡理论，进化生物学的科普大师",
    famousWork: "《自达尔文以来》",
    field: "古生物学",
  },
  {
    id: "dawkins",
    name: "理查德·道金斯",
    nameEn: "Richard Dawkins",
    era: "当代",
    birthYear: 1941,
    deathYear: null,
    keyContribution: "基因中心进化论，模因概念提出者",
    famousWork: "《自私的基因》",
    field: "进化生物学",
  },
  {
    id: "woese",
    name: "卡尔·沃斯",
    nameEn: "Carl Woese",
    era: "现代",
    birthYear: 1928,
    deathYear: 2012,
    keyContribution: "发现古菌域，三域分类系统",
    famousWork: "《细菌进化》",
    field: "微生物学",
  },
  {
    id: "oparin",
    name: "亚历山大·奥巴林",
    nameEn: "Alexander Oparin",
    era: "现代",
    birthYear: 1894,
    deathYear: 1980,
    keyContribution: "生命起源的化学进化假说",
    famousWork: "《生命起源》",
    field: "生物化学",
  },
  {
    id: "muller",
    name: "赫尔曼·穆勒",
    nameEn: "Hermann Muller",
    era: "现代",
    birthYear: 1890,
    deathYear: 1967,
    keyContribution: "发现X射线诱发突变，诺贝尔奖得主",
    famousWork: "《基因的人工蜕变》",
    field: "遗传学",
  },
  {
    id: "hamilton",
    name: "威廉·汉密尔顿",
    nameEn: "William Hamilton",
    era: "现代",
    birthYear: 1936,
    deathYear: 2000,
    keyContribution: "亲缘选择理论，解释利他行为的进化",
    famousWork: "《社会行为的遗传进化》",
    field: "进化生物学",
  },
  {
    id: "wozniak-olson",
    name: "爱德华·威尔逊",
    nameEn: "Edward O. Wilson",
    era: "当代",
    birthYear: 1929,
    deathYear: 2021,
    keyContribution: "社会生物学之父，生物多样性保护先驱",
    famousWork: "《社会生物学：新的综合》",
    field: "社会生物学",
  },
  {
    id: "jennifer-doudna",
    name: "珍妮弗·杜德纳",
    nameEn: "Jennifer Doudna",
    era: "当代",
    birthYear: 1964,
    deathYear: null,
    keyContribution: "CRISPR-Cas9基因编辑技术共同开发者，诺贝尔奖得主",
    famousWork: "《破解基因密码的人》",
    field: "分子生物学",
  },
  {
    id: "svante-paabo",
    name: "斯万特·帕博",
    nameEn: "Svante Pääbo",
    era: "当代",
    birthYear: 1955,
    deathYear: null,
    keyContribution: "古基因组学之父，完成尼安德特人基因组测序",
    famousWork: "《尼安德特人》",
    field: "古基因组学",
  },
  {
    id: "mary-schweitzer",
    name: "玛丽·施韦策",
    nameEn: "Mary Schweitzer",
    era: "当代",
    birthYear: 1955,
    deathYear: null,
    keyContribution: "发现恐龙软组织化石，革新古生物学研究方法",
    famousWork: "恐龙软组织研究",
    field: "古生物学",
  },
];

export function getAllScientists(): Scientist[] {
  return SCIENTISTS;
}

export function getScientistById(id: string): Scientist | undefined {
  return SCIENTISTS.find((s) => s.id === id);
}

export function getScientistsByEra(era: string): Scientist[] {
  return SCIENTISTS.filter((s) => s.era === era);
}
